### ISSUE TITLE
[Wrath] Quality control against Let's Play WoW Draenei Shaman 1 - 80 [video 3/142]

### ISSUE THREAD

**Issue by Phatcat** [cmangos/wotlk-db#1]
https://www.youtube.com/watch?v=f00kCEI8t60&list=PL28173C4849CA7E04&index=3

0:10
Anchorite Fateema is supposed to be part of the event that starts after completing the quest with Daedal,
she is supposed to have a few conversation bits and kneel down in the beginning which seem to be missing from cmangos

0:19
when you select 'The Prophecy of Velen' he is supposed to do /talk animation, he doesn't on cmangos.

0:27
when he turns around after you have accepted 'Nightstalker clean Up, Isle 2...' he is supposed to do /point emote
on cmangos he just turns around.

0:29
Tuluun is supposed to greet you with /shrug animation, not /talk animation
(this may be do to the fact he is missing his gossip menu from cmangos and it going straight to his training menu)

~~0:47
Items presented in wrong order~~ core issue already open in several other quality controls

1:20
The furbolgs run speed is slightly too fast on cmangos, it should be possible to catch up with him if you're behind, but he seems to run as fast as, if not faster than the player

1:39
The furbolgs walk speed seem a bit too fast on cmangos.

2:56
'blurry' vision is missing on cmangos (the same kind of vision it seems as on 'invisible' - perhaps you are invisible along with the furbolg you're following)
furbolg in cat form runs a bit too fast yet again it seems.

3:28
Talking to and acceping the next quest from the totem should not remove the cat form from you, in the video we see the player doing that manually
on cmangos it just vanished from me when I completed the quest (before accepting the next) - I'm sure there was time left on the aura.

3:37
the furbolg getting attacked here seems to be missing from cmangos.

4:37
some of the captive furbolg kids should be bigger than others, on cmangos the guy in this cage is barely half the size the guy in the video.
they seem to all be the same size on cmangos while they seem to vary in size on the video

6:37
Once in a while Engineer "Spark" Overgrind should outburst something soon followed by an emote.
I waited around here at least 15 minutes on cmangos, never happened once.

8:03
when you select the quest from the priestess menu she should do /talk animation, she doesn't.

**Comment by Grz3s** [comment]
```quote
0:10
 Anchorite Fateema is supposed to be part of the event that starts after completing the quest with Daedal,
 she is supposed to have a few conversation bits and kneel down in the beginning which seem to be missing from cmangos
```
This one is wrong...
Reason why u see her doin anything is because another player finished another quest (prev quest in your chain)... and u see mix of both events...
Your missing part comes from here:
https://www.youtube.com/watch?v=BGk9x8_H6II&index=2&list=PL28173C4849CA7E04   
watch from 4:59
;)

**Comment by Phatcat** [comment]
You are right, sorry about that one.

**Comment by Grz3s** [comment]
```quote
0:19
 when you select 'The Prophecy of Velen' he is supposed to do /talk animation, he doesn't on cmangos.
```
fixed* 

* - will update fix after all points from this issue resolved

**Comment by Grz3s** [comment]
```quote
0:27
 when he turns around after you have accepted 'Nightstalker clean Up, Isle 2...' he is supposed to do /point emote
 on cmangos he just turns around.
```
This is part of his quest details...
Click on quest (and leave it... do not press accept for few secs... you will see POINT emote:) - Some ppl reads detals -- some dont
Anyway its nothing to fix here

**Comment by Phatcat** [comment]
Yeah but if that was the case, wouldn't whatever emote he is supposed to do when you click accept override it, even if there's no emote to override it with.
if you slow down the video to 0.25 speed and watch really closely at the 0.27 time, the npc doesn't turn around until he HAS clicked accept, in which the npc immediately turns around and points.

**Comment by Grz3s** [comment]
becasuse .. emote and accept happened in same time... so you may see ... him going back to his original orientation with this emote

**Comment by Phatcat** [comment]
oh yeah, I can see that happening.

**Comment by Grz3s** [comment]
```quote
0:29
 Tuluun is supposed to greet you with /shrug animation, not /talk animation
 (this may be do to the fact he is missing his gossip menu from cmangos and it going straight to his training menu)
```
fixed*

**Comment by Grz3s** [comment]
```quote
2:56
 'blurry' vision is missing on cmangos (the same kind of vision it seems as on 'invisible' - perhaps you are invisible along with the furbolg you're following)
 furbolg in cat form runs a bit too fast yet again it seems.
```
I'm sad with this one... it worked beautiful before.... and sonce i fixed it ..someone did smth on core...and it doesnt work anymore:
Spell:
```code
ID - 30448 Shadow of the Forest
Effect 2:
BasePoints = 100
Targets (21, 0) (TARGET_SINGLE_FRIEND, NO_TARGET)
Aura Id 18 (SPELL_AURA_MOD_INVISIBILITY), value = 100, misc = 0 (0), miscB = 0, periodic = 0
```

**Comment by Grz3s** [comment]
```quote
3:37
 the furbolg getting attacked here seems to be missing from cmangos.
```
no its not...
creature 60693.. has long waypoints ...and that place is one of his stops:)

**Comment by Grz3s** [comment]
```quote
6:37
 Once in a while Engineer "Spark" Overgrind should outburst something soon followed by an emote.
 I waited around here at least 15 minutes on cmangos, never happened once.
```
fixed :)
