### ISSUE TITLE
Something is wrong with mobs speed

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#1001]
Their walking speed is to high?

Check zulfarak mobs that have waypoints for example, they have their speed 2 high.
Uldaman the same.

Even the random movement is 2 high

@Grz3s I need to poke you to this discussion

**Comment by al3xc1985** [comment]
Check for example 7000093 guid, see his random movement speed

**Comment by Grz3s** [comment]
> Check for example 7000093 guid, see his random movement speed

Fixed
Pls collect entrys of all suspected creatures.. so we can look at them on by one.

**Comment by al3xc1985** [comment]
Ok, I will but bare me today. I shall do it

**Comment by al3xc1985** [comment]
Zul'farak:

5649
5650
7246
7247
8095
7795
7272

**Comment by al3xc1985** [comment]
Uldaman

4852
4850
7078
4853
7022
4860
7012
7011
4849
4848
4853
7320
7321
7396
7397
4860
2748

**Comment by al3xc1985** [comment]
Done @Grz3s 
If I find more, I will open a new issue about speed
