### ISSUE TITLE
[Go Supply Crate, Stratholme] Server-side spell

### ISSUE THREAD

**Issue by NeatElves** [cmangos/wotlk-db#101]
go 176308 -> trap 175534 -> spell 16371
go 176304 -> trap 175535 -> spell 16369
go 176307 -> trap 175536 -> spell 16370
dbc 1.12.x
```sql
INSERT INTO spell_template(Id, Attributes, AttributesEx,AttributesEx2,AttributesEx3,ProcFlags,ProcChance,DurationIndex,Effect1,EffectImplicitTargetA1,EffectImplicitTargetB1,EffectRadiusIndex1,EffectApplyAuraName1,EffectMiscValue1,EffectMiscValueB1,EffectTriggerSpell1,IsServerSide,SpellName) VALUES
(16369,400,0,0,0,0,101,5,28,18,0,0,0,10461,64,0,1,'Bugs'),
(16370,400,0,0,0,0,101,5,28,18,0,0,0,10536,64,0,1,'Maggots'),
(16371,400,0,0,0,0,101,5,28,18,0,0,0,10441,64,0,1,'Rats');
```

**Comment by killerwife** [comment]
@MantisLord I remember you doing smth about this.

**Comment by Grz3s** [comment]
@NeatElves 
one is missing on your list:
176309  - > trap 175537 spell 16432

**Comment by NeatElves** [comment]
spell 16432 - there DBC)

**Comment by Grz3s** [comment]
Spells need to be added by core devs.. (we not adding spells direct into DB anymore)
Also i found another issue here:
@killerwife may be interested with this:
All these fake Supply Crates ... have traps linked to them, but in sniff theyre not spawned.
They show up only if player activate main object. Then spell is casted and trap despawns itself.
Also if i'll add that trap manualy ... spell is casted stright away (without interacting with object) - so this  only proofs .. that they must be spawned only if player click on main object.
