### ISSUE TITLE
Jammal'an the Prophet - Missing 1 Text?

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#1019]
https://www.wowhead.com/wotlk/npc=5710/jammalan-the-prophet#abilities;mode:normal
I think he is missing 1 text, I found only 3 listed on acid file. Maybe I a wrong

**Comment by AnonXS** [comment]
one comes from core script.

**Comment by al3xc1985** [comment]
ty

**Comment by AnonXS** [comment]
Also reference this file in your searches: 
![image](https://github.com/cmangos/wotlk-db/assets/19734826/a6a94f41-bdfb-401b-8f87-ac9cc43c5f1e)
