### ISSUE TITLE
Shadowmoon Warlock wrong script

### ISSUE THREAD

**Issue by killerwife** [cmangos/wotlk-db#102]
Shadowmoon warlocks cast spell on themselves 38442. This is wrong, we need to provide a target for this channel because the spell has SPELL_ATTR_EX_CHANNEL_TRACK_TARGET and these spells always require an external target. I am implementing a prototype for this attribute (creature will turn after target) and dont know without sniff who its supposed to cast at.
Since it was UDB code, I am asking here :)
If I am wrong about this, feel free to let me know.

**Comment by Grz3s** [comment]
Well... before ill go into this npc.. 
let me ask You...
Who told you ...that data you using is UDB?
I just look at this npc...
```sql
-- Shadowmoon Warlock (3.0.3 Official Data - Normal Log Only)
('1737101','17371','4','0','100','6','0','0','0','0','49','1','0','0','22','1','0','0','0','0','0','0','Shadowmoon Warlock - Enable Dynamic Movement and Set Phase 1 on Aggro'),
('1737102','17371','9','5','100','3','0','40','3300','4900','11','12739','1','0','0','0','0','0','0','0','0','0','Shadowmoon Warlock (Normal) - Cast Shadow Bolt (Phase 1)'),
('1737103','17371','9','5','100','5','0','40','3300','4900','11','15472','1','0','0','0','0','0','0','0','0','0','Shadowmoon Warlock (Heroic) - Cast Shadow Bolt (Phase 1)'),
('1737104','17371','9','5','100','7','9','80','1000','1000','49','1','0','0','0','0','0','0','0','0','0','0','Shadowmoon Warlock - Enable Dynamic Movement at 9-80 Yards (Phase 1)'),
('1737105','17371','9','0','100','7','0','8','1000','1000','49','0','0','0','0','0','0','0','0','0','0','0','Shadowmoon Warlock - Disable Dynamic Movement at 0-8 Yards'),
('1737106','17371','3','5','100','6','7','0','0','0','49','0','0','0','22','2','0','0','0','0','0','0','Shadowmoon Warlock - Disable Dynamic Movement and Set Phase 2 when Mana is at 7% (Phase 1)'),
('1737107','17371','3','3','100','7','100','15','1000','1000','22','1','0','0','0','0','0','0','0','0','0','0','Shadowmoon Warlock - Set Phase 1 when Mana is above 15% (Phase 2)'),
('1737108','17371','0','0','100','3','1100','7800','14800','30100','11','32197','4','33','0','0','0','0','0','0','0','0','Shadowmoon Warlock (Normal) - Cast Corruption'),
('1737109','17371','0','0','100','5','1100','7800','14800','30100','11','37113','4','33','0','0','0','0','0','0','0','0','Shadowmoon Warlock (Heroic) - Cast Corruption'),
('1737110','17371','0','0','100','7','6600','10700','14900','14900','11','13338','4','33','0','0','0','0','0','0','0','0','Shadowmoon Warlock - Cast Curse of Tongues'),
``` 
I also looked at his template_addon .. addon
movementScripts.... 
**0 about spell 38442** ??

**Comment by killerwife** [comment]
It was in file updatepack 406, maybe it got removed over time? I found it in creature addon template. I noticed this only by mistake when prototyping the C++                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the Orange network.                                                                                                                                                                                                                From: Grz3sSent: Wednesday, February 15, 2017 22:30To: cmangos/wotlk-dbReply To: cmangos/wotlk-dbCc: killerwife; AuthorSubject: Re: [cmangos/wotlk-db] Shadowmoon Warlock wrong script (#102)Well... before ill go into this npc..
let me ask You...
Who told you ...that data you using is UDB?
I just look at this npc...
-- Shadowmoon Warlock (3.0.3 Official Data - Normal Log Only)
('1737101','17371','4','0','100','6','0','0','0','0','49','1','0','0','22','1','0','0','0','0','0','0','Shadowmoon Warlock - Enable Dynamic Movement and Set Phase 1 on Aggro'),
('1737102','17371','9','5','100','3','0','40','3300','4900','11','12739','1','0','0','0','0','0','0','0','0','0','Shadowmoon Warlock (Normal) - Cast Shadow Bolt (Phase 1)'),
('1737103','17371','9','5','100','5','0','40','3300','4900','11','15472','1','0','0','0','0','0','0','0','0','0','Shadowmoon Warlock (Heroic) - Cast Shadow Bolt (Phase 1)'),
('1737104','17371','9','5','100','7','9','80','1000','1000','49','1','0','0','0','0','0','0','0','0','0','0','Shadowmoon Warlock - Enable Dynamic Movement at 9-80 Yards (Phase 1)'),
('1737105','17371','9','0','100','7','0','8','1000','1000','49','0','0','0','0','0','0','0','0','0','0','0','Shadowmoon Warlock - Disable Dynamic Movement at 0-8 Yards'),
('1737106','17371','3','5','100','6','7','0','0','0','49','0','0','0','22','2','0','0','0','0','0','0','Shadowmoon Warlock - Disable Dynamic Movement and Set Phase 2 when Mana is at 7% (Phase 1)'),
('1737107','17371','3','3','100','7','100','15','1000','1000','22','1','0','0','0','0','0','0','0','0','0','0','Shadowmoon Warlock - Set Phase 1 when Mana is above 15% (Phase 2)'),
('1737108','17371','0','0','100','3','1100','7800','14800','30100','11','32197','4','33','0','0','0','0','0','0','0','0','Shadowmoon Warlock (Normal) - Cast Corruption'),
('1737109','17371','0','0','100','5','1100','7800','14800','30100','11','37113','4','33','0','0','0','0','0','0','0','0','Shadowmoon Warlock (Heroic) - Cast Corruption'),
('1737110','17371','0','0','100','7','6600','10700','14900','14900','11','13338','4','33','0','0','0','0','0','0','0','0','Shadowmoon Warlock - Cast Curse of Tongues'),
I also looked at his template_addon .. addon
movementScripts....
0 about spell 38442 ??

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cmangos/wotlk-db","title":"cmangos/wotlk-db","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cmangos/wotlk-db"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Grz3s in #102: Well... before ill go into this npc.. \r\nlet me ask You...\r\nWho told you ...that data you using is UDB?\r\nI just look at this npc...\r\n```sql\r\n-- Shadowmoon Warlock (3.0.3 Official Data - Normal Log Only)\r\n('1737101','17371','4','0','100','6','0','0','0','0','49','1','0','0','22','1','0','0','0','0','0','0','Shadowmoon Warlock - Enable Dynamic Movement and Set Phase 1 on Aggro'),\r\n('1737102','17371','9','5','100','3','0','40','3300','4900','11','12739','1','0','0','0','0','0','0','0','0','0','Shadowmoon Warlock (Normal) - Cast Shadow Bolt (Phase 1)'),\r\n('1737103','17371','9','5','100','5','0','40','3300','4900','11','15472','1','0','0','0','0','0','0','0','0','0','Shadowmoon Warlock (Heroic) - Cast Shadow Bolt (Phase 1)'),\r\n('1737104','17371','9','5','100','7','9','80','1000','1000','49','1','0','0','0','0','0','0','0','0','0','0','Shadowmoon Warlock - Enable Dynamic Movement at 9-80 Yards (Phase 1)'),\r\n('1737105','17371','9','0','100','7','0','8','1000','1000','49','0','0','0','0','0','0','0','0','0','0','0','Shadowmoon Warlock - Disable Dynamic Movement at 0-8 Yards'),\r\n('1737106','17371','3','5','100','6','7','0','0','0','49','0','0','0','22','2','0','0','0','0','0','0','Shadowmoon Warlock - Disable Dynamic Movement and Set Phase 2 when Mana is at 7% (Phase 1)'),\r\n('1737107','17371','3','3','100','7','100','15','1000','1000','22','1','0','0','0','0','0','0','0','0','0','0','Shadowmoon Warlock - Set Phase 1 when Mana is above 15% (Phase 2)'),\r\n('1737108','17371','0','0','100','3','1100','7800','14800','30100','11','32197','4','33','0','0','0','0','0','0','0','0','Shadowmoon Warlock (Normal) - Cast Corruption'),\r\n('1737109','17371','0','0','100','5','1100','7800','14800','30100','11','37113','4','33','0','0','0','0','0','0','0','0','Shadowmoon Warlock (Heroic) - Cast Corruption'),\r\n('1737110','17371','0','0','100','7','6600','10700','14900','14900','11','13338','4','33','0','0','0','0','0','0','0','0','Shadowmoon Warlock - Cast Curse of Tongues'),\r\n``` \r\nI also looked at his template_addon .. addon\r\nmovementScripts.... \r\n**0 about spell 38442** ??"}],"action":{"name":"View Issue","url":"https://github.com/cmangos/wotlk-db/issues/102#issuecomment-280145273"}}}

**Comment by Grz3s** [comment]
406 is quite old updatepack :)
Currently he has 0 in addon

**Comment by killerwife** [comment]
okay, then just lemme know if I should close issue and remove from addon or if it needs a script                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the Orange network.                                                                                                                                                                                                                From: Grz3sSent: Wednesday, February 15, 2017 22:43To: cmangos/wotlk-dbReply To: cmangos/wotlk-dbCc: killerwife; AuthorSubject: Re: [cmangos/wotlk-db] Shadowmoon Warlock wrong script (#102)406 is quite old updatepack :)
Currently he has 0 in addon

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cmangos/wotlk-db","title":"cmangos/wotlk-db","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cmangos/wotlk-db"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Grz3s in #102: 406 is quite old updatepack :)\r\nCurrently he has 0 in addon"}],"action":{"name":"View Issue","url":"https://github.com/cmangos/wotlk-db/issues/102#issuecomment-280149256"}}}

**Comment by Grz3s** [comment]
Ok.
1st: i looked at Blood Furnance sniff.... "Shadowmoon Warlocks" not casting this spell even once.
(funny that spell name is ID - 38442 Shadowmoon Warlock) ;)

2nd:
According to few sources... spell is casted by: 
Shadowmoon Darkweaver <Servant of Illidan> in Shadowmoon Valley. (not scripted in EAI)
- his template addon has this spell in AURAS. (now u know why he casts this on himself)
And now: let me show you sniff:
```quote

ServerToClient: SMSG_AURA_UPDATE (0x3A24)
GUID: Full: 0xF13056410033D599 Type: Creature Entry: 22081 Low: 3397017
[0] Slot: 0
[0] Spell ID: 38442 (38442)
[0] Flags: EffectIndex0, NotCaster, Positive, Unk100 (281)
[0] Level: 69
[0] Charges: 0

ServerToClient: SMSG_SPELL_START (0x212D)
Caster GUID: Full: 0xF13056410033D599 Type: Creature Entry: 22081 Low: 3397017
Caster Unit GUID: Full: 0xF13056410033D599 Type: Creature Entry: 22081 Low: 3397017
Cast Count: 0
Spell ID: 38442 (38442)
Cast Flags: HasTrajectory, Unknown3 (10)
Time: 0
Time2: 0
Target Flags: Self (0)

ServerToClient: SMSG_SPELL_GO (0x6425)
Caster GUID: Full: 0xF13056410033D599 Type: Creature Entry: 22081 Low: 3397017
Caster Unit GUID: Full: 0xF13056410033D599 Type: Creature Entry: 22081 Low: 3397017
Cast Count: 0
Spell ID: 38442 (38442)
Cast Flags: Unknown3, Unknown7 (264)
Time: 0
Time2: 3756856492
Hit Count: 1
[0] Hit GUID: Full: 0xF13056410033D599 Type: Creature Entry: 22081 Low: 3397017
Miss Count: 0
Target Flags: Unit (2)
Target GUID: 0x0
```

**Comment by killerwife** [comment]
Ok, then it works as intended.
