### ISSUE TITLE
Atal'ai High Priest - Fear spell?

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#1020]
![image](https://github.com/cmangos/wotlk-db/assets/6240049/2488871b-0a1b-4146-b0be-11c828d9a5e7)
https://www.wowhead.com/wotlk/npc=5273/atalai-high-priest#comments;mode:normal

Can anyone confirm this fear spell 6 sec cast time for this guys?

**Comment by AnonXS** [comment]
misguided comment, the Atal'ai Deathwalker 5271 fear, these dont.

**Comment by al3xc1985** [comment]
I was thinking to that 2. I saw them that they do have that fear. Ty for conformation
