### ISSUE TITLE
Atal'ai Warrior - Patrols?

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#1021]
https://www.wowhead.com/wotlk/npc=5256/atalai-warrior#comments;mode:normal
![image](https://github.com/cmangos/wotlk-db/assets/6240049/84c71098-a816-4b24-ab7b-5cc072004c60)

Do we miss some patrols on that corridor?
I checked it and true is that there are non patroling

**Comment by AnonXS** [comment]
1090103 + 1090104
