### ISSUE TITLE
Loro - Missing 1 Abiltiy

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#1024]
https://www.wowhead.com/wotlk/npc=5714/loro#comments;mode:normal
![image](https://github.com/cmangos/wotlk-db/assets/6240049/12e5c477-0607-47f5-9ff8-4d34b4e66ed1)

**Comment by al3xc1985** [comment]
I found this line on a different mob
('527701','5277','11','0','100','0','0','0','0','0','0','0','11','12099','0','34','0','0','0','0','0','0','0','0','Nightmare Scalebane - Cast Shield Spike on Spawn'),

This might be what he is missing

**Comment by AnonXS** [comment]
('571401','5714','11','0','100','0','0','0','0','0','0','0','11','12782','0','34','11','9205','0','34','0','0','0','0','Loro - Cast Shield Spike, Hate to Zero (Hate to Zero) on Spawn'),

**Comment by al3xc1985** [comment]
I am sorry AnonXS I read his abilities like several times, and icould not notice any difference. But yes, that ability is there.
Ok, bed time
