### ISSUE TITLE
Anger'rel - Missing Enrage Ability

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#1026]
https://www.wowhead.com/wotlk/npc=9035/angerrel#abilities;mode:normal

**Comment by AnonXS** [comment]
![image](https://github.com/cmangos/wotlk-db/assets/19734826/dcd8e060-5576-4c88-9891-d46c7754f665)
![image](https://github.com/cmangos/wotlk-db/assets/19734826/c4641ceb-9f4b-4fa5-9abd-67654ff72f57)
