### ISSUE TITLE
Hate'rel - Missing 1 Abiltiy

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#1030]
https://www.wowhead.com/wotlk/npc=9034/haterel
![image](https://github.com/cmangos/wotlk-db/assets/6240049/8372e29f-e43d-45e1-928b-7ee5ff3338a1)

**Comment by AnonXS** [comment]
![image](https://github.com/cmangos/wotlk-db/assets/19734826/86c09243-331c-4f84-bd14-d552c2e619f6)

**Comment by al3xc1985** [comment]
why are this spells integrated in creature_Template_Addon?

I am looking in spelllist in acid, now in template_Addon? why?
