### ISSUE TITLE
A Time for Negotiation... quest npc missed

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#104]
http://www.wowhead.com/quest=10682/a-time-for-negotiation

**Comment by NeatElves** [comment]
Waypoint movement

**Comment by rmzV** [comment]
where i can find him?

**Comment by NeatElves** [comment]
http://www.wowhead.com/npc=21981/overseer-nuaar#map

**Comment by rmzV** [comment]
i already saw this link and use \tar metod.. 
but today i rechecked and found him at around 64/44 and i have a fiiling that he was just spawn..  is it possibe that he spawn only whe some one near spawn location (couse i never see him on the road=)
