### ISSUE TITLE
Question - BRD Questline tier 0.5

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#1076]
Do we have this implemented?

![image](https://github.com/cmangos/wotlk-db/assets/6240049/56bf6ad1-a34e-4cd0-8c50-9602da7c27e3)

**Comment by al3xc1985** [comment]
I beleive this is the quest
https://www.wowhead.com/wotlk/quest=9015/the-challenge

**Comment by rmzV** [comment]
Probably yes, becouse last time i was on this q chain it was working.
now i am on https://www.wowhead.com/classic/quest=8945/dead-mans-plea  on my second playthrought


___
question is:
there is a "lever arm" under brd arena... what does this thing do?

**Comment by al3xc1985** [comment]
@rmzV what is you nickname on discotd?

**Comment by al3xc1985** [comment]
> Probably yes, becouse last time i was on this q chain it was working. now i am on https://www.wowhead.com/classic/quest=8945/dead-mans-plea on my second playthrought with is not works (no q giver etc)
> 
> question is: there is a "lever arm" under brd arena... what does this thing do?
Do u play all the game quest by quest? Classic tbx wotlk?

**Comment by rmzV** [comment]
yes. 
i was using (for example)
https://wowwiki-archive.fandom.com/wiki/Borean_Tundra_quests
wowwiki to test quest chains not dropped in the middle.

atm on one char i tested classic, tbc and wotlk (expt icecrown(quests not even linked) and half of stormpeaks(it has broken quest chains)
and on second char i finished tbc. (around 15 quests not fixed (for tbc and classic))

And need to say i played horde side, as soon played horde on live=)

**Comment by al3xc1985** [comment]
@rmzV that is an impressive work u do! 
Why I am asking this is cause I want to focus on checking mobs spell,yells, scripts, special cases, etc instead of playing actually the game. It would be a tremendous work for me to test out the quests 2, at least for now.
I am in a hurry to check all classic content as I heard that wotlk will be gone and cata is coming. As of after the cata launch we still have same tbc and same wotlk until late expansion. But classic is very important from the point I described earlier to me.

I am glad to hear that u are completing my work on that side.

Have you thought on doing same testing on alliance side? chking quests classic-tbc-wotlk ?

**Comment by rmzV** [comment]
@al3xc1985 , thanks!
wotlk will be gone on live? or in mangos?

most of quest testing done. (as i say earlier expt 2 last location and may be some race/class/profession specific quests(

i never played ally on live till may be lvl 15. so i dont really know what quest they have(( so probably answer is no(

**Comment by al3xc1985** [comment]
I guess that burdenn is still onn my sholders

**Comment by rmzV** [comment]
profession quest https://www.wowhead.com/wotlk/quests/professions#0+9+12
class quests https://www.wowhead.com/wotlk/quests/classes#0+9+12

for start need to check if this quests are in database and has proper profession/class/side flag

**Comment by al3xc1985** [comment]
I wish you good luck with that. You allready have a tons of work to be checked
