### ISSUE TITLE
10204!Bloodgem Crystals

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#109]
http://www.wowhead.com/quest=10204/bloodgem-crystals
doesnot work
right click on quest item and nothing

**Comment by offl** [comment]
Netherstorm Crystal Target level should be 1, not 70.
Currently the spell can resist due to high level.

**Comment by Grz3s** [comment]
Netherstorm Crystal Target has lvl 1 in this DB.
Also issue is with spell itself (attributes) somehow ... if player is not in exact line(orientation) with target...
attribute (SPELL_ATTR_EX_CHANNEL_TRACKING_TARGET) ... will change players orientation... and this will brake casting. 
You can use this... (koz correct orien will be set after first cast) 
You can cast again... and spell will go fine.

**Comment by Grz3s** [comment]
fixed
