### ISSUE TITLE
NPC 26477 & 28260 - set correct modelid on Spawn

### ISSUE THREAD

**Issue by NeatElves** [cmangos/wotlk-db#11]
http://www.wowhead.com/npc=26477/dead-mage-hunter
http://www.wowhead.com/npc=28260/defeated-argent-footman

It is necessary to give them a model.
Now it is a rabbit or a imp with a weapons.)))

``` sql
INSERT INTO `creature_ai_scripts` (`id`, `creature_id`, `event_type`, `event_inverse_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action1_type`, `action1_param1`, `action1_param2`, `action1_param3`, `action2_type`, `action2_param1`, `action2_param2`, `action2_param3`, `action3_type`, `action3_param1`, `action3_param2`, `action3_param3`, `comment`) VALUES
(2647701, 26477, 11, 0, 100, 0, 0, 0, 0, 0, 3, 26476, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Dead Mage Hunter - set correct modelid on Spawn'),
(2826001, 28260, 11, 0, 100, 0, 0, 0, 0, 0, 3, 28259, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Defeated Argent Footman - set correct modelid on Spawn');
```

**Comment by bdebaere** [comment]
@NeatElves Can you explain why this is not done in the creature_template table?

**Comment by NeatElves** [comment]
all the data in this table are taken from the sniff

**Comment by Grz3s** [comment]
its done by serverside spell: 47090 "Dead Mage Hunter Transform"
spell does nothing else than transform ..to another entry 26476 .. that contain all 4 req. models
(so fix can be accepted)

Sory that this took so long but... i had to find good sniff to make sure .. its all fine ;)
