### ISSUE TITLE
locales question

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#1105]
hello!
can you please explain this string
INSERT INTO `locales_creature` (`entry`, `name_loc1`, `name_loc2`, `name_loc3`, `name_loc4`, `name_loc5`, `name_loc6`, `name_loc7`, `name_loc8`, `subname_loc1`, `subname_loc2`, `subname_loc3`, `subname_loc4`, `subname_loc5`, `subname_loc6`, `subname_loc7`, `subname_loc8`) VALUES

name_loc1, name loc2  this is different languages? with one is witch?
and second: does all different locales must have different folders? or all locales can be done in one file?

**Comment by Grz3s** [comment]
CmangoS has wiki:
https://github.com/cmangos/issues/wiki
https://github.com/cmangos/issues/wiki/localization_lang
https://github.com/cmangos/issues/wiki/locales_creature

**Comment by rmzV** [comment]
okey thanks
1 | Korean
2 | French
3 | German
4 | Chinese
5 | Taiwanese
6 | Spanish
7 | Mexico
8 | Russian
