### ISSUE TITLE
Smolderthorn Mystic - Missing all his abilites

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#1119]
https://www.wowhead.com/wotlk/npc=9239/smolderthorn-mystic#abilities;mode:normal
![image](https://github.com/cmangos/wotlk-db/assets/6240049/759770b9-6bf3-4a7e-b2f9-02f0c735ecfe)

**Comment by MantisLord** [comment]
Looks like the creature does have EAI currently:

`select * from wotlkmangos.creature_ai_scripts where creature_id IN (9239);`

Smolderthorn Mysic - Cast Chain Heal on Friendly Missing HP
Smolderthron Mystic - Cast Chain Lighting

Maybe there's something wrong with these two existing scripts?

**Comment by al3xc1985** [comment]
hmm, there is a problem in their name, that I could not find them
