### ISSUE TITLE
10426! Flora of the Eco-Domes

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#112]
http://www.wowhead.com/quest=10426/flora-of-the-eco-domes
flovers mutating but killing them doesnot count

**Comment by NeatElves** [comment]
```sql
UPDATE  `quest_template` SET  `ReqSpellCast1` =  '0' WHERE  `entry` =10426;
```

**Comment by killerwife** [comment]
This quest has a special completion spell, 40347 that gives credit.

**Comment by NeatElves** [comment]
Really ?))) 
http://www.wowhead.com/spell=40347  ->  **talbuk-tagging-credit**

**Comment by killerwife** [comment]
Crap, @NeatElves I read the title wrong. Sooooorryyyyyy.
