### ISSUE TITLE
instance_dungeon_encounters is missing

### ISSUE THREAD

**Issue by apo126** [cmangos/wotlk-db#114]
I applied WoTLKDB_1_0_12943.sql, 601-765 updates to Mangos, but still has below error:

2017-02-28 12:10:48 Loading Dungeon Encounters...
2017-02-28 12:10:48 ERROR:SQL: SELECT MAX(id) FROM instance_dungeon_encounters
2017-02-28 12:10:48 ERROR:query ERROR: Table 'mangos.instance_dungeon_encounters' doesn't exist
2017-02-28 12:10:48 ERROR:Error loading instance_dungeon_encounters table (not exist?)

**Comment by NeatElves** [comment]
https://github.com/cmangos/wotlk-db/issues/96

**Comment by Grz3s** [comment]
I understand that you added everything manualy step by step.
In this case you also need to add 2 files:
(CORE)...\\\\sql\base\dbc\original_data\
DungeonEncounter.sql
Spell.sql

This procedure happens automatically if You'll use InstallFullDB.sh tool

Pls remember that we prefer quicker and clean method that is explained here:
https://github.com/cmangos/wotlk-db#installation
GL.

**Comment by apo126** [comment]
@NeatElves @Grz3s sql/base/dbc/original_data is not the usual directory where the sql updates are placed. Anyway, thank you very much for your help!

**Comment by Grz3s** [comment]
blame core devs for that ;)
