### ISSUE TITLE
Darkmaster Gandling - Missing Aggro text

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#1167]
https://www.wowhead.com/wotlk/npc=1853/darkmaster-gandling#abilities;mode:normal
![image](https://github.com/cmangos/wotlk-db/assets/6240049/a52707c0-497a-41ae-95e1-77da85140423)

**Comment by evil-at-wow** [comment]
It's not something he says when you aggro him though, but when he spawns (after killing the other bosses in that room/area).

**Comment by al3xc1985** [comment]
which one? And I will check

**Comment by AnonXS** [comment]
![image](https://github.com/cmangos/wotlk-db/assets/19734826/77f5e56f-fe66-49a8-a8ea-1e4c911929f1)

**Comment by al3xc1985** [comment]
aha, so in script_texts ty
