### ISSUE TITLE
Lord Alexei Barov - Missing 1 spell

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#1170]
https://www.wowhead.com/wotlk/npc=10504/lord-alexei-barov#abilities;mode:normal
https://www.wowhead.com/wotlk/spell=15570/immolate
![image](https://github.com/cmangos/wotlk-db/assets/6240049/8751e8e6-7a47-4d9a-8bf2-36b66c1e1c4f)

**Comment by insunaa** [comment]
99% sure he doesn't have immolate and isn't supposed to have it either
