### ISSUE TITLE
Magistrate Barthilas - Missing all his abbilities

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#1182]
https://www.wowhead.com/wotlk/npc=10435/magistrate-barthilas#abilities;mode:normal
![image](https://github.com/cmangos/wotlk-db/assets/6240049/cdf29b1a-be79-4587-8570-51fb9b62e343)

**Comment by insunaa** [comment]
All of them exist in creature_ai_scripts
