### ISSUE TITLE
25771! Temperance

### ISSUE THREAD

**Issue by bomrox** [cmangos/wotlk-db#119]
http://wowroad.info/?spell=25771
if a paladin uses a "hand of protection, Divine shield, lay on hands and divine protection."
If "hand of protection" or "Laying on of hands" used on ally, then it will be "Temperance". 
"Temperance" on the ally prevents the paladin to use his gift, as if the Forbearance hanging on the paladin.
Only still impossible to use "Wrath of kings".

**Comment by NeatElves** [comment]
core issues here - https://github.com/cmangos/issues/issues

**Comment by Grz3s** [comment]
not a DB issue
