### ISSUE TITLE
Quality Control against a 'Lets play' WoW Draenei Shaman 1 - 80 [Video 4/142]

### ISSUE THREAD

**Issue by Phatcat** [cmangos/wotlk-db#12]
https://www.youtube.com/watch?v=Tpo6XhwwauY&index=4&list=PL28173C4849CA7E04

4:29
~~Right on the same spot as the orb thing there's a battered chest on cmangos.
probably objects shouldn't be allowed to spawn on top of each other like that? It's really immersion breaking having objects clip through eachother like that.~~ **Invalid**

4:57
No level 10 class quest in 3.3.5a ? =/
It's called 'Call of Fire' (ID: 9464) - (Call of Fire (ID: 9462) is skippable)

5:16
~~the clothing for the draenei repairing the building in the background is brown on cmangos; it doesn't look brown at all in the video.~~ **Invalid**

6:14
When you select 'complete quest' he should do an animation as he will go directly to offering up the follow-up, on cmangos he doesn't. I can't quite make out the animation..

6:42
Farii is not standing in the right spot (look at the floor markings)

**Comment by Grz3s** [comment]
> 4:29
 Right on the same spot as the orb thing there's a battered chest on cmangos.
 probably objects shouldn't be allowed to spawn on top of each other like that? It's really immersion breaking having objects clip through eachother like that.

Special for you..i went there with my .. trial acc... to check it :).. and look what i found :)
https://www.youtube.com/watch?v=Hnztv-RaXfI&feature=youtu.be
