### ISSUE TITLE
Death Talon Overseer - Immunities

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#1210]
![image](https://github.com/cmangos/wotlk-db/assets/6240049/a3617e5d-1d09-48bf-bcb2-af554bc20314)
https://www.wowhead.com/wotlk/npc=12461/death-talon-overseer#comments;mode:40player

**Comment by al3xc1985** [comment]
Question: Do they use in game this?
![image](https://github.com/cmangos/wotlk-db/assets/6240049/7a95a436-0079-4386-9b29-e24d7666631d)

**Comment by insunaa** [comment]
It's in creature_template_addon
