### ISSUE TITLE
Master Elemental Shaper Krixix - Missing Loot

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#1213]
https://www.wowhead.com/wotlk/npc=14401/master-elemental-shaper-krixix#drops;mode:40player
Currently he drops only money, and as far as I know and found in db he has that book to drop if u have BS. But nothing on the list is in there in db

**Comment by insunaa** [comment]
he doesn't drop the book. he teaches a player the skill when mind controlled. dropping the book came with cata or mop, pretty sure

**Comment by insunaa** [comment]
checked the loot table, he does drop the book when you have blacksmithing

**Comment by insunaa** [comment]
he has no other loot
