### ISSUE TITLE
Master Elemental Shaper Krixix - Missing Loot

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#1216]
https://www.wowhead.com/wotlk/npc=14401/master-elemental-shaper-krixix#drops;mode:40player

Missing the rest of his loot

![image](https://github.com/cmangos/wotlk-db/assets/6240049/0bac1e0c-623d-4bbf-8eb5-875a192208cc)

**Comment by insunaa** [comment]
he has no other loot.
wowhead data is wrong

**Comment by al3xc1985** [comment]
ok, ty
