### ISSUE TITLE
Lava Surger - Their charge ability Question

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#1219]
https://www.wowhead.com/wotlk/npc=12101/lava-surger#comments;mode:40player
![image](https://github.com/cmangos/wotlk-db/assets/6240049/5ba3595d-f868-4054-95e9-ea85e16812de)

As far as I understand during the fight with them, they will randomly charge a new target. Do we got this?
I can't test this alone

**Comment by insunaa** [comment]
Yes
