### ISSUE TITLE
Anubisath Defender - Missing Summon Player & Some abilties

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#1226]
https://www.wowhead.com/wotlk/spell=20477/summon-player
https://www.wowhead.com/wotlk/npc=15277/anubisath-defender#abilities;mode:40player

**Comment by al3xc1985** [comment]
I also found that they miss the reflect spells, enrage spell

**Comment by insunaa** [comment]
Implemented in SD2
