### ISSUE TITLE
Anubisath Sentinel - Immunities

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#1227]
https://www.wowhead.com/wotlk/npc=15264/anubisath-sentinel#comments;mode:40player
![image](https://github.com/cmangos/wotlk-db/assets/6240049/8ebc72cb-6569-4947-b20d-087b161dce07)

**Comment by al3xc1985** [comment]
do they have mana burn?
![image](https://github.com/cmangos/wotlk-db/assets/6240049/d8f83f24-3de9-4fb1-9d04-b26fa1486d12)

**Comment by insunaa** [comment]
Implemented in SD2
