### ISSUE TITLE
Anubisath Warrior & Defender - Share Spawn

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#1228]
https://www.wowhead.com/wotlk/npc=15537/anubisath-warrior#comments
https://www.wowhead.com/classic/npc=15277/anubisath-defender

![image](https://github.com/cmangos/wotlk-db/assets/6240049/5ad826fe-5c8a-49c0-baca-e1c68481ed7e)

**Comment by insunaa** [comment]
This is not a shared spawn, this is a summoned creature that can be summoned by the Anubisath Defender in combat
