### ISSUE TITLE
Some Mobs in AQ - Spell Question

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#1229]
Arygos
https://www.wowhead.com/wotlk/npc=15380/arygos#abilities
https://www.wowhead.com/wotlk/spell=25149/arygoss-vengeance

Caelestrasz
[k](https://www.wowhead.com/wotlk/npc=15379/caelestrasz#abilities)
https://www.wowhead.com/wotlk/spell=25150/molten-rain

Merithra of the Dream
https://www.wowhead.com/wotlk/npc=15378/merithra-of-the-dream#abilities
https://www.wowhead.com/wotlk/spell=25145/merithras-wake

He is using this spell, what is this?

**Comment by al3xc1985** [comment]
This npc's as I read aren't they involved in War of the Effort event?
And there is where they use those spells?

**Comment by insunaa** [comment]
these mobs each exist twice, once in the 10 hour war event where they're shown fighting some scarab things and then again as quest givers that do nothing except stand around inside of aq40 at the end behind cthun
