### ISSUE TITLE
4506!Corrupted Sabers 

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#123]
http://www.wowhead.com/quest=4506/deprecated-corrupted-sabers
relised cat near well.. nothing happen. cat doesnot move

**Comment by Grz3s** [comment]
Quest is scripted by sd2... 
With recent changes in core more and more sd2 scripts stops working correctly...

**Comment by xfurry** [comment]
> With recent changes in core more and more sd2 scripts stops working correctly...

@Grz3s can you point to the changes that made this quest stop working? Is this about the pet related changes?

**Comment by Grz3s** [comment]
hi @xfurry ..i hope you're well...
@killerwife could explain you more about it...
But ...it can be solved  by:
```code
void JustRespawned() override {}
```

**Comment by xfurry** [comment]
Thanks @Grz3s . I hope you are also well. 
Poke @killerwife to explain the details about this, and why we need to fix it like that.

**Comment by killerwife** [comment]
https://github.com/cmangos/mangos-tbc/commit/839ffa6cc212757faa6448c544b514db2f6aae1a#commitcomment-19930640

https://github.com/cmangos/issues/issues/1218

Affects both EscortAI and FollowerAI

**Comment by xfurry** [comment]
Ok, I remember now (feels like a long time ago).
Will investigate this during the next days.

PS. You promised something about a PR which implements conditions based on pvp scripts.

**Comment by cala** [comment]
Poking one this one as I was pleased to see updates from @xfurry recently. 😉

**Comment by xfurry** [comment]
Ok, I'll assign this to myself. I will check it out soonish.

**Comment by rmzV** [comment]
working as for now
issues can be closed
