### ISSUE TITLE
Locales name_loc8_creatures

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#1238]
[locales_creature_russian.csv](https://github.com/cmangos/wotlk-db/files/13504737/locales_creature_russian.csv)

Generated based on "creature_template" entry
and sourced from wowhead 
https://www.wowhead.com/wotlk/ru/npc=entry

do i need to reformat it as 
"-- Table `locales_creature`
--

INSERT INTO `locales_creature` (`entry`, `name_loc1`, `name_loc2`, `name_loc3`, `name_loc4`, `name_loc5`, `name_loc6`, `name_loc7`, `name_loc8`, `subname_loc1`, `subname_loc2`, `subname_loc3`, `subname_loc4`, `subname_loc5`, `subname_loc6`, `subname_loc7`, `subname_loc8`) VALUES
"??

also there is some creatures that have no translation and cant be found on wowhead. we can keep it as is or can completely remove?

**Comment by rmzV** [comment]
@Grz3s i would like to have feedback from you.

**Comment by rmzV** [comment]
i see "25","Mithril Mechanical Dragonling"  but wowhead doesnot have translation for it... we can remove rows with no translation..

**Comment by Grz3s** [comment]
Locales are not part of main goal here...Our main focus, is to have English ver completed*. So sory, but i wont help you with this.. as i never did anything with them anyway.

**Comment by rmzV** [comment]
[locales_creature_russian2.csv](https://github.com/cmangos/wotlk-db/files/13539824/locales_creature_russian2.csv)
 clean up..

**Comment by rmzV** [comment]
[locales_creature.txt](https://github.com/cmangos/wotlk-db/files/13543638/locales_creature.txt)
REady, replace txt with sql

**Comment by rmzV** [comment]
@Grz3s what is ""locales_page_text"" wowhead equivalent?

**Comment by Grz3s** [comment]
`locales_page_text` = `page_text` = https://github.com/cmangos/issues/wiki/page_text

**Comment by rmzV** [comment]
ty, but i looking for something like
https://www.wowhead.com/page_text=16

cant find equivalent((

**Comment by Grz3s** [comment]
Wowhead is the last place i would look for data .. (only if no other source available - and even then i would search for other source to confirm what its there). You trust it to much.. and wont acknowledge whats not te right way.
Anyway:

`page_text` - can be found in your clinet `cache\WDB\...\pagetextcache.wdb`
So if you have `russian client` (if this is the one you want ofc)  .. and you played a lot on ClassicWotlk ..Your client collected that data there. (do not bother to look at our 3.3.5 cache - koz is collected from our DB) 

Look here:
https://github.com/cmangos/issues/wiki/Pagetextcache

**Comment by rmzV** [comment]
ty for clarification.
ill never played on Ru-servers, so no cache for me:(

not really trust it, but it was easiest way for scrapping... if you can point me another source, i can compare it with what i already have((

**Comment by rmzV** [comment]
https://www.wowhead.com/wotlk/ru/item=10576/%D0%BC%D0%B8%D1%84%D1%80%D0%B8%D0%BB%D0%BE%D0%B2%D1%8B%D0%B9-%D0%BC%D0%B5%D1%85%D0%B0%D0%BD%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9-%D0%B4%D1%80%D0%B0%D0%BA%D0%BE%D0%BD%D1%87%D0%B8%D0%BA


entry 25 == 10576?
