### ISSUE TITLE
Misha - Should sit

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#1247]
https://www.wowhead.com/wotlk/npc=10204/misha
https://youtu.be/RffZE2Jr72E?t=1462

**Comment by AnonXS** [comment]
![image](https://github.com/cmangos/wotlk-db/assets/19734826/c5ae0fe4-cdb6-4e80-964e-cfeaa61b474e)

changes between stats, do you even look at anything?
