### ISSUE TITLE
11174! Corrosion Prevention 

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#126]
http://www.wowhead.com/quest=11174/deprecated-corrosion-prevention
test every recommendations in comments.. quest doesnot work?

**Comment by Grz3s** [comment]
Can't be... @xfurry and I .. we worked so hard on this one... i'll check what is broken this time :o

**Comment by xfurry** [comment]
@rmzV can you describe the current behavior of the quest?

The only reason on which I can think that this might not work, is due to the aura stacking. Maybe poke @warlockbugs about this.

**Comment by Warlockbugs** [comment]
WotLK core does not have aura stacking patch applied. Core still uses legacy "same icon" and hardcoded hacks. I am not currently working on WotLK port, because vanilla and tbc cores still have issues as is. However, positive/negative detection was upgraded to an improved targetid-based dynamic conception. I am not aware of potential conflicts for quests, unless it involves heavy neutral target interactions, which is not supported by existing friend/enemy relations code and most likely will require temporary placeholder until relation issues are taken care of.

**Comment by rmzV** [comment]
@xfurry 
i trued:
1)stay near core get charge and then use q.item on ozzie
2)"If you stand near the Core, get an ooze to attack you, DONT kill it, instead start the Channeling on it, then target another ooze (Far away) the 2nd ooze will pop instead of the one attacking you... do this till you have 9, then pop the last one (thats attacking you)..."
and this wowhed method

**Comment by Grz3s** [comment]
ok this STRANGE:////
Let me explain mehanic...
1.Player uses item. on its traget (spell:42489)
Spell 42489 is scripted in sd2 src/game/SpellEffects.cpp 
```code
Effect 0: Id 3 (SPELL_EFFECT_DUMMY)
BasePoints = 42483
Targets (25, 0) (TARGET_DUELVSPLAYER, NO_TARGET)

Effect 1: Id 3 (SPELL_EFFECT_DUMMY)
BasePoints = 42490
Targets (1, 0) (TARGET_SELF, NO_TARGET)

Effect 2:  NO EFFECT
```
Spell ... 42483 should be executed only if aura from 42490 is active on player (**this part work fine**)

2.
Spell: ID - 42483 Ooze Channel
```code
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 1
Targets (25, 0) (TARGET_DUELVSPLAYER, NO_TARGET)
Aura Id 23 (SPELL_AURA_PERIODIC_TRIGGER_SPELL), value = 1, misc = 0 (0), miscB = 0, periodic = 5000
   Trigger spell (42485) End of Ooze Channel. Chance = 101
```
should be casted on creature... (channel = 5secs) and after that time spell 42485 is casted to kill creature and 42486 - gives player credit.

And here comes our problem:
- if i'll use item... all goes fine up to moment where 42483 cast 42485 (it simply not goes anywhere..no idea why)....
- now (funny) .. if ill cast spell 42483 (manualy: typing .cast 42483 on our creature)... all goes fine .. and credit is given...

Anyone has any idea?? PLS

**Comment by Grz3s** [comment]
Fixed in Core
