### ISSUE TITLE
Armored Gryphon Destroyer - Should stand flying

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#1281]
Guid: 
97063
68907
68908

https://youtu.be/Iqgy5pLTo6I?t=7935
https://www.wowhead.com/wotlk/npc=19324/armored-gryphon-destroyer#comments
![image](https://github.com/cmangos/wotlk-db/assets/6240049/21996a77-e7a4-474e-a1a7-122908b7c370)

**Comment by al3xc1985** [comment]
68908
https://youtu.be/Iqgy5pLTo6I?t=7863
![image](https://github.com/cmangos/wotlk-db/assets/6240049/8308e353-ca1e-4482-be2d-7d42dbaecafd)

**Comment by Grz3s** [comment]
![image](https://github.com/cmangos/wotlk-db/assets/2374069/30f4a73a-eb02-4903-8951-b956909f8a5c)
guid 97063
He does flying animation... 
Can You Pls explain what exactly is not right here?

**Comment by al3xc1985** [comment]
I shall check back and reply

**Comment by al3xc1985** [comment]
Ya, my bad ty
