### ISSUE TITLE
Magelon

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#1296]
This is his real position in Wow. Picture from offi, my account

![image](https://github.com/cmangos/wotlk-db/assets/6240049/c7f77102-4379-44d7-b545-200938df125e)

**Comment by Grz3s** [comment]
Yes wotlk Classic .. Cata position used by them.
Its not first time that i see diffs between current wotlk and 3.3.5..
heres your proof:
sniff:
```code
Detected build: V3_2_2_10505
[1] Position: X: -3985.072 -13877.06 92.04234
[1] Orientation: 5.131268
```
https://youtu.be/aJWK6sSWWno?t=39

Luckly we got him in not exact this spot .. will correct it
