### ISSUE TITLE
Support question(

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#1301]
Hello!
i know that, inside game i can find npc id with command ".npc info"

is there are equivalents for ingame objects id and ingame items id?

thanks

ps also there are is workflow question:
if i must change some strings in sql file, right approach will be, creating sql-injection file with:
a) DELETE statement and INSERT INTO right string
b) UPDATE string with right data?

**Comment by Grz3s** [comment]
`.gobject near X`  - where x = range (example) `.gobject near 10` 
This will show you all objects in 10y range.

a) - DELETE/INSERT - when addin smth new.
b) - UPDATE to stuff that already exist
