### ISSUE TITLE
Gossip Typo

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#1307]
Can we fix this typo in db?
https://www.youtube.com/watch?v=zQfcTrZG9dY

**Comment by cpevors** [comment]
If the typo exists in Wrath of the Lich King, it would seem antithetical to the project's aims to correct it.

**Comment by Grz3s** [comment]
i think this explains whole situation there:
`She's nervous meeting the brave and valiant chosen one.`

and we'll keep it like that

**Comment by al3xc1985** [comment]
@Grz3s I never thought of that, you are right
