### ISSUE TITLE
Starting zones - Auto complete Quests - Not Working

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#1322]
For example Draenei Starting zones:

https://www.wowhead.com/wotlk/quest=9371/botanist-taerix
https://www.wowhead.com/wotlk/quest=9279/you-survived

If u want to complete the quest u can't

**Comment by al3xc1985** [comment]
I tested also the human zones for reference and same problem.

**Comment by insunaa** [comment]
What does "not working" mean

**Comment by al3xc1985** [comment]
If u press the complete button on the quest nothing happends

**Comment by insunaa** [comment]
```sql
UPDATE `quest_template` SET `QuestFlags`=`QuestFlags`|0x00010000 WHERE `entry`=9279;
```
Fixes the issue for this quest, but that would require further investigation. It's possible that "auto-accept" quests are implicitly also Auto-Complete, but I don't know, I don't have the sniff data for this

**Comment by al3xc1985** [comment]
We need a summon to make @Grz3s

**Comment by Grz3s** [comment]
your fix removes yellow complete question mark "?" from quest ending npc.

**Comment by insunaa** [comment]
Without the fix he doesn't have it either, but the quest is not completeable

**Comment by Grz3s** [comment]
Yes - Your core update made it like that 
https://github.com/cmangos/mangos-wotlk/pull/523/files

heres without it:
![image](https://github.com/user-attachments/assets/5284243e-c27d-4d02-a2a2-191a1a6d49e3)

**Comment by insunaa** [comment]
Is `AddQuest()` the wrong function for this task?

**Comment by Grz3s** [comment]
im not sain that smth is wrong.. Simply smth isnt right or still missing and need to be fixed.

**Comment by Grz3s** [comment]
3.3.5a data for simmilar quest (1st human quest - same issue)
```
ServerToClient: SMSG_QUEST_GIVER_QUEST_DETAILS (0x0188) Length: 693 ConnIdx: 0 Time: 09/19/2010 22:48:39.000 Number: 146894
QuestGiverGUID: Full: 0xF130000337000B0D Type: Creature Entry: 823 Low: 2829
InformUnit: 0x0
Quest ID: 783 (783)
Title: A Threat Within
Details: I hope you strapped your belt on tight, young $c, because there is work to do here in Northshire.$B$BAnd I don't mean farming.$B$BThe Stormwind guards are hard pressed to keep the peace here, with so many of us in distant lands and so many threats pressing close.  And so we're enlisting the aid of anyone willing to defend their home.  And their alliance.$B$BIf you're here to answer the call, then speak with my superior, Marshal McBride.  He's inside the abbey behind me.
Objectives: Speak with Marshal McBride.
Auto Accept: true
Quest Flags: 524296 (Sharable, AutoAccept)
Suggested Players: 0
Unknown byte: 0
Choice Item Count: 0
Reward Item Count: 0
Money: 0
XP: 40
Honor Points: 0
Honor Multiplier: 0
Spell Id: 0 (0)
Spell Cast Id: 0 (0)
Title Id: 0
Bonus Talents: 0
Arena Points: 0
Unk UInt32: 1
```

**Comment by kelbren** [comment]
I don't know if this is helpful, but the original m_QuestFlags was getting the value as a uint16 and the change to uint32 seems to have caused the issue. If I limit it to the lower 15 bits.. the quest works again. the wiki indicates that the field is only the first 15 bits as flag values. Perhaps there is some other logic somewhere that is using values out of this range? I dunno.. for now I am limiting the m_QuestFlags value to 16 bits and it seems to work properly.

**Comment by insunaa** [comment]
Not helpful, because limiting the questflags to 16 bits is just incorrect. I changed it to 32 bit for a reason, that is because WotLK uses 32 bit for quest flags, otherwise these 4 flags are cut off:
```cpp
    QUEST_FLAGS_AUTOCOMPLETE   = 0x00010000,                // auto complete
    QUEST_FLAGS_DISPLAY_IN_TRACKER = 0x00020000,            // has something to do with ReqItemId and SrcItemId
    QUEST_FLAGS_OBJ_TEXT       = 0x00040000,                // use Objective text as Complete text
    QUEST_FLAGS_AUTO_ACCEPT    = 0x00080000,                // quests in starting areas
```

**Comment by kelbren** [comment]
I should have looked in QuestDef.h, my bad. I assumed the wiki was up to date. ok, so there is something else afoot.
