### ISSUE TITLE
karahzhan problem

### ISSUE THREAD

**Issue by rmzVI** [cmangos/wotlk-db#1324]
playing on local server
first char entered KZ, second char (on other account) entered KZ, but both of them doesnot see each others. seems they are in different  KZ instances.
how i can fix it?

**Comment by insunaa** [comment]
what does that have to do with the wotlk db?

**Comment by Grz3s** [comment]
![321312](https://github.com/user-attachments/assets/30b8e0b1-5179-48dc-a10f-08f9ad85b3c2)
just did quick test and all works fine.
So:
- are you both in party? (raid group)?

**Comment by rmzVI** [comment]
Party. non raid group...

**Comment by Grz3s** [comment]
![32131](https://github.com/user-attachments/assets/43a8fe00-f4c8-4e83-b8c2-729da5445f92)
then how did you enter if youre not in raid group?

Let me help You.
`.gm off`

**Comment by al3xc1985** [comment]
kharazan in a raid, u must be in party and convert to raid, and enter after that

**Comment by rmzVI** [comment]
i will retest as soon as possible but earlier, we (same Party non raid group) visited Aq40 and Zul'Aman (ZA was opened with GM ON, but we entered in raid as Party group) so i thought that every Raid can be visited as party.

**Comment by al3xc1985** [comment]
1. u must convert your party into raid
2. use .GM OFF
3. enter the raid
4. u should see each other

**Comment by rmzVI** [comment]
@al3xc1985 thanks. i know how to convert to raid group.. the thing that missleads me: some other raids can be entered as party.

i have one more question:
at ZA, how can i change "gong requirement" so only one man will be enough to open doors?

**Comment by al3xc1985** [comment]
hmm, maybe I am wrong, but u can check 2 things:
1. Db requirement for that
2. the script file.....

This is not my strong point.. maybe Grz3s can guide you much better

**Comment by rmzVI** [comment]
Okey.. it was complicated.. other char have 2 bosses already killed((
SO ticket can be closed... only ZA question (change req. to 1 char)  still actual... may be @Grz3s  knows?))

**Comment by Grz3s** [comment]
All i can say here is - if u want to play this game in normal way, then do not use `.gm on` command as a shortcut. Not going to details about what `gm` is for. - if u want to use it then its fine... but expect lots of these kind "of let say" issues will appear.
