### ISSUE TITLE
Weird errors

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#1326]
![image](https://github.com/user-attachments/assets/77332713-43ac-45e6-926a-5b12fc9cf0e0)

They are unique to me. This is why it took my attention

**Comment by Grz3s** [comment]
both comming from TBC Nagrand event. 
Should be fixed with tbc backports (after im done with Icecrown). 
Thyyre on my `TO DO` list. (nothing to worry about)
