### ISSUE TITLE
small ZA question

### ISSUE THREAD

**Issue by rmzVI** [cmangos/wotlk-db#1330]
at ZA entrance you must use gong for eternal doors opening.
it requires 3 or 5 man (not sure about that)

question is: is it possible to change this parameter inside DB, so the instance will be available for solo players? (without gm commands)))
i would like to have this fix on my server((

**Comment by cpevors** [comment]
You'll want to navigate to the `gameobject_template` table of your `tbcmangos` database. Find `entry=187359` and set `data0` to `1`.
