### ISSUE TITLE
UBRS Gyth fight

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#139]
not sure if its a bug.. but if you kill Gluth boss too fast main boss doesnot shown up.. 

may be some emprovement can be done?

**Comment by NeatElves** [comment]
Learn how to correctly make requests:
It is desirable that! 
1. accurate full name in English
2. wowhead link 
3. accurate description (from blizz serv) how it should work

**Comment by rmzV** [comment]
sorry:(
links
http://www.wowhead.com/npc=10339/gyth#comments
http://wowwiki.wikia.com/wiki/Gyth

from first link "Be careful when you kill this guy, if you kill him too quickly, Rend won't spawn, and the gates won't open." so its off server problem too.. but mb it can be fixed on mangos?

**Comment by dagochen** [comment]
Well that doesn't sound like a bug, if it worked exactly like that on official servers?

**Comment by Grz3s** [comment]
Rend is summoned by this code:
```code
// Summon Rend
        if (!m_bSummonedRend && m_creature->GetHealthPercent() < 11.0f)
        {
            if (DoCastSpellIfCan(m_creature, SPELL_SUMMON_REND) == CAST_OK)
            {
                m_creature->RemoveAurasDueToSpell(SPELL_REND_MOUNTS);
                m_bSummonedRend = true;
            }
        }
```
11%  = 3560,7HP
Just wonder... can 80lvl (max wotlk) player do that dmg in one hit?

**Comment by Grz3s** [comment]
If Glyth is down to 11% HP script(spell) will summon Rend.
11% = 3560,7HP
If Player does higher dmg than this ... Rend wont spawn.
Maybe it wasn't a issue for Vanilla or TBC (TBC not sure be hinest :) )... but 100% this may be an issue for WoTLK 80lvl players... 
We can do safety check... in case *if* this will happen we can use:
```sql
-- Glyth
-- Safety spawn for Rend Blackhand .. in case if sd2 script wont work
DELETE FROM dbscripts_on_creature_death WHERE id = 10339;
INSERT INTO dbscripts_on_creature_death (id, delay, command, datalong, datalong2, datalong3, buddy_entry, search_radius, data_flags, dataint, dataint2, dataint3, dataint4, x, y, z, o, comments) VALUES
(10339,0,31,10429,100,0,0,0,0x08,0,0,0,0,0,0,0,0,''), -- terminate if alive
(10339,1,15,16328,0,0,0,0,0,0,0,0,0,0,0,0,0,'');
```
What You think?
