### ISSUE TITLE
Spawntime min & max issues

### ISSUE THREAD

**Issue by xfurry** [cmangos/wotlk-db#140]
@Grz3s I noticed that there are quite a lot of records throwing errors because of this:
```sql
select count(*) from creature where spawntimesecsmin > spawntimesecsmax;
select count(*) from gameobject where spawntimesecsmin > spawntimesecsmax;
```
records: 136270 | 101573

Any idea why is that? Is this core or DB related?

**Comment by Grz3s** [comment]
missing this commit?
https://github.com/cmangos/wotlk-db/commit/151a25f66f6fc0f69b2b7b50062264d8bfb4fbe3

**Comment by xfurry** [comment]
Indeed.
Everything is fine now.
