### ISSUE TITLE
Typo in conditions

### ISSUE THREAD

**Issue by RazzorX** [cmangos/wotlk-db#142]
Typo in [726] line [371](https://github.com/cmangos/wotlk-db/commit/5317365958a184f02b98f67f5e0a98eef0e43111#diff-6c0d01ef64045dabdec6dcb923d787c2R371) : Condition 1130 was already been added in commit [656] line [22](https://github.com/cmangos/wotlk-db/commit/1c3febbdb9580e56102ac3ecf543cedfc1d0cc5c#diff-af127549bd33cd892156563f9277a193R22)

**Comment by Grz3s** [comment]
oh no....
I'm glad that u found it....
thanks..
