### ISSUE TITLE
Skar'this the Heretic (Slave pens)

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#144]
http://wowwiki.wikia.com/wiki/Quest:The_Mark_of_Vashj
according to this npc must be placed in cage 
quest must be in heroic version , for 70 lvl 

atm after first quest npc must gives you "The Cudgel of Kar'desh"
but now he gives you two versions:
http://www.wowhead.com/quest=13431/the-cudgel-of-kardesh
http://www.wowhead.com/quest=10901/the-cudgel-of-kardesh

i suppose, one of them must be removed

**Comment by rmzV** [comment]
also is not this quests must be awailable after completing quest chain, look at comments?
http://www.wowhead.com/quest=10900/the-mark-of-vashj

**Comment by Grz3s** [comment]
Fix is almost ready for both:
I'm missing only Gossip(menuid) for "Skar'this the Heretic" c.22421

Anyone can help?

**Comment by rmzV** [comment]
hi there!
with quest do you leave in game:
13431 or 10901? 
thank you

**Comment by Grz3s** [comment]
```sql
-- q.13431 'The Cudgel of Kar'desh'
-- becomes available after q.10900 'The Mark of Vashj' completed
-- *NOTE* This is the NEW version of Cudgel of Kar'desh. It does NOT reward "Champion of the Naaru". The one pre-3.0.2 did give the title.
-- TBCDB should use q.10901 instead
UPDATE quest_template SET PrevQuestId = 10900 WHERE entry = 13431;
-- Let's remove older version (WotlkDB only)
DELETE FROM creature_questrelation WHERE id = 22421 AND quest = 10901;
DELETE FROM creature_involvedrelation WHERE id = 22421 AND quest = 10901;
```
