### ISSUE TITLE
10284 Escape from durnholde

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#145]
http://www.wowhead.com/quest=10284/escape-from-durnholde#comments

doesnot work.. quest accepted.. talk to thrall ..but event doesnot starts

**Comment by Grz3s** [comment]
Just tested and all works fine...

Did you click on his gossip?
![sdss](https://cloud.githubusercontent.com/assets/2374069/26380771/6994f0f2-4018-11e7-9e25-93c612ee75cd.jpg)

**Comment by rmzV** [comment]
yes.
also i decline and reaccept quest and click gossip..
may be there are is delay timer or i must be in group to start event?

also, when i come to thrall to handle previous quest? i click on gossip first -then completed quest.. may be it creates a bug?

i will recheck a soon as possible and update post.

**Comment by Grz3s** [comment]
> also, when i come to thrall to handle previous quest, i click on gossip first -then completed quest.. may be it creates a bug?
gossip will become available after killing first boss.. and u don't need to finish prev quest.
Reason for this... is that blizz wants players to be able to do that escort everytime player enter instance ..even if quest is finished already.
Anyway... I checked that .. and escort started without any problem...

Update:
I managed to make him not starting running...
It happened only... after he started his escort and I didn't followed him... (he despawned somewhere)..
So I had to use command .respawn... to bring him back to start point.. 
He showeup.... but gossip didn't work anymore.
I found this error then:
`<Scripting Library ERROR>: EscortAI attempt to Start while already escorting.`

..To fix this: (if u can use .gm)
- kill him using command .die ... and .respawn  .. he should work fine after that.
If not.
- go outside instance (restart it) -- and all should go back to normal

Let me know if this helped you at all..

**Comment by rmzV** [comment]
first of al i found strange thing.. when i set last charge.. its immedeately explode.. not sure but i think there are must be some delay timer.

about escort quest.. i checked different variations...and probably i found problem case,
if you didnt kill "lieutenant drake"  - gosip option will not work (you will see her but it clicking on it will do nothing) .. thats happen for me now.. i returned back and kill him .. in this case gossip start working.

also prev quest dont require to kill this boss
http://www.wowhead.com/quest=10283/tarethas-diversion
so if you missed him .. you must return back.. or you cant proceed on quest line...

**Comment by Grz3s** [comment]
ok it looks like we have a conflict .. between db and sd2 here...
Thrall has gossip set up in both.
Gossip for escort start shouldn't show up until 1st boss is killed...
PLS check this and let me know if it helps:
```sql
-- Thrall
UPDATE creature_template SET GossipMunuId = 0 WHERE entry = 17876;
```

**Comment by rmzV** [comment]
whe i tryed to export sql file with
UPDATE creature_template SET GossipMunuId = 0 WHERE entry = 17876;
i have error
[Err] 1054 - Unknown column 'GossipMunuId' in 'field list'
[Err] UPDATE creature_template SET GossipMunuId = 0 WHERE entry = 17876;
[Msg] Finished - Unsuccessfully

**Comment by Grz3s** [comment]
my fault ...try again :)

**Comment by rmzV** [comment]
fix working! th
