### ISSUE TITLE
The Lurker Below

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#146]
http://www.wowhead.com/npc=21217/the-lurker-below#comments
did around 20casts but not fished him.. is this event working?

**Comment by Grz3s** [comment]
event works perfectly fine: (just tested)

```code
    // There is some chance to fish The Lurker Below, sources are from 20s to 10minutes, average 5min => 20 tries, hence 5%
    if (urand(0, 99) < 5)
```
just keep fishing... 

P.S. its a BOSS not a normal NPC
