### ISSUE TITLE
9644!nightbane

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#148]
where is summoning urn placed?
cant find it on masters therrace

**Comment by rmzV** [comment]
okey
small add
urn object working on gm mode
but on normal its just non active

**Comment by NeatElves** [comment]
double focus
```sql
DELETE FROM `gameobject` WHERE `guid` = 99912;
```

**Comment by Grz3s** [comment]
nice catch...
but this wont fix our issue here...
SD2 script for karazhan was made for WOW 2.x.x version, where to be able to interact with this object Player had to have item 24140 "Blackened Urn" in inventory..
3.x.x changed that quest ... So item is not req anymore. where our script still req.

Anyone want to look at that script?:)
