### ISSUE TITLE
Quality control against Lyori's free wow leveling up guide 6- 7 part 1 and 2 (Blood Elf) 

### ISSUE THREAD

**Issue by Phatcat** [cmangos/wotlk-db#15]
https://www.youtube.com/watch?v=jdxH8c_b0cU

0:53
Inkeeper Delaniel is supposed to curtsey when you select quest 'Completing the Delivery' and once again when you press continue (followed up by a sassy hand-on-hip lecture afterwards) on the same quest.
on cmangos she doesn't do that.

1:00
Gossip options are in the wrong order (probably core thing) -- it is

1:50
the Arcane Patrollers need to come closer to the town, it never came this close on cmangos.

1:52 (+ 2:16, 2:55, 3:52, 4:35, 6:06, 6:56)
the arcane Patrollers should always say something when they engage in combat
("Protect the innocent!", "Serve the public trust!")
special note about 6:56: why... is it appearing over the player, as if the player is saying it?

3:27
the Wretched Urchin at this spot should be kneeling, tinkering with something and saying something in Thelassian

7:27
Magister Jaronis is not supposed to do /talk animation when you approach him to turn in "Major Malfunction"

7:45
Sergeant Kan'ren is not supposed to do any animation when select to turn in quest "Wanted: Thaelis the Hungerer"
He is however supposed to do /cheer when you press 'continue' on the same quest, he doesn't on cmangos.

7:54
Aeldon Sunbrand is not supposed to do /talk animation when you select to turn in the quest "Unstable Mana Crystals" from his gossip menu

He posted no more videos after this.

**Comment by Grz3s** [comment]
```quote
He posted no more videos after this.
```
I can't fix that :(

**Comment by Rushor** [comment]
here is part 2 https://www.youtube.com/watch?v=lMf2wWGD278
