### ISSUE TITLE
Ogrila quest relation

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#154]
if i understand right thera must be some quests that leads to Ogrilla

1)after completing "Into the Soulgrinder" quest  " [70] Speak with Mog'dorg. ( http://wowwiki.wikia.com/wiki/Bladespire_Supplicant ) " must appear at circle of blood arena,, this quest can be skiped and "http://wowwiki.wikia.com/wiki/Quest:Ogre_Heaven" must be acceptable too

atm thera is not any quest that leads to Ogrilla

**Comment by rmzV** [comment]
http://www.wowhead.com/quest=11022/speak-with-mogdorg#comments
according to this  [70] Speak with Mog'dorg only ally quest,,, if this correct maybe the next quest
http://www.wowhead.com/quest=11009/ogre-heaven
has the Alyy flag too

but it must have bot A+H

**Comment by rmzV** [comment]
https://github.com/cmangos/tbc-db/commit/0ee1e09a2ee4bbb3f8fad5d4acd4031160fa03cf

**Comment by Grz3s** [comment]
backported already
