### ISSUE TITLE
10977 stasis chambers of mana tombs - key problem

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#155]
http://www.wowhead.com/quest=10977/stasis-chambers-of-the-mana-tombs

i am exalted with consorcium
q giver gives me Mana-Tombs Stasis Chamber Key 
but when i come to MT chamber asks me for shafar's chamber key
i belive that 1) if you are not exalted npc gives you Mana-Tombs Stasis Chamber Key  in exchange for some items (except first time)
2) if you exalted he must gives you  shafar's chamber key (and ofcouse you must complete p1. with a Mana-Tombs Stasis Chamber Key  )

also keep in mind:
"After complete this quest, you'll get either one of two quests below depend on your rep. Revered: //www.wowhead.com/?quest=10981 Exalted: //www.wowhead.com/?quest=10982  As state above, Revered rep will get only 1 time used key (which have to farm another mark of nexus-king, but as your rep is exalted, you'll get permanent key without farming any further."

so may be if i exalted npc must goves me shafar's chamber key and if i revered Mana-Tombs Stasis Chamber Key ... and a chamber must change her state depends on player rep.

**Comment by Grz3s** [comment]
```quote
q giver gives me Mana-Tombs Stasis Chamber Key
 but when i come to MT chamber asks me for shafar's chamber key
```
They're 2 Chambers in MT... Are you checking right one?
from quest details:
```quote
According to the glyphs on the mark, two exist: one near the front and one near Nexus-Prince Shaffar. 
**This key that I am about to give you will open the stasis chamber near the front.**
```
After killing Pandemonius go into next room and turn left..

**Comment by rmzV** [comment]
you are right. it different chambers
small add (i am at exalted) so this one doesnot vissible for me
http://wowwiki.wikia.com/wiki/Quest:Nexus-Prince_Shaffar%27s_Personal_Chamber
is it ok?
couse i still can see
http://wowwiki.wikia.com/wiki/Quest:Purging_the_Chambers_of_Bash%27ir


can you please look at ogrilla ticket?

**Comment by Grz3s** [comment]
Yes this is a bit confusing .. i did some research and this is interesting:
```quote
By Keidric (432 – 1·7)  on 2010/09/16 (Patch 3.3.5) 
(...)
6) Once I hit exalted, a new quest appeared in Blades Edge that required nothing but the rep. 
It awarded the permanent Yor key. [The Eye of Haramad] 
Note: (The old repeatable quest that required [The Mark of the Nexus-King.] was still there so don't freak... Just ignore it.)
```
So ... now i know how to finally fix this chain for good;)

**Comment by killerwife** [comment]
I have it all sniffed and on video.

**Comment by Grz3s** [comment]
up to exalted ?

**Comment by killerwife** [comment]
yes, including boss summon (yor), I just need to give names to 5 files and then I will send it to you                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the Orange network.

**Comment by Grz3s** [comment]
just look at your vids.. what happens when player reaches "exalted" ... if older repeatable wuests are still available to do ..
No need to dig in sniffs

**Comment by killerwife** [comment]
Image of Commander Ameer only has http://www.wowhead.com/quest=10975/purging-the-chambers-of-bashir at Exalted.

**Comment by Grz3s** [comment]
Ok so it makes sense now!
- quest 10975 is available koz blizz wants us to be able to fight all mini bosses from prison.. (fun?)
- other two gives you key to open same prison ..
- also .. whoever farmed that rep (or any rep before cataclysm) knows how hard and how long that was.. so im sure You. had plenty time to even once that repeatable quest .. 
Anyway thanks for you both.
