### ISSUE TITLE
david wayne quests

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#159]
http://wowwiki.wikia.com/wiki/David_Wayne
Tear of the Earthmother (Dungeon) - Shattered Halls and
 Underworld Loam (Dungeon) – Steamvault
Must be acceptable after both of this  
Fresh From the Mechanar (Dungeon) - Mechanar
and The Lexicon Demonica (Dungeon) - Shadow Labyrinth 
completed ..atm after completing  Lexicon demonica they are available. 
So first 2 quests - second 2 quest and then  Bane of the Illidari  must be available . Bane of the ilidary – required some scripting. Now he is just completing quest without action.
Quenching the Blade – doesnot work.. char just dropping item in pull and nothing happens after.. I cant loot quest item back
http://wowwiki.wikia.com/wiki/Quest:Quenching_the_Blade

**Comment by Grz3s** [comment]
both scripts for 2 final quests were added ... so they working fine now ;)

**Comment by rmzV** [comment]
Thanks you!

**Comment by rmzV** [comment]
https://www.wowhead.com/quest=10679/quenching-the-blade
quest stil doesnot work
you can use quest item.. some animation started.. but nothing at the end

**Comment by Grz3s** [comment]
ok ..i just recorded this 5 mins ago...

which   part doesnt work for you?
https://www.youtube.com/watch?v=GNU5mx9QQpY&feature=youtu.be

**Comment by rmzV** [comment]
ill use quest item ( drop it into the pool), i see the animation, but no sword inside pool.

**Comment by Grz3s** [comment]
Pls: 
- Remove Cache from your WoW Game folder (make sure that game isnt running on that time)
- ReRUN ./installfullDB.sh

**Comment by rmzV** [comment]
when i truing to use item . it says "invalid target"

**Comment by Grz3s** [comment]
ok ... i found issue... 
Its core after recent updates... "reported"
