### ISSUE TITLE
[Wotlk] Missing spell script target for spell 42442

### ISSUE THREAD

**Issue by xfurry** [cmangos/wotlk-db#16]
Spell 42442, used by GO 187560 and 188692 are missing script target, and when used, it will target all hostile creatures around, with  a dummy effect (not handled by core or db).
These are part of Borean Tundra area.

**Comment by boxa** [comment]
implemented through R2 FillCustomTargetMap, a very handy function for processing such spells
https://github.com/mangosR2/mangos/blob/master/src/game/Spell.cpp#L749

here handled many non-standard or requires special handling spells
https://github.com/mangosR2/mangos/blob/master/src/game/Spell.cpp#L8631

```
bool Spell::FillCustomTargetMap(...)
{
...

        case 42442: // Vengeance Landing Cannonfire
        {
            unMaxTargets = 1;

            UnitList tempTargetUnitMap;
            FillAreaTargets(tempTargetUnitMap, radius, PUSH_IN_FRONT_90, SPELL_TARGETS_ALL);
            if (!tempTargetUnitMap.empty())
            {
                for (UnitList::const_iterator itr = tempTargetUnitMap.begin(); itr != tempTargetUnitMap.end(); ++itr)
                {
                    if (IsUnit(*itr) && (*itr)->GetEntry() != 25227) // Crypt Crawler
                        targetUnitMap.push_back(*itr);
                }
            }

            // exclude caster
            targetUnitMap.remove(m_caster);
            break;
        }
...

    // random targets
    while (targetUnitMap.size() > unMaxTargets)
    {
        UnitList::iterator itr = targetUnitMap.begin();
        std::advance(itr, urand(0, targetUnitMap.size() - 1));
        targetUnitMap.erase(itr);
    }
    return true;
}
```

**Comment by Grz3s** [comment]
hey @boxa 
I see that you pushing some commits into cmangos recently...
It may be good idea to look on this one also?
.. we can set correct target for this spell:
```sql
DELETE FROM spell_script_target WHERE entry = 42442;
INSERT INTO spell_script_target VALUES
(42442, 1, 25227, 0),
(42442, 1, 25228, 0);
```
but still... gun fires multiple bullets....

**Comment by boxa** [comment]
@Grz3s hi!

R2 based custom target select works great (for me)
and cannon should not be shoot on 25227 (only on dummy invisible stalkers)

soon i make it for cmangos (clear as possible), and without hacks

**Comment by Grz3s** [comment]
:+1: 
```code
cannon should not be shoot on 25227 (only on dummy invisible stalkers)
```
this makes sense..

**Comment by boxa** [comment]
done: https://github.com/cmangos/mangos-wotlk/commit/445bcc84ef6f977fd594503ddc04f6a026032bec

**Comment by Grz3s** [comment]
look like correct fix was added in core.
Closed
