### ISSUE TITLE
*21027 ! Escape from Coilskar Cistern

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#161]
http://www.wowhead.com/npc=21027/earthmender-wilda#comments
escort quest missing

**Comment by NeatElves** [comment]
sd2 script

**Comment by killerwife** [comment]
I have a sniff and video, but I don't have time to script it. Should anyone want to do it, let me know.

**Comment by NeatElves** [comment]
2 killerwife
Script is - npc_wilda, but not working

**Comment by Grz3s** [comment]
I don't get it... 
Are we working on the same databases?
Just tested this quest and I ..escort works fine...
Here vid from today:
https://www.youtube.com/watch?v=_xl-tZ9z3cE&feature=youtu.be

P.S.
Found few small issues during escort etc, but ... they're not major issues here

**Comment by NeatElves** [comment]
Today checked again - it worked, apparently the problem was in the core

**Comment by rmzV** [comment]
![wowscrnshot_081317_150339](https://user-images.githubusercontent.com/22476199/29249470-d2d06488-8038-11e7-81e0-5289c70267ee.jpg)
doesnot work for me

**Comment by rmzV** [comment]
okey , i figured it 1) if you insta kill boss on his spot with ranged skill - quest working if you come on his ledge kill vipers and pull boss in back.. event doesnot start
2)during escort npc turned in dead state
3) during quest - we save elementals.. is not this npc fighting ones?

**Comment by Grz3s** [comment]
@killerwife 
Can you pls send me that sniff ;)

**Comment by killerwife** [comment]
@Grz3s Its on your email with video.
