### ISSUE TITLE
10692/10651 Varedis Must Be Stopped

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#163]
you can kill bosses and get “completed” … but you cant complete quest at quest giver.. I belive you must rip pages +kill to get “completed” .. currently boss doesnot use metamorphosis and you can use book at any time.. but it still not give you a credit 

http://www.wowhead.com/quest=10651/varedis-must-be-stopped

**Comment by Grz3s** [comment]
Fixed
