### ISSUE TITLE
Trial of the Naaru quest sequence

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#165]
13430    Trial of the Naaru: Magtheridon  must be available ONLY after 3 of this quests completed 
10884 - Trial of the Naaru: Mercy
10885 -  Trial of the Naaru: Strength
10886 - Trial of the Naaru: Tenacity

now it available after first two

**Comment by NeatElves** [comment]
```sql
UPDATE `conditions` SET `type` = '-1' WHERE `condition_entry` =1211;
UPDATE `conditions` SET `type` = '-1' WHERE `condition_entry` =1212;
```
