### ISSUE TITLE
10641! against-the-legion

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#166]
*http://wowwiki.wikia.com/wiki/Quest:Altruis
after this quest 3 next must be available, now only 2 available.
Against All Odds/Against the Illidari/Against the Legion 
Against the Legion is missed – I belive I did him before or he is simple missed
http://www.wowhead.com/quest=10641/against-the-legion

**Comment by NeatElves** [comment]
https://github.com/cmangos/wotlk-db/commit/9c7c2d7c2f493669f9139ca1c953f0e7d128bbf0

> .quest remove 10641
