### ISSUE TITLE
10866! Trial of the Naaru: Tenacity

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#168]
http://www.wowhead.com/quest=10886/trial-of-the-naaru-tenacity#comments
Arcatraz fight completely bugged
1)boss doesnot use beam on cages
2)gnome do nothing.. he just speak same words in a circle
3)last big-boss-creature cant be ataackable.

**Comment by killerwife** [comment]
1. Core issue, range targeting nonsense
2. Core issue, AI is slightly faulty
3. Core issue, has to do with 256 512 flag rework.

Will be dealt with after my AI rework is merged, 1-2 weeks. Unrelated to wotlk-db.

**Comment by Grz3s** [comment]
fixed some time ago

**Comment by rmzV** [comment]
at some point.. when creature must eat boss still bugged
