### ISSUE TITLE
10946!Ruse of the Ashtongue

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#172]
http://www.wowhead.com/quest=10946/ruse-of-the-ashtongue

bugged
after accepting quest 
"alar slain "  already marked as completed (probably becouse i killed him before.)
also quest can be completed without using quest item [Ashtongue Cowl] (Provided)

**Comment by NeatElves** [comment]
Script+
```sql
UPDATE `quest_template` SET `SpecialFlags` =2, `ReqCreatureOrGOId1` =0, `ReqCreatureOrGOCount1` =0 WHERE `entry` =10946;
```

**Comment by Ulduar** [comment]
@rmzV maybe this can help?
https://github.com/cmangos/mangos-wotlk/pull/239

@NeatElves 
Eng translate:
Go, go, power developers XD
Ru translate:
Please, пните разрабов XD. Может быстрее фиксанут)

**Comment by NeatElves** [comment]
core add:
https://github.com/cmangos/mangos-wotlk/commit/c9ca0c009a9bfb46fc7c9ca588b88500e7415374
