### ISSUE TITLE
Avatar of Freya dummy event.

### ISSUE THREAD

**Issue by ghost** [cmangos/wotlk-db#174]
https://github.com/dalaranwow/dalaran-wow/issues/4522
More details found here.

Avatar of Freya should revive allies of nature for battle on Scourge in Sholazar Basin.
http://www.wowhead.com/npc=27801
![93984-avatar-of-freya](https://user-images.githubusercontent.com/18075953/30571912-732d266a-9d0c-11e7-977e-7366c13dcd20.jpg)

**Comment by Grz3s** [comment]
fixed
