### ISSUE TITLE
Bread of the Dead - No Buff

### ISSUE THREAD

**Issue by adellaci** [cmangos/wotlk-db#178]
Bread of the Dead  item=46691
"Restore 2% of your Health per second for 24 sec. Must remain seated while eating. If you spend at least 10 seconds eating you will become well fed and gain Stamina and Spirit for 15 min."

This should work on November 1st, & 2nd

WotLK Patch 3.2.2 (2009-09-22): Added.

While eating the healing rate is correct, but after 10 sec you do not become well fed and do not gain Spirit & Stamina.

**Comment by adellaci** [comment]
I did try this on both November 1st & 2nd

**Comment by NeatElves** [comment]
+ item 20516
+ item 21254
