### ISSUE TITLE
Wind Rider Sabamba <Flying Trainer>

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#181]
according to wowhead,
http://www.wowhead.com/npc=35135/wind-rider-sabamba#teaches-recipe
she must have:
Cold Weather Flying and
Flight Master's License

**Comment by Grz3s** [comment]
**Cold Weather Flying** - before 4.x.x only way for this was to buy book https://www.wowhead.com/item=49177/tome-of-cold-weather-flight#comments
in Dalaran for 1K gold.
