### ISSUE TITLE
Utgarde keep missed npc and quests

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#188]
http://www.wowhead.com/npc=24137/dark-ranger-marrah#starts
http://www.wowhead.com/quest=13206/disarmament
http://www.wowhead.com/quest=11262/ingvar-must-die

**Comment by Grz3s** [comment]
fixed ..awaiting to be added

**Comment by Grz3s** [comment]
added:
https://github.com/cmangos/wotlk-db/commit/48d08a96839427c085c37b9b9494dfd72ed62b80
