### ISSUE TITLE
[WotLK] EventAIErrors.log - Action will not have any effect

### ISSUE THREAD

**Issue by adellaci** [cmangos/wotlk-db#2]
CMaNGOS/0.18 (2016-10-08 07:18:46 - e0cf754e1d29c21085fa745fd840c8a7c3c0919a) for Linux_x64

I have the following in the EventAIErrors,log:

```
2016-10-08 10:26:59 Event 511101 Action 2. SpecialFlags for quest entry 8353 does not include |2, Action will not have any effect.
2016-10-08 10:26:59 Event 682601 Action 2. SpecialFlags for quest entry 8355 does not include |2, Action will not have any effect.
2016-10-08 10:26:59 Event 674001 Action 2. SpecialFlags for quest entry 8356 does not include |2, Action will not have any effect.
2016-10-08 10:26:59 Event 1181402 Action 2. SpecialFlags for quest entry 8358 does not include |2, Action will not have any effect.
2016-10-08 10:26:59 Event 692901 Action 2. SpecialFlags for quest entry 8359 does not include |2, Action will not have any effect.
2016-10-08 10:26:59 Event 673501 Action 2. SpecialFlags for quest entry 8357 does not include |2, Action will not have any effect.
2016-10-08 10:26:59 Event 674601 Action 2. SpecialFlags for quest entry 8360 does not include |2, Action will not have any effect.
```

**Comment by Grz3s** [comment]
yes... i know about this one :)
will be fixed today :)

**Comment by stfx** [comment]
You should consider closing this issue tracker and using the central cmangos/issues one

**Comment by Phatcat** [comment]
These different issue trackers are for the different versions of db / acid now acid has been merged with db and it has been moved inside the cmangos organization.

I asked about this just yesterday, which issue tracker to use for db issues now, and I was pointed in this direction, so I think it indeed was considered. DB has also been merged with ACID now.

**Comment by Grz3s** [comment]
i'm more than happy to use *this one* ... it will save time diggin for wotlk DB stuff

**Comment by stfx** [comment]
Just label issues as DB in the central issue repo to find them as easy. Otherwise you are confusing a lot of people. Anyway I am not here to discuss but urge you to think ahead.

**Comment by Grz3s** [comment]
Decision has been made already

**Comment by Phatcat** [comment]
As for the confusion, all we ought to do is update some of our readme's and we should be good.

**Comment by Grz3s** [comment]
i'll make update into txt file...
Also ..We need volunteer to Update Wiki :) ...

**Comment by killerwife** [comment]
I might do it someday at work :D But I first wanna clean up DB schemas.

**Comment by Phatcat** [comment]
this : https://github.com/cmangos/issues/blob/master/README.md
and this : https://github.com/cmangos/issues/wiki/Installation-Instructions

are probably the most important to update to not confuse people (as the readme contains info which is outright wrong now, and the installation instructions points to now outdated repos while stating any compatible db will work with cmangos.. we probably wanna rethink that whole 'open to any db' policy now...) - alright, done spamming an issue with unrelated stuff now, sorry @adellaci

**Comment by Grz3s** [comment]
some info for readme file was added :)

**Comment by adellaci** [comment]
@Phatcat 

Sorry, did i miss some thing. Please explain a bit more.

**Comment by adellaci** [comment]
@Grz3s 

I downloaded the latest of everything just i still have those errors. Am I doing something wrong?

**Comment by Grz3s** [comment]
@adellaci ...
you probably still using https://github.com/unified-db/Database/commits/master as a main DB.
Pls look here:
https://github.com/unified-db/Database/issues/254

We moved under CmangoS organisation... https://github.com/cmangos/wotlk-db/commits/master
So Basically You need to set up your InstallFullDB.sh again with new DB data.

P.S. your error was fixed : in commits [562] [563] ... you wont find them  here:

**Comment by adellaci** [comment]
@Grz3s 

Dah! So sorry Grz3s. I knew that, just didn't change the script to to collect from the right place. I can't believe that I spaced that one so hard.

Thank you

**Comment by adellaci** [comment]
@Grz3s @Phatcat 

And the tiny light bulb just came of about Phatcats rant. I corrected the instructions to point to the right repo for WotLK. Grz3s is there a forum or would you like forums to point to issues in that repo?

**Comment by Grz3s** [comment]
pls use new issue tracker:
https://github.com/cmangos/wotlk-db/issues

**Comment by adellaci** [comment]
@Grz3s 
Okay all taken care of. Forum is pointing there.

**Comment by Phatcat** [comment]
I do love ranting :3 how lovely to see someone take that initiative to get it updated.

**Comment by adellaci** [comment]
I try to help. The Ubuntu Instruction I wrote in the cmangos forum have been changed also. You keep ranting! I do listen once the little light bulb comes on in my head.
