### ISSUE TITLE
11279 green eggs and whelps

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#200]
http://www.wowhead.com/quest=11279/green-eggs-and-whelps#comments

doesnot work

**Comment by NeatElves** [comment]
```sql
DELETE FROM `spell_script_target` WHERE `entry` = 46606;
INSERT INTO `spell_script_target` (`entry`, `type`, `targetEntry`, `inverseEffectMask`) VALUES
(46606, 1, 23777, 0);
```
Then either hack the spell
```sql
UPDATE `spell_template` SET `EffectImplicitTargetA1` = '38' WHERE `Id` =46606
```
or wait for the support in the core for
TARGET_SINGLE_ENEMY(77) similarly
 TARGET_SCRIPT(38) or TARGET_SCRIPT_COORDINATES (46) or TARGET_FOCUS_OR_SCRIPTED_GAMEOBJECT (40)
)))

**Comment by rmzV** [comment]
NeatElves, i have a question:
is there are any chance to make ingame check "if selected quest was already completed (or completed on toon x)" via macro maybe?
i need it for starting testing ally quests, but dont wanna to do same quests twice.

thanks

**Comment by Rog360** [comment]
I'll add a little info for this one... :)

Use item Tillinghast's Plague Canister [33418] on Proto-Drake Egg [23777] Should break Proto-Drake Egg and Summoned Plagued Proto-Whelp [24160] 
When hit by Spell 43157 or 46606. to loot item Plagued Proto-Whelp Specimen [33420]. Not sure on which spell to use on hit... :)

**Comment by NeatElves** [comment]
SpellEffects.cpp
```code
                case 46606:                                 // Plague Canister Dummy
                {
                    if (!unitTarget || unitTarget->GetTypeId() != TYPEID_UNIT)
                        return;

                    unitTarget->CastSpell(m_caster, 43160, TRIGGERED_OLD_TRIGGERED);
                    unitTarget->SetDeathState(JUST_DIED);
                    unitTarget->SetHealth(0);
                    return;
                }
```
