### ISSUE TITLE
11519 the lost shield of the aesirites

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#201]
http://www.wowhead.com/quest=11519/the-lost-shield-of-the-aesirites
missed
http://www.wowhead.com/npc=24910/captain-ellis
and prabably follow up quests

**Comment by Grz3s** [comment]
temp fix added:
https://github.com/cmangos/wotlk-db/commit/1aaef442513c3ab71eada730c7585ef5b338bf92
