### ISSUE TITLE
11464 Gambling Debt

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#203]
http://www.wowhead.com/quest=11464/gambling-debt#comments
1) you can insta kill him if you powerfull enought
2) after "I'll pay! I'll pay! Eeeek! Please don't hurt me!"  - nothing happens

**Comment by Grz3s** [comment]
fixed by:
https://github.com/cmangos/mangos-wotlk/commit/ffe180db4721a045e46881448dec0c0859fe7d6e
