### ISSUE TITLE
Quest: Nexus-King Salhadaar

### ISSUE THREAD

**Issue by Nett118** [cmangos/wotlk-db#204]
For the quest [Nexus-King Salhadaar](http://www.wowhead.com/quest=10408/nexus-king-salhadaar) you are to use a [Protectorate Disruptor](http://www.wowhead.com/item=29618) on one of the conduits nearby and then [Nexus-King Salhadaar](http://www.wowhead.com/npc=20454) becomes hostile and attacks.
Everything works up to the point where he becomes hostile... He just storms off after yelling that you unleashed a God.
Also, the visual beams from the conduits are all coming from one, randomly, but always one instead of all three.

**Comment by killerwife** [comment]
Wotlk aura stacking is the culprit. Also the mmaps in the area are crap when extracted with cmangos tools.

**Comment by Grz3s** [comment]
fixed some time ago

**Comment by Nett118** [comment]
Thanks everyone for the help!
