### ISSUE TITLE
Quest 12182 transport issue

### ISSUE THREAD

**Issue by Rog360** [cmangos/wotlk-db#205]
You should automatically be flown to destination after accepting quest 12182 from Tobias Sarkhoff [24155] unless your mounted... :)

http://youtu.be/k2-oDsifFD8

**Comment by xfurry** [comment]
Does this quest have the "SEND_TAXI_PATH" command on dbscript_quest_start?

**Comment by Rog360** [comment]
No. :)

**Comment by Rog360** [comment]
Thanks for your work... :)
