### ISSUE TITLE
11652 the plans of nasam

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#208]
http://www.wowhead.com/quest=11652/the-plains-of-nasam

cant grab passengers

**Comment by Grz3s** [comment]
no idea why ... but somehow spell:
ID - 47962 Rescue Injured Soldier
doesnt like to work with friendly creatures.. anymore.
Need @xfurry help here

**Comment by rmzV** [comment]
not sure, but isnot vehicle health must scale with characters item lvls? same as in ulduar?

**Comment by xfurry** [comment]
poke @killerwife 
Did you change anything lately to the spell effect positive / negative categorization? I know I saw some changes in that area, so I'm wondering if something got broken because of this.
There are a few other examples where the positive / negative effect of the spell is reversed. This issue looks similar.

**Comment by xfurry** [comment]
@rmzV yes, the stats should scale. I'm not sure why the scaling isn't applied. Some vehicle boarding spells have this triggered automatically but I'm not sure if this happens to all of them.

**Comment by xfurry** [comment]
@Grz3s 
spell 47962:
```
Effect 0: Id 77 (SPELL_EFFECT_SCRIPT_EFFECT)
BasePoints = 49242
Targets (25, 0) (TARGET_DUELVSPLAYER, TARGET_NONE)
```

spell 49242:
```
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 1
Targets (25, 0) (TARGET_DUELVSPLAYER, TARGET_NONE)
Aura Id 236 (SPELL_AURA_CONTROL_VEHICLE), value = 1, misc = 0 (0), miscB = 0, periodic = 0

Effect 1: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 1
Targets (1, 0) (TARGET_SELF, TARGET_NONE)
Aura Id 4 (SPELL_AURA_DUMMY), value = 1, misc = 0 (0), miscB = 0, periodic = 0
```

I'm not sure how this worked before, but the script effect isn't implemented. Maybe that's why it's not working.

**Comment by Grz3s** [comment]
@xfurry 
https://www.youtube.com/watch?v=Ql6GC6pWOcI&feature=youtu.be

Its done by these 2 lines:
``sql
('2710604','27106','8','0','100','1','47962','-1','0','0','11','47968','6','0','22','1','0','0','0','0','0','0','Injured Warsong Warrior - Cast Soldier Rescued And Set Phase 1 on SpellHIT(q.11652)'), 
('2710605','27106','8','0','100','1','47962','-1','0','0','11','49242','6','0','1','-1514','0','0','0','0','0','0','Injured Warsong Warrior - Cast Ride Vehicle AND Say on SpellHIT(q.11652)'), 
```
It worked before... ...
