### ISSUE TITLE
missed ivent ? Ith'rix's Hardened Carapace

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#210]
http://www.wowhead.com/object=187674/ithrixs-hardened-carapace#comments

drops item for a quest
http://www.wowhead.com/quest=11632/what-the-cold-wind-brings

**Comment by Grz3s** [comment]
small update for this ;)

![test](https://user-images.githubusercontent.com/2374069/38168575-ba25702e-353f-11e8-9c99-0d38a9402ce8.jpg)

finall step: balancig timers...
