### ISSUE TITLE
11881 loader-up

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#213]
*http://www.wowhead.com/quest=11881/loader-up
To big agro radius.. like a half of map
Caravan killed by one hit(
Npc disappeared on half way.. reason unknown.. I was trying to use main road
Find same problem in Brd recently, in room where you are looking for torches to light blazers (for oppening doors)  - i mean big agro radius

**Comment by Grz3s** [comment]
Fixed:
https://github.com/cmangos/mangos-wotlk/commit/41e2481308312a8a8a51e6f6b217193456ddce41
