### ISSUE TITLE
TBC fields corrected for WOTLK

### ISSUE THREAD

**Issue by NeatElves** [cmangos/wotlk-db#222]
UNIT_FIELD_BYTES_1
```sql
UPDATE dbscripts_on_spell SET datalong = 73 WHERE command =2 AND datalong =159; 
```

**Comment by Grz3s** [comment]
hmm .. not 74?

**Comment by NeatElves** [comment]
I have recorded:
http://wiki.ytdb.ru/index.php/Character_data
74 | UNIT_FIELD_PETNUMBER

**Comment by Grz3s** [comment]
0x0006hec = 6dec
0x0044hec = 68dec
0x0006 + 0x0044 = 0x4A
0x4Ahec = 74dec
where im wrong here?

**Comment by NeatElves** [comment]
You are right, I checked in practice UNIT_FIELD_BYTES_1 = **74**
'''sql
UPDATE dbscripts_on_spell SET datalong = 74 WHERE command =2 AND datalong =159; 
'''
