### ISSUE TITLE
11879 Kaw the Mammoth Destroyer 

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#224]
Kaw the Mammoth Destroyer 
*http://www.wowhead.com/quest=11879/kaw-the-mammoth-destroyer
Doesnot work
boss in non atackable state

**Comment by Grz3s** [comment]
yhm...
we added fix for this quest:
https://github.com/cmangos/wotlk-db/commit/7b71c028c94f71582183ebdc495db0d922a5ea6f
and this is how it works...
https://www.youtube.com/watch?v=PyXmbCU7ST8

Can you tell me how to reproduce situation that q wont work?

**Comment by rmzV** [comment]
it works like on the video

in my case i just come to boss and trued to aggro him..(without mammonth) is it impossible on live?

**Comment by Grz3s** [comment]
it may be, but..quest says that you should use mount to do this...
so ..if theres any (optional way) to do this.. on blizz... its not our problem:)
