### ISSUE TITLE
Lax issues list pt.7 wotlk (p1 of 8) fjord

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#230]
Dk
* ~~http://www.wowhead.com/item=39371/keleseths-persuader#comments
Must be removed from bag after quest completed~~ **FIXED**

Pala
* ~~Avenger’s shield doesn’t work~~ **Core Issue**
* ~~no flying in dalaran?~~ **INVALID** 
source: https://wow.gamepedia.com/No-fly_zone
(...)No-fly zones are zones in which flying is not allowed or is restricted in some manner. First introduced in Wrath of the Lich King, Dalaran and Wintergrasp were such zones.(...)
(...)With the release of Cataclysm the flight restrictions were lifted on Dalaran and is fully accessible by flying mounts.(...)
* ~~enchanting – abyssal shatter [orange one ] does not increase enchanting skills~~ **FIXED** https://github.com/cmangos/mangos-wotlk/commit/9d48efdda5dbf2ce78058bd847054da639faa36f

**Howling Fjord**
* ~~11167-the new plague – can be completed on one quest item~~ **FIXED**
* ~~http://www.wowhead.com/npc=27344/adeline-chambers#starts~~ **FIXED**
* ~~http://www.wowhead.com/quest=29609/friends-in-dalaran
missed?~~ **INVALID** Quest added in 4.0.3
* ~~http://www.wowhead.com/quest=11227/let-them-eat-crow
Quest  working. Pet doesnot follow.~~ **FIXED**
~~Quest item doesnot disappeared after quest was completed~~ **FIXED**
* ~~crewman coilspan … fell down from the ship. Dialog doesnot work~~ **Core doesnt support npcs on transport yet.. cant be fixed via DB**
* ~~http://www.wowhead.com/quest=11253/sniff-out-the-enemy
Quest item doesnot dissapeared~~ **FIXED**
* ~~http://www.wowhead.com/npc=29159/magister-varenthas
Npc doesnot teleport you~~ **FIXED**
* ~~http://www.wowhead.com/quest=11270/war-is-hell
Quest item doesnot disappeared~~ **FIXED**
* ~~north fleet marine npc – no loot?~~ **FIXED**

Utgarde keep
* ~~npc and quests are missed
http://www.wowhead.com/npc=24137/dark-ranger-marrah#starts
http://www.wowhead.com/quest=13206/disarmament
http://www.wowhead.com/quest=11262/ingvar-must-die~~ **Fixed**

Utgarde pinnacle
* ~~bosses doesnot scripted well~~ **Fixed**
* ~~second boss not summoned~~ **Fixed**
* ~~skadi boss bugged too~~ **Fixed**
* ~~http://www.wowhead.com/quest=11281/mimicking-natures-call
Quest item doesnot disappeared~~ **FIXED**
* ~~http://www.wowhead.com/quest=11314/the-fallen-sisters~~ **FIXED**
~~Quest item doesnot disappeared~~ **FIXED**
* ~~68/29 missed npc camp~~ **FIXED**
* ~~http://www.wowhead.com/quest=11319/seeds-of-the-blacksouled-keepers
Quest item doesnot disappeared from bag after completing~~ **FIXED**
* ~~http://www.wowhead.com/quest=11352/the-rune-of-command
Quest item doesnot disappeared~~ **FIXED**
* ~~http://www.wowhead.com/quest=11365/march-of-the-giants#comments
Can be completed one 1 npc~~ **FIXED**
~~Quest item doesnot disappear~~ **FIXED**
* ~~http://www.wowhead.com/quest=11366/the-lodestone#comments
Quest item doesnot dissapared~~ **FIXED**
* ~~http://www.wowhead.com/quest=11257/gruesome-but-necessary
Quest item doesnot disappeared~~ **FIXED**
* ~~http://www.wowhead.com/quest=11258/burn-skorn-burn
Quest item doesnot disappeared~~ **FIXED**
* ~~http://www.wowhead.com/quest=11256/skorn-must-fall
Summoned npc has sa very big agro radius~~ **FIXED**
* ~~http://www.wowhead.com/quest=11259/towers-of-certain-doom#comments
Quest item doesnot work~~ **FIXED**
* ~~winterskorn rune-seer 
Npcs doesnot cast~~ **FIXED**
* ~~http://www.wowhead.com/quest=11267/the-frost-wyrm-and-its-master
Dragon must come, when quest item used..~~ **FIXED**
* ~~http://www.wowhead.com/quest=11268/the-walking-dead#comments
Not enough Deathless Watcher slain (10)
Fearsome Horror slain (4) doesnot attackable
Cave at 34/13 not full filled. Some creatures missed~~ **FIXED**
* ~~celea frozenmane – wrong pointer on mouse click – must be flight patch~~ **gossip FIXED**
* ~~http://www.wowhead.com/quest=11433/sleeping-giants#comments
Doesnot work~~ **FIXED**
* ~~Angelina soren
Not sure if she must teach you 350 fishing without previous fishing levels~~ **INVALID** she works correct ...  (if theres smth more about it ..pls create new issue)
* ~~npcs doesnot fight at 70/40 and are in non attackable state~~ **FIXED**
* ~~http://www.wowhead.com/quest=11282/a-lesson-in-fear#comments
Quest item doesnot disappeared~~ **FIXED**
* ~~http://www.wowhead.com/quest=11285/baleheim-must-burn
No burning effect on buildings
Quest item doesnot disappeared~~ **FIXED**
* ~~http://www.wowhead.com/quest=11301/brains-brains-brains
Can be completed on 1 corpse
Quest item doesnot disappeared~~ **FIXED**
* ~~http://www.wowhead.com/quest=11399/bring-down-those-shields
Quest item doesnot disappeared~~ **FIXED**
* ~~http://www.wowhead.com/item=34040/saga-of-the-twins
Placed twice~~ **FIXED**
* ~~http://www.wowhead.com/npc=23870/ember-clutch-ancient
Cant complete quest when you on the ground.. “too far away”~~ **INVALID** - what quest?
* ~~http://www.wowhead.com/quest=11279/green-eggs-and-whelps#comments
Quest item doesnot dissapeared~~ **FIXED**
* ~~http://www.wowhead.com/quest=11280/draconis-gastritis
quest item doesnot dissapeared~~ **FIXED**
* ~~http://www.wowhead.com/quest=11307/field-test
Quest item doesnot disappeared~~ **FIXED**
* ~~http://www.wowhead.com/quest=11309/parts-for-the-job
Droprate must be fixed~~ **INVALID** 
Source Wowhead:
```quote
Shoveltusk          | 59 - 80 | Howling Fjord |  8%
Shoveltusk Calf   | 59 - 80 | Howling Fjord |  8%
Shoveltusk Stag  | 58 - 80 | Howling Fjord |  7%
````
* ~~http://www.wowhead.com/quest=11310/warning-some-assembly-required
Quest item dosnot disappeared~~ **FIXED**
* ~~http://www.wowhead.com/quest=11458/avenge-iskaal
Quest item doesnot disappeared~~ **FIXED**
* ~~http://www.wowhead.com/quest=11568/a-return-to-resting
Quest item doesnot dissapeared~~ **FIXED**

UPDATE
* ~~http://www.wowhead.com/quest=11259/towers-of-certain-doom#comments
Quest item must be deleted
Quest item doesnot work~~ **FIXED**
* ~~http://www.wowhead.com/quest=11433/sleeping-giants#comments
Quest item doesnot work~~ **FIXED**
* ~~http://www.wowhead.com/quest=12481/adding-injury-to-insult
Quest item must be deleted~~ **FIXED**
* ~~http://www.wowhead.com/quest=11417/eyes-of-the-eagle#comments
Killing eggs doenot call npc~~ **FIXED**
* ~~http://www.wowhead.com/quest=11296/rivenwood-captives
Cocoons are empty~~ **FIXED**
* ~~http://www.wowhead.com/quest=11453/the-slumbering-king
belive thera was some scripting with lich king at the quest end~~ **FIXED**
~~itemmust disappeared from the bag
http://www.wowhead.com/item=34091/mezhens-writings~~ **FIXED**

**Comment by rmzV** [comment]
http://www.wowhead.com/npc=23870/ember-clutch-ancient
Cant complete quest when you on the ground.. “too far away” INVALID - what quest?

i belive, this one
https://www.wowhead.com/quest=11182/root-causes
not sure why i add this as ticket.. but probably you cant take/complete this quest

**Comment by Grz3s** [comment]
it works just fine.... 
Maybe he moved away from you and gossip just closed... i see no other reason ;)
