### ISSUE TITLE
Lax issues list pt.8 wotlk (p2 of 8) borea

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#231]
**Borean Tundra**
*~~http://www.wowhead.com/quest=11595/the-defense-of-warsong-hold
Keep in mind 3 same quests with different speaking? 11595-11596-11597
*two different version as well
http://www.wowhead.com/quest=11586/hellscreams-vigil#comments
http://www.wowhead.com/quest=11585/hellscreams-vigil~~ **INVALID** (works correct)
* ~~http://www.wowhead.com/object=187674/ithrixs-hardened-carapace#comments
Does this event works? Drops quest item 
http://www.wowhead.com/item=34777/ithrixs-hardened-carapace~~ **FIXED** https://github.com/cmangos/wotlk-db/commit/750024f1549a561546fdf89a3f0869807b596e66
* ~~http://www.wowhead.com/npc=25288/turida-coldwind#starts
Is the quest in game?
http://www.wowhead.com/quest=29609/friends-in-dalaran
I did one at howling fjord.. believe this one not available to me~~ **INVALID** Quest added in 4.0.3
* ~~http://www.wowhead.com/npc=26972/orn-tenderhoof#starts
Same .. not available Couse of howling fjord?~~ **INVALID** (answer:YES)
* ~~http://www.wowhead.com/npc=29155/magistrix-kaelana
Same .. not available Couse of howling fjord?~~ **INVALID** (answer:YES)
* ~~http://www.wowhead.com/quest=11652/the-plains-of-nasam
cant grab passengers~~ **FIXED** https://github.com/cmangos/wotlk-db/commit/e1a2c02d9dfe4cf797961960ed9a328d597d9383
~~leads to 10.   [71] Hellscream's Champion~~ **Invalid* 
~~UPDATE
 Does Vehicle Scaling work correctly?.. camera zoom doesnot work
Out of mana problem
Ability #1 shoots in wrong dirrection~~ **Core issue**

* ~~http://www.wowhead.com/quest=11593/the-honored-dead
Quest item doesnot disappeared after completing quest~~ **FIXED** https://github.com/cmangos/wotlk-db/commit/85201d8f53bb8bcae66721699dcdb996c73563b4
* ~~http://www.wowhead.com/quest=11608/bury-those-cockroaches
I believe there are was some effect on destroyed holes~~ **Invalid** (works correctly)
* ~~http://www.wowhead.com/quest=11899/souls-of-the-decursed
Quest item doesnot dissapeared~~ **FIXED** https://github.com/cmangos/wotlk-db/commit/6c4f31cebf89975c614e2cd0da9ef07e53338753
* http://www.wowhead.com/quest=11560/oh-noes-the-tadpoles
~~On live saved murlocks running near you for some time~~ **REQ SD2 - can't be fixed by DB**
* ~~http://www.wowhead.com/quest=11662/seek-out-karuk
You must complete both Burn in Effigy and Orabus the Helmsman before you can accept this quest.
Now you can complete only first one~~ **FIXED** https://github.com/cmangos/wotlk-db/commit/b42fb521745864829b161bdd719c8a4343498591
* ~~http://www.wowhead.com/npc=25636/captured-tuskarr-prisoner
After get killed npcs body start moving~~ **Core ISSUE REPORTED** - can't be fixed by db

* ~~http://www.wowhead.com/quest=11677/stop-the-plague~~
~~Any effect on cauldron when you use quest item?~~ (NO)
~~Aged magnataur npc is not attackable. Is it correct?~~ (http://www.wowhead.com/npc=24954/aged-magnataur#comments)
~~Quest item doesnot disappeared~~ **FIXED** https://github.com/cmangos/wotlk-db/commit/8ccfb95e512ca14591fa8d94814e17626c50a83a 

* http://www.wowhead.com/quest=11881/loader-up
~~To big agro radius.. like a half of map~~ **FIXED**
~~Caravan killed by one hit~~ **FIXED**  https://github.com/cmangos/wotlk-db/commit/637b59c4a3ec3e919302a3b5abf53c717734a357
~~Npc disappeared on half way.. reason unknown.. I was trying to use main road~~ **FIXED** https://github.com/cmangos/mangos-wotlk/commit/41e2481308312a8a8a51e6f6b217193456ddce41
Find same problem in Brd recently, in room where you are looking for torches to light blazers(mean agro radius)
* ~~http://www.wowhead.com/quest=11695/the-horn-of-elemental-fury
Upper quest item spot doesnot shown on mini map after completing first one~~ **FIXED**  https://github.com/cmangos/wotlk-db/commit/75add02901672694c71d29fe33077b2176ba73ab
* ~~http://www.wowhead.com/quest=11706/the-collapse
I think there was some effect on destroyed sickhole~~ (No: small event occurs ..where you need to kill summoned - and that was fixed long time ago)
* ~~http://www.wowhead.com/quest=11587/prison-break
Key doesnot dissaperaed~~ **FIXED** https://github.com/cmangos/wotlk-db/commit/6c9f04077be0135b7621e8ce3f56254604b205ec
* ~~http://www.wowhead.com/quest=11576/monitoring-the-rift-cleftcliff-anomaly
Q item doesnot dissapeared~~ **FIXED** https://github.com/cmangos/wotlk-db/commit/6c9f04077be0135b7621e8ce3f56254604b205ec
* ~~http://www.wowhead.com/quest=11582/monitoring-the-rift-sundered-chasm
Q item doesnot dissapeared~~ **FIXED** https://github.com/cmangos/wotlk-db/commit/6c9f04077be0135b7621e8ce3f56254604b205ec
* ~~http://www.wowhead.com/quest=12728/monitoring-the-rift-winterfin-cavern
Q item doesnot disappeared~~ **FIXED** https://github.com/cmangos/wotlk-db/commit/6c9f04077be0135b7621e8ce3f56254604b205ec
* ~~http://www.wowhead.com/quest=11590/abduction#comments
Quest item dowsnot disappeared~~ **FIXED** https://github.com/cmangos/wotlk-db/commit/6c9f04077be0135b7621e8ce3f56254604b205ec
* ~~http://www.wowhead.com/quest=11648/the-art-of-persuasion
Quest item doesnot disappeared~~ **FIXED** https://github.com/cmangos/wotlk-db/commit/6c9f04077be0135b7621e8ce3f56254604b205ec
* ~~http://www.wowhead.com/quest=11671/a-race-against-time
Quest item doesnot disappeared~~ **FIXED** https://github.com/cmangos/wotlk-db/commit/6c9f04077be0135b7621e8ce3f56254604b205ec
* ~~http://www.wowhead.com/quest=11680/taking-wing
Quest item doesnot disappeared~~ **FIXED** https://github.com/cmangos/wotlk-db/commit/6c9f04077be0135b7621e8ce3f56254604b205ec
* ~~http://www.wowhead.com/quest=13413/aces-high
Dialog options doesnot work~~ **FIXED** https://github.com/cmangos/wotlk-db/commit/41385825f31eed41e14fd8c01466a60d329f1543

oculus
* ~~If you skipped  any of npcs you cant summon dragon due to aggro..~~ **INVALID** ... its normal that player cant mount if aggroed by smth.
* ~~Ok you cant fly at oculus~~ **FIXED**
* Band of transmutation level of oculus doesnot populated with trees etc?
* ~~Mage-lord uron bugged at second platform and doesnot teleport on 3 one~~ **FIXED**
* ~~No portal at the end of dungeon?~~ **INVALID** No - Need to use orb (same one u came in)

* ~~http://www.wowhead.com/quest=11919/drake-hunt#comments
Quest item doesnot disappeared~~ **FIXED**  https://github.com/cmangos/wotlk-db/commit/70b8abdb07e20a9a071a7c5966856e9e0d7a4c06
* ~~http://www.wowhead.com/quest=11940/drake-hunt
Must have a blue quest mark!?~~ **INVALID** (it is blue if no other q available)
* ~~http://www.wowhead.com/quest=11957/saragosas-end
boss summoned and nothing~~ **FIXED** https://github.com/cmangos/wotlk-db/commit/06d7ad6c233d7707c7739a524ad9f55ad8bdb00b
~~quest item doesnot disappeared~~ **FIXED** https://github.com/cmangos/wotlk-db/commit/06d7ad6c233d7707c7739a524ad9f55ad8bdb00b
* ~~http://www.wowhead.com/quest=11969/springing-the-trap
doesnot work~~ **FIXED** https://github.com/cmangos/wotlk-db/commit/8687c59187ac2317e26751316c949d8c466ad1d5

Nexus
* ~~Does looting this
http://www.wowhead.com/item=43095/berinands-research#comments
summoning boss?~~ **Core ISSUE** - DB added all req spawns there
* ~~grand magus telestra bugged~~ **Improved** 
* ~~crazed mana surge npcs doesnot attackable~~ **FIXED**
* ~~anomalus bugged too~~ **Improved** 
* ~~ormorok boss has some npcs in his area with must be a patrol~~ **FIXED**

* ~~http://www.wowhead.com/quest=11864/a-mission-statement
Dunno, I must take quest and then handle it.. but when I come ..npc just give me option handle the quest~~ **INVALID** (this is start for D.E.T.A. chain)
* ~~http://www.wowhead.com/quest=11876/help-those-that-cannot-help-themselves
Quest item doesnot disappeared~~ **FIXED**
* ~~http://www.wowhead.com/quest=11878/khunok-will-know
Is not there must be some npc with you?~~ **FIXED** https://github.com/cmangos/wotlk-db/commit/b88d0bb457de975b4809d41deaf34699971ed7ff
* ~~http://www.wowhead.com/npc=25803/karen-i-dont-caribou-the-culler#comments
“an be found at 57,56 with several (2 or 3) stealthed guards. She has a special whirlwind attack that does approximately 300 damage on leather.”~~ **FIXED**
* ~~http://www.wowhead.com/quest=11865/unfit-for-death
Quest item doesnot disappeared~~ **FIXED**
* ~~http://www.wowhead.com/quest=11945/preparing-for-the-worst
Must have a blue mark~~ **INVALID** (it has)
* ~~http://www.wowhead.com/quest=11610/leading-the-ancestors-home
Quest item doesnot disappeared~~ **FIXED** https://github.com/cmangos/wotlk-db/commit/70b8abdb07e20a9a071a7c5966856e9e0d7a4c06
*  ~~http://www.wowhead.com/npc=28382/hotawa
Did not give me quest.. probably couse I did him before
http://www.wowhead.com/quest=12117/travel-to-moaki-harbor~~ **INVALID** (player can pick up only one of leading quests)
* ~~strange plane at /55/27~~ **FIXED**
* ~~http://www.wowhead.com/quest=11892/the-assassination-of-harold-lane
Quest item doesnot dissapeared~~ **FIXED** https://github.com/cmangos/wotlk-db/commit/70b8abdb07e20a9a071a7c5966856e9e0d7a4c06
* ~~http://www.wowhead.com/quest=11945/preparing-for-the-worst
Must have a blue mark~~ **Duplicate**

UPDATE 1
* ~~http://www.wowhead.com/quest=11881/loader-up
Quest item must be removed~~ **FIXED**
* ~~http://www.wowhead.com/quest=11640/words-of-power
Nefarset cant be killed.. he doesnot wake up when you kill guards~~ **FIXED**
* ~~http://www.wowhead.com/quest=11940/drake-hunt
Must have blue mark~~ it does when you finish it first time
*need this to be fixed, so i can test maligos q chain
https://github.com/cmangos/wotlk-db/issues/235
this is the last part m that not tested yet

**Comment by Grz3s** [comment]
```quote
*http://www.wowhead.com/quest=11595/the-defense-of-warsong-hold
 Keep in mind 3 same quests with different speaking? 11595-11596-11597
 *two different version as well
http://www.wowhead.com/quest=11586/hellscreams-vigil#comments
http://www.wowhead.com/quest=11585/hellscreams-vigil
```
and whats wrong with it??
i fixed all 3 ... long time ago... each version appears has his condition ..
more info here:
https://github.com/cmangos/wotlk-db/commit/703848e0e2e7986c9b5c76bed2f19605cb2c25ca

**Comment by Grz3s** [comment]
leads to 10. [71] Hellscream's Champion

**Comment by Grz3s** [comment]
```quote
http://www.wowhead.com/npc=26972/orn-tenderhoof#starts
 Same .. not available Couse of howling fjord?
```
http://www.wowhead.com/quest=13087/northern-cooking#comments:id=447345

**Comment by Grz3s** [comment]
```quote
•http://www.wowhead.com/quest=11608/bury-those-cockroaches
 I believe there are was some effect on destroyed holes
```
can you see any other effect than explosion?
https://youtu.be/2_sKYViT3ls?t=57

**Comment by rmzV** [comment]
1) i didnt know that all 3 was fixed, couse test only one
2) "leads to" marker for me.. if previvious quest get fixed, i must check this one
3) ok
4) agreed,

**Comment by Grz3s** [comment]
```quote
2."leads to" - marker for me..
```
yes but other 2 leads to this also ;) ... and thats why all 3 must be completed

**Comment by rmzV** [comment]
"http://www.wowhead.com/quest=11940/drake-hunt
Must have blue mark it does when you finish it first time"
is it possible? that.. when you finish quest as yellow one.. it become daily.. but after server restart it turns into yellow again?

**Comment by Grz3s** [comment]
First quest u'll see is this one:
http://www.wowhead.com/quest=11919/drake-hunt (not daily) - thats why i said ..that after finishing "drake-hunt" first time You'll see blue mark..
Basically ... finishing 11919 is req. for your Daily "http://www.wowhead.com/quest=11940/drake-hunt
I hope  this time i explained it better ;)

**Comment by rmzV** [comment]
ye.. just checked npc has
http://www.wowhead.com/quest=11940/drake-hunt
but with blue"!"
thats why i was missleaded

**Comment by rmzV** [comment]
same with that quest
http://www.wowhead.com/quest=11945/preparing-for-the-worst

**Comment by rmzV** [comment]
epik work!
do i need to create icket in server section for this ones^


http://www.wowhead.com/quest=11560/oh-noes-the-tadpoles
On live saved murlocks running near you for some time REQ SD2 - can't be fixed by DB

and
Does looting this
http://www.wowhead.com/item=43095/berinands-research#comments
summoning boss? Core ISSUE - DB added all req spawns there

**Comment by AnonXS** [comment]
Yes please add them here https://github.com/cmangos/issues/issues

**Comment by rmzV** [comment]
tikets done=)

**Comment by Grz3s** [comment]
@rmzV 
```quote
Does looting this
http://www.wowhead.com/item=43095/berinands-research#comments
summoning boss? Core ISSUE - DB added all req spawns there
```
conditional spawn system was added long time ago...  ..and this issue was fixed...
it wasnt item problem ..but normal spawn for "X" depends of "Y"
It works fine now;)
