### ISSUE TITLE
Two quests - NPCs do not appear to complete quests

### ISSUE THREAD

**Issue by mcsescott** [cmangos/wotlk-db#234]
Two quests where the NPCs do not appear to turn in the quest, even when it shows completed in the quest log:

- [x] 12238 - Cleansing Drak'Tharon - http://www.wowhead.com/quest=12238/cleansing-draktharon

- [x] 12661 - Infiltrating Voltarus - http://www.wowhead.com/quest=12661/infiltrating-voltarus

Wrong aura or phase, maybe?

Thanks in advance...

**Comment by rmzV** [comment]
http://www.wowhead.com/quest=12238/cleansing-draktharon
works for sure. just checked.. you need 5 mojos to sumn quest ender

**Comment by Grz3s** [comment]
12238 - fixed https://github.com/cmangos/wotlk-db/commit/25d710aa55aa2cd726d9912259a7c1c0baf0c50a

**Comment by Grz3s** [comment]
both fixed
