### ISSUE TITLE
Lax issues list pt.9 wotlk (p3 of 8)  dragon

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#237]
- [x] http://www.wowhead.com/quest=11960/planning-for-the-future
Must have a blue mark
- [x] Nagojut npc placed in water  **temp. FiX**
- [x] Aumanil npc placed in water  **temp. FiX**
- [x] http://www.wowhead.com/quest=12017/meat-on-the-hook
https://www.youtube.com/watch?v=X1CAoguiWa0
not correct scripting?
Quest item doesnot disappeared  **FIXED**
- [x] http://www.wowhead.com/quest=12028/spiritual-insight
Quest item doesnot disappeared **FIXED**
- [x] indu’le fisherman 38/67 and 42/68 in non attackable state  **FIXED**
- [x] 38/67 Dragonblight mage hunters in underwater? **FIXED**
- [x] http://www.wowhead.com/quest=12032/conversing-with-the-depths
https://www.youtube.com/watch?v=jZBF9FExel8
doesnot work  **FIXED**
- [x] http://www.wowhead.com/quest=12189/imbeciles-abound
Did not get this quest.. maybe couse of doing
http://www.wowhead.com/quest=12182/to-venomspite
prior??? **FIXED**
- [x] http://www.wowhead.com/quest=12545/the-cleansing-of-jinthakalar
Not enough enemy npcs at 88/21 **FIXED**
- [x] quest not available for testing
http://www.wowhead.com/npc=29162/magister-tyrganal
http://www.wowhead.com/quest=12791/the-magical-kingdom-of-dalaran~~ **INVALID**  works fine (quest can be obtain in few places = so if taken somewhere else .. will not show up here)
- [x] http://www.wowhead.com/quest=12456/the-plume-of-alystros
Quest item use spot,… must be corrected.. hard to find it now
Quest item doesnot work even at boss spot **FIXED**
- [x] http://www.wowhead.com/quest=12173/attunement-to-dalaran
Not tested **FIXED**
- [x] http://www.wowhead.com/quest=12791/the-magical-kingdom-of-dalaran
Was done before and non available now? **FIXED**
- [x] http://www.wowhead.com/quest=11960/planning-for-the-future
Must have blue mark ! **FIXED**
- [x] http://www.wowhead.com/quest=12456/the-plume-of-alystros
Doesnot work.. quest item must be removed **FIXED**
- [x] http://www.wowhead.com/quest=12188/the-forsaken-blight-and-you-how-not-to-die
Mobs at 81/69 in non attachable state..when you kill npc.. horses still alive? **FIXED**
- [x] http://www.wowhead.com/quest=12218/spread-the-good-word
Too big agro radius for quest mobs **FIXED**
- [x] http://www.wowhead.com/quest=12252/torture-the-torturer
Item must be used 5 times
Quest item doesnot disappeared **FIXED**
- [x] http://www.wowhead.com/quest=12273/the-denouncement
Doesnot work.. quest item missed? Must be disappeared after complete **FIXED**
- [x] http://www.wowhead.com/quest=12304/beachfront-property
wrong quest giver?
currently it given by High Executor Wroth
but must be given by
http://www.wowhead.com/npc=32599/surveyor-hansen **FIXED**
- [x] quest sequences broken in Venomspite. need deeper investigation. **FIXED**
- [x] "Need to Know" opens after "Stealing from the Siegesmiths": **FIXED**
- [x] 80/66 non attackable npc **FIXED**
- [x] http://www.wowhead.com/quest=12230/stealing-from-the-siegesmiths
Must have completed Let Them Not Rise! in order to accept this quest.
Pre-Requisite for A Means to an End, and Need to Know from other quest givers in Venomspite. **FIXED**
- [x] http://www.wowhead.com/quest=12232/bombard-the-ballistae
Doesnot work **FIXED**
- [x] http://www.wowhead.com/quest=12214/fresh-remounts
Prequest req
http://www.wowhead.com/quest=12209/materiel-plunder **FIXED**
- [x] http://www.wowhead.com/quest=12234/need-to-know#comments
Prequest req
http://www.wowhead.com/quest=12230/stealing-from-the-siegesmiths **FIXED**
- [x] http://www.wowhead.com/quest=12206/blighted-last-rites
Opens next one **FIXED**
- [x] http://www.wowhead.com/quest=12211/let-them-not-rise
prerequisite is Blighted Last Rites
Leads to Stealing from the Siegesmiths **FIXED**
- [x] http://www.wowhead.com/quest=12240/a-means-to-an-end **FIXED**
- [x] http://www.wowhead.com/item=37269/scarlet-onslaught-daily-orders-beach
Placed twice **FIXED**
- [x] http://www.wowhead.com/quest=12260/the-perfect-dissemblance
doesnot work **FIXED**
- [x] http://www.wowhead.com/quest=12274/a-fall-from-grace
https://www.youtube.com/watch?v=iCAnVB33RqU
doesnot work **FIXED**
- [x] http://www.wowhead.com/quest=12232/bombard-the-ballistae
Quest item must be removed after completing…. Quest doesnot work **FIXED**
- [x] http://www.wowhead.com/quest=12240/a-means-to-an-end
Quest item must be removed **FIXED**
- [x] http://www.wowhead.com/quest=12211/let-them-not-rise
Quest item must be rmoved **FIXED**
- [x] http://www.wowhead.com/quest=12243/fire-upon-the-waters
https://www.youtube.com/watch?v=A1xK83GFq7U
quest item doesnot works and must be removed after end **FIXED**

**Naxx**

- [x] Spider wing
Was teleported out of dungeon with game crash several time.. some spider made this error
Carrion spinner spinner may be?
- [x] after maexna portal portaled me at wrong place.. to the sapphiron lair ..instead of entrance.. and you cant portal back on lower level
P;ague portal did the same
- [x] extend raid lock doesnot work
- [x] after wipe on kel,thuzad you cant enter.. encounter in progess
- [x] to many ozzies in patchwerk tunneil
- [x] grobbulus ..where the pool mechanics? I believe you must kite him.. or I did not saw them on stairs
- :x: last boss of construct quarter (tardius).. I killed both minibosses on one platform.. but boss did not start his attacks..bug? or this event cant be done by 1 char? -- sd2 script & core issue ... confirmed and reported there... should be resolved soon
- [x] nstructor razuvious .. mechanics doesnot work 
- [x] how to pull gothic the harvester?
- [x] sapphiron 10-25 missed? He must be acceptable even you don’t clean 4 wings
http://www.wowhead.com/npc=15989/sapphiron
- [x] must drop
http://www.wowhead.com/item=44569/key-to-the-focusing-iris?ilvl=1
http://www.wowhead.com/item=44577/heroic-key-to-the-focusing-iris?ilvl=1~~ **FIXED**

Onyxia
- [x] Mature Black Dragon Sinew
No longer drops from boss
http://wowwiki.wikia.com/wiki/Mature_Black_Dragon_Sinew
- [x] krasus 
http://www.wowhead.com/npc=27990/krasus
has^
http://www.wowhead.com/quest=26013/assault-on-the-sanctum
http://www.wowhead.com/quest=13385/heroic-judgment-at-the-eye-of-eternity
http://www.wowhead.com/quest=13384/judgment-at-the-eye-of-eternity
 all of this quests has a pre quests~~ **FIXED** 

UPDATE 1
- [x] http://www.wowhead.com/quest=11960/planning-for-the-future
Each server restart quest become yellow.. must be blue marked~~ **FIXED**
- [x] http://www.wowhead.com/quest=12095/to-dragons-fall
Prerequisite Quests
 Wanted - Dreadtalon //wotlk.wowhead.com/?quest=12091
 Wanted - Gigantaur //wotlk.wowhead.com/?quest=12090
Wanted - Magister Keldonus //wotlk.wowhead.com/?quest=12089~~ **FIXED**
- [x] http://www.wowhead.com/quest=12097/sarathstra-scourge-of-the-north
Dragon places in the ground and cant be killed
Preq
www.wowhead.com/quest=12095/to-dragons-fall~~ **FIXED**
- [x] http://www.wowhead.com/quest=12056/marked-for-death-high-cultist-zangus
Opens after this quest chain http://www.wowhead.com/quest=12034/victory-nears
Leads too
- [x] http://www.wowhead.com/quest=12057/the-flesh-bound-tome
leads too
- [x] http://www.wowhead.com/quest=12115/koltira-and-the-language-of-death
leads to
- [x] In Service of Blood
- [x] In Service of Frost
- [x] In Service of the Unholy~~ **FIXED**
- [x] 30/48 a strange pull of npcs~~ **FIXED**
- [x] http://www.wowhead.com/quest=11979/the-taunka-and-the-tauren
To check if this quest in game+quest sequences~~ **FIXED**
- [x] strange spot near waterfall at 13/41 missed npcs?~~ **FIXED**
- [x] http://www.wowhead.com/quest=11983/blood-oath-of-the-horde
Doesnot work~~ **FIXED**
- [x] Onto “the Kor'kron Vanguard” (unlocks after "The Forsaken Blight and You" chain is completed in Venomspite and "The Pit of Narjun & Nerubians in Icemist Village" chain is completed in Agmar's Hammer)~~ **FIXED**
- [x] http://www.wowhead.com/quest=12053/the-might-of-the-horde
Doesnot work~~ **FIXED**

* Azjol-Nerub (instance)
- [x] Hadronox bugged.. he become grayone  while fighting his way to top and after kill he was insta reswsed up and cant be killed again… npcs  continue to spawn after..~~ **FIXED** (core fix)
* Ahn'kahet: The Old Kingdom
- [x] Elder Nadox unkillable die to an aura .. npcs just poisoned each other in non stop mode~~ **FIXED**
- [x] Npc missed:
http://www.wowhead.com/npc=31104/ahnkahar-watcher
with drop
http://www.wowhead.com/item=43494/ahnkahar-watchers-corpse
q cant complete couse previvious npc missed
http://wowwiki.wikia.com/wiki/Quest:All_Things_in_Good_Time
also even with quest item blaizer doesnot works~~ **FIXED**
- [x] after killing pack at 51/61 some fantom npcs become following me.. and I cant kill them
portal at the end of the instance doesnot work~~ **FIXED**
- [x] http://www.wowhead.com/quest=12033/message-from-the-west
Pre q chains
http://www.wowhead.com/quest=11595/the-defense-of-warsong-hold
http://www.wowhead.com/quest=11716/the-wondrous-bloodspore
http://www.wowhead.com/quest=11916/hellscreams-champion~~ **FIXED**
- [x] http://www.wowhead.com/quest=12039/black-blood-of-yogg-saron
Pre req chain
http://www.wowhead.com/quest=12034/victory-nears~~ **FIXED**
- [x] http://www.wowhead.com/quest=12096/strengthen-the-ancients#comments
This quest appears to become available when you pick up the quest Atop the Woodlands.~~ **FIXED**
- [x] http://www.wowhead.com/quest=11999/rifle-the-bodies#comments
No bodies placed only their weapons~~ **FIXED**
- [x] http://www.wowhead.com/quest=12072/blightbeasts-be-damned
Doesnot work
Quest item must be removed after quest completed~~ **FIXED**
- [x] http://www.wowhead.com/quest=12039/black-blood-of-yogg-saron
Pre req
http://www.wowhead.com/quest=12034/victory-nears
quest item must be removed after completion~~ **FIXED**
- [x] http://www.wowhead.com/quest=12111/where-the-wild-things-roam
Doesnot work
Quest item must be removed~~ **FIXED**
- [x] http://www.wowhead.com/quest=12064/chains-of-the-anubar
Keys doesnot drop.. probably npcs posted in wrong spots~~ **FIXED**
- [x] http://www.wowhead.com/quest=12069/return-of-the-high-chief
Doesnot work?
You can just loot item from corpse?~~ **FIXED**
- [x] http://www.wowhead.com/quest=12140/all-hail-roanauk
Doesnot work
Quest item must be removed after completion~~ **FIXED**
- [x] http://www.wowhead.com/quest=12127/in-service-of-frost
http://www.wowhead.com/quest=12125/in-service-of-blood
http://www.wowhead.com/quest=12126/in-service-of-the-unholy
doesnot work
quest items musr be deleted after completion
this 3 quest are prereq to
http://www.wowhead.com/quest=12132/the-power-to-destroy~~ **FIXED**
- [x] http://www.wowhead.com/quest=12061/projections-and-plans
Quest item must be removed~~ **FIXED**
- [x] http://www.wowhead.com/quest=12096/strengthen-the-ancients#comments
Must be available after was picked up  http://www.wowhead.com/quest=12084/atop-the-woodlands~~ **FIXED**
- [x] http://www.wowhead.com/quest=12066/the-focus-on-the-beach
Quest item must be removed after completion~~ **FIXED**
- [x] http://www.wowhead.com/quest=12084/atop-the-woodlands
Quest item must be removed~~ **FIXED**
- [x] http://www.wowhead.com/quest=12107/the-end-of-the-line#comments
Quest item must be removed~~ **FIXED**
- [x] http://www.wowhead.com/quest=12066/the-focus-on-the-beach#comments
Quest item must be removd~~ **FIXED**
- [x] http://www.wowhead.com/quest=12500/return-to-angrathar
Must be available after
http://www.wowhead.com/quest=12498/on-ruby-wings~~ **FIXED**
- [x] http://www.wowhead.com/quest=12448/heated-battle
are they summoned on timer or what? Cousr I don’t see any spawned npsc to fight with (after first pack get killed)~~ **FIXED**

UPDATE 2
- [x] http://www.wowhead.com/quest=12449/return-to-the-earth#comments
Can be done on one dragon.. is not there are was an animation on live>~~ **FIXED*
- [x] http://www.wowhead.com/quest=12498/on-ruby-wings
Doesnot work
Quest item must be removed~~ **FIXED**
- [x] http://www.wowhead.com/quest=12372/defending-wyrmrest-temple
Must have blue mark. Is I working?~~ **FIXED*
- [x] http://www.wowhead.com/quest=12150/reclusive-runemaster
Doesnot work~~ **FIXED*
- [x] http://www.wowhead.com/quest=12470/mystery-of-the-infinite
Doesnot work
Quest item must be removed~~ **FIXED*
- [x] http://www.wowhead.com/quest=12151/wanton-warlord
Quest item must be removed~~ **FIXED*
- [x] http://www.wowhead.com/quest=12459/that-which-creates-can-also-destroy
Quest item must be removed~~ **FIXED*
- [x] http://www.wowhead.com/quest=13343/mystery-of-the-infinite-redux#comments
Doenot work~~ **FIXED*
- [x] quest sequence
http://www.wowhead.com/quest=26012/trouble-at-wyrmrest
->http://www.wowhead.com/quest=26013/assault-on-the-sanctum
->http://www.wowhead.com/quest=26034/the-twilight-destroyer~~ **INVALID** 1st quest is not req. for seconnd to show up... its just another optional quest to do...
- [x] quest sequence (starts with saphiron 10 item)
http://www.wowhead.com/quest=13375/the-heroic-key-to-the-focusing-iris
->http://www.wowhead.com/quest=13385/heroic-judgment-at-the-eye-of-eternity~~ **FIXED*
- [x] quest sequence ((starts with saphiron 25item)
http://www.wowhead.com/quest=13372/the-key-to-the-focusing-iris
->http://www.wowhead.com/quest=13384/judgment-at-the-eye-of-eternity#comments~~ **FIXED*

- [x] The Ruby Sanctum 
General zarithrian in non attackable state
So hallion cant be summoned and
http://www.wowhead.com/quest=26034/the-twilight-destroyer
cant be completed
- [x] http://www.wowhead.com/quest=12262/no-one-to-save-you
http://www.wowhead.com/quest=12261/no-place-to-run
pre quest req
http://www.wowhead.com/quest=12447/the-obsidian-dragonshrine~~ **FIXED*
- [x] http://www.wowhead.com/quest=12261/no-place-to-run
Ward can one hited by enemy.. its impossible to complete this quest
Quest item must be removed~~ **FIXED*
- [x] http://www.wowhead.com/quest=12263/the-best-of-intentions~~ **FIXED**
Prereq 
- [x] http://www.wowhead.com/quest=12262/no-one-to-save-you~~ **FIXED**
- [x] http://www.wowhead.com/quest=12261/no-place-to-run~~ **FIXED**
leads to
- [x] http://www.wowhead.com/quest=12264/culling-the-damned~~ **FIXED**
- [x] http://www.wowhead.com/quest=12265/defiling-the-defilers~~ **FIXED**
- [x] http://www.wowhead.com/quest=12267/neltharions-flame
“In the cave (31.31). Throw the quest item into the lava unlocking Rothin the Decaying and kill him.”
Now you can just kill him
Quest item must be removed~~ **FIXED**
- [x] Spot 43/19 a lot of server crashes here.. game just froze~~ **FIXED**
* quest chain missed
- [x] http://wowwiki.wikia.com/wiki/Quest:Darkness_Stirs~~ **FIXED**
- [x] http://www.wowhead.com/quest=13242/darkness-stirs~~ **FIXED**
- [x] http://www.wowhead.com/quest=13257/herald-of-war~~ **FIXED**
- [x] http://www.wowhead.com/quest=13266/a-life-without-regret~~ **FIXED**
- [x] http://www.wowhead.com/quest=13267/the-battle-for-the-undercity~~ **duplicate** can be found here https://github.com/cmangos/wotlk-db/issues/240

UPDATE 3 (last one)
- [x] http://www.wowhead.com/quest=12044/stocking-up~~ **FIXED**
Prereq
- [x] http://www.wowhead.com/npc=26660/xink~~ **FIXED**
Has non working dialog option~~ **FIXED**
- [x] probably this quest must appears in this sequence
  [74] Shaved Ice +
  [74] Soft Packaging +
  [74] Something That Doesn't Melt+ &   [74] Hard to Swallow +
  [74] Harp on this!+ &   [74] Lumber Hack +~~ **FIXED**
- [x] and the second sequences
  [74] Stiff Negotiations +
  [74] Slim Pickings +
  [74] Messy Business+ &   [74] Stomping Grounds +
  [74] Apply This Twice A Day +
  [74] Worm Wrangler+ &   [74G3] Really Big Worm +~~ **FIXED**
- [x] http://www.wowhead.com/quest=12052/harp-on-this
54/32 npc in non combat state (misstess of the coldwind)~~ **FIXED**
- [x] http://www.wowhead.com/quest=12050/lumber-hack
Doesnot work~~ **FIXED**
- [x] after http://www.wowhead.com/quest=12052/harp-on-this
AND http://www.wowhead.com/quest=12050/lumber-hack
Quest item must be removed~~ **FIXED** 
- [x] http://www.wowhead.com/quest=12049/hard-to-swallow
Doesnot work
Quest item must be removed~~ **FIXED**
- [x] http://www.wowhead.com/quest=12075/slim-pickings
Preq req
http://www.wowhead.com/quest=12112/stiff-negotiations~~ **FIXED**
- [x] ice heart cavern doesnot populated well(
http://www.wowhead.com/quest=12078/worm-wrangler
Quest item must be removed~~ **FIXED**
- [x] http://www.wowhead.com/quest=12076/messy-business
Quest item must be removed~~ **FIXED**

**Comment by Grz3s** [comment]
mistake from classic backport sor :)

**Comment by rmzV** [comment]
:)

**Comment by rmzV** [comment]
https://dropmefiles.com/JIHhS

**Comment by rmzV** [comment]
btw, can you confirm, that no need to clean all of the 4 naxx wings to get ported to saphiron?

**Comment by Grz3s** [comment]
this one was a challenge :)

**Comment by al3xc1985** [comment]
OMG this is so awesome! Ty

**Comment by rmzV** [comment]
EPIC!
