### ISSUE TITLE
Flight paths shortcut issues

### ISSUE THREAD

**Issue by RazzorX** [cmangos/wotlk-db#244]
- from Southshore to Light's Hope Chapel
-- in Menethil you fly through the Menethil Keep

- from Light's Hope Chapel to Southshore
-- near Ironforge you fly through a "Tower" of Ironforge

- Lakeshire to Booty Bay
-- near Rebel Camp you fly through a hill
   Generally there are a few problems here with the "direction of flight" near shortcut point.
   I can't explain it better...

- from Southshore to Thelsamar and vice versa
-- near Refuge Pointe you fly through the ground

**Comment by Warlockbugs** [comment]
Thanks for feedback. Unfortunately, some of these are already known ones. You can help by finding videos which contain said nodes within a long flight. What you see is a result of an algorithm when data is missing. It works fine for some nodes and not so much for others, which is expected, no size fits all. Many flight paths were made by different employees at different point in time.

**Comment by RazzorX** [comment]
Thanks for your explanation. Isn't easy to find useful videos for all points. So i made a few points on my own.

```
-- Alliance
DELETE FROM `taxi_shortcuts` WHERE `pathid` IN (257, 258, 261, 268, 273, 275, 746, 750, 751);
INSERT INTO `taxi_shortcuts` (`pathid`, `takeoff`, `landing`, `comments`) VALUES
(257, 0, 3, 'Lakeshire - Darkshire'),
(258, 5, 0, 'Darkshire - Lakeshire'),
(261, 4, 0, 'Darkshire - Nethergarde Keep'),
(268, 3, 0, 'Refuge Pointe - Thelsamar'),
(273, 3, 0, 'Refuge Pointe - Southshore'),
(275, 3, 0, 'Refuge Pointe - Aerie Peak'),
(746, 2, 0, 'Rebel Camp - Booty Bay'),
(750, 3, 2, 'Rebel Camp - Darkshire'),
(751, 4, 0, 'Darkshire - Rebel Camp');
```

Maybe this points are not 100% correct, but ingame they looks good for me.

**Comment by Warlockbugs** [comment]
As a matter of fact, I've managed to capture a few flight paths from the list on retail during the last free weekend.

You also seem to be chasing odd edge cases which we will likely never be able to capture. Rebel camp is rarely used as an actual junction if Stormwind is known. Capturing such flights on retail requires some form of packet modification, because UI wont allow manually specifying chain of nodes even if they are connected.

**Comment by Warlockbugs** [comment]
Should be closed by https://github.com/cmangos/wotlk-db/pull/245.
