### ISSUE TITLE
12029/12038

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#247]
must be available first
http://www.wowhead.com/quest=12029/seared-scourge
then, daily
http://www.wowhead.com/quest=12038/seared-scourge
now you get daily first

charges on quest items are wrong

also required prequest to complete
http://www.wowhead.com/quest=12484/scourgekabob

**Comment by Grz3s** [comment]
fixed:
https://github.com/cmangos/wotlk-db/commit/fba6d6ed3660996d4d983337564d04b758963c57
