### ISSUE TITLE
gorgonna

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#249]
After completing last conquest pit quest npc disappeared
http://www.wowhead.com/npc=27102/gorgonna
but she still had non taken quest
http://www.wowhead.com/quest=12425/ruuna-the-blind
how can I supposted to take this quest?

**Comment by rmzV** [comment]
@Grz3s i revisit npc but no quest available.. its because i ended flowed up quests?

**Comment by Grz3s** [comment]
remove cache in your wow (game) folder
make sure you finished prequest which started from book:
https://github.com/cmangos/wotlk-db/commit/a76b4851c394f88a215bde0aa42fc258673e3816
