### ISSUE TITLE
anthions-parting-words

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#259]
http://wowwiki.wikia.com/wiki/Quest:Anthion%27s_Parting_Words_(Horde)
https://www.wowhead.com/quest=9020/anthions-parting-words
quest doesnot appeared... i belive it has similar issues as
https://github.com/cmangos/wotlk-db/issues/94

**Comment by rmzV** [comment]
so it works now?

**Comment by AnonXS** [comment]
wrong linking from another commit

**Comment by rmzV** [comment]
may be @Grz3s can look at this issue and backport is possible?

**Comment by Grz3s** [comment]
quest appeared stright after q.9015 'The Challenge' completed...
nothing to fix here

**Comment by rmzV** [comment]
https://dropmefiles.com/II2aQ
@Grz3s 
still doesnot work. cache cleaned

**Comment by Grz3s** [comment]
ok i know whats wrong ... (TBC) Horde paladin and Alliance shaman
... will fix it soon

**Comment by rmzV** [comment]
oh) thx

**Comment by Grz3s** [comment]
![Uploading xxx.jpg…]()

**Comment by Grz3s** [comment]
![xxx](https://user-images.githubusercontent.com/2374069/112909817-0c6ab980-90ea-11eb-9d67-176859fc6b06.jpg)
