### ISSUE TITLE
[WOTLK] Quest Tree's Company

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#27]
UDB 408

I use the disguise kit at the proper place and after I transform into tree, Engineer Spark show up and he start walking in the direction of the camp where he actually is!
Everything else is fine. Geezle comes perfect he start the speach, but Spark isn't there to answer to his lines. The quest complete like it would work perfect!

Enginner Spark is the only problem!

Thank you

**Comment by NeatElves** [comment]
I confirm that something broke in the core with motion generators.

**Comment by xfurry** [comment]
Poke @cyberium 
Any recent changes in the movement behavior? I also noticed some weird stuff going on with the movement lately.

**Comment by cyberium** [comment]
I dont remeber a specific change that could do that. However this issue is pretty obsure to me.

So the best is to have all step detailed to make it replicable for me or for other that would help on this.
