### ISSUE TITLE
Pilgrim's Bounty Food Buff

### ISSUE THREAD

**Issue by adellaci** [cmangos/wotlk-db#283]
@Grz3s 

The food buff where not fixed in the database. The fix was offered in ([WOTLK] Food Spell Buff Patch #1570) by @NeatElves,  and they may apply to classic-db & tbc-db.

#Slow-Roasted Turkey
UPDATE  `spell_template` SET `EffectTriggerSpell3` = '65414' WHERE `Id` =65422;
#Candied Sweet Potato
UPDATE  `spell_template` SET `EffectTriggerSpell3` = '65410' WHERE `Id` =65418;
#Cranberry Chutney
UPDATE  `spell_template` SET `EffectTriggerSpell3` = '65412' WHERE `Id` =65420;
#Pumpkin Pie
UPDATE  `spell_template` SET `EffectTriggerSpell3` = '65415' WHERE `Id` =65421;
#Spice Bread Stuffing
UPDATE  `spell_template` SET `EffectTriggerSpell3` = '65416' WHERE `Id` =65419;

**Comment by Grz3s** [comment]
problem is thats not a DB... 
fix need to be applied by core developers... @killerwife can you pls look at this?

**Comment by adellaci** [comment]
@Grz3s 
Thank you and to you also @killerwife

**Comment by adellaci** [comment]
@Grz3s 
Can you explain to me if i manual make these entries into the database the buffs function or does it only appear to be functioning?

**Comment by Grz3s** [comment]
fixed:
https://github.com/cmangos/mangos-wotlk/commit/ba3f1aa218f99663f13ab97625b2c6afe24613db
