### ISSUE TITLE
[patch] Add lost random daily TBC cooking quest

### ISSUE THREAD

**Issue by NeatElves** [cmangos/wotlk-db#285]
source TBCDB
**NPC**:
https://www.wowhead.com/npc=24393/the-rokk
**quest**:
1  https://www.wowhead.com/quest=11377/revenge-is-tasty
2  https://www.wowhead.com/quest=11379/super-hot-stew
3  https://www.wowhead.com/quest=11380/manalicious
4  https://www.wowhead.com/quest=11381/soup-for-the-soul

```sql
DELETE FROM game_event WHERE entry IN (1249,1248,1247,1246);
INSERT INTO game_event (entry, start_time, end_time, occurence, length, holiday, linkedTo, EventGroup, description) VALUES
(1249, '2011-01-14 02:00:00', '2020-12-31 00:00:00', 0, 1440, 0, 0, 3, 'Cooking - Random Daily - Soup for the Soul'),
(1248, '2011-01-14 02:00:00', '2020-12-31 00:00:00', 0, 1440, 0, 0, 3, 'Cooking - Random Daily - Manalicious'),
(1247, '2011-01-14 02:00:00', '2020-12-31 00:00:00', 0, 1440, 0, 0, 3, 'Cooking - Random Daily - Super Hot Stew'),
(1246, '2011-01-14 02:00:00', '2020-12-31 00:00:00', 0, 1440, 0, 0, 3, 'Cooking - Random Daily - Revenge is Tasty');
DELETE FROM `game_event_quest` WHERE `quest` in (11377,11379,11380,11381);
DELETE FROM game_event_quest WHERE event BETWEEN 1246 AND 1249;
INSERT INTO game_event_quest(event,quest) VALUES
(1246,11377), (1247,11379), (1248,11380), (1249,11381);
```

**Comment by Grz3s** [comment]
@NeatElves
`
1130 - Cooking - Random Daily - Soup for the Soul
1129 - Cooking - Random Daily - Manalicious
1128 - Cooking - Random Daily - Super Hot Stew
1127 - Cooking - Random Daily - Revenge is Tasty
`
isnt this a duplicate?

**Comment by NeatElves** [comment]
Sorry, this part is not in the database
```sql
DELETE FROM `game_event_quest` WHERE `quest` in (11377,11379,11380,11381);
DELETE FROM game_event_quest WHERE event BETWEEN 1127 AND 1130;
INSERT INTO game_event_quest(event,quest) VALUES
(1127,11377), (1128,11379), (1129,11380), (1130,11381);
```
typo in up **1163_Game_Events_Part2.sql**
https://github.com/cmangos/wotlk-db/blob/master/Updates/1163_Game_Events_Part2.sql#L113 - q11381 
https://github.com/cmangos/wotlk-db/blob/master/Updates/1163_Game_Events_Part2.sql#L133 - delete quest in (13424,13423,13422,13425)
