### ISSUE TITLE
8736 the nightmare manifests

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#290]
- [ ] https://www.wowhead.com/quest=8736/the-nightmare-manifests#comments

event started.. you can foolow the npc to the center of village.. then hi sumn eranikus and you+him moved to the village center.. at that point you must start killing ghost.. and in one moment eranikus dissapeared and no ghosts.. andnothing(

**Comment by Grz3s** [comment]
its a sd2 script ... @cala or @xfurry .. ?

**Comment by cala** [comment]
Yes, the script is currently broken (and missing a few elements also). It is already on my todo list.

**Comment by xfurry** [comment]
It could be that the escort point counter has some problem:
https://github.com/cmangos/mangos-wotlk/blob/master/src/game/AI/ScriptDevAI/scripts/kalimdor/moonglade.cpp#L452

Maybe someone can debug this and see exactly where it fails

**Comment by cala** [comment]
I'll fully rework this in a near future.

**Comment by cala** [comment]
Fixed by https://github.com/cmangos/mangos-classic/commit/a3f3d46c4c867475a1a72d57ed0b67eef694dce9 and https://github.com/cmangos/classic-db/commit/da70377e3cafe5dfebb9c030e49a1c078fe418a3

**Comment by rmzV** [comment]
after boss fight...quest ender dissapeared from fight spot, bot not appeared in quest enders spot

**Comment by AnonXS** [comment]
open new issue.

**Comment by rmzV** [comment]
done
