### ISSUE TITLE
Axel Issues part 1

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#292]
- [x] 1. Kids in the leatherworker house near the fish trainer north of goldshire shouldn't they have waypoints?
- [x] 2. Draenei paladin doesn't have Seal of Righteousness in actionbar when you create him
- [x] 3. Gazels groups in durotar just stand, they should have waypoints and link
4. ~~Garrick Padfoot from human start point should have his guard linked with him, when you attack him, his guard, even thou is neutral should attack too~~
- [x] 5. Missing Training Dummies in Stormwind
- [x] 6.  Hordes of gazzeles in durotar path script around the mountains and all over the entire map

**Comment by Grz3s** [comment]
4. not true...
https://youtu.be/_gaU-uCQdxQ?t=438

**Comment by al3xc1985** [comment]
yes you are right, my bad. and I copy paste wrong. I had a "?" sign on my notes. I forget to add it. but you are right

**Comment by rmzV** [comment]
@Grz3s  hello. everything fine with you? didnot see any activity from you for a long period of time^(
hoope you fine.

**Comment by Grz3s** [comment]
im ok ;)

**Comment by rmzV** [comment]
nice to hear that!!

**Comment by Grz3s** [comment]
sor it took that long ;)

**Comment by al3xc1985** [comment]
Don't worry.

**Comment by Grz3s** [comment]
regarding to 1.
actualy thats very nice - wonder how many ppl knew about it :)
https://wow.gamepedia.com/Children_of_Goldshire

**Comment by al3xc1985** [comment]
not 2 many believe me...I didn't saw them scripted on any server

**Comment by Grz3s** [comment]
you will soon ;)

**Comment by al3xc1985** [comment]
@Grz3s I will start playing again for you just to start doing full reports on everything...
I did a small check on the core differences...but couldn't find anythig lost during backports...I might do it again.. I know that I saw something during time.

Also I added a new point tot this issue..

There groups of gazzeles in durotar that NOONE ever scripted them 
Just check and you shall see they are spawned in group... they should have a script

**Comment by Grz3s** [comment]
i should finish with TDB backports soon... also i have lots my own updates for dragonblight but will add them after .. ;)

**Comment by al3xc1985** [comment]
will you do a full db release?

**Comment by Grz3s** [comment]
thx
