### ISSUE TITLE
Incorrect Damage Multipliers in Zul'Farrak

### ISSUE THREAD

**Issue by albeecode** [cmangos/wotlk-db#298]
Some of the mobs within Zul'Farrak seem to be hitting way to hard.  I compared the damage values within the creature_template table from the WOTLK database to the Classic database.  
See below code and outputs:
Classic:
`SELECT Name, MinMeleeDmg, MaxMeleeDmg, DamageMultiplier FROM classicmangos.creature_template WHERE Name like '%Zul\'Farrak%';`
Output:
`# Name, MinMeleeDmg, MaxMeleeDmg, DamageMultiplier
'Zul\'Farrak Dead Hero', '75.6', '102.4', '1'
'Zul\'Farrak Zombie', '269', '346', '1'`

WOTLK:
`SELECT Name, MinMeleeDmg, MaxMeleeDmg, DamageMultiplier FROM wotlkmangos.creature_template WHERE Name like '%Zul\'Farrak%';`
Output:
`# Name, MinMeleeDmg, MaxMeleeDmg, DamageMultiplier
'Zul\'Farrak Dead Hero', '77', '102', '1'
'Zul\'Farrak Zombie', '72', '96', '7.5'`

The Scarab's also appear to be off.
Classic:
`SELECT Name, MinMeleeDmg, MaxMeleeDmg, DamageMultiplier FROM classicmangos.creature_template WHERE Name like 'Scarab';`
Output:
`# Name, MinMeleeDmg, MaxMeleeDmg, DamageMultiplier
'Scarab', '72', '102.4', '1.3'`

WOTLK:
`SELECT Name, MinMeleeDmg, MaxMeleeDmg, DamageMultiplier FROM wotlkmangos.creature_template WHERE Name like 'Scarab';`
Output:
`# Name, MinMeleeDmg, MaxMeleeDmg, DamageMultiplier
'Scarab', '72', '96', '2.4'`

I modified the WOTLK database values to match the Classic values with the following codes:
`UPDATE wotlkmangos.creature_template
SET 
    MinMeleeDmg = 75.6,
    MaxMeleeDmg = 102.4,
    DamageMultiplier = 1
WHERE Name = 'Zul\'Farrak Dead Hero';`
`UPDATE wotlkmangos.creature_template
SET 
    MinMeleeDmg = 269,
    MaxMeleeDmg = 346,
    DamageMultiplier = 1
WHERE Name = 'Zul\'Farrak Zombie';`
`UPDATE wotlkmangos.creature_template
SET 
    MinMeleeDmg = 72,
    MaxMeleeDmg = 102.4,
    DamageMultiplier = 1.3
WHERE Name = 'Scarab';`

I also think some of the Sandfury mobs might be off in the damage they do, however I havn't learned enough about the database yet to identify where to modify spell damages.  I hope this helps!

Regards,
Albeecode

**Comment by Grz3s** [comment]
thx for reports... 
You dont really need to update these anymore  `MinMeleeDmg, MaxMeleeDmg`  -- if multiplier is correct .. then everything else will be taken from CLS talbe and calculated automat..
I'll correct it asap

**Comment by albeecode** [comment]
I'm assuming CLS table is the creature_template table?

Also, when I update these values they don't see to change right away.  Usually takes a service restart.  Is there a way to update this while keeping the server "live"?

**Comment by AnonXS** [comment]
https://github.com/cmangos/issues/wiki/mangosdb_struct shows which tables are reloadable while server is running
