### ISSUE TITLE
The Etymidian quest chain

### ISSUE THREAD

**Issue by Darth-Postal** [cmangos/wotlk-db#30]
Found some issues with "The Etymidian" quest chain from Avatar of Freya in Sholazar Basin.

1. q12803 "Force of Nature" should be skippable. You should be able to start the quest chain by picking q12561 "An Issue of Trust" directly from Avatar of Freya. [Source 1](http://www.wowhead.com/quest=12561/an-issue-of-trust#comments:id=1202312), [Source 2](http://www.wowhead.com/quest=12803/force-of-nature#comments:id=368259:reply=166704).

2. Both q12803 "Force of Nature" and q12561 "An Issue of Trust" should require "Cold Weather Flying" ability. [Source 1](http://www.wowhead.com/npc=27801/avatar-of-freya#comments:id=467311:reply=60099), [Source 2](http://www.wowhead.com/quest=12803/force-of-nature#comments:id=449423).

3. q12805 "Salvaging Life's Strength" should require q12611 "Returned Sevenfold" instead of q12612 "The Fallen Pillar" [Source](http://www.wowhead.com/quest=12612/the-fallen-pillar#comments:id=454709)

4. q12620 "The Lifewarden's Wrath" should require completion of both q12617 "Exterminate the Intruders" and q12660 "Weapons of Destruction". Currently it only requires q12617 "Exterminate the Intruders". [Source](http://www.wowhead.com/quest=12617/exterminate-the-intruders#comments:id=368342)

5. **[MOST LIKELY CORE ISSUE]** Quest item [i40397 "Lifeblood Gem"](http://www.wowhead.com/item=40397/lifeblood-gem) doesn't work. q12805 "Salvaging Life's Strength" cannot be completed. Created issue in core https://github.com/cmangos/issues/issues/1158

6. [NPC 28222 The Etymidian](http://www.wowhead.com/npc=28222) (It's the Vehicle one) should have Mana bar, because his spells use Mana. Currently has empty bar (UnitClass = 1). Mana bar can be seen [here](https://www.youtube.com/watch?v=s059jClsUuU).

Suggested fix:
```sql
-- Remove q12803 "Force of Nature" as requirement for q12561 "An Issue of Trust"
UPDATE quest_template SET PrevQuestId = 0 WHERE entry = 12561;

-- Make q12803 "Force of Nature" and q12561 "An Issue of Trust" require "Cold Weather Flying" ability.
UPDATE quest_template SET RequiredCondition = 309 WHERE entry IN (12561, 12803);

-- Make q12805 "Salvaging Life's Strength" require q12611 "Returned Sevenfold"
UPDATE quest_template SET PrevQuestId = 12611 WHERE entry = 12805;

-- Make q12620 "The Lifewarden's Wrath" require completion of both q12617 "Exterminate the Intruders" and q12660 "Weapons of Destruction"
UPDATE quest_template SET NextQuestId = 12620 WHERE entry IN (12617, 12660);
UPDATE quest_template SET PrevQuestId = 0 WHERE entry = 12620;

-- Give The Etymidian his Mana bar
UPDATE creature_template SET UnitClass = 2 WHERE entry = 28222;
```

**Comment by Darth-Postal** [comment]
@Grz3s Correct me if I'm wrong, but problem 2 cannot be solved in DB and requires Core support just like your issue here: https://github.com/cmangos/wotlk-db/issues/7

Cold Weather Flying is not a skill, it's a passive ability and cannot be set in RequiredSkill column. So we need something new implemented in Core.

**Comment by killerwife** [comment]
*sigh. Its basically an aura. So yeah, I see how that isnt working... I could help out on the #2 but I can think of multiple solutions and cant decide which is best design.

**Comment by Darth-Postal** [comment]
@killerwife Maybe it will help your decision if you also look at this issue: https://github.com/cmangos/wotlk-db/issues/7
It has another 2 cases of unusual quest requirements that cannot be set in DB.

A solution to all 3 cases would be perfect. 😊

**Comment by killerwife** [comment]
Thank you, I will make sure to look at them so I can give you guys support for it :) No etas unfortunately because I am at home. Likely I will use mangosd.conditions for it to finally use a unified condition system.

**Comment by Darth-Postal** [comment]
It seems problem 5 is also a Core issue. Made a ticket there: https://github.com/cmangos/issues/issues/1158

**Comment by killerwife** [comment]
@Darth-Postal https://github.com/killerwife/mangos-wotlk/commit/b84c9629e70bf6d0810ba05f3976998044078725

This should provide an interface for all your issues with conditions :) Sadly I wont help u with the other stuff because its wotlk specific and I do not have time for that. If you ever need a DB tool added let me know though, I do add stuff for @Grz3s from time to time.

**Comment by Darth-Postal** [comment]
@killerwife Thank you! 👍 
Downloading to test now. Will report in 20-30 minutes.

**Comment by killerwife** [comment]
Also this basically makes RequiredSkill column obsolete, so over time we should probably get rid of it.

**Comment by Darth-Postal** [comment]
@killerwife I have no idea why, but I can't compile in VS2015:
```
10>  ScriptLoader.cpp
10>  system.cpp
10>  ScriptMgr.cpp
10>  Generating Code...
10>LINK : fatal error LNK1181: cannot open input file 'mangosd.lib'
```
Tried re-cloning repo, tried debug/release/Win32/x64 -  same result.

Regular CMangos-Wotlk compiles fine.

I used `git clone -b feature/quest-condition --single-branch git://github.com/killerwife/mangos-wotlk.git GIT_TEMP01` to clone your repo.

What am I doing wrong?

**Comment by Darth-Postal** [comment]
Also:
```
2>  ObjectMgr.cpp
2>..\..\src\game\ObjectMgr.cpp(111): error C2065: 'CONDITION_FROM_SPELLCLICK': undeclared identifier
```

**Comment by killerwife** [comment]
I was investigating it and that error was causing it. It was caused by me working on it on TBC branch :) I just force pushed to the branch, try newest and it should work accordingly now.

**Comment by Darth-Postal** [comment]
@killerwife Compiled OK 👍 

Seems to be working OK 👍 There already was a condition to check for Cold Weather Flying in conditions table (ID 309), so I simply did
```sql
UPDATE quest_template SET RequiredCondition = 309 WHERE entry IN (12561, 12803);
```
and the result is below:

![wowscrnshot_112216_205616](https://cloud.githubusercontent.com/assets/19946716/20537779/1305b43e-b0f7-11e6-8c64-3e8207261377.jpg)

![wowscrnshot_112216_205645](https://cloud.githubusercontent.com/assets/19946716/20537787/1b879316-b0f7-11e6-8b03-0ad9bc5291f0.jpg)

**Comment by killerwife** [comment]
The only issue atm is that it does not update when you learn it next to him (the Qgiver overhead punctuation) as that would require spamming server with resending opcodes for punctuation. That would require much deeper logic, but it can be implemented in the future, so no biggie. Likely it will be done on certain interactions when we figure out which conditions are needed.

**Comment by Darth-Postal** [comment]
It DID update for me. Look at second screen's chat. I learned all riding from quest giver and the quest appeared right away.

**Comment by killerwife** [comment]
It updated gossip menu, not overhead punctuation :)

**Comment by Darth-Postal** [comment]
I understand now. Still, great job 👍 Thank you!

**Comment by Darth-Postal** [comment]
@Grz3s now this can be accepted and closed. **Requires core patch 12948 to work.**
