### ISSUE TITLE
[Pet] Mage Water Elemental

### ISSUE THREAD

**Issue by albeecode** [cmangos/wotlk-db#301]
When summoning mage water elemental with glyph of eternal water, it makes the pet use creature ID 37994.

If you execute the following query, you will see that the summoned water elementals both have flaws, 1. If you don't use glyph of eternal water, the level will only scale from 60 - 70 instead of 50 (when the spell is learned) up to 80 (max level cap in wotlk)
2. The glyph of eternal water version (entry 37994) has a min-max level of 1, and the stats are all off for this creature.

I'm not sure exactly what the values should be and I'm not sure how to find them.  If theres a way I can find them let me know and I will gladly work on writing the update statement to resolve this issue.

Query:
`SELECT * FROM wotlkmangos.creature_template WHERE entry IN (510, 37994);`
Output:
```
Entry, Name, SubName, IconName, MinLevel, MaxLevel, DifficultyEntry1, DifficultyEntry2, DifficultyEntry3, ModelId1, ModelId2, ModelId3, ModelId4, Faction, Scale, Family, CreatureType, InhabitType, RegenerateStats, RacialLeader, NpcFlags, UnitFlags, DynamicFlags, ExtraFlags, CreatureTypeFlags, SpeedWalk, SpeedRun, Detection, CallForHelp, Pursuit, Leash, Timeout, UnitClass, Rank, Expansion, HealthMultiplier, PowerMultiplier, DamageMultiplier, DamageVariance, ArmorMultiplier, ExperienceMultiplier, MinLevelHealth, MaxLevelHealth, MinLevelMana, MaxLevelMana, MinMeleeDmg, MaxMeleeDmg, MinRangedDmg, MaxRangedDmg, Armor, MeleeAttackPower, RangedAttackPower, MeleeBaseAttackTime, RangedBaseAttackTime, DamageSchool, MinLootGold, MaxLootGold, LootId, PickpocketLootId, SkinningLootId, KillCredit1, KillCredit2, QuestItem1, QuestItem2, QuestItem3, QuestItem4, QuestItem5, QuestItem6, MechanicImmuneMask, SchoolImmuneMask, ResistanceHoly, ResistanceFire, ResistanceNature, ResistanceFrost, ResistanceShadow, ResistanceArcane, PetSpellDataId, MovementType, MovementTemplateId, TrainerType, TrainerSpell, TrainerClass, TrainerRace, TrainerTemplateId, VendorTemplateId, EquipmentTemplateId, VehicleTemplateId, GossipMenuId, VisibilityDistanceType, AIName, ScriptName
'510', 'Water Elemental', '', '', '60', '70', '0', '0', '0', '525', '0', '0', '0', '115', '1', '0', '4', '3', '3', '0', '0', '32770', '0', '0', '0', '1.125', '1.14286', '20', '0', '0', '0', '0', '8', '0', '0', '0.75', '0.33', '1', '1', '1', '1', '2998', '2998', '3043', '3043', '252', '357', '215', '320', '6719', '304', '44', '2000', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '', ''
'37994', 'Water Elemental', '', '', '1', '1', '0', '0', '0', '525', '0', '0', '0', '35', '1', '0', '4', '3', '3', '0', '0', '32768', '0', '0', '0', '1', '1.14286', '20', '0', '0', '0', '0', '2', '0', '1', '0.75', '0.33', '1', '1', '1', '1', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '', ''
```

**Comment by albeecode** [comment]
I updated my original post to clean-up the output.

**Comment by Grz3s** [comment]
try this:
`
UPDATE creature_template SET MinLevel = 50, MaxLevel = 80 WHERE entry = 510;
UPDATE creature_template SET MinLevel = 50, MaxLevel = 80, Expansion = 1, UnitClass = 8 WHERE entry = 37994;

UPDATE creature_template SET MinLevelHealth = 1163, MaxLevelHealth = 2804, MinLevelMana = 1450, MaxLevelMana = 2908 WHERE entry IN (510);
UPDATE creature_template SET MinLevelHealth = 1163, MaxLevelHealth = 4858, MinLevelMana = 1450, MaxLevelMana = 2908 WHERE entry IN (37994);

DELETE FROM pet_levelstats WHERE creature_entry IN (37994);
INSERT INTO pet_levelstats (creature_entry, level, hp, mana, armor, str, agi, sta, inte, spi) VALUES
(37994,1,60,60,0,20,16,20,13,8),
(37994,2,73,73,0,21,17,21,14,10),
(37994,3,87,87,0,22,18,22,15,12),
(37994,4,101,101,0,23,19,23,16,14),
(37994,5,115,115,0,24,20,24,17,16),
(37994,6,129,129,0,25,21,25,18,18),
(37994,7,152,152,0,26,22,26,19,20),
(37994,8,156,156,0,27,23,27,20,22),
(37994,9,170,170,0,28,24,28,21,24),
(37994,10,184,184,0,29,25,29,22,26),
(37994,11,198,198,0,30,25,32,22,28),
(37994,12,225,225,0,31,26,36,24,31),
(37994,13,254,254,0,32,28,43,26,32),
(37994,14,284,254,0,33,28,44,25,35),
(37994,15,313,313,0,34,30,48,26,37),
(37994,16,343,343,0,36,30,52,27,39),
(37994,17,375,375,0,38,31,55,28,42),
(37994,18,392,392,0,39,33,59,28,44),
(37994,19,438,438,0,40,33,63,30,46),
(37994,20,471,471,0,42,35,67,31,49),
(37994,21,500,500,0,44,36,80,31,51),
(37994,22,528,528,0,46,36,84,32,53),
(37994,23,558,558,0,47,38,89,33,55),
(37994,24,595,595,0,49,39,83,34,58),
(37994,25,630,630,0,50,40,87,35,61),
(37994,26,678,678,0,52,41,91,36,62),
(37994,27,705,705,0,53,42,95,37,65),
(37994,28,740,740,0,55,43,99,38,67),
(37994,29,775,775,0,56,44,103,39,70),
(37994,30,800,800,0,58,46,107,40,72),
(37994,31,856,856,0,59,47,111,40,74),
(37994,32,921,921,0,61,48,115,41,77),
(37994,33,987,987,0,62,49,119,42,79),
(37994,34,1047,1047,0,63,51,123,43,82),
(37994,35,1107,1107,0,65,52,127,44,84),
(37994,36,1167,1167,0,66,53,131,45,87),
(37994,37,1227,1227,0,68,53,135,46,89),
(37994,38,1288,1288,0,70,55,139,47,91),
(37994,39,1348,1348,0,72,56,143,48,94),
(37994,40,1408,1408,0,74,58,148,49,97),
(37994,41,1468,1468,0,76,59,152,50,99),
(37994,42,1528,1528,0,81,59,156,51,102),
(37994,43,1588,1588,0,86,61,160,52,104),
(37994,44,1648,1648,0,89,62,164,53,107),
(37994,45,1708,1708,0,91,64,169,54,109),
(37994,46,1768,1768,0,94,65,173,55,112),
(37994,47,1828,1828,0,96,66,178,56,115),
(37994,48,1889,1889,0,99,68,182,57,117),
(37994,49,1950,1950,0,101,69,186,58,120),
(37994,50,2003,2003,0,104,71,191,59,123),
(37994,51,2055,2055,0,107,72,195,61,126),
(37994,52,2108,2108,0,109,73,199,62,128),
(37994,53,2161,2161,0,112,75,204,63,131),
(37994,54,2213,2213,0,114,76,208,64,134),
(37994,55,2266,2266,0,117,77,213,65,136),
(37994,56,2318,2318,0,119,79,217,66,139),
(37994,57,2371,2371,0,122,80,221,67,142),
(37994,58,2424,2425,0,124,82,226,68,144),
(37994,59,2476,2476,0,127,83,230,69,147),
(37994,60,2529,1874,0,129,85,234,70,150),
(37994,61,2582,2682,0,130,86,238,71,153),
(37994,62,2635,2735,0,131,87,242,72,156),
(37994,63,2688,2788,0,132,88,246,73,159),
(37994,64,2741,2841,0,133,89,250,74,162),
(37994,65,2794,2894,0,134,90,254,75,165),
(37994,66,2847,2947,0,135,91,258,76,168),
(37994,67,2900,3000,0,136,92,262,77,171),
(37994,68,2953,3053,0,137,93,266,78,174),
(37994,69,3006,3100,0,138,94,280,79,177),
(37994,70,3059,3212,0,139,95,284,80,180),
(37994,71,2489,4568,0,167,123,81,299,195),
(37994,72,2549,4676,0,171,127,82,305,200),
(37994,73,2609,4784,0,175,131,83,311,205),
(37994,74,2669,4892,0,179,135,84,317,210),
(37994,75,2729,5000,0,183,139,85,323,215),
(37994,76,2789,5108,0,187,143,86,329,220),
(37994,77,2849,5216,0,191,147,87,335,225),
(37994,78,2909,5324,0,195,151,88,341,230),
(37994,79,2969,5432,0,199,155,89,347,235),
(37994,80,3029,5540,0,203,159,90,353,240);
`

**Comment by albeecode** [comment]
Just ran it now, going to check the water elemental in game now.

**Comment by albeecode** [comment]
Looks like that fixed the issue.  
I'm also noticing the spell it casts "Waterbolt" only costs 6 mana, which seems off in my opinion. 
Also, when summoned, it doesn't summon with full HP and Mana (but that might be expected behavior for the version of the pet that lasts permanently)

**Comment by Grz3s** [comment]
(...)it doesn't summon with full HP and Mana(...) I doub... this is another core issue...
about aterbolt ill check if correct spell is used by him

**Comment by albeecode** [comment]
Okay.  Do you want me to open another issue for the core issue of pet not summoning with full HP and Mana?  I don't want to mix or confuse matters

**Comment by Grz3s** [comment]
Can do ...
