### ISSUE TITLE
what-the-dragons-know

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#312]
- [ ] https://www.wowhead.com/quest=24555/what-the-dragons-know

krakus havent any dialog options(

**Comment by Grz3s** [comment]
Dragonblight is in heavy reconstruction prosess now.. Will be added after next release...

**Comment by rmzV** [comment]
nice to hear that
i ended with tbc testing.. and that was a realy empressed work!
*
can you please look at this issue
https://github.com/cmangos/wotlk-db/issues/304
may be some temp fixes, so i can continue my research
thx
