### ISSUE TITLE
Database Errors

### ISSUE THREAD

**Issue by adellaci** [cmangos/wotlk-db#313]
Ubuntu 18.04.4 LTS Server

WotLK
Using commit hash(ed6f5be404e5eea8e6079341360f086103baca7a) committed on 2020-04-23T11:46:54+02:00

Database-WotLK
Using commit hash(223d2d8bb87d7cc60644799cd6273a83d139e4bc)

DBErrors.log

https://paste2.org/vIP6Ud8m

**Comment by adellaci** [comment]
@Grz3s 
The database hash is saying I am using TBC database, but i do not download that database. I am more confused now

**Comment by Grz3s** [comment]
its all fine ...commit was backported from TDB... thats all

**Comment by adellaci** [comment]
That commit did fix three of them

**Comment by Grz3s** [comment]
thats why it says `Part of` not `closes` ;)

BTW: lots of these are only info .. that smth is not completed etc... and req. huge amount of time and data to proof... (prob. will never be fixed).
example: `gossip_menu - not added to any creature` - this is only info - not a real problem...
Slowly but surly we will eliminate all of them ;)

**Comment by adellaci** [comment]
I'll will try to look through the other entries and see if i can work on any of them

**Comment by Grz3s** [comment]
i already did some work on creature_template_addons  - so you can leave them for me ;)

**Comment by adellaci** [comment]
2020-04-26 09:57:11 Item (Entry: 3034) has unexpected RequiredDisenchantSkill (0) for non-disenchantable item class (6), reset it.

This item in the table item_template is a Glyphed Breastplate when it should be this item;

Deprecated BKP "Impact" Shot Item Level 35 ProjectileSocket Bonus: +18 Stamina, +12 Dodge, and +12 Armor | Projectile |

**Comment by adellaci** [comment]
Item Template should be this for that item

(3034, 6, 3, -1, 'Deprecated BKP "Impact" Shot', 5998, 2, 0, 0, 200, 300, 0, 24, -1, -1, 35, 30, 0, 0, 0, 0, 0, 0, 0, 0, 1000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3000, 0, 0, 0, 0, 0, 0, -1, 0, -1, 0, 0, 0, 0, -1, 0, -1, 0, 0, 0, 0, -1, 0, -1, 0, 0, 0, 0, -1, 0, -1, 0, 0, 0, 0, -1, 0, -1, 2,  '', 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0,  '', 0, 0, 0, 0,  0)

**Comment by Grz3s** [comment]
thx . i'll check this one soon*

**Comment by Grz3s** [comment]
outdated... got new list of errors from here:
https://github.com/cmangos/issues/issues/3140
