### ISSUE TITLE
Static Creature spawns

### ISSUE THREAD

**Issue by SuperSmelly** [cmangos/wotlk-db#314]
Spawns of Shadowmaw Panthers and Stranglethorn tigress's are static instead of sharing a pool.

There are other areas I remember from when i was playing, like the bears and spiders outside of TM.  I am happy to script up other changes for this if someone can point me to the data

This will add add them to the Creature spawn table
-- This gets the entry Id
/*SELECT * FROM wotlkmangos.creature_template
where name in ('shadowmaw panther','stranglethorn tigress');*/

DELETE FROM wotlkmangos.creature_spawn_entry where entry in (684,772);

Insert into wotlkmangos.creature_spawn_entry (guid,entry)
SELECT guid,id FROM wotlkmangos.creature
where id in (684)
union
SELECT guid,772 FROM wotlkmangos.creature
where id in (684)
union
SELECT guid,id FROM wotlkmangos.creature
where id in (772)
union
SELECT guid,684 FROM wotlkmangos.creature
where id in (772);

**Comment by rmzV** [comment]
hello
if i understand correct
Silithid Invader+Hive Drones
https://classic.wowhead.com/npc=4131/silithid-invader#comments

**Comment by AnonXS** [comment]
perfect usecases for creature_spawn_entry though its still not 100% blizzlike probably but a hugh improvement over static single entry spawns

**Comment by SuperSmelly** [comment]
> hello
> if i understand correct
> Silithid Invader+Hive Drones
> https://classic.wowhead.com/npc=4131/silithid-invader#comments

Yes

this script will change it in the Db, although I'm not 100% happy with the searcher piece

Does this need to be tested? If this is a viable solution, how do you want me to present it?

SELECT * FROM wotlkmangos.creature_template
where name in ('Silithid Invader','Silithid Hive Drone','Silithid Searcher');

DELETE FROM wotlkmangos.creature_spawn_entry where entry in (4130,4131,4133);

/* In the cave Invaders and drones*/
Insert into wotlkmangos.creature_spawn_entry (guid,entry)
SELECT guid,id FROM wotlkmangos.creature /* select all the Invaders that are not pathing */
where id in (4131) and MovementType!=2 and position_z <-84
union
SELECT guid,4133 FROM wotlkmangos.creature /* add all the drones */
where id in (4131) and MovementType!=2 and position_z <-84
union
SELECT guid,id FROM wotlkmangos.creature
where id in (4133) and MovementType!=2 and position_z <-84
union
SELECT guid, 4131 FROM wotlkmangos.creature
where id in (4133) and MovementType!=2 and position_z <-84;

/* re think this bit .. maybe its only outside the ruins at the edges*/
/* outside the cave searchers and drones*/
Insert into wotlkmangos.creature_spawn_entry (guid,entry)
SELECT guid,id FROM wotlkmangos.creature /* select all the searchers that are not pathing */
where id in (4130) and MovementType!=2 and position_z >-84
union
SELECT guid,4133 FROM wotlkmangos.creature /* add all the drones */
where id in (4130) and MovementType!=2 and position_z >-84
union
SELECT guid,id FROM wotlkmangos.creature
where id in (4133) and MovementType!=2 and position_z >-84
union
SELECT guid, 4130 FROM wotlkmangos.creature
where id in (4133) and MovementType!=2 and position_z >-84;

**Comment by Grz3s** [comment]
will check these 2 soon* `Silithid Invader+Hive Drones`

**Comment by SuperSmelly** [comment]
for the bears and spiders around Tarren Mill,



SELECT * FROM wotlkmangos.creature_template
where name in ('Forest moss creeper','gray bear');

DELETE FROM wotlkmangos.creature_spawn_entry where entry in (2350,2351);


Insert into wotlkmangos.creature_spawn_entry (guid,entry)
SELECT guid,id FROM wotlkmangos.creature -- select only map 0 and positive x creatures, so those around TM 
where id in (2350) and map=0 and position_x>0
union
SELECT guid,2351 FROM wotlkmangos.creature 
where id in (2350) and map=0 and position_x>0
union
SELECT guid,id FROM wotlkmangos.creature
where id in (2351) and map=0 and position_x>0
union
SELECT guid, 2350 FROM wotlkmangos.creature
where id in (2351) and map=0 and position_x>0;

**Comment by SuperSmelly** [comment]
for stranglethorn tigers and panthers

SELECT * FROM wotlkmangos.creature_template
where name in ('panther','stranglethorn tiger');

DELETE FROM wotlkmangos.creature_spawn_entry where entry in (682,736);

Insert into wotlkmangos.creature_spawn_entry (guid,entry)
SELECT guid,id FROM wotlkmangos.creature
where id in (682)
union
SELECT guid, 736 FROM wotlkmangos.creature
where id in (682)
union
SELECT guid,id FROM wotlkmangos.creature
where id in (736)
union
SELECT guid,682 FROM wotlkmangos.creature
where id in (736);


UPDATE creature SET id = 0 WHERE id IN (682,736);

**Comment by SuperSmelly** [comment]
for Mosh'Ogg Brutes and witch doctors

SELECT * FROM wotlkmangos.creature_template
where name in ('Mosh''Ogg Brute','Mosh''Ogg Witch Doctor');

SELECT * FROM wotlkmangos.creature
where id in (1142,1144);


DELETE FROM wotlkmangos.creature_spawn_entry where entry in (1142,1144);

Insert into wotlkmangos.creature_spawn_entry (guid,entry)
SELECT guid,id FROM wotlkmangos.creature 
where id in (1142) 
union
SELECT guid,1144 FROM wotlkmangos.creature 
where id in (1142)
union
SELECT guid,id FROM wotlkmangos.creature
where id in (1144)
union
SELECT guid, 1142 FROM wotlkmangos.creature
where id in (1144);

UPDATE creature SET id = 0 WHERE id IN (1142,1144);

**Comment by Grz3s** [comment]
- :x:  ('Silithid Invader','Silithid Hive Drone','Silithid Searcher') (4130,4131,4133); - not true ... checked on WotlK Classic - never happened
- :x:  ('Forest moss creeper','gray bear') (2350,2351); - not true ... checked on WotlK Classic - never happened

- [ ]  ('panther','stranglethorn tiger') (682,736); - added
- [ ]  ('Mosh''Ogg Brute','Mosh''Ogg Witch Doctor') (1142,1144); - confirmed  - will add it later (need to recheck all waypoints and duplicates there)
