### ISSUE TITLE
[for core cmangos WOTLK] Fix for waypoints with point = 0

### ISSUE THREAD

**Issue by NeatElves** [cmangos/wotlk-db#317]
https://gist.github.com/NeatElves/0d6fe91cd1e8f9da0d68302666565d8c
ATTENTION QUESTION!
What to do with this???
example [**SetCurrentWaypoint**]:
https://github.com/cmangos/mangos-wotlk/blob/master/src/game/AI/ScriptDevAI/scripts/outland/terokkar_forest.cpp#L1049
or [**MoveWaypoint**]
https://github.com/cmangos/mangos-wotlk/blob/master/src/game/AI/ScriptDevAI/scripts/kalimdor/dustwallow_marsh.cpp#L738

**Comment by Grz3s** [comment]
@NeatElves nice one... but this need to be PR in core repo not here,,,

**Comment by cala** [comment]
> ATTENTION QUESTION!
What to do with this???
example [SetCurrentWaypoint]:
https://github.com/cmangos/mangos-wotlk/blob/master/src/game/AI/ScriptDevAI/scripts/outland/terokkar_forest.cpp#L1049
or [MoveWaypoint]
https://github.com/cmangos/mangos-wotlk/blob/master/src/game/AI/ScriptDevAI/scripts/kalimdor/dustwallow_marsh.cpp#L738

`SetCurrentWaypoint(index)` forces the EscortAI to update the position of the NPC along the path, considering it is now at index set by `SetCurrentWaypoint(index)`. Thus, if we are speaking of a path that were previously starting with point1=0, all values in `SetCurrentWaypoint(index)` must be increased by 1 for this escort.

`MoveWaypoint(pathId)` refers to the pathId currently used and 0 is still the default value. So no changes are needed here.

**Comment by cala** [comment]
Merged in https://github.com/cmangos/mangos-wotlk/commit/fd314f724bffb820f6a631256300894214ad04aa
Thank you !
