### ISSUE TITLE
Sky-Reaver Korm Blackscar

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#322]
https://www.wowhead.com/npc=30824/sky-reaver-korm-blackscar
can this nps and other .. from the ship placed into one icc spot on the ground/

**Comment by rmzV** [comment]
what if we have vehical with moving from position x1 to x2.
And we place npc in air with moving from position x1 to x2/

so you can take end handle quests to this npc /// or we ca stop both wehicle and npc when player unteract with npc

**Comment by Grz3s** [comment]
it will soon desync...  and both npc and transport will be in diff possitions...
BTW: Transports are not vehicles (vehicles works like npcs in this game) -- more like moving maps...

**Comment by rmzV** [comment]
ahh ok(( may be then possible to place npc from transport in icecrown in some temp spot? so quest can be taken from them/

**Comment by Grz3s** [comment]
fixed

**Comment by rmzV** [comment]
still cant find him((

**Comment by rmzV** [comment]
ill trued to teleport to him..and get server error.

**Comment by rmzV** [comment]
can you point me where to find him(

**Comment by Grz3s** [comment]
do not use `.go c ....` commands on transports ... they wont work.. koz these npcs using local cords.
and you will find him where he should be:
![image](https://user-images.githubusercontent.com/2374069/107983997-d6042f80-6fbe-11eb-9b38-571306501244.png)

**Comment by rmzV** [comment]
ok. its working.
but you cant use flying mount on boat.. and there are a total mess with quests(
