### ISSUE TITLE
Axel Issues List Part 1 - Dk Zone -

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#325]
- [x] In quest "The Endless Hunger" some Unworthy Initiate do not have the circle chain spell around them (3 of them). They have the chains that bounds them to the wall behind them!

- [x] Scarlet Preacher (Phase 1 with Eye of Archerus at quest) that patrol from The Chapel are 2 in number! Should they be 2? or they SHOULD have a special formation? -- Grz3s: they should walk like that

- [x] In quest "Grand Theft Palomino", when u take a Havenshire Stalion/Mare/colt u can run with it, but if mob hits u by MELLE attack, your horse just freeze in place.

   - Get off the horse to fight/or do anything else, when u want to jump on it again, he will do the animation to jump in, but horse despawn!

- [x] In quest "Into the realm of shadows", Mob Dark Rider of Archerus should be mounted each on Archerus mount! Currently they are without horse! They give the horse after they die! BUT they must appear mounted!

  - Also there is a problem somehow, because Scarlet Infantryman/Medic are riding Archerus mount!!!!! They should ride a horse instead!

- [x]  In quest "Death's Challenge" After u defeat a dk, if he has dots on u, he doesn't do defeat animation, instead he stays in combat position, not attackig u, until dots expire on u, or his time expires and he despawn

- [x] In quest "Masacre at Light's Point"after u defeat the 100 defenders and hit the Skeletal gryphon button from the cannon, a skeletal will take you be IT is VERY VERY slow flying! it is like walking flaying if u understand me!

- [x] In quest "How to Win friends and influence enemies" a mob that start to talk, doens't fully stop attacking u. every 5 -6 seconds he use an ability on you, as long as the talking script goes. I tested on casters Scarlet Preachers! THEY should stop attacking!

- [x] Prince Keleseth  gives u quest "Behind Scarlet Lines" after u finish q "How to Win friends and influence enemies". But when u hit the accept button u receive message that u don't meet the requirements for that q

-:x: - In quest "Bloody Breakowt" Koltira Deathweaver use a smite spell that hits for 1.4 dmg and that is NOT normal! his spell should hit for about 130 - 150 dmg - Koltira in this quests do not use any combat spell ... but if you talk about inquisitor... he should hit you hard.. thats why u should stay inside that magic barrier... anyway INVALID

- [x] the weaves must come more fluid
https://www.youtube.com/watch?v=JEm3TEBBApM

- [x] In quest "Plaguebringer Request" The cauldron and it's chains objects should not be spawned. they must be added after u complete the quest

- [x] the last quest "The Light of Dawn" have some serious problems.

   - Darion doesn't stand in the direction of tirion
   - battle needs more touching
   - when he charge lich king he despawns and u are unable to finish the quest
   - https://www.youtube.com/watch?v=T8g7K3_MFRM
   This is how it should really be that fight. Our fight is way far away for the moment. The fight currently is done in one point in our db. I movie the fight is done on many flancs not just one point, and scarlets are respawning fast to keep the fight real on many flancs
Also our mobs ai might need a good improve as u see chains used by patchwercks, that forcefield on the battleground, and holy wrath and penace casted by scarlet paladins, etc
Also the texts during the fight scene need some improve. and the fight as u can see it lasts some quite time. Anyways all the info is in the movie
Also ghouls keep spawning for example and get into fight, as scarlet paladins do
Res spell casted by tirion on his fellows and darion in the end
- [x] After you defeat Patchwerk u don't receive the quest to be sent in SW to speack with the king

Beside this OMG ALL is working very nice!

**Comment by al3xc1985** [comment]
I updated the battle for light chappel info a little BUT more info can be found on the movie attached to the info.
As I see it is a VERY complex quest and fight scene. In my opinion I never saw a more complex in wow like this one.

**Comment by Grz3s** [comment]
`the last quest "The Light of Dawn" have some serious problems.` fixed with latest updates
