### ISSUE TITLE
Axel Issues Part 3 - Stormwind City -

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#327]
Until this point!!

- [x] Strand of The Ancients Emissary in Stormwind are just standing into the tunnel in "The Canals"district! They should have a path to follow and they are 2!

there are other groups in Stormwind that must have their own waypoint their own path

- [x]  Mini Tyrael has the absolute best "idle" animations of any non-combat pet!

He will respond to the /dance command and proceed to bust some moves of his own. Anyone can target him and type the command out to get him to start grooving!

Also (as of patch 3.2), while idle, he will occasionally fall asleep - lying first on his back, then adjusting and rolling over to his side, where he continues his snoring, and even scratches his rear! He will then wake up suddenly with a powerful shout animation!

- [x] Investigate the blue Recluse does not work
https://www.youtube.com/watch?v=t0jFkP1k2ag
- :x: Justine Demalier speack with Melris Malagan (only a part of text on vid) -- blizz removed it in Wotlk :(
https://www.youtube.com/watch?v=qL9kz8cy7UA

- [x]  Ol' Emma OOC text 
I don't know where her texts are in db? on acid file she is emty line.. she does actually say something in game... should she need to be converted to acid style? and maybe add missing text if there are any?

- :x: this guard should not have random movement assigned -- you're wrong here (HE should) .. 
![WoWScrnShot_022121_172132](https://user-images.githubusercontent.com/6240049/108629590-54524d00-7469-11eb-9765-c69e54fc10f3.jpg)

- [x]  food crate spawned over barrel
![WoWScrnShot_022121_172259](https://user-images.githubusercontent.com/6240049/108629616-75b33900-7469-11eb-8137-54ee657205f4.jpg)

- [x]  I believe this guard should stand on the other side of the tunnel entrance and NOT wondering arround
![WoWScrnShot_022121_172327](https://user-images.githubusercontent.com/6240049/108629645-8ebbea00-7469-11eb-931a-2fc52b017e9c.jpg)

- [x]  Corbet path has some mistakes... he goes after cheese shop on the wrong direction.. instead of going through the left trade distric exit he is going through the center trade distric exit, and have a longer path until left trade district exit, and back to his shop
https://www.youtube.com/watch?v=LBP34Nvd67M

- [x]  The orphans from cathedral square , those from the orphan house, have small event. can be seen in the beggining of the movie
https://www.youtube.com/watch?v=6Vx4BCb60lY

- [x] we miss one npc Orphan Matron Nightingale. she is not spawned
also
please check if she has https://classic.wowhead.com/quest=1468/childrens-week assigned

- :x: William and Donna , the 2 kids that run through stormwind have a mistake in their text  they say "Crybaby!" instead of "Cry baby!" -- it is correct text taken from broadcast.. 
- [x] Missing Guard
 https://youtu.be/KoLwD3j_m0Q?t=673
![WoWScrnShot_032121_212518](https://user-images.githubusercontent.com/6240049/111918087-1b1ef400-8a8c-11eb-8e9d-7ff85788e50d.jpg)

**Comment by al3xc1985** [comment]
post updated @Grz3s be suprised of this quest bug Investigate the blue Recluse,,, 
1, This quest have 1 aggro problem like the one in deadmines reported by me
2. When u use the spell to make the in coffers, they transform for just a moment but u can;t loot them.. the coffers dissapear so fast

**Comment by al3xc1985** [comment]
first post updated

**Comment by Grz3s** [comment]
` Investigate the blue Recluse does not work
https://www.youtube.com/watch?v=t0jFkP1k2ag`
classic vid from 2016? - m8 this one is fake as..... start script missing .. and everything else is wrong there...
BTW: theres no issue with aggro - spell used by player to make them visible has radius 100 .. so everything inside is catched ..and they will attack player if touched by it.

**Comment by al3xc1985** [comment]
I will test it again...I might did something wrong...I layed that movies cause I was not able to find anything else at least 10 years or later ago

**Comment by al3xc1985** [comment]
Are u sure about this one? it might be changed in wotlk, cause in classic on all movies I found he was standing still like here 
https://youtu.be/ZCO7u3wScQM?t=11930

He passed this guy like 3 times, and same position

![image](https://github.com/cmangos/wotlk-db/assets/6240049/07ac1a42-973a-426b-bd43-744573c4acb7)

**Comment by Grz3s** [comment]
> Are u sure about this one? it might be changed in wotlk, cause in classic on all movies I found he was standing still like here https://youtu.be/ZCO7u3wScQM?t=11930
> 
> He passed this guy like 3 times, and same position
> 
> ![image](https://user-images.githubusercontent.com/6240049/255292480-07ac1a42-973a-426b-bd43-744573c4acb7.png)

im 100% sure about this guy... he has random movement on wotlk
