### ISSUE TITLE
Axel Issues List Part 1 Revised - Dk Zone -

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#328]
- [x] Archerus Necromancer should face the Death Knight Initiate when Instructor Razuvius Gives him command... he does instructor will, but not facing the Initiate, he is with his back on the initiate

- ❌  The Death Knight Initiate after he goes to lich king and salute him, he goes on the teleport portal to darion mograin, BUT he should walk on the stairs and get around the wall to the teleport NOT directly through wall down stairs -- see explain below

- [x]  ???? Shold the other knight initiate give a punch in vain, instead in the direction of a ghoul?

- [x]  When under the control of Eye of Archerus, the archers, shouldn't they have a bigger range? is like u do the quest very very easy... when u inspect an objective nothing happends...I believe that someone should enter combat and alert in tha objective contruction spot
- [x] In Quest Grand Theft Palomino If scarlet Infantryman use his stun ability while u are riding on horse, u are unable to move. U need to get down and take an other horse

- [x]  In realm of Shadows, Dark Rider of Archerus is not mounted on the horse, the horse wonders alone on path given by server, but it is untargetable. The horse will attack u with dark rider horseman abbilities and u can't even select it. If u kill a dark rider, one of the horses will transform to friendly and u can hop on it!

- [x]  In quest Massacre at Light Point, 

  - the lightning strike spell, kills you instantly
  - when u call the skeletal gryphon to take u, his flying speed is walking speed
  - while flying the gryphon the cannons keep continue to fire at you. Is that normal? Shoudn't they stop attacking?

**Comment by Grz3s** [comment]
4th fixed with - https://github.com/cmangos/mangos-wotlk/commit/1e59e2a3fdf9e606a62b94592020ef4f07150135

**Comment by al3xc1985** [comment]
updated issues list
until this point the list... I will continue with other zones until u finish the zone redone...

**Comment by Grz3s** [comment]
2nd: .. at 8th wp point npc should jump to final wp point in portal ... (currently core does not support db with that - one day will be updated)
BTW: all wp points are correct

**Comment by al3xc1985** [comment]
@Grz3s should I do I ticket only with it? or you have it on your list?

**Comment by Grz3s** [comment]
no -- its core issue... and i have list with them

**Comment by al3xc1985** [comment]
perfect..ty friend
