### ISSUE TITLE
Axel Issues Part 8 - Dragonblight -

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#329]
- [x] In Quest Lumber Hack some trees cam be harvested 4-5 times, is that normal|?

- [x] In quest Lumber Hack Xink's Shreder his first spell Lauch saw blades, sometimes is not fired... is that based on hit? or it is normal in that quest that your fireing device to not work? -- its based on range.. if you're to far ..nothing will happen

- [x] While in Xink's Shreder is that normal to harm yourself with Twisting Blade?

- [x] .NPC Mistress of Coldwind and Coldwing Wich doesn't cast thier spells, I mean for example misstress starts to cast Arctiv Whirliwind, and MANY MANY times she cancel it immediatly without me doing anything just autoattack 
I believe that this problem with mobs starting to cast a spell and somewhere before finishing casting is a general problem. I saw mobs with this behaviour in classic part 2. Maybe a small return somewhere is missing! -- both spells have `flag: 0x00000002 - SPELL_INTERRUPT_FLAG_DAMAGE` -- so will be canceled on hit  

- [x] When u call out Allystor the verdant keeper with using that beacon spell, he will aggro u, but he can not come down that hill on wich he is spawned and after a while go back to sleep.. it;s a mmaps problems and this can be seen very well, cause if I go to him after thatm he comes after me nice

:x: Reanimated Frost Wrym when brought to ground should stand like any mobs in their feet, not flying in ground -- this is expected behaviour : https://youtu.be/BF4HKuqlKMQ?t=47

- [x] ALL Fordragon Battle Steed are unmounted

:x: On the Court of skull place, spawned mobs should come also on the right side of the stairs to attack the horde camp. The alliance side is ok -- **INVALID** PLS look below for explanation

- [x] Shouldn't Moa'ki Warrior fight with Snofall Glave Reaver?

:x: In quest meat on the hook u can spawn as many Tu'u'gwar as u wish -- **core issue** db scripts is correct

:x: In quest meat on the hook there is a problem with attacking Tu'u'gwar in water, or any other shark fish in that water zone, they allways evade -- **core issue** db scripts is correct

:x: Quest conversing with the depths does not work as intended at all..need review -- **core issue** db scripts is correct

https://www.bing.com/videos/search?q=conversing+with+the+depths&docid=608028715147397695&mid=07649C7FE61CDE0BDFBC07649C7FE61CDE0BDFBC&view=detail&FORM=VIRE

- [x]  Risen Gryphon Rider are standing in air without gryphon and their gryphons are patroling around alone
- [x]  The Quest Focus on the Beach, u use that ring and nothing happends
It shoud be like 
https://www.youtube.com/watch?v=mAyD7dzYnuA
- [x] Quest Atop the Woodlands is the same problem with the amulet that u must use like in previous quest... nothing happends
- [x] Quest The end of the line does the same thing after u use that talisman provided..nothing

:x:  In the Ruby Dragonshire Tree, u are seen by server at the exit of the cave from baseinside of the tree as underwater, and if u try to mount you will have the message with cannot do that while swimming -- **INVALID** this isnt db issue...  maybe smth to with maps or vmaps
- [x] In quest Defending Wyrmrest Temple, while on the dragon, u can not attack any other dragons
- [x]  Malygos is missing his loot table and with it the quest item to finish also this quest judgement at the eye of eternity... I don't know but maybe there are other quest items needed to his loot
- [x] Stell gate flying machine is spawned at the court of skull, at the small group of hordes on the left side of the stairs
- :x: Wonderring troops in front of stairs at icecrown point should be involved in battle..u have screen shot down from here where we talk about the core issues - no they're there to control summoned waves.. not to overpopulate place

**Comment by Grz3s** [comment]
all  water creatures (inhabitType = 2) ... are broken currently...  It req `core` fix for it...  
As a temp you can use: 
`UPDATE creature_template SET InhabitType = 4 WHERE InhabitType = 2;`  .... but this is only temp... for checking reasons

**Comment by al3xc1985** [comment]
Ok, ty..
This is only first part of bug report, i will continue testing and update list

**Comment by al3xc1985** [comment]
list updated

**Comment by Grz3s** [comment]
well im quite shocked .. that many things stopped working ..and i just made whole zone .. and tested it ... hmmm
let me finish transports and ill jump back to this

**Comment by al3xc1985** [comment]
I will do a fresh install 2 and try at least those 2 npc's that should be raiding

**Comment by al3xc1985** [comment]
ok...fresh install...did tests on those 2 npc's that should be mounted...and they are not mounted...

**Comment by al3xc1985** [comment]
somehow for example the gryphon raider gets dismounted in flight

**Comment by Grz3s** [comment]
make sure youre testing with `.gm off`  transports may drop passangers with gm on

**Comment by al3xc1985** [comment]
I am gm off

**Comment by al3xc1985** [comment]
ok...redone tests with latest core and
Risen Gryphon Rider are standing in air without gryphon and their gryphons are patroling around alone seems to not do problems anymore...maybe it will do again, but it looks ok...probably a small sincronization between client and core may get bad, but is fine now

**Comment by Grz3s** [comment]
that kind of out sync ... happens when you're swithich between gm on and off... otherwise should work fine

**Comment by Grz3s** [comment]
@al3xc1985 
`In Quest Lumber Hack some trees cam be harvested 4-5 times, is that normal|?`
can you pls provide me screen or xyz using `.gps` command.... where you found that tree??? i checked lots and cant find even one

**Comment by Grz3s** [comment]
`On the Court of skull place, spawned mobs should come also on the right side of the stairs to attack the horde camp. The alliance side is ok`
they are -- whole script is balanced to make sure... that defenders will never lose:
![zzzz](https://user-images.githubusercontent.com/2374069/103158917-20391380-47bb-11eb-832b-505eb9c1fd84.jpg)

**Comment by al3xc1985** [comment]
I shall redo the whole server and rest those back again, and give back additional info. Ty for all fixes. I am in a small holliday currently

**Comment by al3xc1985** [comment]
![WoWScrnShot_123120_211111](https://user-images.githubusercontent.com/6240049/103423074-5f95a480-4bad-11eb-83a5-b8c889aa13c7.jpg)
![WoWScrnShot_123120_211155](https://user-images.githubusercontent.com/6240049/103423075-60c6d180-4bad-11eb-8de6-a837baea06e7.jpg)
![WoWScrnShot_123120_211222](https://user-images.githubusercontent.com/6240049/103423076-615f6800-4bad-11eb-8abd-0f46ce4de055.jpg)
![WoWScrnShot_123120_211356](https://user-images.githubusercontent.com/6240049/103423077-61f7fe80-4bad-11eb-818c-4a086e835731.jpg)

This are the tress @Grz3s

**Comment by al3xc1985** [comment]
also tested "On the Court of skull place, spawned mobs should come also on the right side of the stairs to attack the horde camp. The alliance side is ok" and all is fine now

**Comment by Grz3s** [comment]
yes i seen this issue already...
problem is very strange... 
spell that is used has = 5yards range. Object (spell focus) has also 5 yards range...
It works like that: ... spell searches for object in 5yards.. if not found - error throwed
If object found then credit is given and object activates self (despawns). Simple right? .. heh should be...
Problem is.. that you can stand 5.5 - 6 yards and it still triggers credit... but because of its range gobject will not activate self so will never despawn = you can stay there and cast it forever...
I have no idea why it allows you to cast it with greater range than 5 yards... 
Ill do more tests i hopefully find smth...

**Comment by al3xc1985** [comment]
@Grz3s  about the core Issues should I make a list with them and port them to core issues? or they are known issues?

**Comment by Grz3s** [comment]
yes it should

**Comment by al3xc1985** [comment]
ok..I am noting on the report about this guys right now..and when u finish them, check them done...

@Grz3s  Next task? want me to test dragonsblight by horde side 2? or anything else?
