### ISSUE TITLE
[NPC1983] Nightlash

### ISSUE THREAD

**Issue by NeatElves** [cmangos/wotlk-db#33]
http://www.wowhead.com/npc=1983
http://www.wowhead.com/quest=437
Npc not static spawn
```sql
DELETE FROM `creature` WHERE `id` = 1983;
INSERT INTO `creature_ai_scripts` (`id`, `creature_id`, `event_type`, `event_inverse_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action1_type`, `action1_param1`, `action1_param2`, `action1_param3`, `action2_type`, `action2_param1`, `action2_param2`, `action2_param3`, `action3_type`, `action3_param1`, `action3_param2`, `action3_param3`, `comment`) VALUES
(177203, 1772, 6, 0, 5, 0, 0, 0, 0, 0, 12, 1983, 6, 60000, 0, 0, 0, 0, 0, 0, 0, 0, 'Rot Hide Gladerunner - 5% Summon Nightlash on Death');
```

**Comment by Grz3s** [comment]
```quote
Killing gnolls is just to kill time I think, while my partner was afk, she just randomly appeared, killed her, she was dead for a good amount of time, then killed her again, and not a single gnoll was being fought around the area...

PS: Fought her both times as a lvl 12 tauren prot warrior, and it was fairly easy to do with the +3 stam fortitude buff from my partner whom was afk, had to keep her away from him so he wouldn't get killed by the debuff that seems to hit anyone in a certain range of the target. I hope this bit of information helps anyone.

Last Edit (Hopefully): So, me and my priest buddy are sitting out of range of any mob, but close enough to Nightlash to hear her.. and when she spawns an emote goes that says "Nightlash lets out a high pitched screech, calling for help." And then later on she despawns saying "I shall return in time.."
```

I think this one is a bit dif....
She spawns for 5-6 mins and then despawns... with respawntime (random? - we can use 300secs - common for creatures)
We also could use EAI for her texts for spawn and desp...
Maybe @cala has some more info about her?

**Comment by cala** [comment]
There was [an issue in core repo](https://github.com/cmangos/issues/issues/775) and another one in [Classic DB](https://github.com/classicdb/database/issues/846) about this NPC.

The first issue is the same that this one. Basically, there as much "evidences" (it would be more accurate to call these "feelings") that the NPC is randomly spawned/despawned than evidences that the NPC is spawned by killing the nearby gnolls.

However, the quest text says:
> Go to the Dead Fields and assault the rot hides. If you don't see Nightlash then kill the rot hides until she appears, then defeat her.

So, I can't tell for sure.

The second issue is about the spell target of the NPC leech spell. It targets players (killing them) while it should only target nearby gnolls. This last one is a core issue.

**Comment by killerwife** [comment]
There is a PR for the leeching issue. It just got forgotten.
