### ISSUE TITLE
Axel Issues Part 5 - Westfall -

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#332]
- [x]  The sign direction for Jangolode Mine is not in his proper place

x:-9976.921875     y:1006.883423    z:31.658434

- [x]  All chests are spawned in Westfall

**Comment by Grz3s** [comment]
![sign](https://user-images.githubusercontent.com/2374069/103110988-e7286400-463f-11eb-84f9-0d4fc05ec99a.jpg)
fixed :)

**Comment by al3xc1985** [comment]
Nice..ty

**Comment by al3xc1985** [comment]
I clode this @Grz3s . U got it noted
