### ISSUE TITLE
Axel Issues Part 7 - Deadmines -

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#334]
- [ ] When u get to boat after defeating Mr.Smite, and head right to get on the upstairs, when u aproach the stairs, the mobs from upstairs will aggro ALL. There is a LOS problem in there
- [ ]  The same problem happends before last stair to Captain GreenSkin, Captain will aggro and get all mobs with him towards u

**Comment by al3xc1985** [comment]
@killerwife can I summon u, just for a thought?

**Comment by Grz3s** [comment]
i'll look at this noon .. prob detection range need to be reduced thats all

**Comment by al3xc1985** [comment]
Ok. Ty

**Comment by al3xc1985** [comment]
fixed
