### ISSUE TITLE
Axel Issues - Forge of Souls -

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#339]
- [x] Spitfull apartion, I believe that they should get visible somehow.. I didn;t saw them spawned in movies, they spawn somehow...I guess ACID will take care of it
https://www.wowhead.com/npc=36551/spiteful-apparition#comments

we have this comment: "Can be seen if buffed with Elixir of Detect Lesser Invisibility or a warlocks Detect Invisibility and other detecting spells/elixirs, along with any invisibility effect on self. This includes potions and the mage spell." 
So they are invisible. They break the invisible when u get near them...I don't believe they have a big range of aggro by judging this movie at 1:14
 https://www.youtube.com/watch?v=vc2QkJfPlAk

Judging even by his spell we have
https://www.wowhead.com/spell=68895/spite
we have "Deals 1449 Shadow damage to enemies within 15 yards." So my gues might be correct about his aggro range...

**Comment by al3xc1985** [comment]
@xfurry I guess that is the problem that I reported to first problem...the souls somehow get invisible, and keep attacking

**Comment by xfurry** [comment]
Please retest using latest core and DB.
As per my knowledge all issues are fixed.

**Comment by al3xc1985** [comment]
retested...and updated first post

**Comment by al3xc1985** [comment]
first post updated @xfurry  this are last changes that must be done, and the dungeon, from my perspective is 100%

**Comment by xfurry** [comment]
First point is for @killerwife 
Second point: I will fix it soon

**Comment by al3xc1985** [comment]
I believe that is a general issue @xfurry because in ToC the Snobold Vessel act in the same way

**Comment by al3xc1985** [comment]
also @xfurry what do u think about:
Spitfull apartion, I believe that they should get visible somehow.. I didn;t saw them spawned in movies, they spawn somehow...I guess ACID will take care of it

**Comment by xfurry** [comment]
I don't know how the spiteful apparitions work. Maybe we can remove them completely from the map.

**Comment by al3xc1985** [comment]
I will search movies. Just give me time pls

**Comment by al3xc1985** [comment]
@Grz3s can u help with this last task on fos instance pls? whenever u have time 
Is the info I lay down inoff or should I look for more?
