### ISSUE TITLE
error on compliling

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#342]
Sorry, thatpost in wrong section, but i have this error:

19>LINK : fatal error LNK1181: cannot open input file '..\shared\Release\shared.lib'

how can i fix it?

**Comment by Grz3s** [comment]
pls update your core and DB.. then try again..
if fails pls report it in core section

**Comment by rmzV** [comment]
i ll opened ticket in core section,
https://github.com/cmangos/issues/issues/2360

may be there are something with boost or newer instaled version of cmake?
