### ISSUE TITLE
Axel Issues - Loch Modan -

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#354]
- [ ] Mountaineer Morran should have some waypoints ..? going inside, and outside..until where?..dunno
https://www.youtube.com/watch?v=_SdTlMvhJa0&feature=emb_logo
sec 28
Also he is missing from ACID file

**Comment by Grz3s** [comment]
wrong link?
also .. point to when exact it happens .. (xxx min yyy sec) ... or if its YT. right click on timer and "copy from this moment" .. then i know where to look instead of watch whole thing

**Comment by al3xc1985** [comment]
edited...Sorry @Grz3s ..I was very tired...a lot of quests checked, one by one, movie by movie, detail by detail
