### ISSUE TITLE
Axel Bugs - Westfall -

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#355]
- [x]  We have the same orientation problem with defias messanger when he gets on front of dungeon entrance house. he should not turn back 2 u... but stay still facing the entrance
 https://classic.wowhead.com/quest=155/the-defias-brotherhood

- :x:  after u take the quest from the chicken by doing /chicken on it, u must not receive the ? to finish the quest... u must use /cheer command to have the ? to finish the quest -- see below

- [x] Scout Gallian OOC say (u can see it in the beggining of the movie)
https://www.youtube.com/watch?v=POfdHxDB5T8

- [x]  Klaven Mortwake when he aggro he has am aggro text in wich he use the word "rogue" instead of paladin (I am paladin).. he should have sintax with #class in his aggro text
- [x] Daphne Stilwel does not do the hooray emote when last weave is killed. She has a moment of pause and after that she does the hooray (3:40)
https://www.youtube.com/watch?v=73F_9Q28gk4
- [x] ALSO she does hooray emote too when u click her to quest complete
- [x] Also her end text is not complete is not just "we've done it! We've won!" (1:55)
https://www.youtube.com/watch?v=Q8ZwKGah1LI

- [x] Daphne Stilwel should sometimes also work on the barrel 2, not just moving around (2:35)
 https://www.youtube.com/watch?v=Q8ZwKGah1LI
UPDATE `creature_template` SET `InteractionPauseTimer` = 30000 WHERE `entry` = 6182;

- ❌  upon completing "the test of righteousness" quest, Duthorian Rall, should hooray emote 2
https://www.youtube.com/watch?v=73F_9Q28gk4 -- emote is part of his text and works fine

- [x] on last quest the "the test of righteousness" from the paladin when Jordan Stilwell works on your hammer, there is a desincronization. When jordan finish, after he kneel to the anvil, and stand up again, the hammer from the anvil should dissapear 7:15
https://www.youtube.com/watch?v=Q8ZwKGah1LI

**Comment by Grz3s** [comment]
`Klaven Mortwake`  - text is OK. (checked) .. it was diff issue ..  Text should only be displayed to Rogue Players in `stealth mode` doing quest there.... (BTW:  HE has no aggro text)  - fixed

**Comment by Grz3s** [comment]
`chicken quest` - theyre lots of posts like this:

`By MrDummy on 2006/12/30 (Patch 2.0.1) 
Subject: "/cheer important?"
Seems not... i forgot to type /cheer after giving food, but the chicken lays egg and i can loot it.
Well? /cheer seems not really needed :P`

`Subject: "No /cheer required"
I just did this tonight, and I didn't need to /cheer the chicken before I could get the "quest" after it looked at me quizzically.`

or mistake made by blizz or whatever .. we want stuff to work like it was there... and it it ;)

**Comment by al3xc1985** [comment]
Don't we have here a random action type? The chickencan wait for cheer and chicken lay it automatically?
From classic movies, i found that they wait for cheer.
Also, 2.0.1 is still a beta version not end release point of patch

**Comment by al3xc1985** [comment]
I read many comments even in classic and i found your info amd mine. There is a random chance for chicken to give quest directly and also to wait for a cheer

**Comment by Grz3s** [comment]
i told you to stop using links from 1.13 classic... its based on legion client not on original vanilla .

**Comment by al3xc1985** [comment]
@Grz3s u break my feelings :((( ... but I still love you!
what about this?
https://www.youtube.com/watch?v=OQP9oAwAwU0&feature=emb_logo

**Comment by al3xc1985** [comment]
this one is prove that what u say is ALSO a random posibility
https://www.youtube.com/watch?v=mc-rjrzwEV0 ...and there are many like this one
BUT believe me, there is a 50/50 chance with that mechanism

**Comment by Grz3s** [comment]
both your links poovs that /cheer is not needed... wheres that 50/50 on them?

**Comment by al3xc1985** [comment]
I let it as u say. U have more exp, and your eyes see more details.

**Comment by al3xc1985** [comment]
this can be closed now
