### ISSUE TITLE
Axel Bugs - Errors during game -

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#357]
- [ ] 2021-02-21 19:37:15 ERROR: DB-SCRIPTS: Process table `dbscripts_on_relay` id 10103, command 0 has buddy 19425 by guid 69482 but buddy is dead, skipping.

- [ ] 2021-02-21 19:37:20 ERROR: DB-SCRIPTS: Process table `dbscripts_on_relay` id 10103, command 0 has buddy 19425 by guid 69484 but buddy is dead, skipping.

- [ ] 2021-02-21 19:38:31 ERROR: DB-SCRIPTS: Process table `dbscripts_on_relay` id 10103, command 0 has buddy 19425 by guid 69482 but buddy is dead, skipping.
- [ ] 2021-02-21 19:38:35 ERROR: DB-SCRIPTS: Process table `dbscripts_on_relay` id 10103, command 0 has buddy 19425 by guid 69484 but buddy is dead, skipping.

- :x:  2021-02-21 20:00:37 ERROR:Table `command` have nonexistent command 'combatstop', skip. -- core issue .. not db

- [ ]  2021-02-21 22:53:14 ERROR: DB-SCRIPTS: Process table `dbscripts_on_creature_movement` id 2319001, command 1 call for non-unit, skipping.
- [ ] 2021-02-21 22:53:14 ERROR: DB-SCRIPTS: Process table `dbscripts_on_creature_movement` id 2319001, command 16 could not find proper source
- [ ] 2021-02-21 22:53:15 ERROR: DB-SCRIPTS: Process table `dbscripts_on_creature_movement` id 2319001, command 1 call for non-unit, skipping.
- [ ] 2021-02-21 22:53:15 ERROR: DB-SCRIPTS: Process table `dbscripts_on_creature_movement` id 2319001, command 16 could not find proper source
- [ ] 2021-02-21 22:53:17 ERROR: DB-SCRIPTS: Process table `dbscripts_on_creature_movement` id 2319001, command 1 call for non-unit, skipping.
- [ ] 2021-02-21 22:53:17 ERROR: DB-SCRIPTS: Process table `dbscripts_on_creature_movement` id 2319001, command 16 could not find proper source
- [ ] 2021-02-21 22:53:17 ERROR: DB-SCRIPTS: Process table `dbscripts_on_creature_movement` id 2318901, command 15 call for non-unit, skipping.
- [ ] 2021-02-21 22:53:18 ERROR: DB-SCRIPTS: Process table `dbscripts_on_creature_movement` id 2319001, command 1 call for non-unit, skipping.
- [ ] 2021-02-21 22:53:18 ERROR: DB-SCRIPTS: Process table `dbscripts_on_creature_movement` id 2319001, command 16 could not find proper source
- [ ] 2021-02-21 22:53:19 ERROR: DB-SCRIPTS: Process table `dbscripts_on_creature_movement` id 2319001, command 1 call for non-unit, skipping.
- [ ] 2021-02-21 22:53:19 ERROR: DB-SCRIPTS: Process table `dbscripts_on_creature_movement` id 2319001, command 16 could not find proper source
- [ ] 2021-02-21 22:53:20 ERROR: DB-SCRIPTS: Process table `dbscripts_on_creature_movement` id 2318901, command 1 call for non-unit, skipping.
- [ ] 2021-02-21 22:53:20 ERROR: DB-SCRIPTS: Process table `dbscripts_on_creature_movement` id 2319001, command 1 call for non-unit, skipping.
- [ ] 2021-02-21 22:53:20 ERROR: DB-SCRIPTS: Process table `dbscripts_on_creature_movement` id 2319001, command 16 could not find proper source
- [  ]2021-02-21 22:53:21 ERROR: DB-SCRIPTS: Process table `dbscripts_on_creature_movement` id 2319001, command 1 call for non-unit, skipping.
- [ ] 2021-02-21 22:53:21 ERROR: DB-SCRIPTS: Process table `dbscripts_on_creature_movement` id 2319001, command 16 could not find proper source
- [ ] 2021-02-21 22:53:22 ERROR: DB-SCRIPTS: Process table `dbscripts_on_creature_movement` id 2319001, command 1 call for non-unit, skipping.
- [ ] 2021-02-21 22:53:22 ERROR: DB-SCRIPTS: Process table `dbscripts_on_creature_movement` id 2319001, command 16 could not find proper source
- [ ] 2021-02-21 22:53:23 ERROR: DB-SCRIPTS: Process table `dbscripts_on_creature_movement` id 2319001, command 1 call for non-unit, skipping.
- [ ] 2021-02-21 22:53:23 ERROR: DB-SCRIPTS: Process table `dbscripts_on_creature_movement` id 2319001, command 16 could not find proper source
- [ ] 2021-02-21 22:53:24 ERROR: DB-SCRIPTS: Process table `dbscripts_on_creature_movement` id 2319001, command 1 call for non-unit, skipping.
- [ ] 2021-02-21 22:53:24 ERROR: DB-SCRIPTS: Process table `dbscripts_on_creature_movement` id 2319001, command 16 could not find proper source
- [ ] 2021-02-21 22:53:25 ERROR: DB-SCRIPTS: Process table `dbscripts_on_creature_movement` id 2319001, command 1 call for non-unit, skipping.
- [ ] 2021-02-21 22:53:25 ERROR: DB-SCRIPTS: Process table `dbscripts_on_creature_movement` id 2319001, command 16 could not find proper source
- [ ] 2021-02-21 22:53:26 ERROR: DB-SCRIPTS: Process table `dbscripts_on_creature_movement` id 2319001, command 1 call for non-unit, skipping.
- [ ] 2021-02-21 22:53:26 ERROR: DB-SCRIPTS: Process table `dbscripts_on_creature_movement` id 2319001, command 16 could not find proper source

**Comment by al3xc1985** [comment]
feel free to edit my report as u like, and next ones will be an example for me

**Comment by Grz3s** [comment]
all related to TDB backports .. nothing serious...  will be fixed one day.

**Comment by al3xc1985** [comment]
Well, I let them here just to have them noted
