### ISSUE TITLE
Axel Issues - Scarlet Monastery -

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#362]
- [x]  Ashbringer event
- When Highlord Mogranin comes to speak with reanaul, there is no pause time between renault "please forgive me" and mograin "you are forgiven"...
- Mograin doesn't use the lightning spell to kill mograin, he just stands and despawn after a while
- their disccusion timers need to be improved
- also there are a few emotes in their talk
https://www.youtube.com/watch?v=cp-jhDgbR08

- Fairbanks should stand
- Fairbanks should have a cleanse spell casted on him when u click him and transform him only then into human, and only than u are able to talk with him

**Comment by insunaa** [comment]
Try with this: https://github.com/cmangos/mangos-tbc/pull/438

**Comment by insunaa** [comment]
OK, the Pullrequest now has a hackfix in place that temporarily changes the faction of the scarlet guys and girls to `35` => friendly. If someone can supply me with a sniff of the actual faction, that'd be sweet!

Or better yet, if someone can make the spell-effect of the ashbringer actually change the reputation to these NPCs appropriately (this is outside of my realm of expertise)

**Comment by AnonXS** [comment]
Looking at what goes wrong with

```
('429806','4298','8','0','100','1','28441','-1','30000','30000','0','0','53','9000','6','0','0','0','0','0','0','0','0','0','Scarlet Defender - Start Relay Script on AB Effect 000 Spellhit'),
```

and others might be the solution.

**Comment by insunaa** [comment]
Database stuff unfortunately is *leagues* outside of my area of expertise, I haven't the slightest idea what any of these numbers mean or do :(

**Comment by insunaa** [comment]
The reason why the faction isn't friendly is because the Spell-Effect 28441 is only applied once on Item-Equip, when actually it should be re-applied every 5 seconds.

My PR now hackfixes only this part and it works, as shown in this video, *but* this should actually be fixed in the spellscript / database somewhere.
https://www.youtube.com/watch?v=u6ufxlm7DDc

**Comment by rmzV** [comment]
what about
"This item dropped from the cache of the Four Horsemen in the Deathknight Wing of the original Naxxramas. In Wrath of the Lich King, Highlord Mograine has been replaced by Baron Rivendare in Naxxramas, and Corrupted Ashbringer cannot be looted"
https://wow.gamepedia.com/Corrupted_Ashbringer

**Comment by insunaa** [comment]
The item can't be obtained in WotLK anymore, but if the server is using some progression from TBC to WotLK for example, it could still be in someone's inventory. Also if the Server has custom vendors it could be bought. Either way it makes sense to have the script in working order, even on a WotLK server.

**Comment by rmzV** [comment]
i think the answer is: was this event worked on Wotlk official?

earlier i was concerned about old quests that can be done because naxx was moved... but thats is how blizz server worked.

**Comment by al3xc1985** [comment]
first post updated 
@MantisLord @AnonXS this is the current status

**Comment by Grz3s** [comment]
tested and all works correct
