### ISSUE TITLE
Axel Issues - Console Errors -

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#368]
- [ ] 2021-03-19 22:08:20 ERROR:Invalid poly ref in BuildPolyPath. polyLength: 2, pathStartIndex: 0, startPos: (2697.15, 6165.92, 70.1656), endPos: (2698.86, 6165.06, 67.7732), mapId: 571

- [ ] 2021-03-19 22:34:50 ERROR:Invalid poly ref in BuildPolyPath. polyLength: 2, pathStartIndex: 0, startPos: (-10002, 466.407, 32.3527), endPos: (-9993.41, 478.576, 32.9126), mapId: 0

- [ ] 2021-03-19 22:49:30 ERROR:Invalid poly ref in BuildPolyPath. polyLength: 2, pathStartIndex: 0, startPos: (2701.31, 6170.59, 72.4341), endPos: (2702.74, 6168, 69.8048), mapId: 571

**Comment by Grz3s** [comment]
core issue cannot be fixed via DB

**Comment by al3xc1985** [comment]
can u read this pls?
2021-03-19 23:02:53 ERROR:Delete Gameobject (Entry: 31442 Guid: 9000683) with SpellId 818 LinkedGO 0 that lost references to owner Player Highfather (Guid: 5) GO list. Crash possible later.
2021-03-19 23:02:53 ERROR:Delete Gameobject (Entry: 29784 Guid: 9000682) with SpellId 818 LinkedGO 31442 that lost references to owner Player Highfather (Guid: 5) GO list. Crash possible later.

**Comment by al3xc1985** [comment]
this I get when I use .shutdown server command
do u know what they are?

**Comment by al3xc1985** [comment]
googling this objects they are camp fires..why whould we receive such errors?

**Comment by al3xc1985** [comment]
they are from cooking...one I believe aprentice and the other one jorney cooking

**Comment by Grz3s** [comment]
another core issue... not db related

**Comment by al3xc1985** [comment]
@Grz3s should I report them there? Or u have it noted or they know about it?
