### ISSUE TITLE
Axel Issues - Missing Items in DB -

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#369]
- [x] https://classic.wowhead.com/item=8546/powerful-smelling-salts
- [x] https://classic.wowhead.com/item=8547/formula-powerful-smelling-salts

The item is in db now, but it doesn't have the full description
![image](https://user-images.githubusercontent.com/6240049/234379729-9c06dc11-7701-42de-874e-c5f19621f2fc.png)

- [x] https://www.wowhead.com/item=36942/frostmourne
- [ ] https://www.wowhead.com/item=17/martin-fury

Even thou it's a shirt it's also says plate, wich is not normal
![image](https://user-images.githubusercontent.com/6240049/234379780-b6768b15-3d8c-4d89-a363-8d2b4783aaea.png)

- [x] https://www.wowhead.com/item=43651/craftys-pole
There are refenrences about this fishing pole since 2009...but as usual it is unobtainable but I believe we should have it in db

- [x] https://www.wowhead.com/item=12947/alexs-ring-of-audacity
Alex's Ring of Audacity
Finger
Equip: Defense + 1000. Consider
yourself born again hardcore!

This items are missing from game db. Even thou they can not be obrtainable, we should have them in db

**Comment by rmzV** [comment]
https://www.wowhead.com/item=43651/craftys-pole
Added in patch 4.1.0.13726

**Comment by al3xc1985** [comment]
I thought the same thing, but I found this
https://classic.wowhead.com/forums/topic/92979

**Comment by insunaa** [comment]
![image](https://user-images.githubusercontent.com/3718129/111917595-17d23b00-8a81-11eb-8c66-c3b467df5070.png)

![image](https://user-images.githubusercontent.com/3718129/111917588-0a1cb580-8a81-11eb-8c15-8eec1158208b.png)
\*doubt\*

**Comment by al3xc1985** [comment]
I am 100% sure that there are many other items missing in db, many also implemented in tbc, and wotlk 2, not just classic...I will note it down, I and I might track them one day

**Comment by al3xc1985** [comment]
First post updated

**Comment by celguar** [comment]
Items that are > 180000+ itemId are new items added during classic era, 3.3.5 item.dbc doesn't have any info on them

**Comment by celguar** [comment]
They also use new spells that don't exist in 3.3.5

**Comment by celguar** [comment]
https://www.wowhead.com/wotlk/item=8547/formula-powerful-smelling-salts-ph
spell was removed in wrath, only present in 1.12 and 2.4.3

**Comment by celguar** [comment]
wotlk wowhead also has no description and shows spell not found

**Comment by al3xc1985** [comment]
aa yes... it's correct than

**Comment by al3xc1985** [comment]
what about martin fury?

**Comment by celguar** [comment]
there is an item with ID 17 added, but with empty name. I guess I need to update script to add it. But spell ID is missing from it in new client data, even thought it's probably spellID=7.

**Comment by AnonXS** [comment]
Data was added with bruteforce thx @celguar, any more adjustments become their own issues for discussions.
