### ISSUE TITLE
This is ICC04  Skybreaker

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#375]
Ymirheim 

- [x] *1  [80] Get to Ymirheim! 
https://www.wowhead.com/quest=13296/get-to-ymirheim
- [x] *2   [80P Daily] King of the Mountain
https://www.wowhead.com/quest=13280/king-of-the-mountain#comments
•	 --[80] Joining the Assault 
•	https://www.wowhead.com/quest=13341/joining-the-assault
o	 ---- [80 Daily] Assault by Air
o	https://www.wowhead.com/quest=13309/assault-by-air
o	 ----  [80 Daily] Assault by Ground
o	https://www.wowhead.com/quest=13284/assault-by-ground
•	--  [80 Daily] Slaves to Saronite
•	https://www.wowhead.com/quest=13300/slaves-to-saronite#comments
•	--  [80 Daily] Blood of the Chosen
•	https://www.wowhead.com/quest=13336/blood-of-the-chosen

Broken Front 
- [x] *1  [80] The Broken Front
That completes the quest objectives, but the Dying Soldier then offers   [80] Finish Me!
https://www.wowhead.com/quest=13231/the-broken-front
- [x] *2  [80] Finish Me!
https://www.wowhead.com/quest=13232/finish-me#comments
- [x] *3  [80P Daily] No Mercy!
https://www.wowhead.com/quest=13233/no-mercy

After The Broken Front 
- [x] *1  [80] ...All the Help We Can Get.
https://www.wowhead.com/quest=13286/all-the-help-we-can-get
- [x] *2  [80] Poke and Prod 
https://www.wowhead.com/quest=13287/poke-and-prod
o	--  [80] That's Abominable! (Daily version)
o	https://www.wowhead.com/quest=13288/thats-abominable
o	https://www.wowhead.com/quest=13289/thats-abominable
- [x] *3  [80G3] Against the Giants 
https://www.wowhead.com/quest=13294/against-the-giants
o	--  [80G5] Coprous the Defiled
o	https://www.wowhead.com/quest=13298/coprous-the-defiled
- [x] *4  [80G5] Basic Chemistry (Daily version)
https://www.wowhead.com/quest=13295/basic-chemistry
https://www.wowhead.com/quest=13297/neutralizing-the-plague

After The Broken Front: 
- [x] *1  [80] Your Attention, Please
https://www.wowhead.com/quest=13290/your-attention-please
- [x] *2  [80] Borrowed Technology 
https://www.wowhead.com/quest=13291/borrowed-technology
o	  --[80 Daily] The Solution Solution
o	This quest is available after completing Borrowed Technology.
o	https://www.wowhead.com/quest=13292/the-solution-solution
- [x] *3  [80] Killohertz
https://www.wowhead.com/quest=13383/killohertz
- [x] *4  [80] Leading the Charge 
https://www.wowhead.com/quest=13380/leading-the-charge
o	 -- [80 Daily] Static Shock Troops: the Bombardment
o	https://www.wowhead.com/quest=13404/static-shock-troops-the-bombardment
- [x] *5  [80] Watts My Target 
https://www.wowhead.com/quest=13381/watts-my-target
this is strange quest : This quest can not be taken in-game. It was probably data-mined, but the npc simply does not give it. Never. Only the 'followup', Putting the Hertz: The Valley of Lost Hope (a daily), can be done.
o	  --[80 Daily] Putting the Hertz: The Valley of Lost Hope
o	https://www.wowhead.com/quest=13382/putting-the-hertz-the-valley-of-lost-hope

- [x] Aldur'thar: 
•	  [80] Sneak Preview 
•	https://www.wowhead.com/quest=13315/sneak-preview#comments
After completing this, the following three quests were available to me:Drag and Drop Chain of Command Cannot Reproduce
o	 -- [80] Drag and Drop (Daily version) 
o	https://www.wowhead.com/quest=13318/drag-and-drop#comments
o	Leads to daily 
o	https://www.wowhead.com/quest=13323/drag-and-drop
	----  [80] Not a Bug (Daily version)
	https://www.wowhead.com/quest=13342/not-a-bug#comments
	https://www.wowhead.com/quest=13344/not-a-bug
	----  [80G3] Need More Info 
	https://www.wowhead.com/quest=13345/need-more-info
	[chained to https://www.wowhead.com/quest=13346/no-rest-for-the-wicked]
	 ------ [80G5] No Rest For The Wicked (Daily version) 
	https://www.wowhead.com/quest=13346/no-rest-for-the-wicked
	https://www.wowhead.com/quest=13350/no-rest-for-the-wicked
	 -------- [80G5] The Ironwall Rampart 
	https://www.wowhead.com/quest=13337/the-ironwall-rampart#comments
	Leads to http://www.wowhead.com/?quest=13335
	No Rest For The Wicked must be completed for this quest to open up.
	http://www.wowhead.com/?quest=13332 is also needed in order to open this quest.
	----------  [80G5] Before the Gate of Horror
	https://www.wowhead.com/quest=13335/before-the-gate-of-horror#comments
	Leads to: Shatter the Shards the Guardians of Corp'rethar 
	Was unlocked for me when I completed http://www.wowhead.com/?quest=13337.
	Prollyy too http://www.wowhead.com/?quest=13334 is a prereq
	 ------------ [80G5] Shatter the Shards
	https://www.wowhead.com/quest=13339/shatter-the-shards#comments
	 ------------ [80G5] The Guardians of Corp'rethar
	https://www.wowhead.com/quest=13338/the-guardians-of-corprethar#comments
o	--  [80] Chain of Command
o	https://www.wowhead.com/quest=13319/chain-of-command#comments
o	--  [80] Cannot Reproduce 
o	https://www.wowhead.com/quest=13320/cannot-reproduce#comments
	 ---- [80] Retest Now (Daily version)
	https://www.wowhead.com/quest=13321/retest-now#comments
	https://www.wowhead.com/quest=13322/retest-now

Valley of Fallen Heroes, after [Need More Info]: 
- [x] *1  [80] Raise the Barricades
https://www.wowhead.com/quest=13332/raise-the-barricades
- [x] *2  [80] Bloodspattered Banners 
https://www.wowhead.com/quest=13334/bloodspattered-banners
o	  [80] Get the Message (Daily version)
o	https://www.wowhead.com/quest=13314/get-the-message
o	https://www.wowhead.com/quest=13333/capture-more-dispatches

**Comment by Grz3s** [comment]
completed
