### ISSUE TITLE
This is ICC05  Ogrim's Hammer

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#376]
This is ICC05  Ogrim's Hammer
Ymirheim 
- [x] *1   [80] Get to Ymirheim!
•	https://www.wowhead.com/quest=13293/get-to-ymirheim
- [x]  *2   [80Da] King of the Mountain
https://www.wowhead.com/quest=13283/king-of-the-mountain#comments
- [x] •	  [80] Joining the Assault 
•	https://www.wowhead.com/quest=13340/joining-the-assault#comments
o	-----  [80 Daily] Assault by Air
o	https://www.wowhead.com/quest=13310/assault-by-air#comments
o	 ----- [80 Daily] Assault by Ground
o	https://www.wowhead.com/quest=13301/assault-by-ground
- [x] •	  [80 Daily] Slaves to Saronite
•	https://www.wowhead.com/quest=13302/slaves-to-saronite
- [x] •	  [80 Daily] Blood of the Chosen
•	https://www.wowhead.com/quest=13330/blood-of-the-chosen#comments

Broken Front 
- [x] •	*1  [80] The Broken Front 
•	https://www.wowhead.com/quest=13228/the-broken-front
- [x] *2  [80] Avenge Me!
o	https://www.wowhead.com/quest=13230/avenge-me
- [x]  3 •    [80Da-PvP] Make Them Pay!
o	https://wowwiki-archive.fandom.com/wiki/Quest:Make_Them_Pay!
o	https://www.wowhead.com/quest=13234/make-them-pay

After the Broken Front https://www.wowhead.com/quest=13228/the-broken-front
- [x] *1  [80] Takes One to Know One
https://www.wowhead.com/quest=13260/takes-one-to-know-one
- [x] *2  [80] Poke and Prod 
https://www.wowhead.com/quest=13237/poke-and-prod#comments
Opens the quests:
That's Abominable!
Against the Giants
o	-----  [80] That's Abominable! (Daily version)
o	Completing this quest opens up the quest [Sneak Preview].same for ally?
o	https://wowwiki-archive.fandom.com/wiki/Quest:That%27s_Abominable!_(Horde)
o	https://www.wowhead.com/quest=13264/thats-abominable
o	https://www.wowhead.com/quest=13276/thats-abominable
- [x] *3  [80] Against the Giants 
https://www.wowhead.com/quest=13277/against-the-giants
o	-----  [80G5] Coprous the Defiled
o	https://www.wowhead.com/quest=13278/coprous-the-defiled
- [x] *4  [80G5] Basic Chemistry
https://www.wowhead.com/quest=13279/basic-chemistry
                           [80G5 Daily] Neutralizing the Plague
https://www.wowhead.com/quest=13281/neutralizing-the-plague

After the Broken Front https://www.wowhead.com/quest=13228/the-broken-front

- [x] *1  [80] Good For Something?
https://www.wowhead.com/quest=13238/good-for-something#comments
- [x]  *2  [80] Volatility 
https://www.wowhead.com/quest=13239/volatility
o	-----  [80 Daily] Volatility
o	https://www.wowhead.com/quest=13261/volatility
- [x] *3  [80] Green Technology
https://www.wowhead.com/quest=13379/green-technology
- [x] *4  [80] Fringe Science Benefits 
https://www.wowhead.com/quest=13373/fringe-science-benefits
Opens the quests:
Riding the Wavelength: The Bombardment.
Total Ohmage: The Valley of Lost Hope!
o	----  [80 Daily] Riding the Wavelength: The Bombardment
o	https://www.wowhead.com/quest=13406/riding-the-wavelength-the-bombardment
o	Prerequisite quest: Fringe Science Benefits.
- [x]  *5  [80] Amped for Revolt! 
https://www.wowhead.com/quest=13374/amped-for-revolt
o	----  [80 Daily] Total Ohmage: The Valley of Lost Hope!
o	https://www.wowhead.com/quest=13376/total-ohmage-the-valley-of-lost-hope

Aldur'thar: 
- [x]  •	  [80] Sneak Preview 
•	https://www.wowhead.com/quest=13351/sneak-preview#comments
•	Opens up:
http://wotlk.wowhead.com/?quest=13352
http://wotlk.wowhead.com/?quest=13354
http://wotlk.wowhead.com/?quest=13355
o	--  [80] Drag and Drop (Daily version) 
o	https://www.wowhead.com/quest=13352/drag-and-drop
o	https://www.wowhead.com/quest=13353/drag-and-drop
	 ---- [80] Not a Bug (Daily version)
	https://www.wowhead.com/quest=13358/not-a-bug#comments
	https://www.wowhead.com/quest=13365/not-a-bug
	----  [80] Need More Info 
	https://www.wowhead.com/quest=13366/need-more-info#comments
	 ------ [80G5] No Rest For The Wicked (Daily version) 
	https://www.wowhead.com/quest=13367/no-rest-for-the-wicked#
	https://www.wowhead.com/quest=13368/no-rest-for-the-wicked
	--------  [80G5] The Ironwall Rampart 
	https://www.wowhead.com/quest=13312/the-ironwall-rampart
	 ---------- [80G5] Before the Gate of Horror 
	https://www.wowhead.com/quest=13329/before-the-gate-of-horror
	Becomes available after The Ironwall Rampart. Leads to The Guardians of Copre'thar and Shatter the Shards.
	You must complete Bloodspattered Banners before you can get this.
	-------------  [80G5] Shatter the Shards
	https://www.wowhead.com/quest=13328/shatter-the-shards
	-------------  [80G5] The Guardians of Corp'rethar
	https://www.wowhead.com/quest=13316/the-guardians-of-corprethar
o	  --[80] Chain of Command
o	https://www.wowhead.com/quest=13354/chain-of-command
o	 -- [80] Cannot Reproduce 
o	https://www.wowhead.com/quest=13355/cannot-reproduce
	  ----[80] Retest Now (Daily version)
	https://www.wowhead.com/quest=13356/retest-now
	https://www.wowhead.com/quest=13357/retest-now

Valley of Fallen Heroes:  after after [Need More Info]:??? same as Ally?
- [x] *1  [80] Raise the Barricades
https://www.wowhead.com/quest=13306/raise-the-barricades#comments
- [x] *2  [80] Bloodspattered Banners 
https://www.wowhead.com/quest=13307/bloodspattered-banners
o	----  [80] Blinding the Eyes in the Sky (Daily version)
o	Completing this quest opens a daily version,   [80 Daily] Keeping the Alliance Blind.
o	https://www.wowhead.com/quest=13313/blinding-the-eyes-in-the-sky
o	https://www.wowhead.com/quest=13331/keeping-the-alliance-blind

**Comment by Grz3s** [comment]
completed
