### ISSUE TITLE
redundant real-time duration flag

### ISSUE THREAD

**Issue by apo126** [cmangos/wotlk-db#38]
Latest World DB: WoTLKDB v1.0 'Echoes of Northrend' for CMaNGOS-WOTLK 12943 with 623 update has below small bugs:
ERROR:Item (Entry: 5513) has redundant real-time duration flag in ExtraFlags, item not have duration
ERROR:Item (Entry: 5514) has redundant real-time duration flag in ExtraFlags, item not have duration
ERROR:Item (Entry: 8007) has redundant real-time duration flag in ExtraFlags, item not have duration
ERROR:Item (Entry: 8008) has redundant real-time duration flag in ExtraFlags, item not have duration
ERROR:Item (Entry: 22044) has redundant real-time duration flag in ExtraFlags, item not have duration
ERROR:Item (Entry: 33312) has redundant real-time duration flag in ExtraFlags, item not have duration

**Comment by Grz3s** [comment]
Duplicate:
https://github.com/cmangos/wotlk-db/issues/37
