### ISSUE TITLE
Extra-Dimensional Ghost Revealer

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#385]
https://classic.wowhead.com/item=22115/extra-dimensional-ghost-revealer

probably its not db related, but you can see Anthion without using item..
may be it becouse i used this item earlier?

update : Bodley at brd works as it should

**Comment by Grz3s** [comment]
he has correct aura set on...
- or you're in gm mode - so you can see all
- or you still have aura from item active.
anyway he works correct
