### ISSUE TITLE
Message to Maxwell

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#389]
https://classic.wowhead.com/quest=5002/message-to-maxwell

probably that was disscused earlier...is that only ally quest?
https://classic.wowhead.com/quest=5002/message-to-maxwell#comments
why i see it?

**Comment by Grz3s** [comment]
Quest You talking about req. prev `q.5001 'Bijou's Belongings'` completed... and that quest has RaceReq = 1101 (alliance only)
so question is... 
- how did you finish prev quest if its alliance only)
??

**Comment by rmzV** [comment]
ok i opened "character queststatus"
and "quest" 5001 have "status" 1 with is not correct?  must be 0?

ill probably completed this prequest when it has not RaceReq = 1101

**Comment by rmzV** [comment]
.q r 5001
did the job thanks!

**Comment by Grz3s** [comment]
@rmzV this quest want ever changed ... you added it manualy... by `.q a 5001` .. or with `gm on`

**Comment by rmzV** [comment]
i think it have it roots something here
https://github.com/cmangos/wotlk-db/issues/21

"1.after completing quest "operative Bijou" , Bijou NPC has two same quests "Bijou's Belongings" !4982 and !5001 and later it gives two different quests " Bijou's reconnaisance report " and "message to maxwell" report must be Horde quest and message is for aliance(with cant be completed). so i think 4982 and 5001 are different faction quests as well"
proly i completed 5001 long time ago..

**Comment by Grz3s** [comment]
ok just to conclude.... yes .. there was a fix for it:
https://github.com/cmangos/wotlk-db/commit/1167f5bcad288f70402cb4dc8ba6d834eede0432
and now:
if you did ths before fix.. then yes .. both followups will be available for you...
best way to correct it ..is to remove whole chain from your quest log.
```code
.q r 5002
.q r 5001
```
relog .. and start chain again ...

**Comment by rmzV** [comment]
removing 5001 do the job. thx!

**Comment by rmzV** [comment]
@Grz3s btw what is your thoughts on icecrown quest chains? is it possible to link quest between each other for first iteration, so i can check if something work or no later and update my research?

**Comment by Grz3s** [comment]
im not planning to go into ic yet... got enough on my list.

**Comment by rmzV** [comment]
okey:( will wait then!
may be you can give me a code example, for UPDATE ... i mean quest X available after Y complete?
