### ISSUE TITLE
[Bug Report] Tamed Kodo Doesn't Work

### ISSUE THREAD

**Issue by ClassicW** [cmangos/wotlk-db#392]
The quest Kodo Roundup doesn't work because the npc tamed kodo are bugged
Quest: ID=5561
Npc: ID=11627
You can speak to the kodo before presenting it to smeed Scrabblescrew and Kodos don't disappear once validated, he just stays in place.

Expected behavior
You must present the 5 tamed kodos one by one to Smeed Scrabblescrew (the quest giver). Then, the kodo must disappear once validated
This video explains how it works
https://www.youtube.com/watch?v=NS-oEeZhm9o&ab_channel=DibuckTV

Steps to reproduce
Create a hero level 35
Go to smeed Scrabblescrew .go creature 27923
Take the quest kodo-roundup ID=5561
go to the kodo .go creature 28296
use Kodo Kombobulator in kodo and speak to the kodo

**Comment by Grz3s** [comment]
just tested that quest & i cant reproduce what u said:
- after item used  - they becomes friendly... still no gossip flag - so how can you speak to them????
- they do despawn -- ~~ 20delay
Are you sure .. youre using fresh WotlkDB ?

Only issue i see is that they missing gossip texts ... will add that soon*

**Comment by ClassicW** [comment]
I tested on a vanilla 1.12 version, I wanted to know if you have the same problem on wotlk because I can't find anyone from classic to tell me. 
Thanks for your feedback.

**Comment by Grz3s** [comment]
this is wotlkDB section ... not 1.12.
nothing to fix here.
closed
