### ISSUE TITLE
LAX issues list....

### ISSUE THREAD

**Issue by Grz3s** [cmangos/wotlk-db#4]
source: http://cmangos.net/thread-7605.html
Author: LaX

**Eversong Woods:**
~~no dragonhawks near flightmaster "Skymistress Gloaming"~~ -- **Fixed**
 ~~Sathein "letherworking trainer" has anvil instead of book icon~~ -- **Fixed**
**Ghostlands:**
 ~~no dragonhawks near flightmaster "Skymaster Sunwing"~~ -- **Fixed**
**Hillsbrad Foothills:**
~~567! Dangerous! - wanted poster partically going into the house wall and quest mark non visible"~~ -- **Fixed**
 ~~High executor Darthalia gives same quest twice 550 and 14351"~~ -- **Fixed**
 ~~524! elixir of Agony - when you place keg peasants must drink from it etc~~ -- **Fixed**

**Undercity:**
~~Doors and platforms sometimes works in non synchronised mod~~ **Fixed**
**Silverpine forest**
 ~~437! The dead fields - Gnols must be killed untill Nightflash appear~~ -- **Fixed**
~~Pyrewood Village - Pyrewood's inhabitants have been cursed so that they undergo a nightly transformation into the bestial worgen (measured at 8:59PM–9:00PM server time), then return to their human forms upon the arrival of dawn. It is during this time that they become hostile to all players regardless of faction. Despite all its hardships, however, the village continues to service Alliance travellers by selling cloth, leather, and mail armor to customers. Just a little south of the village is an~~ **FIXED** 
**The Bareens:**
~~4021! counterattack  - doesnot work~~ **FIXED**
**Tirisfal Glades**
 ~~Zapetta "Durotar Zepellin master" dialog with "where zepellin now" doesnot work~~ -- **Fixed**
 **Arathi highlands**
~~Fozruk NPC - as you start fight with him adds must join the fight~~ -- **Fixed**
http://www.wowhead.com/npc=2611/fozruk#comments
**Thousand Needles**
~~Highperch patriarch - some of this mobs bugged in non target state and some of them located on lover floor~~ -- **Fixed**
~~1147! the swarm grows - only one "invider" spawn=(
 from wowhead " The invaders are down in the cave, you must kill the drones for invaders to spawn.""~~ -- **Fixed**
**Desolace**
~~6134! ghost - o - plasm round up - spirits doesnot spawn~~ -- **Fixed**
**Musc:**
~~Sometimes you are dead after using flightmaster~~ -- **Fixed in core**
~~item "message in a bottle" fished from lake.. but nothing inside
http://www.wowhead.com/item=6307/message...e#contains~~ -- **Fixed**
~~Recipe:Herb Baked Egg (if you learn from trainer - recipe from ah doesnot say "already know"~~ **Core Issue (if still exist) - need to be fixed there**
~~Formula:Imbue cloak - protection (same problem)~~ **Core Issue (if still exist) - need to be fixed there**
~~Formula:Enchant boots - minor stamina (same problem)~~ **Core Issue (if still exist) - need to be fixed there**
~~Achivement - statistics - creature killed  doesnot count~~ **Core Issue - need to be fixed there**
**Classes:**
~~DK: 12867 ! Into the realms of shadows - cant be completed. use item.. npc appeared but no quest mark on him. dismiss horse -quest non complete~~ -- **Fixed**
~~NE "Shadowmeld " - ability doesnot work~~ **Core Issue - need to be fixed there**
**BG:**
~~7789! Quell the Silverwing Usurpers - cant be completed couse the req mark are no longer in game.. probably quest replaced with never one"~~ -- **Fixed**
~~8162!Cut Arathor Supply Lines - same problem~~ -- **Fixed**
**Dungeon and Raids:**
~~RFK - 1221!Blueleaf  tubers - pet summoned in wrong spot. stik doesnot work at all~~ **works fine ... small not ..may req more spawns for tubers**

**Comment by killerwife** [comment]
I will script Ghost-O-Plasm Round-up when I have time. (this quest is on my personal desolace vendetta)

**Comment by xfurry** [comment]
1221 and 12867 should work. 
Undercity elevators out of sync looks to be a core problem.

**Comment by Phatcat** [comment]
elevators out of sync already reported as a core issue; https://github.com/cmangos/issues/issues/1091

**Comment by Grz3s** [comment]
ok ... I did some tests with:
```quote
Silverpine forest
 437! The dead fields - Gnols must be killed untill Nightflash appear
 Pyrewood Village - Pyrewood's inhabitants have been cursed so that they undergo a nightly transformation into the bestial worgen (measured at 8:59PM–9:00PM server time), then return to their human forms upon the arrival of dawn. It is during this time that they become hostile to all players regardless of faction. Despite all its hardships, however, the village continues to service Alliance travellers by selling cloth, leather, and mail armor to customers. Just a little south of the village is an 
```
Game_event = 27 "nights"
Should start  =20:00
c.1891"Pyrewood Watcher" should transform into 1892 Moonrage Watcher ....
we can see this action here:
```code
game_event_creature_data
(guid,  entry_id, modelid, equipment_id, spell_start, spell_end, event):
(19084, 1892, 0, 0, 7671, 7671, 27) 
```
What happens:
1st ... event starts 21:00 ??? why (should at 20:00) ??? realm time = local time
2nd...after transform - creatures still have equipment from prev entry :/ (updates only after server restart)
3rd... new creatures (transformed ones) ..
If player kill one of tchem ...after respawn... we having spam in console:
```sql
2016-10-12 21:11:21 ERROR:Map::GetReachableRandomPosition> Unsupported unit type is passed!
2016-10-12 21:11:21 ERROR:Map::GetReachableRandomPosition> Unsupported unit type is passed!
2016-10-12 21:11:21 ERROR:Map::GetReachableRandomPosition> Unsupported unit type is passed!
2016-10-12 21:11:21 ERROR:Map::GetReachableRandomPosition> Unsupported unit type is passed!
2016-10-12 21:11:21 ERROR:Map::GetReachableRandomPosition> Unsupported unit type is passed!
2016-10-12 21:11:21 ERROR:Map::GetReachableRandomPosition> Unsupported unit type is passed!
2016-10-12 21:11:21 ERROR:Map::GetReachableRandomPosition> Unsupported unit type is passed!
2016-10-12 21:11:21 ERROR:Map::GetReachableRandomPosition> Unsupported unit type is passed!
2016-10-12 21:11:21 ERROR:Map::GetReachableRandomPosition> Unsupported unit type is passed!
2016-10-12 21:11:21 ERROR:Map::GetReachableRandomPosition> Unsupported unit type is passed!
2016-10-12 21:11:22 ERROR:Map::GetReachableRandomPosition> Unsupported unit type is passed!
2016-10-12 21:11:22 ERROR:Map::GetReachableRandomPosition> Unsupported unit type is passed!
2016-10-12 21:11:22 ERROR:Map::GetReachableRandomPosition> Unsupported unit type is passed!
2016-10-12 21:11:22 ERROR:Map::GetReachableRandomPosition> Unsupported unit type is passed!
2016-10-12 21:11:22 ERROR:Map::GetReachableRandomPosition> Unsupported unit type is passed!
2016-10-12 21:11:22 ERROR:Map::GetReachableRandomPosition> Unsupported unit type is passed!
2016-10-12 21:11:22 ERROR:Map::GetReachableRandomPosition> Unsupported unit type is passed!
2016-10-12 21:11:22 ERROR:Map::GetReachableRandomPosition> Unsupported unit type is passed!
2016-10-12 21:11:22 ERROR:Map::GetReachableRandomPosition> Unsupported unit type is passed!
```
to stop it...we need to kill him again... (after resp..situation will repeat) :/

I cant remember this happening before...  anyone has any idea?

**Comment by killerwife** [comment]
I tested on mangos-tbc and stuff is not happening. Equipment ID is caused by this line     if (eventData && eventData->equipment_id), which if set 0 in DB, its not executed, probably with the intention of skipping this setting if you want to leave it the same. There is no easy solution, easiest is to change condition to     if (eventData) and for each game_event_creature_data always set correct equipment_id.

**Comment by killerwife** [comment]
Try changing 
    if (eventData && eventData->equipment_id)
    {
        LoadEquipment(eventData->equipment_id);             // use event equipment if any for active event
    }

to 

    if (eventData)
    {
        if(eventData->equipment_id)
            LoadEquipment(eventData->equipment_id);             // use event equipment if any for active event
        else if(eventData->entry_id)
            LoadEquipment(cinfo->EquipmentTemplateId, true);     // use changed entry default template
    }

The code kinda doesnt handle the possibility of target entry not having equipment at all.

**Comment by Grz3s** [comment]
Hey @killerwife 
thank fo your patch..
just tested it today... and "yes" it does the job... they transform  and equipment is correctly set = 0...
I also checked .. when event finishes... and they transform back into original entry... and it also works fine (equipment for tchem loaded ok)
:+1:

**Comment by killerwife** [comment]
Then ask someone to commit it to the core :D I still have no clue about the other issue.

**Comment by Grz3s** [comment]
@phatcat ??

**Comment by Phatcat** [comment]
that's me :3

Well, I am not quite sure what the code fixes, if someone gives me an appropriate commit title and message I'll get on it.

**Comment by killerwife** [comment]
It forces equipment change on game event start, even if the new Creature entry has EquipmentId==0. Before we skipped it and as a result, worgen had a staff, when he was supposed to have empty hands (i.e. equipment id ==0)

**Comment by rmzV** [comment]
Pyrewood Village - fixed.. just checked yesterday,, they all was worgens
Fozruk NPC - working correct atm
NE "Shadowmeld " working too
as for :Quell the Silverwing Usurpers 
http://www.wowhead.com/quest=7789/quell-the-silverwing-usurpers
comments says its removed
and:http://wowwiki.wikia.com/wiki/Quest:Cut_Arathor_Supply_Lines_(level_20)
patch changes says ite removed too
