### ISSUE TITLE
NPC Tabetha can have a wrong display id

### ISSUE THREAD

**Issue by Nytanath** [cmangos/wotlk-db#404]
[Tabetha](https://tbc.wowhead.com/npc=6546/tabetha) has a 50% chance to get a wrong display id. Issue was fixed for TBC in https://github.com/cmangos/tbc-db/commit/e0222dd244098e8c7aceae1f4ff831613af10fd6, needs to be ported to WotLK too.

**Comment by AnonXS** [comment]
just to make it right, the backport from classic-db is missing probably, we lack manpower to do all this db porting stuff.

**Comment by al3xc1985** [comment]
@Grz3s will ne back soon
