### ISSUE TITLE
Gnomish flame turret

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#415]
Does nothing but follow u and 1 dmg.. I believe the scope of this item is to stand still not follow and use some flame spells

Also the cooldown of the item does not reset it allways says "cooldown start upon out of combat" or something like that

**Comment by Grz3s** [comment]
using root spells .. etc will not stop him following players.
Maybe @killerwife can help here.

**Comment by AnonXS** [comment]
```
-- summoned creature behaves like wild summon and not like guardian
UPDATE `spell_template` SET `EffectMiscValueB1`=64 WHERE `Id` IN(30526);
```

**Comment by Grz3s** [comment]
with this ... he wont attack anything :/
