### ISSUE TITLE
[Quest] Powering our Defenses

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#419]
The Enraged Wraith do not attack the Infused Crystal that u spawn, they should come and attack it. Instead, they come to the crystal and just stand and watch it

**Comment by Grz3s** [comment]
pls always provide more details... like quest id .. item id npc entry etc... it will reduce searching time - what u asking for.
thank  you

**Comment by al3xc1985** [comment]
ok, sorry

Quest ID: https://tbc.wowhead.com/quest=8490/powering-our-defenses
Mob ID: https://tbc.wowhead.com/npc=17086/enraged-wraith
Crystal Id: https://tbc.wowhead.com/npc=16364/infused-crystal
