### ISSUE TITLE
[NPC] Shadowpine Catlord

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#421]
Shadowpine Catlord     https://tbc.wowhead.com/npc=16345/shadowpine-catlord
Ghostclaw Lynx            https://tbc.wowhead.com/npc=16348/ghostclaw-lynx

I see many many Shadowpine Catlord with his pet Ghostclaw Lynx and an other Ghostclaw Lynx spawned as a normal spawn in Zeb' Nowa. Is that correct?

**Comment by AnonXS** [comment]
https://github.com/cmangos/tbc-db/commit/9a54f9546c8455512ce3b845f5acbd8f33ce5d7e

**Comment by al3xc1985** [comment]
yes that it
Ty @AnonXS  I am sure @Grz3s  will take care of this

**Comment by al3xc1985** [comment]
I guess this is just a miss backport

**Comment by Grz3s** [comment]
not all of them are spawned from this spell... also wotlkDB has 0 guids for 99xxx range .. So TDB commit has no use here...
Will remove all that shouldnt be in the village
