### ISSUE TITLE
Remote-Controlled Golem - Too high damage

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#429]
https://classic.wowhead.com/npc=2520/remote-controlled-golem

This guys are spawned by  Goblin Engineer
[Goblin Engineer](https://classic.wowhead.com/npc=622/goblin-engineer)

They do between 150 - 250 dmg. That is abnormal for this lvl of dungeon

**Comment by AnonXS** [comment]
wotlk:
![grafik](https://user-images.githubusercontent.com/19734826/178397954-e34ac279-806c-48bd-bfd6-abd0d06ffacd.png)
tbc:
![grafik](https://user-images.githubusercontent.com/19734826/178397975-d80de0ec-b37c-4351-a4aa-6a02a54a4813.png)
classic:
![grafik](https://user-images.githubusercontent.com/19734826/178398001-3e9a9f65-b2cc-454a-8b6c-331b23c179e4.png)

**Comment by al3xc1985** [comment]
The dmg is 2 much multiplied
