### ISSUE TITLE
Mr.Smite - Broatcast text 

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#431]
https://classic.wowhead.com/npc=646/mr-smite

The text is not well written
![smite](https://user-images.githubusercontent.com/6240049/171467963-7dabfcd1-c4aa-4217-9b6a-693cc0793c50.png)

**Comment by Grz3s** [comment]
it comes from broadcast table.. with language 7 "common" so Blood Elf will not understand it... (strange)

source 3.3.5 sniff
```
ServerToClient: SMSG_CHAT (0x0096) Length: 77 ConnIdx: 0 Time: 02/24/2010 02:19:16.000 Number: 83907
Type: 14 (MonsterYell)
Language: 7 (Common)
GUID: Full: 0xF13000028600437D Type: Creature Entry: 646 Low: 17277
Constant time: 0
Name Length: 10
Name: Mr. Smite
Receiver GUID: Full: 0x28000000341B4DC Type: Player Low: 54637788 Name: XXX
Text Length: 33
Text: You there! Check out that noise.
Chat Tag: 0 (None)
```
Question ... can any Blood Elf Player say if this is how it should be ??

**Comment by Grz3s** [comment]
DM is not an easy place for horde to get... anyway...
Nothing to fix here then.
