### ISSUE TITLE
[Wailing Caverns] Final boss script

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#433]
The script to final boss when u escort the druid to awake Naralex from his deep sleep is broken..
What we have so far:
1.Deviate Moccasin spawn in the air and do not come to attack the druid
https://classic.wowhead.com/npc=5762/deviate-moccasin
2.Nightmare Ectoplasm are coming, but 2 fast, the time between waves si 2 short
https://classic.wowhead.com/npc=5763/nightmare-ectoplasm
3.The boss do not spawn at all - Mutanus
https://classic.wowhead.com/npc=3654/mutanus-the-devourer
4. The druid do not face Naralex when chanelling
5. The druid stop to chanel after a short period of time

**Comment by AnonXS** [comment]
as're trying to close of issues in wotlk-db can you please start refering to our issue tracker where there is already an open issue for this?

https://github.com/cmangos/issues/issues/2833
