### ISSUE TITLE
Arugal's Voidwalker 

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#434]
https://classic.wowhead.com/npc=4627/arugals-voidwalker

So u kill the wolf, arugal appear, spawn this guys, but u cam  move fast from them and not enter combat with them at all. Is that normal?
Shoudn't they get in combat with you after spawned?

**Comment by al3xc1985** [comment]
so it's ok as they are?

**Comment by Tobschinski** [comment]
that I can't say, maybe they should have a higher detection radius

only thing I did check is that you can avoid pulling them retail-classic

**Comment by AnonXS** [comment]
Also depends on their spawn in AggroDelay, but as they can be skipped, the nature of this report is invalid.

**Comment by al3xc1985** [comment]
Ok, ty closing this as îs normal behavioir

**Comment by AnonXS** [comment]
we would really appreciate if you could provide sources (ytube links, videos, guides) for future reports instead of making a witch hunt out of nothing.

**Comment by al3xc1985** [comment]
@AnonXS if u read again my ticket it's all full of  question mark? This was not ment to be a repot , instead of consulting with u guys.

I dislike discord if u ask me, and this is the only way to get in touch with u that I do for the moemnt
I am sorry @AnonXS u will have to accept me as I accept you !

No offense!
