### ISSUE TITLE
Fallenroot Shadowstalker - Missing Stealth Ability

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#435]
NPC        https://tbc.wowhead.com/npc=4798/fallenroot-shadowstalker#abilities;mode:normal

Missing 
https://tbc.wowhead.com/spell=22766/sneak

**Comment by miraco** [comment]
As we are trying to close of issues in wotlk-db can you please start refering to our issue tracker

**Comment by al3xc1985** [comment]
OK
