### ISSUE TITLE
hearthstone doesnot works(

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#437]
:(
well i cant get it.
Some of the characters have working hearthstone, and other has "cooldown starts upon leaving combat" how can i reset this warning on my char?

**Comment by rmzV** [comment]
https://github.com/cmangos/wotlk-db/issues/438
probably they are relative and have a common problem of cooldown resset(

**Comment by Grz3s** [comment]
jest tested it with new core... and works fine...
pls check with fresh compile

**Comment by rmzV** [comment]
i am on mangos-wotlk-with-ahbot-889acc04.zip
old chars that was not in use recently doesnot have this error.. and "used" chars have it(

**Comment by rmzV** [comment]
picture
https://dropmefiles.com/T3N74

**Comment by rmzV** [comment]
fixed by
https://github.com/cmangos/issues/issues/3038
