### ISSUE TITLE
Scarlet Commander Mograine fight

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#439]
https://www.wowhead.com/npc=3976/scarlet-commander-mograine

after you kill him first time, lady doesnot reset him... she just fight with you(

.go c id 3976

**Comment by rmzV** [comment]
@Grz3s can you look at this plz?

**Comment by AnonXS** [comment]
![grafik](https://user-images.githubusercontent.com/19734826/192769299-786edd68-5c00-4118-8e6e-688fa789a6a0.png)
![grafik](https://user-images.githubusercontent.com/19734826/192769315-555d3818-574d-4f03-8cf8-df03b49c0800.png)

works in tbcmangos

**Comment by rmzV** [comment]
i am a bit over geared so he can be killed by one shot.. does this creating this bug?

**Comment by AnonXS** [comment]
It should not, because that would mean that DeathPrevention() is bugged.

**Comment by Grz3s** [comment]
fixed
