### ISSUE TITLE
some quests and pointers

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#440]
- :x: https://classic.wowhead.com/quest=1109/going-going-guano
quest object shown in tirisfal glades, instead on pointing in dungeon location
- :x: https://www.wowhead.com/quest=3341/bring-the-end
same problem
- [x] i have a drop, but it hase to be ally quest?
https://www.wowhead.com/quest=2198/the-shattered-necklace

horge quest, must have this item as quest object?
https://www.wowhead.com/quest=2283/necklace-recovery

**Comment by Grz3s** [comment]
first 2.
Pois are correct(snifed values)-  if u check them they point places - inside instances. The only problem is fact that wotlk has no old continent instance maps... so those points point to nowhere.. If im correct they added them maps in cata.
you can see ppl commenting about that back in time:
```
By corvis9 on 2010/05/17(https://www.wowhead.com/quest=1109/going-going-guano (Patch 3.3.3)
For some reason the in game quest helper shows this as having a possible questing area just north of Deathknell in Tirisfal Glades. I've looked into the defined area, both in the cave and in the eerie undeveloped area on the surface. Nothing relevant to the quest there.
```
```
I had to do a double-take because the quest mentioned RFK specifically but showed a defined zone just outside Undercity. They're trying to fool our dependency on the in-game quest helper! :P
```

We may think about changing those pois to point instance entrance... but thats open discusion.

**Comment by Grz3s** [comment]
third:
Source `WowHead`
```Subject: "Explanation to the Horde about "your race can't do that""
There is a quest line for the Alliance that BEGINS with right clicking the necklace.  
This is why no Horde can right click it to begin a quest.  The quest line for the 
Horde is the one that BEGINS in Orgrimmar.
So don't worry, you will never be able to do that quest that it says it will give you 
("this item begins a quest" should be removed from the item on the horde side, imo).
There ya have it.```

What should be done... its fact that for Horde . item should only drop if u have quest accepted and not completed yet...  Will fix that

**Comment by rmzV** [comment]
okey)
"goblin commoner" in booty bay placed twice each(

**Comment by rmzV** [comment]
-[ ] https://classic.wowhead.com/npc=2420/targ
no npc in place..there are something like blue box instead of npc
part of quest 
https://classic.wowhead.com/quest=519/the-crown-of-will

**Comment by rmzV** [comment]
"item should only drop if u have quest accepted" i get this item dropped without quest. so it must be fixed?

**Comment by Grz3s** [comment]
> no npc in place..there are something like blue box instead of npc
> part of quest
![xxx](https://user-images.githubusercontent.com/2374069/176197142-f0fc29cd-e9aa-4de2-acf1-c491442ac415.jpg)
i see no issue there...
Pls recheck it again

**Comment by rmzV** [comment]
https://dropmefiles.com/20FUb

blue box again((

**Comment by al3xc1985** [comment]
aaa, that problem is core problem... I met the same problem in Icecrown zone.
Somehow the client gets bugged after I use some admin spells. Don't ask me what I used, and what I did.

@rmzV  Try this. 
Delete the wow cache... create a new char, just use the command to level him, and go visit the place.. For me it worked.
Also, if that doesn't do the thing, reinstall the db, delete cache and try again... this should work 99.99%

**Comment by rmzV** [comment]
display id 536
its strange: i was near npc and it transformed to a normal one(

**Comment by al3xc1985** [comment]
Role ta îs a visual bug

**Comment by rmzV** [comment]
well. i have a question: after i completed Horde quest about "shattered necklace", the item ("shattered necklace") drops again..((

**Comment by Grz3s** [comment]
https://youtu.be/WR83ILLEj4U

I cannot confirm what u said -- all conditions are set there

**Comment by rmzV** [comment]
hmmm. i will recheck with new core soon. may be i am on old one

**Comment by rmzV** [comment]
btw. can you check this please?
https://classic.wowhead.com/quest=2933/venom-bottles
according to link this quest must be possible to take at different places...
i found it only at 23/58

**Comment by rmzV** [comment]
necklace drop fixed. confirmed
