### ISSUE TITLE
Not a bug but....  Uldaman Archaedas Temple doors doesnot opens in gm mode

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#446]
To open doors leading to Archaedas, you need 3 peoples click on "Altar of the Keepers" 

as soon as i didnot have 3 peoples on my server i used ".gm on" command and open first doors on upper level with right click, 
then i go to the lower level and try to open lower doors with same trick, but it doesnot work.

is it possible to add option to lower level door at gm mode?

**Comment by AnonXS** [comment]
I think this was changed in wotlk to only require one person to click, something in go template or something.

**Comment by rmzV** [comment]
just tested, after a long "channeling" (i mean 5+ minutes, dunno if it normal),nothing happens((

**Comment by AnonXS** [comment]
works in tbcmangos if set to 1, something in core as this event is not scripted in DB 2228
![grafik](https://user-images.githubusercontent.com/19734826/180600845-9896441d-b5c3-4db9-a6b4-7b1003366781.png)

**Comment by rmzV** [comment]
hmm. wait a second, 
when i tested "Stone keepers" become alive too, 
after you kill them, is not door (with leads to lower level) must open automaticaly?

**Comment by AnonXS** [comment]
yes it opened.
![grafik](https://user-images.githubusercontent.com/19734826/180601312-e6fe2a5f-c5db-4830-b7b5-51677b192461.png)

**Comment by rmzV** [comment]
do you clean trash in the room?
well, i just teleported to coordinate you provide, doesnot kill trash and it worked. will recheck in next hour without trash mobs

**Comment by AnonXS** [comment]
Also works with gm on for me.
![grafik](https://user-images.githubusercontent.com/19734826/180601611-9b607cc8-e27a-43dc-87b8-0a71fa91d7f3.png)

**Comment by rmzV** [comment]
well its worked(( dunno why it failed first time((
