### ISSUE TITLE
Riddle quest chain not completed (probably tbc and classic affected)

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#447]
this quest can be completed:
https://classic.wowhead.com/quest=624/cortellos-riddle

after completion, scroll must start follow up:
https://classic.wowhead.com/quest=625/cortellos-riddle
and next scroll start following:
https://classic.wowhead.com/quest=626/cortellos-riddle

**Comment by Grz3s** [comment]
i dont know ... if you testing them quests or not...
Just went through whole q chain.. and everything works correct...
Only small issue was .. that for 1rst quest u have 3 random places for object to spawn... and we had them all spawned at once...
- so object has been added to spawn groups.. 

Can you explain me whats wron with it?

**Comment by rmzV** [comment]
i take the first quest from the boat at booty bay.. this quest leads me in swamp of sorrows to the "under the bridge scroll" i ended one quest but no following up quest was available https://classic.wowhead.com/quest=625/cortellos-riddle

**Comment by Grz3s** [comment]
![1](https://user-images.githubusercontent.com/2374069/180620592-bf08f2f0-4da3-4f50-a7ed-f31867b192a3.jpg)
![2](https://user-images.githubusercontent.com/2374069/180620598-4a8592bb-d0e4-4973-a1f9-96d26c418e30.jpg)
as u see followup quest is given correctly...
First make sure u have newest core and DB
Next remove all quests:
`.q r 626
.q r 625
.q r 624`
-- and recheck whole chain again...
Let me know result

**Comment by rmzV** [comment]
working. can be closed
