### ISSUE TITLE
quest relation

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#449]
https://wowwiki-archive.fandom.com/wiki/Quest:Horde_Trauma  <-first one
https://wowwiki-archive.fandom.com/wiki/Quest:Triage_(Horde)  <- leads up

currently i completed second quest without prequest(

**Comment by NeatElves** [comment]
There is no prequest
```sql
UPDATE `quest_template` SET `BreadcrumbForQuestId` = '6622' WHERE `entry` =6623;
```

**Comment by rmzV** [comment]
on classic
https://classic.wowhead.com/quest=6622/triage
on live 
https://www.wowhead.com/quest=6622/triage

**Comment by rmzV** [comment]
okey on wotlk page no dependencies
https://www.wowhead.com/wotlk/quest=6622/triage
