### ISSUE TITLE
The Battle for Arathi Basin!

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#450]
https://classic.wowhead.com/quest=8120/the-battle-for-arathi-basin#see-also

for some reason this quests doesnot dissapeared on completion, are they repeatable?

**Comment by Grz3s** [comment]
fixed in core

**Comment by AnonXS** [comment]
quick db query showed that wotlk db is missing a commit that sets maxlevel in quest_template for these quests.
