### ISSUE TITLE
Lost Thunderbrew Recipe

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#452]
https://www.wowhead.com/wotlk/quest=4134/lost-thunderbrew-recipe

quest item dropped and can be taken multiple times... probably character must have only one

**Comment by Grz3s** [comment]
it will happen only if you kill group `c.9541 Blackbreath Cronys` without looting each... and then start checking corpses one by one...
Its a quest item.. so as soon as you take one... another will not drop until you remove it from your inventory.

**Comment by AnonXS** [comment]
It's a core issue, item should be "reded out" in loot window and not be lootable.

**Comment by Grz3s** [comment]
so its global issue then.. .. not much can be done here anyway

**Comment by AnonXS** [comment]
we could rename and transfer the issue to /issues tracker.

**Comment by Grz3s** [comment]
better to create new... if u want to..
