### ISSUE TITLE
anvilrage reservist

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#453]
https://www.wowhead.com/wotlk/npc=8901/anvilrage-reservist
spawn too fast.. like 20sec cooldown

**Comment by Grz3s** [comment]
Wowhead:
`By Gunhaven on 2007/08/07 (Patch 2.1.3)

Has a respawn timer of 20 second, very, very nasty.`

https://www.wowhead.com/wotlk/npc=8901/anvilrage-reservist#comments
