### ISSUE TITLE
The Wrath of Neptulon

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#462]
https://www.wowhead.com/wotlk/quest=8729/the-wrath-of-neptulon

comment says:
"We completed this quest with a group of four lvl 70s: two feral druids (tank-bear and cat), a beast mastery hunter for Tranquilizing Shot, and a holy priest. The fight against [Maws](https://www.wowhead.com/wotlk/npc=15571) was very easy; guess it would be possible to do it with just a tank and a healer.

~36 hours after you complete the quest, you'll receive a letter with 100 gold from [Narain Soothfancy](https://www.wowhead.com/wotlk/npc=11811). Message reads as follows:
Champion,

The Blue Dragonflight believes that you are fated for greater things than even I could predict.

Despite what some would have you believe, our world needs heroes. In your darkest hour, when you face the blight of Kalimdor, recall the epic journies, trials, and tribulations that you undertook for an old gnome and let those memories lift your spirits.

Humbly,

Narain Soothfancy

P.S. Sorry about the repair costs."

now you got message after https://www.wowhead.com/wotlk/quest=8728/the-good-news-and-the-bad-news
without 36 hours cooldown and without gold

**Comment by rmzV** [comment]
also from comments
"After defeating Maws a world yell will appear stating "The beast returns from whence it came. The wrath of Neptulon has subsided." This is heard in old world and Outlands."

no i just killed MAws and no quest completion and no "stating"

**Comment by AnonXS** [comment]
Linked to https://github.com/cmangos/wotlk-db/commit/126a700a295fe25369239dbd34e24fca34a05a62#r83488966

**Comment by Grz3s** [comment]
so if you diggin in comments which is good ofc.. i suggest to check everything .. u may find more interesting info like:
```code
regarding quest 8729...
(Patch 3.0.2)
Actually it's not based on when you complete this quest, but the previous (or maybe on accepting this quest): I got this quest more than 2 months ago and received the mail with 100g some day later but still haven't completed it.
```

And here comments from quest 8728:
https://www.wowhead.com/quest=8728/the-good-news-and-the-bad-news#comments:id=519608

Regarding delay and loot ... will correct it.

**Comment by rmzV** [comment]
Drop Chance: 95.91%
https://www.wowhead.com/wotlk/item=21137/blue-scepter-shard

so thats can explain "no drop" on first time kill
