### ISSUE TITLE
Latest [TBC][WotLK], typo in cmangos_fixes\Spell.sql

### ISSUE THREAD

**Issue by NeatElves** [cmangos/wotlk-db#466]
file cmangos_fixes\Spell.sql, line:

>UPDATE spell_template SET RangeIndex = 0 WHERE Id IN (16613,16619,16630,16631);

There is no "0" value in **SpellRange.dbc** file)). Need to fix:

>UPDATE spell_template SET RangeIndex = **1** WHERE Id IN (16613,16619,16630,16631);

**Comment by killerwife** [comment]
https://github.com/cmangos/mangos-wotlk/commit/bcc878263b8dd49d8472c345e20ff5d233700bd6
