### ISSUE TITLE
Scholo

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#468]
There is a door leading to Janice barov? never see them before and why they closed?

scholomance students attack with no reason

**Comment by rmzV** [comment]
@Grz3s can you check doors plz?

**Comment by Ischtaratu** [comment]
confirmed:
Door stay closed, even all boss are killed, so no trigger to open door!
Testet on TBC Build eb86f02ad0d58ebe0d67cd65d0b7934b7cf9fd03 from 23/01/07
![WoWScrnShot_011223_194313](https://user-images.githubusercontent.com/6404203/212152618-5b9f6c82-9630-439d-9c9d-ba88e9712d5f.jpg)

**Comment by rmzV** [comment]
i belief in wotlk it was opened by default

**Comment by rmzV** [comment]
doors at scholo fixed
