### ISSUE TITLE
Items with wrong stas/name/procs

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#471]
-- Frostmourne

I believe this are the real stats or no? - custom!
https://www.wowhead.com/wotlk/item=33475/frostmourne
https://www.wowhead.com/wotlk/item=36942/frostmourne
![image](https://user-images.githubusercontent.com/6240049/234382517-4b63e185-2787-492b-b662-e996b5b3446e.png)

-- Glaive of the Defender - custom!
https://www.wowhead.com/wotlk/item=23051/monster-bow-raid-snake-zg
https://vanilla-twinhead.twinstar.cz/?item=23051
https://youtu.be/7FTufpZNPP0?t=314

This item should be a sword, and not a bow
Also reduces the dmg by 75%, and has different stas. It needs to be revised

-- Reins of Bengal Tiger
https://youtu.be/7FTufpZNPP0?t=1023
The mount should have  the part with races added, and from that info Tauren must not raid it

-- Monster bow raid snake Zg
This item is missing 2 and messed up with glaive of the defender
https://www.wowhead.com/tbc/item=23051/monster-bow-raid-snake-zg

**Comment by AnonXS** [comment]
Better we make it this <https://www.wowhead.com/tbc/item=23051/monster-bow-raid-snake-zg>

**Comment by al3xc1985** [comment]
Well this are nice items to have in game.

BTW thank you guys for keeping up the fantastic work u guys do. I am still backgrounding, not doing to much, cause u have a whole list of bugs to be fixed,.

**Comment by al3xc1985** [comment]
First post updated after the big update with new items

**Comment by AnonXS** [comment]
Data was added with bruteforce thx @celguar, any more adjustments become their own issues for discussions.
