### ISSUE TITLE
Resonating Crystal Formation

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#472]
https://wowpedia.fandom.com/wiki/Resonating_Crystal_Formation

found this one in barrens

probably they must spawn on event with no available at wotlk

**Comment by Grz3s** [comment]
... and You expecting Us flying around Barrens and search for it? .... 
PLS spend 30 secs more .. on creating correct ticked otherwise noone gona bother to even look at it.

**Comment by AnonXS** [comment]
https://github.com/cmangos/tbc-db/commits/master/Updates/0493_WDB-4308_war_effort_release.sql

**Comment by rmzV** [comment]
@Grz3s i just thought that it possible SELECT them in db completely:(

**Comment by rmzV** [comment]
barrens 53/35

**Comment by AnonXS** [comment]
location is correct, gets respawned by commits above. 
![grafik](https://user-images.githubusercontent.com/19734826/197883803-81a02de2-5508-45ba-a3a6-418434738d39.png)

**Comment by rmzV** [comment]
this event was remowedin wotlk? Aq oppenning?

46/68 packof kodos...may be they must move?

**Comment by Grz3s** [comment]
fixed...
`46/68 pack of kodos...may be they must move?` - will be added soon*
