### ISSUE TITLE
quests want remove

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#474]
https://www.wowhead.com/quest=11106/defender-no-more
https://www.wowhead.com/classic/quest=8333/medallion-of-station

i completed this quests earlier

but they are back in my quest log..

i removed them.. restart.. they appeared again

**Comment by rmzV** [comment]
https://github.com/cmangos/wotlk-db/issues/502

**Comment by Grz3s** [comment]
duplicte
