### ISSUE TITLE
Hot Fiery Death

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#477]
https://www.wowhead.com/classic/quest=5103/hot-fiery-death

placed twice

**Comment by AnonXS** [comment]
first time mc instantly cancelled.
second mc:
![grafik](https://user-images.githubusercontent.com/19734826/198830212-68654a7d-b6e4-4f06-95e5-70f5141d28eb.png)
after some attempts:
![grafik](https://user-images.githubusercontent.com/19734826/198830289-2f9827f3-2b2c-4f62-ab0e-c81b4299037b.png)
i'm not able to make it forged seal of ascension using Flame Breath (mc spell on emberstrife)

```
.go c id 10321
.q add 5103
open item in bag
hit emberstrife down to ~10%
use i.12323
use i.12300
use flame spell
profit
```

**Comment by rmzV** [comment]
https://www.wowhead.com/classic/object=176090/human-remains#starts

placed twice at blackrockspire, each of them have quest

**Comment by AnonXS** [comment]
![grafik](https://user-images.githubusercontent.com/19734826/198830516-4b23388d-c643-4041-a58b-4db4ddf910d9.png)
![grafik](https://user-images.githubusercontent.com/19734826/198830526-25b15846-6d98-4584-b942-f6aa76e65eda.png)

can be turned in fine in tbcmangos, some "leftover" quest items are not removed from player inventory confirmed in wow classic.
