### ISSUE TITLE
probably must be a series of quests

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#478]
https://www.wowhead.com/quest=27408/banner-of-the-stonemaul
https://www.wowhead.com/quest=27410/spirits-of-stonemaul-hold
https://www.wowhead.com/quest=27411/challenge-to-the-black-flight#

https://wowpedia.fandom.com/wiki/Spirits_of_Stonemaul_Hold

**Comment by NeatElves** [comment]
> 27... - Added in patch 4.0.3.13277

**Comment by rmzV** [comment]
Cataclysm [Patch 4.0.3a](https://wowpedia.fandom.com/wiki/Patch_4.0.3a) (2010-11-23): Updated for Cataclysm.
Bc icon.gif [Patch 2.3.0](https://wowpedia.fandom.com/wiki/Patch_2.3.0) (2007-11-13): Added.

https://wowpedia.fandom.com/wiki/Spirits_of_Stonemaul_Hold

maybe there are was another numbers for this quests?

**Comment by rmzV** [comment]
https://www.wowhead.com/tbc/quest=11160/banner-of-the-stonemaul
Once you complete this quest and [The Essence of Enmity](https://www.wowhead.com/tbc/quest=11161), you get [Spirits of Stonemaul Hold](https://www.wowhead.com/tbc/quest=11159).

https://www.wowhead.com/tbc/quest=11162/challenge-to-the-black-flight

**Comment by NeatElves** [comment]
UPDATE `quest_template` SET `PrevQuestId` = '11158', `NextQuestId` = '11159', `ExclusiveGroup` = '-11160' WHERE `entry` IN (11160,11161);
