### ISSUE TITLE
Lich king & Inspector Razuvious - Dk Starting Zone -

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#480]
Dunno since when, but they are missing. If u do a fresh DK u will not find them there at all to start your journey as a dk

**Comment by al3xc1985** [comment]
I did a fresh installation of the db and core. Latest till today

**Comment by al3xc1985** [comment]
so, @Grz3s , I get in this morning, and used the .gm on command to see if they are accidentaly moved to a different phase. but no luch

**Comment by al3xc1985** [comment]
ok, so I added them manually and all worked great!. Somehow, somewhere they were deleted

**Comment by al3xc1985** [comment]
even razouvious took this pathing and small events at once

**Comment by rmzV** [comment]
well,, some old quests, with worked earlier, bugged too.. dunno how it can happens(

**Comment by al3xc1985** [comment]
well, it is normal sometimes that at this scale project, and so many updates to get something bad.
I am just playing a little bit of everything. but not 2 serious, cause, I am waiting @Grz3s  to finish the whole northrend so we can get up and test everything all over, while he finishes the rest of bugs that he has on his list.

I see that we need a lot of patience here, and things will get very nice in the end.

Also I am willing to set up a private server on december, only for this kind of stuff, so whoever wish to join the fight to find bugs and report, and have fun in the same time while playing on a cmangos server, to be able to do that.

Honestly I dont know if there is any cmangos private server outthere. well see
