### ISSUE TITLE
Venture Co. Gemologist & Venture Co. Saboteur

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#484]
https://www.wowhead.com/tbc/npc=17279/venture-co-gemologist
https://www.wowhead.com/tbc/npc=17278/venture-co-saboteur

@AnonXS or @Grz3s  These 2 guys share the same ability from time to time, that deals 10 dmg. On wowhead comments I found that Saboteur is viable for that spell, but I could not find any for the Gemologist.

What made me thought about this think was that even thou they use same ability, the gemologist also has mana. And I was thinking if there is a different spell that he should have? or same as the gemologist?

My attent whent in this dirrection when I first saw that even thou the gemologist use ability, his mana does not decrease.

**Comment by AnonXS** [comment]
its torch spell, i either looked at it wrong or not will recheck.

**Comment by al3xc1985** [comment]
For saboteur I am 100% sure that is torch, but dunno for gemologist for sure

**Comment by AnonXS** [comment]
```
ClientToServer: CMSG_QUERY_CREATURE (0x0060) Length: 12 ConnIdx: 0 Time: 09/25/2009 18:46:40.000 Number: 683513
Entry: 17279 (17279)
GUID: Full: 0xF13000437F02EDF2 Type: Creature Entry: 17279 Low: 191986

ClientToServer: CMSG_QUERY_GAME_OBJECT (0x005E) Length: 12 ConnIdx: 0 Time: 09/25/2009 18:46:40.000 Number: 683514
Entry: 181920 (181920)
GUID: Full: 0xF11002C6A000075A Type: GameObject Entry: 181920 Low: 1882

ServerToClient: SMSG_AURA_UPDATE_ALL (0x0495) Length: 16 ConnIdx: 0 Time: 09/25/2009 18:46:40.000 Number: 683515
GUID: Full: 0xF13000437F02EDF2 Type: Creature Entry: 17279 Low: 191986
[0] Slot: 0
[0] Spell ID: 5680 (5680)
[0] Flags: 9 (EffectIndex0, NotCaster)
[0] Level: 7
[0] Charges: 0
```

**Comment by al3xc1985** [comment]
yes, same spell they share
Ty 

I will close this one
