### ISSUE TITLE
Testing the Vessel!!!! probably classic and tbc affected too

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#485]
quest:
https://www.wowhead.com/classic/quest=3123/testing-the-vessel

has goals of this quest:
https://www.wowhead.com/quest=25336/testing-the-vessel

with is no wotlk quest

https://dropmefiles.com/BahTP

**Comment by Grz3s** [comment]
`
This quest was changed in 3.2. He no longer asks you to get wildkin muisek. He now sends you just north of Camp Mojache to get "Beast Muisek" from Ironfur bears and Longtooth runners. The wildkin version of this quest no longer exists; the followup is still to gather Hippogryph muisek.
`
Closed

**Comment by rmzV** [comment]
@Grz3s can you check this quest please?
i killed bears and use vessel on them but it doesnot works,(

**Comment by Grz3s** [comment]
Fixed here:
https://github.com/cmangos/mangos-wotlk/pull/410/commits/698a6d64a9d4c0598623e8ca3f0c684f1362e185

Will be added soon*

**Comment by rmzV** [comment]
thx
