### ISSUE TITLE
Bugged quests in Northrend starter zones

### ISSUE THREAD

**Issue by ReneM** [cmangos/wotlk-db#487]
All quests have been tested on latest Core and Database versions (as of the date of this post).

| Zone | Quest link  | Issue |
| ----------| ------------- | ------------- |
| Borean Tundra | https://www.wowhead.com/wotlk/quest=11637/kaganishu | The item (Fetish) used on the quest NPC seems to work (NPC says his line as well), but no credit is given|
| Borean Tundra | https://www.wowhead.com/wotlk/quest=11969/springing-the-trap | Doesnt give credit towards quest after the scenes - script seems to work (altough it bugs out at times - agros random drakes or gets frozen the second it spawns)|
| Borean Tundra | https://www.wowhead.com/wotlk/quest=11711/coward-delivery-under-30-minutes-or-its-free | Alliance NPC can be spawned and will ride and gesture (Script working?), but never gives credit towards quest|
| Borean Tundra | https://www.wowhead.com/wotlk/quest=11611/taken-by-the-scourge  | No NPCs seem to be inside the webs - killed ~100 with nothing inside the webs |
| Borean Tundra | https://www.wowhead.com/wotlk/quest=11640/words-of-power | High Priest Naferset doesnt become attackable when killing his Necromancers, see [this video](https://youtu.be/lcnNPKX9tIU?t=264) for how its supposed to go. |
| Howling Fjord | https://www.wowhead.com/wotlk/quest=11282/a-lesson-in-fear | The banner can be used on the named NPCs corpses, no quest credit given|
| Howling Fjord |https://www.wowhead.com/wotlk/quest=11519/the-lost-shield-of-the-aesirites  | Seems unfinished? Boat cant be boarded (without flight). Captain Ellis isn't aboard the boat (no NPCs at all) to finish the quest and give the followups|

**Comment by Grz3s** [comment]
https://www.wowhead.com/wotlk/quest=11282/a-lesson-in-fear
Fixed in core:
https://github.com/cmangos/mangos-wotlk/commit/dbe6bb966940a32ecf28636876bfdb1d58cac2fe

**Comment by Grz3s** [comment]
https://www.wowhead.com/wotlk/quest=11519/the-lost-shield-of-the-aesirites
`
Seems unfinished? Boat cant be boarded (without flight). Captain Ellis isn't aboard the boat (no NPCs at all) to finish the quest and give the followups
`
they were all populated...  prob smth happened in core... that theyre not spawned anymore...  (DB data for them is still there)

**Comment by rmzV** [comment]
@Grz3s is not there was a problem, to place NPC on boat and  in this case this NPC was placed someone near...

**Comment by ReneM** [comment]
I've been retesting the fixed quests and can confirm that the following are now working:
* https://www.wowhead.com/wotlk/quest=11637/kaganishu
* https://www.wowhead.com/wotlk/quest=11969/springing-the-trap (script also seems to work a lot better, except for the fact she started fighting random mobs when landing after the flight - see attached screenshot)
* https://www.wowhead.com/wotlk/quest=11711/coward-delivery-under-30-minutes-or-its-free
* https://www.wowhead.com/wotlk/quest=11611/taken-by-the-scourge
* https://www.wowhead.com/wotlk/quest=11640/words-of-power


![image](https://user-images.githubusercontent.com/483707/201440545-4db917cb-e4f7-4506-9d88-c6e8e81135b9.png)

**Comment by Grz3s** [comment]
> @Grz3s is not there was a problem, to place NPC on boat and in this case this NPC was placed someone near...

all transports should work by now... we populated them some time ago.. 
anyway: .. issue was confirmed and fixed by killerwife in core..

**Comment by ReneM** [comment]
Just tested https://www.wowhead.com/wotlk/quest=11519/the-lost-shield-of-the-aesirites again - the NPCs are there now :)

There's a few problems left with the quest:
There's no way to get up on the ship, without flying (from current core/db):
![image](https://user-images.githubusercontent.com/483707/201480655-0e454552-8fc2-427b-b98d-73191bab9436.png)

There's supposed to be a ladder (taken from [Youtube](https://www.youtube.com/watch?v=Px62tha23hM)):
![image](https://user-images.githubusercontent.com/483707/201480885-ea0ac031-8f45-448c-ae20-b790a5f734c9.png)

The follow up quests are somewhat buggy too (the last one in the chain seem incompletable), but I can open up a new ticket for those if you prefer :)

Overall, all quests are completable now, and ticket can be closed 👍

**Comment by Grz3s** [comment]
i did some improvements to https://www.wowhead.com/wotlk/quest=11969/springing-the-trap
- so all issues there should be fixed by now (also fixed that werid flying anim of hers)

`There's supposed to be a ladder`
these is... in gm mode :) .. i simply couldnt sync it with ship (npcs on transports were not working back then)
leave it open ..ill fix it - then we'll close it ;)

**Comment by Grz3s** [comment]
`There's supposed to be a ladder` - fixed

**Comment by ReneM** [comment]
I can confirm that every quest on the list is now working :)
The ladder is a bit descyned from the boat (at least on my server), but that's a non-issue in my mind:
![image](https://user-images.githubusercontent.com/483707/202869451-e24154db-6bbe-44f8-b40c-8b79ed2dd75b.png)

The followup quest https://www.wowhead.com/quest=11529/sorlofs-booty is bugged, but I've created [a different issue](https://github.com/cmangos/wotlk-db/issues/492) for that one.
Thanks for the hard work you're doing @Grz3s :D
