### ISSUE TITLE
Hungry, Hungry Hatchling

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#490]
https://www.wowhead.com/quest=13889/hungry-hungry-hatchling

does not work.. cant feed meat to the pet

**Comment by rmzV** [comment]
@Grz3s after meat feded to pet, no completion mark appeared.((
Can you check this please?

**Comment by Grz3s** [comment]
![dsada](https://user-images.githubusercontent.com/2374069/203024602-8792500c-c703-4369-abbf-10a555e947b6.jpg)

This is `Daily quest` .. so if not done in same day... You will not be adle to complete it next day (if another quest is given)
You can wait .. when it becomes available again... or delete it.. and do currently provided one...

Question to @killerwife @AnonXS .. how Dailys work on blizz? ... are they stay in players quest log or should be removed if not done in same day ??

**Comment by evil-at-wow** [comment]
Daily quests you still have when at the daily reset just stay in your player quest log, and you can complete them whenever you want. Of course, as long as you have an 'old' one in your quest log, you can not get (and thus complete) any other. This includes other players of your group picking up the one for 'today', and trying to share it with you (sharing does not work unless you remove the old one first). If you hand in an old one from your log, that's it for today and you won't be able to get another one until after the reset.

Essentially the system is pretty simple to summarize:
* You can get/have at most one quest of the daily set in your log at any time.
* You can turn in at most one quest of the daily set on any given day. As a result, after turning one in, you can't get another one that same day.

**Comment by Grz3s** [comment]
then current system in cmangos is wrong :)
