### ISSUE TITLE
Ardent Guard Sword

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#491]
https://www.wowhead.com/wotlk/item=48044/ardent-guard

When u try to equip it u can not "Item can not be equiped"

**Comment by Grz3s** [comment]
![dwad](https://user-images.githubusercontent.com/2374069/202307438-202ac94f-e7ef-4523-8ac5-ce499c18ec73.jpg)
Yo're Horde - right? and ca n use swords - right?

**Comment by al3xc1985** [comment]
my bad @Grz3s is only for horde, and I am alliance. I didn't noticed that. Ty
