### ISSUE TITLE
pack of not mooving animals

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#496]
- [x] barrens 51/32pack of gazelle's
- [ ] silithus 24/45 cenarion outrider
- [ ] silithus 69/36 cenarion outrider

**Comment by Grz3s** [comment]
finally was able to check it on official ... and gues what.. they do exact the same there (just standing)
![WoWScrnShot_052823_220744](https://github.com/cmangos/wotlk-db/assets/2374069/b1bfaa3c-e7b9-4c54-a58a-54dda456e2a2)
![WoWScrnShot_052823_223215](https://github.com/cmangos/wotlk-db/assets/2374069/54ca9d58-9a81-450b-b438-f6a12c7b9d46)
Closing it as complete
