### ISSUE TITLE
Spell entry 41975

### ISSUE THREAD

**Issue by apo126** [cmangos/wotlk-db#50]
Spell entry 41975, effect 0 has EffectImplicitTargetA/EffectImplicitTargetB = TARGET_SCRIPT, but creature are not defined in `spell_script_target`

**Comment by Grz3s** [comment]
`Id: 2 (SPELL_EFFECT_SCHOOL_DAMAGE)
BasePoints: 5088 to 5913
Targets: (38, 0) (TARGET_UNIT_SCRIPT_NEAR_CASTER, TARGET_NONE)`

So this should fix issue..

**Comment by Grz3s** [comment]
sor my bad :)

**Comment by AnonXS** [comment]
```
-- Black Temple
-- Ashtongue Defender 23216 - Heroic Strike only on npc target?
('2321603','23216','0','0','100','1025','11000','16000','13000','17000','0','0','11','41975','5','0','0','0','0','0','0','0','0','0','Ashtongue Defender - Cast Heroic Strike'),
```

 i think i didnt find this spell atall in sniffs related to this mob, but i didnt want to be too hasty to remove old data from it.
