### ISSUE TITLE
Hogger

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#500]
As far as I remember he should have waypoints and move around . He currently stays in one place with random walk near his spawn point

https://www.wowhead.com/classic/npc=448/hogger

**Comment by Grz3s** [comment]
Hogger has few random spawns with randomovement on WoTLK. ..
Thx to @killerwife for checking it.

**Comment by al3xc1985** [comment]
ok, ty

**Comment by al3xc1985** [comment]
I believe @Grz3s that we have them in db added, is it?

**Comment by al3xc1985** [comment]
maybe we have them implemented but I was unlucky to find him on the same spot

**Comment by Grz3s** [comment]
`.npc info` will show you if he is part of `Pool: xxxx` or new "spawn_group` system... 
He has 5 spawn locations in WoTLK
