### ISSUE TITLE
Warsong Outrider Update

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#502]
somethig wrong with this, i complete quest but he appeared again in my log
https://www.wowhead.com/wotlk/quest=6546/warsong-outrider-update

**Comment by rmzV** [comment]
removed from the log, restart game and quest are in log again((

**Comment by Grz3s** [comment]
looks like core issue...

**Comment by rmzV** [comment]
same with
https://www.wowhead.com/wotlk/quest=8333/medallion-of-station
https://www.wowhead.com/wotlk/quest=11106/defender-no-more

**Comment by Grz3s** [comment]
its confirmed ..and affects many quests... pls list them here .. if any more found - it req core FIX.
@killerwife  knows about it... and will try to find whats wrong.

**Comment by rmzV** [comment]
https://www.wowhead.com/wotlk/quest=1707/water-pouch-bounty

https://www.wowhead.com/wotlk/quest=8242/restoring-fiery-flux-supplies-via-heavy-leather
probably other given by this npc affected too

**Comment by rmzV** [comment]
this is not acceptable bag. with ruins the game.
if you remove one of this quests and get quests up to 25/25 it will remove random quest and replace with one of this broken ones

**Comment by killerwife** [comment]
Commit that fixes the origin linked, here is query that needs to be applied to server when its offline to fix it.

DELETE a FROM wotlkcharacters.character_queststatus AS a where a.rewarded=0 AND EXISTS(SELECT b.entry FROM wotlkmangos.quest_template b WHERE a.quest=b.entry AND b.Method=0);

**Comment by rmzV** [comment]
@killerwife thankyoufor fix will test it recently

**Comment by rmzV** [comment]
as now , fixed=)

**Comment by rmzV** [comment]
@killerwife  i need some help

after your script seems all start working fine,
but i have two quests:
https://www.wowhead.com/wotlk/quest=8333/medallion-of-station
https://www.wowhead.com/wotlk/quest=11106/defender-no-more

with still doesnot work, i think its local bug
ill trying to delete both ->restart-> they appear again
ill trying to complete again both->restart-> they appear again

how can i fix this problem quests((

i also tryed deleting and completing them before fix too if it matter

**Comment by rmzV** [comment]
when i talk to
[Aurel Goldleaf](https://www.wowhead.com/wotlk/npc=15282/aurel-goldleaf)

quest  have yellow mark
https://www.wowhead.com/wotlk/quest=8333/medallion-of-station
but i dont have required items for quest completion

https://dropmefiles.com/IrIg1

**Comment by rmzV** [comment]
false positive=)
but
https://www.wowhead.com/quest=12677/hazardous-materials
i have "[Drakuru's task complete](https://www.wowhead.com/npc=28762/drakurus-task-complete)"  5/1 at start

**Comment by Grz3s** [comment]
@rmzV You messed up with addin quests via `.q a xxx` ... and now you got what u got.
Let me explain you:
You will never see this quest available until:
- you'll get 3000 rep for faction 609 that first ... 
- then you need to finish 2 pre quests.. where one `https://www.wowhead.com/wotlk/quest=8332/dukes-of-the-council` - is exact the same quest to the one you have problem with... with 1 important diff... Its not repeatable.. and finishing it will lead you to Your quest. 
Now:
You will never be able accept it... koz its only completing in case if you have items already.. and YES it shows correctly Blue mark:
![adawd](https://user-images.githubusercontent.com/2374069/214200146-ca63a882-50db-4640-9f25-7fe2f272308a.jpg)

Only solution for you here,, is to remove all 3 quests in reverse order using
1.`.q r 8333` 
2.`.q r 8332` 
3,`.q r 8331`
4,`.m rep 609 100` - must have your char selected
Shut down server
Then run KW's solution again:
```Commit that fixes the origin linked, here is query that needs to be applied to server when its offline to fix it.

DELETE a FROM wotlkcharacters.character_queststatus AS a where a.rewarded=0 AND EXISTS(SELECT b.entry FROM wotlkmangos.quest_template b WHERE a.quest=b.entry AND b.Method=0);
```

Login You char & go step by step:
`.m rep 609 3000` - must have your char selected
`.go c id 15282`
`.q a 8331` - yelow ? should appear above her head... just finish it...
next Quest should appear. https://www.wowhead.com/wotlk/quest=8332/dukes-of-the-council - take it
`.q c 8332` - return to her and finish it
From now repeatable quest should become available... and shouldnt give you any troubles anymore. 

And PLs if u want to play with manualy addin/removing quests ... do it right. And avoid issues like `5/1 task complete` in prev ticket. - which was using `.q a xxxx` 5 times without removing any ...
GL

**Comment by rmzV** [comment]
"next Quest should appear. https://www.wowhead.com/wotlk/quest=8332/dukes-of-the-council - take it"
it says requirements not meet and dissapiared.
ill restarted game and bad quests are in place again.

"And avoid issues like 5/1 task complete" i thought that if i use "quest add command" it creates single line in database, and second use just change this line.

**Comment by rmzV** [comment]
i understand that it waste of time for you.
but:
1) as i recall i use add quest only in zul'drak, couse i havent any quests to continue testing this quest chain.
and i didnot see this quest five times in my log=) this will explain me my error
2) completely new char (without quest add) have another problems with this two quests.

3) i did a new try with:
.q r 8348  --followed up quest
.q r 8349  --followed up quest

.q r 8333
.q r 8332
.q r 8331
.m rep 609 100

server shutdown, fix applied , server start up and this quest are again in my log=(
i removed him in game and did a second try on second part ,now couse i removed 8349 and 8348 quest
https://www.wowhead.com/wotlk/quest=8332/dukes-of-the-council
was available

did entire chain, restart game and bad quest are in place again.

**Comment by rmzV** [comment]
can you please explain one thing tome:
quest dependence for this quest is "You must first complete N [60] [Dukes of the Council](https://wowwiki-archive.fandom.com/wiki/Quest:Dukes_of_the_Council)."
as soon as removed all of this:
.q r 8348 --followed up quest
.q r 8349 --followed up quest

.q r 8333
.q r 8332 - Dukes of the Council 
.q r 8331


how that can be possible that 
https://www.wowhead.com/wotlk/quest=8333/medallion-of-station
placed in my log every remove and restart?

**Comment by rmzV** [comment]
the fix is:
remove 
.q r 8348 --followed up quest
.q r 8349 --followed up quest

.q r 8333
.q r 8332 - Dukes of the Council
.q r 8331
.m rep 609 100

they shutdown server.
go to table "character_queststatus"
look for 8333 (guid = char id)  but surpraisly only one char with problem has this quest in log.
remove this string

return to game and everything become fine

**Comment by Grz3s** [comment]
You not wastin my time... im glad that you reporting issues.
IM only explaing what we have here...
To summary:
- You should never ever have quest 8333 in your quest log..  Quest offer you only complete option (theyre no detail and accept for it) - so thats why i know you added it manualy.
`go to table "character_queststatus"
look for 8333 (guid = char id) but surpraisly only one char with problem has this quest in log.`
- this is what KW's script does.. so You sain doing it manualy fixes issue.. and running script not. (strange)

**Comment by rmzV** [comment]
KW script fixed all other problem quests except this two.
i am not using "Q add" often as my main testing shredule:

zul'draki can recall for sure, and probably two of this, but i cant remember..it was like year ago(

**Comment by MilkmanMHOC** [comment]
Im getting reports of the warsong quest in Classic also not being removed. Not sure if this is was backported not yet?  Also unsure if the manual fix for this will work in classic as well?
