### ISSUE TITLE
Mob that has a wrong game event

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#503]
Wronge gameevent

![image](https://user-images.githubusercontent.com/6240049/204903923-5e8e70bb-4c8c-46e5-9704-ac9b40db9df1.png)

**Comment by al3xc1985** [comment]
![image](https://user-images.githubusercontent.com/6240049/204904321-5da0c49b-3640-4132-b1cf-39f7b405ed56.png)

**Comment by al3xc1985** [comment]
![image](https://user-images.githubusercontent.com/6240049/205430426-a4825bc6-49c9-4f0a-b611-807e2a5c2b34.png)

**Comment by AnonXS** [comment]
Seems to be all the same type (entry) so query against the id.

**Comment by NeatElves** [comment]
```sql
INSERT IGNORE INTO `game_event_creature` (`guid`, `event`) SELECT `guid`, 1 FROM `creature` WHERE id in (26401);
```

**Comment by al3xc1985** [comment]
yeah I didn't checked all the zones, cause I am slow leveling and testing all up again as much as I can. But that is the solution to find them all by querry
