### ISSUE TITLE
Quest unavailable to draenei?

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#504]
https://www.wowhead.com/wotlk/npc=491/quartermaster-lewis 
he should give u the quest 
https://www.wowhead.com/wotlk/quest=6181/a-swift-message

but as a draeneim, I don't receive that

Is that the right way?

**Comment by AnonXS** [comment]
![grafik](https://user-images.githubusercontent.com/19734826/204907771-ea4e3bab-f209-48c4-98c4-023284a7c03e.png)

**Comment by NeatElves** [comment]
Only human.
Draenei version : https://www.wowhead.com/quest=9603/beds-bandages-and-beyond
p.s. Study sources carefully

**Comment by al3xc1985** [comment]
than it's ok. ty
