### ISSUE TITLE
Justin Roman & Bradon

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#505]
They stay all in one place over there and talking. 3 guys in the same spot. I believe they should be splitted
![image](https://user-images.githubusercontent.com/6240049/205223914-5a6530ec-1385-45ac-8877-fb9d13596b0c.png)

**Comment by al3xc1985** [comment]
I see them fixed. Dunno when!. But it's fine

**Comment by Grz3s** [comment]
https://github.com/cmangos/wotlk-db/commit/ae78e409039e021b1e10f467a5ae0a84046fbddf

**Comment by al3xc1985** [comment]
I knew it, that I saw that update. Ty Great One!
