### ISSUE TITLE
Sethir and his minions

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#507]
https://www.wowhead.com/wotlk/npc=6911/minion-of-sethir#comments
https://www.wowhead.com/wotlk/npc=6909/sethir-the-ancient#comments

They are 3 minions and sethir in the same spot. They should not share the spot

According to wowhead, they have more points on the map in the same area. Is it possible that they would have waypoints and a special formation in wich they stand?

Obviously they should not be in same point sapwned

**Comment by al3xc1985** [comment]
some info can be found on
https://www.wowhead.com/wotlk/npc=7319/lady-sathrah#comments
about them. They are like 5 minions (at some point some is saying) and cam from now where. Invisibility? and more spawns than 3 that we currently have?

**Comment by Grz3s** [comment]
He is part of Rogue quest... and yes he has waypoints... and no adds spawned nex to him:
He summons his minions on aggro.. you can see in his EAI
