### ISSUE TITLE
Quest 10588 The Cipher of Damnation

### ISSUE THREAD

**Issue by killerwife** [cmangos/wotlk-db#51]
select * from creature_template where entry IN(21685,21687,21686);

These three NPCs have wrong stats. 

UPDATE creature_template SET MinLevel=70,MaxLevel=70 WHERE entry IN(21685,21687,21686);
UPDATE creature_template SET MinLevelHealth=20250,MaxLevelHealth=20250 WHERE entry=21685;
UPDATE creature_template SET MinLevelHealth=16200,MaxLevelHealth=16200 WHERE entry=21686;
UPDATE creature_template SET MinLevelHealth=55888,MaxLevelHealth=55888 WHERE entry=21687;

This is minimal fix but likely requires more.
They are also missing Equipment Templates.

Also at the end of the script in SD2 the three heroes do not fly away on wyverns. I can add this if someone gives me mount ID or spell id for the wyverns.

http://www.wowhead.com/quest=10588/the-cipher-of-damnation
https://www.youtube.com/watch?v=dn9Yuy00hZg - can see it at the end in the video

@Grz3s Sorry, gotta rely on your help once again :)

**Comment by Grz3s** [comment]
im planing to ... fix all stats in future.. 
but will look at this soon*

**Comment by killerwife** [comment]
@Grz3s The script is done in SD2 for ages and from what I can tell its done well. (i went to bed, saw your reply on IRC). I only slightly changed it, so that we use an unused text and so that the encounter does not bug out. To properly finish it we need Movement Formations for the trio and add the wyvern thing at the end. If you are interested in adding that yourself to SD2, I can give you my changes so you can add those and finish whatever you want. Let me know. (cos i dont see them being merged anytime soon.
