### ISSUE TITLE
Captain Greenskin - Aggro Range

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#510]
https://www.wowhead.com/wotlk/npc=647/captain-greenskin

Many npc from Deadmines were modified to aggro range and ALL is perfect, but Captain Greenskin can be aggroed from here (se the image) if u ever stay there and he passes near that part of the boat he is aggroed
![image](https://user-images.githubusercontent.com/6240049/205466185-b9e86643-e197-4053-85ae-00a04a1cc31c.png)

**Comment by AnonXS** [comment]
Retest after aggro radius reduction. not sure if you cant aggro him at all from the lower deck.

**Comment by al3xc1985** [comment]
latest db release still happening.
BUT as u said that might be normal.. dunno

**Comment by Grz3s** [comment]
and this is a question or its a bug that u know it shouldnt happen?
Pls also take part of checking stuff .. like go and watch old vids .. and maybe you will find proof or smth.
Dont expect that... (you will say smth that in your opinion: maybe should/shouldnt happen) .. and every dev will jump to check sniffs vids etc.. 
`latest db release still happening.` - again where is proof that this situation is wrong?

**Comment by MilkmanMHOC** [comment]
i remember in making sure we didn't go up the ramp while they were on same side of boat because they would sometimes pull back in original classic (2005ish?).

**Comment by al3xc1985** [comment]
I could not find any Grz3s. I took it as a bug like it was with the other mobs radius problem that was fixed.
Ty milkman for helping with this. Closing it!
