### ISSUE TITLE
Betrayed

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#513]
https://www.wowhead.com/wotlk/quest=3506/betrayed

activate one crystal, killed guard and nothing

**Comment by NeatElves** [comment]
Work

> Tip for high levels:
> If you are doing this quest at a high level, don't just one hit the [Blood Elf Defender](https://www.wowhead.com/?npc=8581) which eventually spawns from the crystal or else he won't call for [Magus Rimtori](https://www.wowhead.com/?npc=8578) and you will have to wait for the crystal to respawn.

**Comment by rmzV** [comment]
well killed npc as normal but no summon

**Comment by AnonXS** [comment]
Currently, you only get her to spawn if you are lucky enough to have a bloodelf npc spawn instead of a infernal, this bloodelf npc will then summon her when you hit her below 50% hp (could be safeguarded by setting npc invincible until this action is executed)

![grafik](https://user-images.githubusercontent.com/19734826/209468558-b5fbbd35-fbfd-44ff-bcf6-4f8aa01d29de.png)

50% to spawn the bloodelf <https://github.com/cmangos/tbc-db/commit/9667269f1e0e5e10f4c23b47c08a2e8a1959cf7d#diff-3e86790c612f9f2921c8256576a7703bbdf8b14d2c66b439795a454512dc6feaR13>

**Comment by rmzV** [comment]
well it explains, but tryed 3+ times and only elemental spawns(

**Comment by AnonXS** [comment]
I also find it strange that you click one crystal, then you have 50% to get the wanted elf to spawn and after 12.5secs all crystals despawn for ~1min so you have 50% per minute to get the right npc to spawn, seems strange.

**Comment by rmzV** [comment]
Can you reopen this ticket7

**Comment by miraco** [comment]
> Can you reopen this ticket7

Why? Its not buged, its just the way it should be. Just tested this on wotlk classic, you click on the crystal and it spawn a infernal or a blood elf. Did it 10 times now, and it was 5 blood elfs 5 infernals.

**Comment by AnonXS** [comment]
do all crystals despawn when you click one?

**Comment by miraco** [comment]
Yes they despawn all.

**Comment by AnonXS** [comment]
thanks for confirming and they respawn after 1min?

**Comment by miraco** [comment]
The way blizzard does it seems to be like this.

Elf/Inferal = 1 spawn_group
If you click crystal, worldstate for this spawn_group gets changed to true so the elf/inferal "spawns". Cant spawn multiple npcs even if you try to click all 3 crystals before they despawn. (Despawn ~10 secs after clicking one of them).

Same for the quest npc = 1 spawn_group
If elf has x% ) worldstate sets true and quest npc "spawns". If he already got killed before he doesnt spawn cause of respawn time)

Crystals cant be clicked if you have the quest item in back.

Here is a video from it with timers:
https://youtu.be/qB_e1vgWXyE 

Btw there is also a rare that can spawn here "Magister Hawkhe".
