### ISSUE TITLE
Spirit of Azuregos

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#514]
https://www.wowhead.com/classic/npc=15481/spirit-of-azuregos#comments;mode:normal

is not he must give q item for scpeter quest chain?

**Comment by Grz3s** [comment]
![wfewu](https://user-images.githubusercontent.com/2374069/206903265-c81b6e00-68d2-4b9f-8c5c-6981870e1f89.jpg)
Could You be more specific??? 
i went to this guy and got item without any issues .... 

To be able to talk to this guy u need fufill these conditions:
```(Player Has Less Than 1 of Item ID 20949 in Inventory/Bank AND Quest ID 8555 Rewarded)```

**Comment by rmzV** [comment]
well i dont have 8555 completed.

can be closed then(
