### ISSUE TITLE
Rescue From Jaedenar

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#516]
https://www.wowhead.com/wotlk/quest=5203/rescue-from-jaedenar
after qustd completion npc runs back in cage and the enemies kills him

**Comment by Ischtaratu** [comment]
half confirmed:
Quest runs in an endless loop!

After Arko'narin has been successfully escorted once and the quest gets its 100% Compleet status, Arko runs back to her prison and the quest starts again. She runs to the box, grabs her clothes (which she already has on) and runs out a second time.

Completed the quest 3 times in a row.

The quest can be finished, but Arko's script has no end ! (except when she dies)

**Comment by Ischtaratu** [comment]
had start new issue on right place !
https://github.com/cmangos/issues/issues/3277

/close

**Comment by AnonXS** [comment]
https://github.com/cmangos/issues/issues/3277
