### ISSUE TITLE
missed item 

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#518]
https://www.wowhead.com/wotlk/object=176213/blood-of-heroes

missed or not enought items..i found 0

**Comment by AnonXS** [comment]
https://github.com/cmangos/classic-db/commit/95bce412914b59b26752c84e0b08ee9608b84266
https://github.com/cmangos/tbc-db/commit/1792c3436f68c3081f4dbb696aa340da3d51fe2a

**Comment by rmzV** [comment]
can you recheck?none found

**Comment by AnonXS** [comment]
6/7 in EPL WPL will check maybe its spawn group

**Comment by AnonXS** [comment]
Checked already first 4 guids had 2 nodes spawned. (guids range from 57072 to 57229) only 7/8 are up at a time in WPL/EPL.
