### ISSUE TITLE
Aurel Goldleaf

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#519]
to check
npcs have
https://www.wowhead.com/wotlk/quest=8333/medallion-of-station

where are other quests to sumn dukes?
https://www.wowhead.com/wotlk/quest=8331/aurel-goldleaf

**Comment by Grz3s** [comment]
and you checked this right?
`You can only do this quest if you have friendly status with the Cenarion circle`

**Comment by rmzV** [comment]
yes im friendly

just trying to find this quests with reward
https://www.wowhead.com/classic/item=20451/twilight-cultist-ring-of-lordship#reward-from-q

**Comment by Grz3s** [comment]
sor you had to be `To see this quest you must be at least revered with Cenarion Circle.`
corrected + wrong prev q removed

**Comment by rmzV** [comment]
thank you
