### ISSUE TITLE
Treant Muisek

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#527]
https://www.wowhead.com/classic/quest=3126/treant-muisek

only one treant available?

**Comment by AnonXS** [comment]
We've all ~5 spawns "Wandering Forest Walker". . . https://www.wowhead.com/classic/npc=7584/wandering-forest-walker

guids  50797 50798 50799 50800 50801

**Comment by rmzV** [comment]
ok,can beclosed
