### ISSUE TITLE
Pusillin

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#528]
https://www.wowhead.com/classic/npc=14354/pusillin

after activation you must start to follow him, after you catch him first time it has no option to continue

**Comment by AnonXS** [comment]
I suggest removing this dbscript on gossip from instance file as it uses conditions that are used in other scripts too and conditions dont seem to align.

**Comment by AnonXS** [comment]
![grafik](https://user-images.githubusercontent.com/19734826/213868192-a11de282-d9d6-4801-9b5e-efd8197afd47.png)
![grafik](https://user-images.githubusercontent.com/19734826/213868245-6eacf6dc-6cbd-4cd1-b829-0067ad13b4b4.png)
![grafik](https://user-images.githubusercontent.com/19734826/213868307-b0be738d-11f4-4e45-bb87-f099fe12bd22.png)
![grafik](https://user-images.githubusercontent.com/19734826/213868351-6edfd983-a7bd-46a6-90c1-ff53d0ba7077.png)
![grafik](https://user-images.githubusercontent.com/19734826/213868393-5c32af9e-5a06-4aed-aff0-9500e266011e.png)
![grafik](https://user-images.githubusercontent.com/19734826/213868397-c12683e9-55cc-4cc5-8444-34e75255bc51.png)

gossipmenu text adjusted too. frostmourne for maximum flex.
