### ISSUE TITLE
The Calling

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#531]
https://www.wowhead.com/classic/quest=8315/the-calling

after previous quest "[Unraveling the Mystery](https://www.wowhead.com/classic/quest=8314/unraveling-the-mystery)"

this new one no available, because you dont meet requirements.

https://wowwiki-archive.fandom.com/wiki/Quest:The_Calling

**Comment by Grz3s** [comment]
8315 becomes available after 8314 finished
Reason why it didint work... was that 8314 had flag repeatable, so req. for it finished .. would never happen. (now its fixed)

**Comment by rmzV** [comment]
ineab "retake 8314"and answer is yes.

tested and everything works fine.
