### ISSUE TITLE
Greater Windstone (silithys)

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#532]
can you check please if it realy random?

have 
https://www.wowhead.com/wotlk/npc=15305/lord-skwol#comments
five times in row((

**Comment by NeatElves** [comment]
See for yourself - the link to the script is already given
https://github.com/cmangos/wotlk-db/issues/521

**Comment by rmzV** [comment]
well, if provided link fixing both issues then okey.
other way this issues are different(

**Comment by rmzV** [comment]
today i summoned nother mob, so they realy randomand i close this issue
