### ISSUE TITLE
Aq40 c'thun doors

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#534]
if i remember correctly, thera was short way to c'thun

or short way after he was killed? 
now after kill, no doors available

and no short way to questgivers like
https://www.wowhead.com/wotlk/npc=15380/arygos

teleporters  from
https://www.wowhead.com/wotlk/npc=15502/andorgos
doesnot work

**Comment by rmzV** [comment]
after this https://www.wowhead.com/classic/npc=15379/caelestrasz#comments
npc if you going from C'thun side you  will find ledder with leads to closed doors

**Comment by AnonXS** [comment]
There is no door that could open there, i'd say unfinished dungeon mapping.

**Comment by AnonXS** [comment]
https://youtu.be/_MTgbediN0c?t=6889

**Comment by rmzV** [comment]
seems you are right
found this as well
https://www.youtube.com/watch?v=kfQhq8Yw-04
the guy run all the way back to the entrance of dungeon for completing 8802
