### ISSUE TITLE
ERROR:Pet::InitStatsForLevel

### ISSUE THREAD

**Issue by apo126** [cmangos/wotlk-db#54]
ERROR:Pet::InitStatsForLevel> Error trying to set stats for creature Pet (Petnumber: 16 Guid: 12) (entry: 22228) using ClassLevelStats; not enough data to do it!
ERROR:Pet::InitStatsForLevel> Error trying to set stats for creature Pet (Petnumber: 48 Guid: 38) (entry: 24981) using ClassLevelStats; not enough data to do it!
ERROR:Pet::InitStatsForLevel> Error trying to set stats for creature Pet (Petnumber: 170 Guid: 1) (entry: 24815) using ClassLevelStats; not enough data to do it!
ERROR:Pet::InitStatsForLevel> Error trying to set stats for creature Pet (Petnumber: 186 Guid: 16) (entry: 24708) using ClassLevelStats; not enough data to do it!

**Comment by Grz3s** [comment]
thx will fix this soon*

**Comment by Darth-Postal** [comment]
Some more errors of this kind:

> 2017-01-10 18:55:37 Pet::InitStatsForLevel> Error trying to set stats for creature Pet (Petnumber: 325 Guid: 1) (entry: 28384) using ClassLevelStats; not enough data to do it!
> 2017-01-10 18:55:37 Pet::InitStatsForLevel> Error trying to set stats for creature Pet (Petnumber: 326 Guid: 2) (entry: 28384) using ClassLevelStats; not enough data to do it!
> 2017-01-10 18:55:37 Pet::InitStatsForLevel> Error trying to set stats for creature Pet (Petnumber: 327 Guid: 3) (entry: 28384) using ClassLevelStats; not enough data to do it!
> 2017-01-10 18:56:17 Pet::InitStatsForLevel> Error trying to set stats for creature Pet (Petnumber: 328 Guid: 5) (entry: 28384) using ClassLevelStats; not enough data to do it!
> 2017-01-10 18:56:17 Pet::InitStatsForLevel> Error trying to set stats for creature Pet (Petnumber: 329 Guid: 6) (entry: 28384) using ClassLevelStats; not enough data to do it!
