### ISSUE TITLE
Dreadsteed of Xoroth

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#540]
after imp delivery, quest 
https://www.wowhead.com/wotlk/quest=7631/dreadsteed-of-xoroth

not available

according to this:
https://wowpedia.fandom.com/wiki/Dreadsteed_of_Xoroth_(quest)
it was removed in 4.0.3

**Comment by Grz3s** [comment]
![dwadaw](https://user-images.githubusercontent.com/2374069/216708437-a8d34e3a-7730-4b4a-b138-f92cc35c2c9b.jpg)
quest becomes available after imp delivery just fine... 
I think .. its still issue with you addin smth manualy before...
Pls check:
```code
.q r 7629
.q a 7629
.q c 7629
-- give it back to quest ender
check if 7631 becomes available
```

**Comment by AnonXS** [comment]
can confirm working in tbc too. . .

![grafik](https://user-images.githubusercontent.com/19734826/216709524-1f848ddc-227e-4e06-ba46-95fb15cc0dc1.png)
![grafik](https://user-images.githubusercontent.com/19734826/216709573-1ed4ec48-5a91-4216-a133-6d95ee7e96d8.png)

**Comment by rmzV** [comment]
will retest soon.
its not my account, 'its account one of my friends without admin rights.

**Comment by rmzV** [comment]
https://dropmefiles.com/eyyRm

maybe its related
https://github.com/cmangos/wotlk-db/issues/470

**Comment by rmzV** [comment]
hmm. not 100% sure what happens.
but today i found this quest in log.
can be closed
