### ISSUE TITLE
Craftsman Wilhelm quests

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#541]
this npc start  quests:
https://www.wowhead.com/wotlk/npc=16376/craftsman-wilhelm#starts

but this quests also required pre quest:
"he following quests can be picked up from [Craftsman Wilhelm](https://www.wowhead.com/classic/npc=16376/craftsman-wilhelm) at the Light's Hope Chapel in the [Eastern Plaguelands](https://www.wowhead.com/classic/zone=139/eastern-plaguelands) by completing[ Omarion's Handbook](https://www.wowhead.com/classic/quest=9233/omarions-handbook) which you get from [Master Craftsman Omarion](https://www.wowhead.com/classic/npc=16365/master-craftsman-omarion). He's trapped in a cage, in the first room of trash in the Deathknight Wing inside [Naxxramas](https://www.wowhead.com/classic/zone=3456/naxxramas). If you have 300 in either[ Tailoring](https://www.wowhead.com/classic/skill=197/tailoring),[ Leatherworking](https://www.wowhead.com/classic/skill=165/leatherworking) or[ Blacksmithing](https://www.wowhead.com/classic/skill=164/blacksmithing) you will be able to aquire a total of 13 different patterns depending on your profession.
"

source
https://www.wowhead.com/classic/quest=9244/icy-scale-bracers#comments

also this quests probably rep and profession? or class? affected

**Comment by Niam5** [comment]
I believe in Wrath he was removed. He is only in Naxx40 from Vanilla and TBC era.

**Comment by rmzV** [comment]
according to this
https://wowpedia.fandom.com/wiki/Master_Craftsman_Wilhelm
The subject of this section was removed from [World of Warcraft](https://wowpedia.fandom.com/wiki/World_of_Warcraft) in [patch 3.0.2](https://wowpedia.fandom.com/wiki/Patch_3.0.2) but is present in [Classic](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Classic).

you right

**Comment by rmzV** [comment]
also "Because Master Craftsman Omarion was removed from Naxxramas in patch 3.0.2, it appears that it is no longer possible to get the quest or epic items from Craftsman Wilhelm."
and 
"For Craftsman Wilhelm to craft you Frost Resist Gear, you first need to do a prequest started by talking to [Master Craftsman Omarion](https://www.wowhead.com/wotlk/npc=16365/master-craftsman-omarion)

Master Craftsman Omarion is locked in a cage located inside The Millitary Quarter of Naxxramas (Deathknight Wing).
You need to clear first hallway and room from Trash mobs to reach him.

Omarion will teach players crafting recipes, depending on their crafting profession and reputation with Argent Down:
Tailoring Revered:
-[ Glacial Wrists](https://www.wowhead.com/wotlk/item=22655/glacial-wrists)
-[ Glacial Gloves](https://www.wowhead.com/wotlk/item=22654/glacial-gloves)
Tailoring Exalted:
-[ Glacial Vest](https://www.wowhead.com/wotlk/item=22652/glacial-vest)
-[ Glacial Cloak](https://www.wowhead.com/wotlk/item=22658/glacial-cloak)
Leatherworking Revered
-[ Polar Bracers](https://www.wowhead.com/wotlk/item=22663/polar-bracers)
-[ Polar Gloves](https://www.wowhead.com/wotlk/item=22662/polar-gloves)
-[ Icy Scale Bracers](https://www.wowhead.com/wotlk/item=22665/icy-scale-bracers)
-[ Icy Scale Gauntlets](https://www.wowhead.com/wotlk/item=22666/icy-scale-gauntlets)
Leatherworking Exalted
-[ Polar Tunic](https://www.wowhead.com/wotlk/item=22661/polar-tunic)
-[ Icy Scale Breastplate](https://www.wowhead.com/wotlk/item=22664/icy-scale-breastplate)
Blacksmithing Revered
-[ Icebane Bracers](https://www.wowhead.com/wotlk/item=22671/icebane-bracers)
-[ Icebane Gauntlets](https://www.wowhead.com/wotlk/item=22670/icebane-gauntlets)
Blacksmithing Exalted
-[ Icebane Breastplate](https://www.wowhead.com/wotlk/item=22669/icebane-breastplate)

If your character doesn't have one of the listed crafting profession, he will instead give you a book[ Omarion's Handbook](https://www.wowhead.com/wotlk/item=22719/omarions-handbook) which starts quest[ Omarion's Handbook](https://www.wowhead.com/wotlk/quest=9233/omarions-handbook).
Upon turning in the quest at Light's Hope Chapel you will be granted a new option to obtain Frost Resist Gear.
[Craftsman Wilhelm](https://www.wowhead.com/wotlk/npc=16376/craftsman-wilhelm) will craft requested items for your class for required crafting Reagents (same amount as when crafter by player) along with a hefty fee of 200 or 300 golds, depending on the piece."
source 
https://www.wowhead.com/wotlk/npc=16376/craftsman-wilhelm#comments


so must be prequest with nolonger available and this npc will not offer you quests in that case

**Comment by NeatElves** [comment]
`UPDATE `quest_template` SET `PrevQuestId`=9233 WHERE `entry` IN (9234,9235,9236,9237,9238,9239,9240,9241,9242,9243,9244,9245,9246):`
