### ISSUE TITLE
Blood of Heroes missed again

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#548]
i looted item after last fix, now i am on another char and no loot at this spot..

https://www.wowhead.com/classic/object=176213/blood-of-heroes

**Comment by Grz3s** [comment]
![dwadau](https://user-images.githubusercontent.com/2374069/227740675-55354c9c-4466-493c-b922-2682c79d50b6.jpg)
search more... theyre only few spawns available in each zone

**Comment by rmzV** [comment]
so they can spawn in different locations>? if so ticket can be closed
