### ISSUE TITLE
AQ40 Twin emperrors doors

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#549]
AQ40 Twin emperrors doors closed, cant be opened even with gm mode((

thinks its related
https://github.com/cmangos/wotlk-db/issues/468

**Comment by AnonXS** [comment]
Can confirm on tbc, `5310001, Entry 180634 - [Door X:-8929.610352 Y:1344.380005 Z:-104.210999 MapId:531]` is closed by default now when it should be open.

**Comment by rmzV** [comment]
can this doors will get fix too?))

**Comment by AnonXS** [comment]
Tested, it opens if you kill boss befor that.

**Comment by rmzV** [comment]
ahh! seems i need new updates:)
will retest soon!
thx

**Comment by rmzV** [comment]
fixed. just tested
