### ISSUE TITLE
Spell entry 45222

### ISSUE THREAD

**Issue by apo126** [cmangos/wotlk-db#55]
Spell entry 45222, effect 1 has EffectImplicitTargetA/EffectImplicitTargetB = TARGET_FOCUS_OR_SCRIPTED_GAMEOBJECT, but gameobject are not defined in `spell_script_target`

**Comment by NeatElves** [comment]
```sql
INSERT INTO `spell_script_target` (`entry`, `type`, `targetEntry`, `inverseEffectMask`) VALUES
(45222, 0, 187359, 0);
```
