### ISSUE TITLE
Incorrect sign location

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#550]
Inccorect sign location

![image](https://user-images.githubusercontent.com/6240049/231000604-3430c11d-efba-48da-943e-56dc9062b501.png)

**Comment by Grz3s** [comment]
![ewrwr](https://github.com/cmangos/wotlk-db/assets/2374069/5a441e30-71c0-42f6-b02d-bba0fc631d46)
![231u](https://github.com/cmangos/wotlk-db/assets/2374069/d501ce6d-dcef-44ed-8cbf-7ddc6fbecf17)

You owe me 10 mins of swimming there and checking .....

sign location is correct

**Comment by al3xc1985** [comment]
At least u found something to fix. I ow you a KFC
