### ISSUE TITLE
Small text mistake

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#552]
In his speech he has a mistake at the beggining

![image](https://user-images.githubusercontent.com/6240049/236651373-1a8021ab-f922-42cf-a3e2-93e7ae6cc41f.png)
![image](https://user-images.githubusercontent.com/6240049/236651378-8fb39c96-0154-40a3-bce4-8775cba2a14c.png)

**Comment by Grz3s** [comment]
these texts commin from bradcast..
so whats wrong?

**Comment by al3xc1985** [comment]
that is no problem, I saw them wrong
