### ISSUE TITLE
Dire condor spamming ability

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#558]
This type of mob is spamming his ability, u can;t even touch him with this stun

![image](https://github.com/cmangos/wotlk-db/assets/6240049/53bc90ac-f6d9-4bc8-afd9-88e778aad5f0)

**Comment by al3xc1985** [comment]
let's see, , reinstalling everything. Cause somethin ain't right

**Comment by al3xc1985** [comment]
yes, confirmed. all the mobs are doing so. 
poking @killerwife in this one

**Comment by insunaa** [comment]
![image](https://github.com/cmangos/wotlk-db/assets/3718129/4c76cc55-853d-4290-9f73-7c53a32b536e)
can't confirm. behaves completely normally

**Comment by al3xc1985** [comment]
lol
Something is wrong with me than. I redowloaded everything, and redone the core. I will redo the whole db from scratch and coming back with replies

**Comment by insunaa** [comment]
To be fair, I didn't recreate the entire DB for this test, I only used option 2 in the InstallFullDB.sh script, which should wipe the wotlkmangos database and then remake it with the big SQL and the small updates.
I can't think of a reason why data in the wotlkrealmd or wotlkcharacters databases should have an effect on creature attack times, however.

**Comment by al3xc1985** [comment]
I was doing the same thing like u when I encountered this

**Comment by al3xc1985** [comment]
Tested with everything new.. Same result

**Comment by insunaa** [comment]
Yes, I pulled the latest core immediately before writing my comment here.

**Comment by al3xc1985** [comment]
This is weird. I will let this ticket open, maybe someone encounters same thing, or wait a few more days, and redo the whole server proces again, and test

**Comment by insunaa** [comment]
Did you re-run cmake before compiling?
If you did, can you try my meson fork of mangos-wotlk and try to compile and install the core with meson?
https://github.com/insunaa/mangos-wotlk/tree/meson

Maybe there's some issue with the linker or something, which my meson fork catches, but cmake doesn't.
Other than that I don't know what could be different between our setups, except timezone maybe.

**Comment by al3xc1985** [comment]
I will try it

**Comment by al3xc1985** [comment]
ok I somehow managed to make it work..

What I did is that I compiled everything without AHBot... For me is something with the AHBot that caused the problem @insunaa

**Comment by al3xc1985** [comment]
Ya, @insunaa please make a build with AHBot and try, I recheck and remade the core with and without and without it's working fine, with AHBot I have same issue

**Comment by insunaa** [comment]
![image](https://github.com/cmangos/wotlk-db/assets/3718129/ebaba5f7-beb1-4925-a0f5-fec70fd93958)
built with AHBot

**Comment by al3xc1985** [comment]
Ok, I  am closing this, I don't want tonpopulate this section with things that do not exist. It moght be my machine or compiler that does the problem

**Comment by insunaa** [comment]
Are you compiling on Windows or on Linux?

**Comment by al3xc1985** [comment]
Windows

**Comment by al3xc1985** [comment]
I found the problem @insunaa it was the cmake. Somehow it was messing the build. Cause I waited and did a new fresh update with new stuff introduced in core, and compiled in both ways with or without AHBot, and I had the same issue, and I updated the cmake, and tried again and voila, case solved.

Dunno what cmake could do to me. I was version 2.4.x something, and now i use 2.6.x
