### ISSUE TITLE
Ragefire Chasm - Small aggro problem

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#564]
When u aggro (from range) the yellow group, the orange group is also coming. This ammount of mobs is not normal for even 5 players doing the dungeon. U aggro like 6-7 mobs in one aggro which makes the encounter impossible to complete

I suggest to revise the aggro range of  Ragefire Troggs and Shamans
https://www.wowhead.com/classic/npc=11318/ragefire-trogg
https://www.wowhead.com/classic/npc=11319/ragefire-shaman

![1](https://github.com/cmangos/wotlk-db/assets/6240049/7f0ab5e7-d2e8-4641-9bc1-a025ba883b92)

**Comment by miraco** [comment]
Linking wise they are fine (on TBC).   Thats because of CallForHelp i guess. If you pull those 2, the Shaman behind them (with rnd movement) gets pulled too and he then pulls the npc in the back.
https://youtu.be/toVYkgiFAjs 

Here you can see it on tbc core.

> +---------+-------------+
| guid    | master_guid |
+---------+-------------+
| 3890039 |     3890013 |
| 3890014 |     3890013 |

**Comment by insunaa** [comment]
the initial aggro call for help shouldn't spread to the mobs that are activated by the call for help. they should only enqueue their own periodic calls for help and do the first one after 3 or 5 seconds, not sure.
I'm guessing in this case the call for help sets the other NPCs in combat, and they then immediately also broadcast their own call for help, which is not intended behaviour

**Comment by al3xc1985** [comment]
@miraco in tbc core in your video only first 3 mobs are attacking, in wotlk branch the other 3 mobs are coming 2 from orange circle

@insunaa this is indeed not the behaviour we expect, because there are 2 many mobs and u can't control nor defeat them at this level

**Comment by al3xc1985** [comment]
I remember a case in deadmines that @AnonXS or @Grz3s fixed with range aggro when u got on the van cleaf boat at base before going on stairs. Only by moving below the stairs a large number of mobs were aggroed. Or aggroing the mobs below the stars would have aggro also the mobs above the stairs

**Comment by miraco** [comment]
> @miraco in tbc core in your video only first 3 mobs are attacking, in wotlk branch the other 3 mobs are coming 2 from orange circle
> 
> @insunaa this is indeed not the behaviour we expect, because there are 2 many mobs and u can't control nor defeat them at this level

Yeah in the first pull only 3 came, in 2nd pull the others aggroed too.

> the initial aggro call for help shouldn't spread to the mobs that are activated by the call for help. they should only enqueue their own periodic calls for help and do the first one after 3 or 5 seconds, not sure. I'm guessing in this case the call for help sets the other NPCs in combat, and they then immediately also broadcast their own call for help, which is not intended behaviour

Idk how blizz handles Aggro tho

**Comment by AnonXS** [comment]
The Linking at this location is simply wrong.

**Comment by al3xc1985** [comment]
ok, in the video not even first 3 are aggroed..

**Comment by AnonXS** [comment]
https://github.com/cmangos/tbc-db/commit/c1d2ea5e7f95d95b0e62c00452b02745194b70ba

**Comment by al3xc1985** [comment]
well, I am waiting patiently until @Grz3s decide the best moment to backport this and all the other things that need to be backported, fresh or old.
