### ISSUE TITLE
Glinid

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#565]
The mobs should it be immune to stuns? I can currently stun him
I should be able only to interrupt his spellcast but not stun
https://www.wowhead.com/classic/npc=1763/gilnid#drops;mode:normal

**Comment by AnonXS** [comment]
https://github.com/cmangos/tbc-db/commit/b1d0063dfc9a5423ce430fbd10113433dd6c59c0#diff-f2c6c3af2a8102b95f2f2a5fa0155f119f27af1d4ebf9ed05cd97ff1058f5183R77

**Comment by AnonXS** [comment]
Does not have MECHANIC_STUN immunity in wotlkmangos.
