### ISSUE TITLE
Rhahk'Zor <The Foreman> 

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#567]
https://www.wowhead.com/classic/npc=644/rhahkzor

The guy can pe stunned... that is not normal he is boss

**Comment by AnonXS** [comment]
![grafik](https://github.com/cmangos/wotlk-db/assets/19734826/ced8ae37-502a-4ab7-892c-c12992760af0)

https://youtu.be/cyQKD4CTTEw?t=281
