### ISSUE TITLE
A Daughter's Love - Quest RP Missing

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#570]
Quest final roleplay missing.
I mean the guy appear from the grave, but he doesn;t say anything
https://www.wowhead.com/wotlk/quest=231/a-daughters-love

https://www.youtube.com/watch?v=ORAeGgUzDCE

**Comment by Grz3s** [comment]
fixed:
https://github.com/cmangos/wotlk-db/commit/b25a2b1ef2d5f27853cdea04678466fe8fb347db
