### ISSUE TITLE
Paladin: Redoubt and Ardent Defender Bug

### ISSUE THREAD

**Issue by vscoding1988** [cmangos/wotlk-db#577]
Hi,

the talent Rebound (https://wotlk.evowow.com/spell=20127) does not increase the passiv blockchance, only when it procs

Current State:
- without talent: block 5%
- with talent: block 5%
- with talent and proc: block 15% 

Expectation:
- without talent: block 5%
- with talent: block 15%
- with talent and proc: block 25% 

The Talent Ardent Defender (https://www.wowhead.com/wotlk/spell=31850/ardent-defender) is not reviving with 30% life, but with much less, not sure how much, but it looks like it is lower than 1%

**Comment by killerwife** [comment]
You are reading it wrong. It is meant to passively increase BLOCK VALUE not BLOCK PERCENT. 
![image](https://github.com/cmangos/wotlk-db/assets/7995382/3a647345-4e78-44a2-85ad-c1cfad62e0d6)

**Comment by insunaa** [comment]
![image](https://github.com/cmangos/wotlk-db/assets/3718129/7aa2ff9b-2f69-48cb-a821-167518753a04)
![image](https://github.com/cmangos/wotlk-db/assets/3718129/e5a7af21-5910-4364-85ec-1c9fa03ffc62)
![image](https://github.com/cmangos/wotlk-db/assets/3718129/39fa7516-89f5-48fb-b529-fb77aeec6ce0)

Ardent Defender works fine for me. Can you elaborate?

**Comment by vscoding1988** [comment]
Yep you are right sorry!

About Ardent Defender my stats are:

Level: 46 
Live: 2496 
Talent: Rang 3
Defense: 236 

I am healed after dying for 24lp (the log is in german, not sure how to force it in english sorry)

![image](https://github.com/cmangos/wotlk-db/assets/78851337/9ee743f5-0530-4c7f-b25c-1d7bf08ab0f0)

**Comment by insunaa** [comment]
Ahh yes, that. Unfortunately this part of the spell is unknown. The healing factor of ardent defender is based on the defense points you have (from armor/gear). If you're crit-immune you heal the full % the talent says, but if you only have barely any defense above the natural defense from levelling, then it only heals for very little or not at all, it only prevents the deadly strike then.

![image](https://github.com/cmangos/wotlk-db/assets/3718129/09a0583f-29ff-469b-8952-d71528a36c9b)
