### ISSUE TITLE
Mordresh Fire Eye - Just a question

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#580]
He currently dance like a human, is that normal? shouldn't he dance like an undead?

Just asking

**Comment by f0n1x** [comment]
Nope, he should have the undead dancing animation.
Sources:
Vanilla: https://www.youtube.com/watch?v=ufxnYIkF5OQ
Classic: https://www.youtube.com/watch?v=wIHLvjZhSOg

**Comment by AnonXS** [comment]
![grafik](https://github.com/cmangos/wotlk-db/assets/19734826/1275ae56-e29d-4483-a7ca-a814a645b45f)
works just fine for me with emotestate 10.

**Comment by f0n1x** [comment]
just checked my local install, he is dancing correctly like an undead.

**Comment by al3xc1985** [comment]
well that is why I am asking, cause on wotlk branch he is dancing like a human

**Comment by AnonXS** [comment]
maybe they flipped the emote to use "special dance"

**Comment by AnonXS** [comment]
He works fine in my wotlkmangos:

![grafik](https://github.com/cmangos/wotlk-db/assets/19734826/66c492f2-379c-4070-8425-dc0a71d467f3)

**Comment by al3xc1985** [comment]
ok, remade the whole db. All is ok. ty
