### ISSUE TITLE
Saving Princess Stillpine - Quest - Small Problem

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#597]
The chieftein was spawned before I took the quest from princess.
He must spawn after a certain period of time, after I kill inoff stillpine all kind of mobs. U know...
https://www.wowhead.com/tbc/npc=17682/princess-stillpine

https://www.wowhead.com/tbc/quest=9667/saving-princess-stillpine
![image](https://github.com/cmangos/wotlk-db/assets/6240049/5593422e-20c2-4264-91eb-2fb7159a4ba6)

**Comment by al3xc1985** [comment]
I killed him but u understand the ideea

**Comment by Grz3s** [comment]
the idea you talking about was implemented .. around ~7yars ago or more...
both type npcs there have 8%.. chance to spawn that guy you req for key. You were lucky to get it that quick... it took me clearing whole village twice before he showed up.

ACID par of it:
```code
-- Bristlelimb Shaman 17320
...
('1732003','17320','6','0','8','0','0','0','0','0','0','0','53','19001','0','0','0','0','0','0','0','0','0','0','Bristlelimb Shaman - Summon High Chief Bristlelimb on Death (dbscripts_on_relay)'),
-- Bristlelimb Warrior 17321
...
('1732102','17321','6','0','8','0','0','0','0','0','0','0','53','19001','0','0','0','0','0','0','0','0','0','0','Bristlelimb Warrior - Summon High Chief Bristlelimb on Death (dbscripts_on_relay)'),
```

**Comment by al3xc1985** [comment]
I learned something new. Ty

**Comment by AnonXS** [comment]
I mean overall the question stands if this or others npcs (e.g barrens one) should spawn without having the quest, this should be tested or reconfirmed).

**Comment by al3xc1985** [comment]
@Grz3s or @AnonXS but he was spawned allready, before I took the quest is that normal? That is my main concern

**Comment by al3xc1985** [comment]
https://www.wowhead.com/tbc/npc=17682/princess-stillpine-saved#comments

the comments says that u must kill before he appears
https://www.wowhead.com/tbc/npc=17702/high-chief-bristlelimb

**Comment by AnonXS** [comment]
there is no static spawn for SELECT * FROM creature where id IN (17702);

please learn your commands like

```
.npc info
```
to post useuful info.

**Comment by al3xc1985** [comment]
well, from what I understood is that, the script should start after u get the quest and not being able to spawn it whit no quest.

I believe u can summon him without quest

**Comment by Grz3s** [comment]
> I mean overall the question stands if this or other npcs (e.g barrens one) should spawn without having the quest, this should be tested or reconfirmed.

could add condition check... but need to be proven first..

**Comment by al3xc1985** [comment]
Well that was the point cause the mob spawned when I killed the other mobs without havingbthe quest. Dunno if that is normal
