### ISSUE TITLE
[WotLK] - InstallFullDB.sh for ACID

### ISSUE THREAD

**Issue by adellaci** [cmangos/wotlk-db#6]
@Grz3s 

Should the script be changed so that it pull the ACID sql from the clone of wotlk-db/ACID? If so, I'll work on changing the Installation Instructions

**Comment by killerwife** [comment]
It should work the same for tbc-db, should you make a install script, please forward it to me for usage in tbc branch :)

**Comment by Grz3s** [comment]
@adellaci 
Script is already changed... 
here: https://github.com/cmangos/wotlk-db/commit/7f3c46056b0142e2223695765175bd0e5c1988d9
No need to clone Acid repo anymore... (its inclued in DB) and it works fine :)...

**Comment by adellaci** [comment]
@Grz3s 

Thanks. I all ready change the instruction that wrote in cmangos forum to reflect that. I just need to change the GitHub instructions
