### ISSUE TITLE
SQL Update 621

### ISSUE THREAD

**Issue by Martos** [cmangos/wotlk-db#60]
When i run ./InstallFullDB.sh, crash with this error 

ERROR 1292 (22007) at line 3: Incorrect datetime value: '0000-00-00 00:00:00' for column 'start_time' at row 12

**Comment by Grz3s** [comment]
its your MySQL configuration:
more info can be found here:
https://github.com/cmangos/issues/issues/1203

**Comment by cyberium** [comment]
@Grz3s we should fix workflow for 5.7 without those change. I'll work on it next week.

**Comment by killerwife** [comment]
We "fixed it" by moving the alter table and repopulating whole table again *grin*
