### ISSUE TITLE
Disciple of Naralex - after reset bug

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#607]
https://www.wowhead.com/wotlk/npc=3678/disciple-of-naralex

So u kill all the fang lords, and get back to him, talk to him and way u go on a small jorney to rescue naralex. BUT

IF

the grup dies on the mutanus chamber or disciple of nalaex dies, after he resets, and talk back with him, he comes nice with u, until first wave of Deviate Ravager, where he get stuck and only if u move the Deviate Ravegers, start to attack them, and after u kill them both, he just get stucked in place, and the event does not continue anymore.

So, u can't spawn mutanus and by that save naralex

**Comment by AnonXS** [comment]
i think its a one way ticket so he should not even respawn.

**Comment by al3xc1985** [comment]
that means u must the the whole dungeon again?
cause it that case it make sense

**Comment by al3xc1985** [comment]
the truth is that I forced his respawn by gm command

**Comment by AnonXS** [comment]
Has to be actually tested then (befor a report is filed), maybe somebody can provide input on that.

**Comment by al3xc1985** [comment]
as noted `For those that may still be interested in this. He is SUPPOSED to respawn after a set amount of time , at the front and you re-escort him. The amount of times this actually works is very very small.

It is worth it if you have a heal, to focus the tauren and keep him up if possible. Back in the day he did -not- respawn and you had to actually bail entirely and redo the instance.`

I believe it should respawn fast

**Comment by al3xc1985** [comment]
also on wowhead we have this

`[608771](https://www.wowhead.com/user=608771) [on 2010/06/01](https://www.wowhead.com/wotlk/npc=3678/disciple-of-naralex#comments:id=1008784:reply=166043) (Patch 3.3.3)

tell me about it,same thing happened,except we spent 30 minutes waiting for him to respawn. He really does not respawn.`

**Comment by al3xc1985** [comment]
so bassicaly it's one shot event, as is intended to work and it does in our db

**Comment by al3xc1985** [comment]
if u find anything else @AnonXS let me know, until than it's just clear

**Comment by al3xc1985** [comment]
ok, no need to keep this open found the evidance that u must restart the instance
https://www.wowhead.com/wotlk/npc=3678/disciple-of-naralex#comments;mode:n10
