### ISSUE TITLE
ShadowFang Keep - Chest pooling

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#608]
I found like all chests spawned in Shadowfang Keep.

I believe they should be involved in a pool system

**Comment by AnonXS** [comment]
please provide some guids so you reports can be processed faster.

**Comment by al3xc1985** [comment]
ups, I shall remember that for future...ok, getting back in dungeon

**Comment by al3xc1985** [comment]
ok, restarting the server, retesting, and only one was there..hmm...maybe it was just me
