### ISSUE TITLE
Defias thug missing text

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#610]
According to this classic video we miss one text for Defias thug
https://www.wowhead.com/wotlk/npc=38/defias-thug

https://youtu.be/ZCO7u3wScQM?t=2550

![image](https://github.com/cmangos/wotlk-db/assets/6240049/652821bb-9bc1-4551-8fa6-4f93310efcb9)

**Comment by AnonXS** [comment]
![grafik](https://github.com/cmangos/wotlk-db/assets/19734826/98c4ab2d-c043-41f6-b500-9a7fd1b9be6b)

**Comment by al3xc1985** [comment]
nop, I checked the broodcast texts and there is none of those 3 that match it

**Comment by al3xc1985** [comment]
What I observed is that all defiases use the same text lines

**Comment by miraco** [comment]
Broadcast_text Id  7134  This land belongs to the Defias Brotherhood now!

```
1865	Ah, a chance to use this freshly sharpened blade.
1866	The Brotherhood will not tolerate your actions.
1867	Feel the power of the Brotherhood!
```
