### ISSUE TITLE
Hogger - Spawn point

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#612]
https://www.wowhead.com/wotlk/npc=448/hogger#abilities

- [ ] His spawn point should be pooled. We currently have him in one place
- [ ] Second problem is that in the movies he has a longer random ?? walking around his spawn point

https://youtu.be/ZCO7u3wScQM?t=10062
https://www.youtube.com/watch?v=itB6de-6nRI

**Comment by Grz3s** [comment]
he is part of spawn group - 19983 (5 diff spawn points)..
1 has waypoints
4 have randommovement

Pls check before creating issue.

**Comment by al3xc1985** [comment]
Ok, tty
