### ISSUE TITLE
Defias messenger - Missing More Texts

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#619]
The text that he is missing 474
https://www.wowhead.com/wotlk/npc=550/defias-messenger
https://youtu.be/ZCO7u3wScQM?t=31283

![image](https://github.com/cmangos/wotlk-db/assets/6240049/f2a1b7f9-8278-4a3f-bd20-8652d405e9c2)

![image](https://github.com/cmangos/wotlk-db/assets/6240049/4967d612-9718-4a93-9928-89f71b24cc11)

**Comment by AnonXS** [comment]
says alot: https://www.wowhead.com/wotlk/npc=550/defias-messenger

![grafik](https://github.com/cmangos/wotlk-db/assets/19734826/80b3d411-cd6a-4b38-a482-9118276f343f)

**Comment by al3xc1985** [comment]
ya,, but we have only a few implemented

**Comment by AnonXS** [comment]
so say we miss "more" texts.

**Comment by al3xc1985** [comment]
we only have 3 implemented 473,478,479

**Comment by al3xc1985** [comment]
Ya, while I started to create the bug report and read more, and search more I found more to be missing. But your list is most comprehensive

**Comment by AnonXS** [comment]
if you say we miss text, we assume it has no texts at all, if you say we miss more texts, you specify what more texts we miss.

**Comment by al3xc1985** [comment]
undrstood, ty for that, and my apologises
