### ISSUE TITLE
Stormwind - Missing Orphans RP 

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#620]
Like is seen in the video they are moving around in that area
https://youtu.be/ZCO7u3wScQM?t=32384

They currently stay inside now

![image](https://github.com/cmangos/wotlk-db/assets/6240049/c328f39c-b071-4570-9850-064c2f126448)

**Comment by AnonXS** [comment]
serious question, are you watching the whole thing?

**Comment by al3xc1985** [comment]
nop, just skipping a lot of it, looking for things we might miss

**Comment by al3xc1985** [comment]
and believe me I have like 50 vids waiting.

after I finish with them, I might start a subscription session

**Comment by Grz3s** [comment]
you guys doin everything to keep me away from Northrend :D

**Comment by al3xc1985** [comment]
:D well... more will come...
