### ISSUE TITLE
Stormwind Patroller - What is wrong with this guy?

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#621]
What is wrong with this guy? He just stands and wonder around his spawn location

Guid: 120789

If he is a patroler why he doesn't patrol?

or he might be an extra spawn that needs to be removed?
I searched the zone, and there 2 patrollers currently, that I found on vids 2 but not this one. 

He might have a different path

![image](https://github.com/cmangos/wotlk-db/assets/6240049/19dc9a13-271f-4071-a4b4-31322f35394d)

**Comment by AnonXS** [comment]
Misplacement/Start of patrol, long gone in classic/tbc.

**Comment by al3xc1985** [comment]
guid is on the image.. if needed I will writ them down

**Comment by al3xc1985** [comment]
ok, understood.. ty

**Comment by AnonXS** [comment]
e.g with guards and and on a live server, it could also be a temp spawn, so making clear it is a permanent spawn is important.

**Comment by al3xc1985** [comment]
I will try to be carefful with that
