### ISSUE TITLE
Howling Fjord - Missing Penguin Spawns

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#622]
I don't know the penguind entry id, but I did find them missing from a small iceberg at entrace in howling fjord.
There are a ton of them spawned there

![image](https://github.com/cmangos/wotlk-db/assets/6240049/f500e83e-d714-4f34-9e46-40803a9d926f)

**Comment by al3xc1985** [comment]
there is 2 an iceber in the right side, but I can't tell if there should be any spawns on that one 2

**Comment by AnonXS** [comment]
Do they move?
