### ISSUE TITLE
Lord Irulon Trueblade <The Argent Crusade> - Small RP 

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#629]
First of all I poke @Grz3s into this for confirmation or infirmation about this small RP implementation. If it is implemented please close it.. I stood a little bit there waited, and tried to find clues on db about it, but I could not find (my poor knowledge)

https://www.wowhead.com/wotlk/npc=24191/lord-irulon-trueblade

He has a small RP With Lord Fordring. But I can't find his id
![image](https://github.com/cmangos/wotlk-db/assets/6240049/20fc14c1-7aa2-4044-8ad3-e07c8968a79d)

![image](https://github.com/cmangos/wotlk-db/assets/6240049/4515c13d-69a1-4dc3-8ad8-1b06fcfbf388)

**Comment by Grz3s** [comment]
You couldnt see it again koz it a end script for quest https://www.wowhead.com/wotlk/quest=11289/guided-by-honor
https://youtu.be/5W689ezOFuU?t=183
and Yes.. We have it done.

**Comment by al3xc1985** [comment]
Perfect
