### ISSUE TITLE
Leesha Tannerby <Dockmaster> - Teleporter to Valliance Keep

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#630]
https://www.wowhead.com/wotlk/npc=26548/leesha-tannerby#comments
I believe that she should be able to teleport u to Valliance Keep
https://youtu.be/ljaOBYyZA0k?list=PL01y0oZQjUTz1lghLi8hWYzm-mOlmoDKL&t=10545

![image](https://github.com/cmangos/wotlk-db/assets/6240049/cd78d1a6-c246-4a39-a251-9bdf6fdce24f)

![image](https://github.com/cmangos/wotlk-db/assets/6240049/33250d67-b4ea-495d-b1b9-7db124dc4f45)

**Comment by insunaa** [comment]
This was added in 3.4 Classic and is not how the NPC worked in 3.3.5

**Comment by al3xc1985** [comment]
Perfect. Ty.. I wanted to close it myself, by digging further I found that it was temporary added
