### ISSUE TITLE
Borean Tundra - 2 Taunka Longrunners Patrol Missing

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#639]
I could not find them at all on the map 
https://www.wowhead.com/wotlk/npc=26790/taunkale-longrunner

There are 2 guys that should spawn on that part of map

![image](https://github.com/cmangos/wotlk-db/assets/6240049/8de96ed0-bb90-415f-9184-5456fe1bd84a)

**Comment by Grz3s** [comment]
.go c 515666

**Comment by al3xc1985** [comment]
They look perfect...ty
