### ISSUE TITLE
10211 !city of light

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#64]
bugged.. servant doesnot talking and instead of ending he starting move again and again.. may be it doesnot work for blood elfs?

**Comment by killerwife** [comment]
This is being fixed in core, not DB. https://github.com/cmangos/issues/issues/1218 Closing duplicate issue.

**Comment by rmzV** [comment]
still doesnot work
tested today on latest build

**Comment by rmzV** [comment]
may be bug exist for blood elfs only? with are already friendly with scryers
