### ISSUE TITLE
mana tombs - missed npc and quest

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#65]
http://www.wowhead.com/quest=10218/someone-elses-hard-work-pays-off
http://wowwiki.wikia.com/wiki/Quest:Someone_Else%27s_Hard_Work_Pays_Off

**Comment by Grz3s** [comment]
Yes somehow wrong conditio has been set for object :/
I'll fix this ASAP:

BTW:
- Make sure preq 10216 is completed
- U'll need to click on gossip option to activate event to happen.
