### ISSUE TITLE
Reddrige Mountain - 2 More Blackrocks patrols Missing

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#660]
https://www.wowhead.com/wotlk/npc=4065/blackrock-sentry
https://www.wowhead.com/wotlk/npc=4064/blackrock-scout

https://youtu.be/J6h7GWgZ2rA?t=10898
U will observ in the vid, they will kill both, one after the other, and do have a given path that we currently miss

**Comment by Grz3s** [comment]
they simply have waiting time on some points... and u may think that we missing them - we don't
