### ISSUE TITLE
[General Bug] Mobs/NPC's with Charge spell

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#664]
https://youtu.be/4BcUXMH1TG8?t=18188

1. As I suspected and see so many times, but not it got to my attention, ALL mobs with charge will use the charge ONLY on aggro  phase. Wich is not correct. Mobs should use the charge spell even during combat, when u try to escape, they should use the charge on you if Charge cooldown is ready so the mob can get to you.

I posted a vid for proof

2. One more problem is that even thou u get very very close to mob he will still use the charge, wich is not correct also.
https://youtu.be/4BcUXMH1TG8?t=20813

3. Charge should be used ONLY on a minimum distance from target, otherwise not using it at all

Can be tested on 
https://www.wowhead.com/classic/npc=345/bellygrub

**Comment by al3xc1985** [comment]
This is the way I see the problem. Solving this would make them look more official way

**Comment by Grz3s** [comment]
If You will find more of these .. pls let us know ..
