### ISSUE TITLE
Loch Modan - 1 Guard missing

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#678]
At that gate we have 2 guards. One is mounted and one not.. We miss the one from right side, that is not mounted

![image](https://github.com/cmangos/wotlk-db/assets/6240049/7a404b47-7724-4e2f-b18b-c1dc11482ddc)

**Comment by al3xc1985** [comment]
@AnonXS this is a classic repo thing... can u check and fix it for classic? and close this, cause I found that it's not for wotlk

**Comment by AnonXS** [comment]
its a patrol. 
![grafik](https://github.com/cmangos/wotlk-db/assets/19734826/9c501acd-5679-4591-a096-c2a7e501461c)

**Comment by Tobschinski** [comment]
https://www.wowhead.com/classic/npc=1283/mountaineer-kalmir

guy is patrolling

**Comment by al3xc1985** [comment]
how can I make to see those wisps?

**Comment by al3xc1985** [comment]
thank you
