### ISSUE TITLE
Grz3s I was right about that Guard

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#688]
Guid 120692

https://youtu.be/qa2vJD2hyTc?t=10214

The guard should NOT have random movment
![image](https://github.com/cmangos/wotlk-db/assets/6240049/9860e6f6-8063-4167-b511-09583f2a34c8)

**Comment by AnonXS** [comment]
confirms my finding about the guard, i think it's static too.

**Comment by Grz3s** [comment]
i spent enough time there ... recording/sniffing area there... 
```code
[1] UpdateType: CreateObject1
[1] Object Guid: Full: 0x20457C0000001100000006000074CE16 Creature/0 R4447/S6 Map: 0 Entry: 68 Low: 7654934
[1] Object Type: 5 (Unit)
[1] MoverGUID: Full: 0x20457C0000001100000006000074CE16 Creature/0 R4447/S6 Map: 0 Entry: 68 Low: 7654934
[1] Movement Flags: 0 (None)
[1] Movement Flags 2: 0 (None)
[1] Movement Flags 3: 0 (None)
[1] MoveTime: 1766073276
[1] Position: X: -8822.998 611.07416 95.05364
[1] Orientation: 0.926326453685760498

ServerToClient: SMSG_ON_MONSTER_MOVE (0x2DD4) Length: 80 ConnIdx: 1 Time: 05/29/2023 22:47:43.268 Number: 2462
MoverGUID: Full: 0x20457C0000001100000006000074CE16 Creature/0 R4447/S6 Map: 0 Entry: 68 Low: 7654934
Position: X: -8822.998 611.07416 95.05364
(MovementMonsterSpline) (MovementSpline) Flags: 2434793472 (CanSwim, Unknown5, Steering, Unknown10)
(MovementMonsterSpline) (MovementSpline) [0] Points: X: -8825.359 612.6654 94.77015
(MovementMonsterSpline) (MovementSpline) [0] WayPoints: X: -8824.679 612.36975 94.911896

ServerToClient: SMSG_ON_MONSTER_MOVE (0x2DD4) Length: 76 ConnIdx: 1 Time: 05/29/2023 22:48:12.440 Number: 3392
MoverGUID: Full: 0x20457C0000001100000006000074CE16 Creature/0 R4447/S6 Map: 0 Entry: 68 Low: 7654934
Position: X: -8825.359 612.6654 94.77015
(MovementMonsterSpline) (MovementSpline) [0] Points: X: -8825.101 614.08594 94.59878

ServerToClient: SMSG_ON_MONSTER_MOVE (0x2DD4) Length: 76 ConnIdx: 1 Time: 05/29/2023 22:48:30.235 Number: 4260
MoverGUID: Full: 0x20457C0000001100000006000074CE16 Creature/0 R4447/S6 Map: 0 Entry: 68 Low: 7654934
Position: X: -8825.021 612.4588 94.84156
(MovementMonsterSpline) (MovementSpline) [0] Points: X: -8826.237 614.6298 94.51453

ServerToClient: SMSG_ON_MONSTER_MOVE (0x2DD4) Length: 68 ConnIdx: 1 Time: 05/29/2023 22:48:31.807 Number: 4331
MoverGUID: Full: 0x20457C0000001100000006000074CE16 Creature/0 R4447/S6 Map: 0 Entry: 68 Low: 7654934
Position: X: -8826.237 614.6298 94.51453
(MovementMonsterSpline) (MovementSpline) FaceDirection: 0.866306483745574951

ServerToClient: SMSG_ON_MONSTER_MOVE (0x2DD4) Length: 76 ConnIdx: 1 Time: 05/29/2023 22:48:48.001 Number: 5290
MoverGUID: Full: 0x20457C0000001100000006000074CE16 Creature/0 R4447/S6 Map: 0 Entry: 68 Low: 7654934
Position: X: -8826.237 614.6298 94.51453
(MovementMonsterSpline) (MovementSpline) [0] Points: X: -8824.972 613.51587 94.68413
```

**Comment by Grz3s** [comment]
also heres pic from 2009 vid:
is he static on it?
 
![1](https://github.com/cmangos/wotlk-db/assets/2374069/e84419c1-bf59-44fc-907e-efa7f0d2b7a3)
![2](https://github.com/cmangos/wotlk-db/assets/2374069/ae8e9877-c839-4c13-99ce-9c10fdf6c7a2)

**Comment by al3xc1985** [comment]
u made him move just to be right on this one

**Comment by al3xc1985** [comment]
I still think is static

**Comment by insunaa** [comment]
It's not. People keep talking to the guards and the guards have an exceptionally long wait-time after being talked to (5 minutes) until they restart random movement

**Comment by al3xc1985** [comment]
Yes insinua but when u talk with them  and stop them in different random positions

**Comment by insunaa** [comment]
Yes, but their random movement has some weird factor that makes them re-orient a lot during the random movement, and the re-orientation is usually away from the wall

**Comment by al3xc1985** [comment]
https://www.youtube.com/watch?v=Sz2jkjR4lvI

Static

**Comment by insunaa** [comment]
https://youtu.be/2mz03crgEcc?t=34
moving

**Comment by al3xc1985** [comment]
That guard is static. Picture from first vid
![image](https://github.com/cmangos/wotlk-db/assets/6240049/58ddc6d5-5852-4821-9218-556f7b6f23ff)

**Comment by al3xc1985** [comment]
second vid does not include that guard

**Comment by insunaa** [comment]
I told you before: The guard once talked to stands still for 5 minutes. 5 minutes is a long time and to no surprise the guards are talked to a lot

**Comment by AnonXS** [comment]
he posted sniff that shows the guard moving random without being in combat.

so go there on live, do a 1h video and report back.

**Comment by al3xc1985** [comment]
live we have Asmongold from live and static guard

**Comment by al3xc1985** [comment]
besides, I called blizzard a few moments ago, and they told me it was static

**Comment by insunaa** [comment]
Asmongold is classic, classic is not an authoritative source ***not to mention that they move on classic, too***

**Comment by AnonXS** [comment]
you're slowly loosing your credibility with these answers.

**Comment by al3xc1985** [comment]
I am talking about this guy
![image](https://github.com/cmangos/wotlk-db/assets/6240049/870fe5bb-aaed-45c7-b207-04dd34b9bc9c)

**Comment by al3xc1985** [comment]
not rest of the guards. He has static point as many other guards

**Comment by insunaa** [comment]
He only stands still for 5 minutes at a time.

**Comment by AnonXS** [comment]
> also heres pic from 2009/2010 vid: is he static on it?
> 
> ![1](https://user-images.githubusercontent.com/2374069/258939283-e84419c1-bf59-44fc-907e-efa7f0d2b7a3.jpg) ![2](https://user-images.githubusercontent.com/2374069/258939300-ae8e9877-c839-4c13-99ce-9c10fdf6c7a2.jpg)

so what about this?

**Comment by al3xc1985** [comment]
Hmm...I am a little confuse. But this is a good point

**Comment by insunaa** [comment]
Please tell me what the hell this is (made this video 5 minutes ago on abk)
https://cdn.discordapp.com/attachments/829284244375339028/1138567343321141329/2023-08-08_22-18-32.mp4

**Comment by AnonXS** [comment]
As you say it might even be a long waypoint script disguised as random movement, so we think its static but infact he just has waittime for a long time (my finding) that makes us believe he is static when infact he has static points after some while where he is emulating random movement.

**Comment by al3xc1985** [comment]
yes, u are right @insunaa . Hands down

@AnonXS that it. That fact fooled me all the way. 
Ty guys

**Comment by insunaa** [comment]
Pink pigtails are love (and life)

**Comment by al3xc1985** [comment]
The hunger for small details kills me. I am for small details and as u can see in my reports I allways try to get a full attention to little insignifiant small details

I want to contribute to this project so we can have a perfect blizzlike enviroment, like noone

**Comment by AnonXS** [comment]
What i'd like to end this with is, befor opening issues its always best to get in touch with devs to get feedback on the issue that is about to be reported, often times you get feedbak towards said issue, or even more information towards said issue to specify it better. in this case, its an edge case we've not seen much and should def be reviewed as a "detail" that can happen anywhere in the world and hence has to be looked at in detail.

**Comment by al3xc1985** [comment]
yes @AnonXS! hands down

**Comment by insunaa** [comment]
> The hunger for small details kills me. I am for small details and as u can see in my reports I allways try to get a full attention to little insignifiant small details
> 
> I want to contribute to this project so we can have a perfect blizzlike enviroment, like noone

And that's really cool and I appreciate it a lot! But please also sometimes believe it when multiple people tell you that you may be incorrect and give you plausible explanations :)

**Comment by al3xc1985** [comment]
I do apopogize. I may overreact sometimes, and that is a mistake on my side

**Comment by al3xc1985** [comment]
And please bear with me in future

**Comment by insunaa** [comment]
> And please bear with me in future

Of course! You're one of the most prolific creators of issues here and the vast majority of them are valid. There are definitely no hard feelings :)
