### ISSUE TITLE
scepter of the sand q chain"blue part

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#69]
you must talk to the"Azuregos"
but he hasnot any dialog options and no spirit after killing him (
http://db.vanillagaming.org/?npc=6109#wh-comments

http://wowwiki.wikia.com/wiki/The_Scepter_of_the_Shifting_Sands_quest_chain

**Comment by cala** [comment]
The Spirit of Azuregos is always spawned, whenever Azuregos is alive or not. You do not need to kill Azuregos to spawn the spirit.

Also, both NPCs share the same dialogs and gossip options in regards on the Scepter of the Shifting Sand blue shard. Those are working in Classic DB (and should have the right IDs), so I suggest simply porting them.
