### ISSUE TITLE
Eliza - 2 more spawns

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#702]
Eliza should spawn 2 more  guards, not just one, total of 3
https://youtu.be/aSrEAqWtStI?t=15327

https://www.wowhead.com/wotlk/npc=314/eliza#abilities

**Comment by al3xc1985** [comment]
![image](https://github.com/cmangos/wotlk-db/assets/6240049/0fff83ba-9a85-46b8-93ea-5dda5d76da6f)

**Comment by Grz3s** [comment]
she was nerfed in wotlk... 
not elite anymore .. and 1 guard.

Pls refer to wotlk vids (asmon also has them) .. to avoid these mistakes in future
