### ISSUE TITLE
~Discussion ~ Shadowhide Mobs - Resistances

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#708]
I found some usefull info by reading all the comments

They currently have 50 resistance to shadow set in db, but as we see the comments they kind of have to all spell schools resistances, the highes would be shadow.

![image](https://github.com/cmangos/wotlk-db/assets/6240049/0599e9a9-1456-43b1-81bb-35893000bdf0)

![image](https://github.com/cmangos/wotlk-db/assets/6240049/41904559-67c9-4cc6-8d05-460adcf83a83)

**Comment by al3xc1985** [comment]
https://youtu.be/OMqUehP-BB0?t=3191
https://youtu.be/OMqUehP-BB0?t=3908

I don't see any evidance that we have any school resistances set, at least for holy


I let this open as I will check more about

**Comment by AnonXS** [comment]
![grafik](https://github.com/cmangos/wotlk-db/assets/19734826/6002b653-f7ec-4f79-a143-fbd82115d0ed)

**Comment by al3xc1985** [comment]
perfect.. ty @AnonXS for helping me out
