### ISSUE TITLE
6583! the Test of sculls, Somnus 

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#71]
missed npc for a quest
6583! the Test of sculls, Somnus
http://wowwiki.wikia.com/wiki/Quest:The_Test_of_Skulls,_Somnus

http://wowwiki.wikia.com/wiki/Somnus

**Comment by NeatElves** [comment]
```sql
UPDATE `creature` SET `map` =  '0' WHERE `guid` =72694;
```
