### ISSUE TITLE
1 Blackrock Path should have pool

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#711]
Guid = 26167

Can be also Shadowcaster
https://www.wowhead.com/wotlk/npc=436/blackrock-shadowcaster#comments

https://youtu.be/OMqUehP-BB0?t=4150

**Comment by Grz3s** [comment]
he is.
Pls use `.npc info` ... you will see 
![adwadu](https://github.com/cmangos/wotlk-db/assets/2374069/9fc916f1-1318-47a1-8ee6-d327bb3b27d8)
