### ISSUE TITLE
Some skeletal holy resistance

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#713]
https://youtu.be/OMqUehP-BB0?t=5016

As we can see:

Skeletal Raider
https://www.wowhead.com/wotlk/npc=1110/skeletal-raider#comments
Skeletal Fiend
https://www.wowhead.com/wotlk/npc=531/skeletal-fiend#comments
Skeletal Healer
https://www.wowhead.com/wotlk/npc=787/skeletal-healer
Skeletal Horror
https://www.wowhead.com/wotlk/npc=202/skeletal-horror#abilities
Skeletal Warder
https://www.wowhead.com/wotlk/npc=785/skeletal-warder

They have  holy resistance

**Comment by al3xc1985** [comment]
Also
Carrion Recluse
https://www.wowhead.com/wotlk/npc=949/carrion-recluse#comments

**Comment by AnonXS** [comment]
![grafik](https://github.com/cmangos/wotlk-db/assets/19734826/0181a781-d363-49c8-ac1d-db18adeb63fc)

![grafik](https://github.com/cmangos/wotlk-db/assets/19734826/2f311853-e398-45ff-896c-ae9023cef452)

**Comment by killerwife** [comment]
Unless I misremember, holy resistance is an urban legend.

**Comment by al3xc1985** [comment]
@AnonXS  wow. I believe u are right. But nice info! Is that a site or a book?

Well, @killerwife I remember that 2 now when u mentioned, the time when I played offy about that sort of "legends"
