### ISSUE TITLE
Dragonmaw Bonewarder - Missing 1 Ability and text

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#718]
https://www.wowhead.com/wotlk/npc=1057/dragonmaw-bonewarder#abilities
[Curse of Weakness](https://www.wowhead.com/wotlk/spell=6205/curse-of-weakness)

He is missing that curse of weakness
https://youtu.be/aSrEAqWtStI?t=18414
![image](https://github.com/cmangos/wotlk-db/assets/6240049/00662131-a72f-4afd-8703-bafa556f1cbb)

**Comment by al3xc1985** [comment]
Text
![image](https://github.com/cmangos/wotlk-db/assets/6240049/41308d08-b3b8-4859-b79d-9896b1db3829)


![image](https://github.com/cmangos/wotlk-db/assets/6240049/a56da41e-2c0b-49f4-8bac-05b318ea1815)

**Comment by AnonXS** [comment]
strange seems they never got the demon armor spell working.

![grafik](https://github.com/cmangos/wotlk-db/assets/19734826/aa70f18e-c18b-4a8e-b330-c0907ff1c4fe)

**Comment by AnonXS** [comment]
https://github.com/cmangos/wotlk-db/commit/22660c3b048703d0b2c34d68c666b3e7f076151c
