### ISSUE TITLE
mor'vek quest chain

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#72]
http://www.wowhead.com/npc=11701/morvek#comments
first comment explains how it must works.. atm he is offering all of 3 quests at start... daily on random bassis doesnot work
i am not familar with c++ syntax but may be JS analog of math.random() can be used?
we get some random number in [0:1] on daily basis
if we have 3 daily quests then 1/3=0.33 so we have 3 zone 
0-0.33 first quest
0.34-0.66 second
0.67-1 third.

**Comment by NeatElves** [comment]
core problem, it is necessary not only to choose one quest - you also need to be written to the database until the end of the day which is selected

**Comment by rmzV** [comment]
can you please explain me the logic. if this is a core issue ,and  you just close it 
so i must reopen this ticket at core branch?

**Comment by NeatElves** [comment]
Currently, there are no tools in the core for the job is not.
