### ISSUE TITLE
Finkle_Einhorn

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#73]
missed npc in UBRS
he will shown after you kill the beast boss
http://wowwiki.wikia.com/wiki/Finkle_Einhorn

http://www.wowhead.com/quest=5047/finkle-einhorn-at-your-service
Unlocks 3 following quests: Cap of the Scarlet Savant, Leggings of Arcana, Breastplate of Bloodthirst.
The Malyfous's Catalogue, which gives the quests, is next to Malyfous.
http://wowwiki.wikia.com/wiki/Malyfous's_Catalogue

**Comment by offl** [comment]
> This NPC appears when you skin The Beast in Upper Blackrock Spire.

The kill is not enough.

**Comment by rmzV** [comment]
offl, i am sure that in tbc days i get this quest on my lock with was not a skinner...
not sure if we have skinner in a party..((

**Comment by offl** [comment]
I think you can also wait until The Beast's corpse despawn.
Looks like it's the second way to spawn him on [retail](https://youtu.be/skMUm06O3PY?t=1145). And this  was implemented [here](https://github.com/scriptdev2/scriptdev2/issues/128).

**Comment by Grz3s** [comment]
yes... he will spawn or after skinning or after despawn "the beast"
and both works fine.

**Comment by rmzV** [comment]
https://www.wowhead.com/news/finkle-einhorn-renamed-more-transphobic-sexual-and-racially-suggestive-dialogue-324490
just info.

**Comment by Grz3s** [comment]
nothing to do with true pre Cata WoW..

**Comment by rmzV** [comment]
@Grz3s yes))  just post it in case if you take something from live server (non vanilla wotlk)

**Comment by Grz3s** [comment]
dont you wory about that ;) it wont happen
