### ISSUE TITLE
Mosshide Mystic - Wrong Acid data

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#736]
Mosshide Mystic
https://www.wowhead.com/wotlk/npc=1013/mosshide-mystic#abilities

But he has 4 different abilities that are not yet implemented

> -- Mosshide Mystic 1013 - creature_spell_list
('101301','1013','11','0','100','0','0','0','0','0','0','0','57','2','35','0','0','0','0','0','0','0','0','0','Mosshide Mystic - Enable Range Mode on Spawn'),
('101302','1013','4','0','15','0','0','0','0','0','0','0','1','1871','1870','0','0','0','0','0','0','0','0','0','Mosshide Mystic - Say on Aggro'),
('101303','1013','27','0','100','1','12544','1','15000','30000','0','0','11','12544','0','0','0','0','0','0','0','0','0','0','Mosshide Mystic - Cast Frost Armor on Missing Buff'),
('101304','1013','2','0','100','0','15','0','0','0','0','0','25','0','0','0','1','1150','0','0','0','0','0','0','Mosshide Mystic - Flee at 15% HP'),

**Comment by AnonXS** [comment]
creature_spell_list

**Comment by al3xc1985** [comment]
nice
