### ISSUE TITLE
2203!2501! Badlands Reagent Run II

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#74]
http://www.wowhead.com/quest=2501/badlands-reagent-run-ii
http://www.wowhead.com/quest=2203/badlands-reagent-run-ii

requires alchemy 210 info from comments

**Comment by NeatElves** [comment]
```sql
UPDATE `quest_template` SET `RequiredSkillValue` = 210 WHERE `entry` =2203;
```

**Comment by Grz3s** [comment]
@NeatElves 
Q.2202 Uldaman Reagent Run is req. not q.17 ;) ... and this is in horde side only...
We have that already applied.
Thx for your fix :+1:
