### ISSUE TITLE
blasted land NPC and Q

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#75]
http://wowwiki.wikia.com/wiki/Bloodmage_Lynnore
http://wowwiki.wikia.com/wiki/Bloodmage_Drazial

after completing quest once.. must turn to reppitable quests

**Comment by Grz3s** [comment]
Small info into this:
They are ... 
But somehow Core doesnt show blue "!" anymore... all yellow (like with normal quests)
DB cannot fix this.

**Comment by rmzV** [comment]
ye.. i saw this blue "!" problem on alterac valley as well(
may be i must make ticket in core branch?

**Comment by Grz3s** [comment]
yes u can

**Comment by rmzV** [comment]
cant find the issues butmn=(
