### ISSUE TITLE
A-Me 01 npc and quests

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#77]
npc 
http://db.vanillagaming.org/?npc=9623
mostly instant killed by surrounding mobs... but i was able to complete pre quests
but not the escort quest
http://db.vanillagaming.org/?quest=4245
this one doesnot work..
+when npc dying -quest log doesnot mark this quest as "failed"

**Comment by rmzV** [comment]
bassicaly if npc killed you must get "failed" state andretake escort quest

as for now without this state,, when you run into a cave enemy npcs killing A-Me.

**Comment by Grz3s** [comment]
fixed some time ago
