### ISSUE TITLE
Quest - Suspicious Hoofprints

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#773]
https://www.wowhead.com/wotlk/quest=1284/suspicious-hoofprints

Upon completition he should have a quote
![image](https://github.com/cmangos/wotlk-db/assets/6240049/16879361-021c-43a0-8aab-1e4d8f3d485b)

https://youtu.be/HyM_RARkWOE?t=6467
![image](https://github.com/cmangos/wotlk-db/assets/6240049/4a8ea42b-a71d-4876-a68b-bfa6b69d01a3)

**Comment by al3xc1985** [comment]
https://www.wowhead.com/wotlk/npc=4948/adjutant-tesoran
Adjutant Tesoran answer on that quest 2

**Comment by al3xc1985** [comment]
@Grz3s u should know if other 2 quotes are used of Captain Garran Vimes (I hope u remember)

**Comment by Grz3s** [comment]
other 2 texts comes from q. 1220 - already scripted ;)
![dwad](https://github.com/cmangos/wotlk-db/assets/2374069/7f9a5039-23b9-4cf5-b158-87f7a9a2f144)
