### ISSUE TITLE
Gavis Greyshield - Missing equipment

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#785]
https://www.wowhead.com/wotlk/npc=23941/gavis-greyshield

I check and he does not have his shield and 1h sword equiped

**Comment by Grz3s** [comment]
![32423](https://github.com/cmangos/wotlk-db/assets/2374069/7459d1c4-f4ba-47e3-a0f3-0c12a95f4770)
you sure?

**Comment by al3xc1985** [comment]
hmm...reinstalling the db again... checking and I shall be back

**Comment by al3xc1985** [comment]
yes, u are right... something was wrong here on my machine
