### ISSUE TITLE
Nathanos Blightcaller quest chain

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#79]
1 quest in row doesnot have a timer
http://wowwiki.wikia.com/wiki/Quest:To_Kill_With_Purpose
later
Sylvanas gives you 
http://wowwiki.wikia.com/wiki/Quest:The_Crimson_Courier
without completing 
http://wowwiki.wikia.com/wiki/Quest:The_Call_to_Command
with is pre quest
and later following quest chain
http://wowwiki.wikia.com/wiki/Quest:Nathanos%27_Ruse
not available,,, i saw quest window for a second and it gives "quest requirments doesnot met"

**Comment by Grz3s** [comment]
```quote
1 quest in row doesnot have a timer
http://wowwiki.wikia.com/wiki/Quest:To_Kill_With_Purpose
```
Please read comments... 
```quote
TinkerBell on 2008/03/31 (Patch 2.4.0)
Generally, timed quests will have a time-counter. This quest doesn't have it, but if you look at the tooltip on every Living Rot you have you see that when you got it it will have 10 Minutes remaining, it decrease individually. As Nekudotayim said, no time limit to deliver the quest.
```
just tested and works fine
