### ISSUE TITLE
Wretched Thug - Missing Text

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#794]
https://www.wowhead.com/wotlk/npc=15645/wretched-thug
![image](https://github.com/cmangos/wotlk-db/assets/6240049/b4e57586-32f9-49e1-bb62-11182e7f2ca0)

**Comment by AnonXS** [comment]
-- Wretched Thug 15645 - Not sure when RP is played, not on aggro seemingly
('1564501','15645','1','0','15','1','4000','30000','20000','75000','0','0','53','19989','0','0','0','0','0','0','0','0','0','0','Wretched Thug - Start Relay Script 19989 OOC'),

**Comment by al3xc1985** [comment]
yes, found them..ty
