### ISSUE TITLE
Initiate Colin - Missing Text

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#796]
![image](https://github.com/cmangos/wotlk-db/assets/6240049/edc02b87-41ee-46b8-9a60-b35eb3171dd8)

https://www.wowhead.com/wotlk/npc=18174/initiate-colin

**Comment by al3xc1985** [comment]
This is from TC

![image](https://github.com/cmangos/wotlk-db/assets/6240049/a67d4625-7d74-4d53-8c44-6f6fe9a84c19)

**Comment by AnonXS** [comment]
Same issue as https://github.com/cmangos/wotlk-db/issues/797
