### ISSUE TITLE
6568!Mistress of Deception

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#80]
quest is missid.. i made full quest chain but no this quest at the end
http://www.wowhead.com/quest=6568/mistress-of-deception
http://wowwiki.wikia.com/wiki/Quest:Mistress_of_Deception
dunno what is the namy of ally q

**Comment by NeatElves** [comment]
questline remove 3.0.1

**Comment by rmzV** [comment]
quest chain is working
but i made a mistake, i already done this quest earlier.. comment from wowhead just misslead me.
ticket can be closed
