### ISSUE TITLE
7481!elven legends

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#82]
http://www.wowhead.com/quest=7481/elven-legends
"This quest is the prerequisite to the creation of Librams of Focus, Protection and Rapidity. It simply requires that you go to the library between Dire Maul West and North and inspect a skeleton near Lorekeeper Lydros."

atm you cant complete him.. but libram quests are available
also leads to
http://www.wowhead.com/quest=7877/the-treasure-of-the-shendralar#comments

**Comment by NeatElves** [comment]
part
```sql
DELETE FROM conditions WHERE condition_entry IN (x, y, z);
INSERT INTO `conditions` (`condition_entry`, `type`, `value1`, `value2`) VALUES
(x, 8, 7481, 0),
(y, 8, 7482, 0),
(z, -2, y, x);
UPDATE `quest_template` SET `RequiredCondition` = z WHERE `entry` IN (7483,7484,7485);
```

**Comment by Grz3s** [comment]
```quote
also leads to
http://www.wowhead.com/quest=7877/the-treasure-of-the-shendralar#comments
```

thats not true... quest has diff preq.
http://wowwiki.wikia.com/wiki/Quest:The_Treasure_of_the_Shen%27dralar
