### ISSUE TITLE
Losing Gracefully

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#827]
https://wowpedia.fandom.com/wiki/Losing_Gracefully

quest removed as 2.4

**Comment by al3xc1985** [comment]
well wowhead does not say that
https://www.wowhead.com/wotlk/quest=10169/losing-gracefully

**Comment by rmzV** [comment]
From your link it says: "Added in patch 2.5.1.38225"
2.5.1 is not classic patch
comment from same link 
"<html><body>
<div class="comment-header">

By 56975 (556 –  1·6)  on 2008/03/28 (Patch 2.4.0) |   |  
-- | -- | --


</div><div class="text comment-body comment-high-rating" lang="en">This quest appears to have been removed now that the soldiers occupying the inner ring of Shattrath are aligned with <a href="https://www.wowhead.com/wotlk/faction=1077">Shattered Sun Offensive</a>.</div>
</body>
</html>
By [56975](https://www.wowhead.com/wotlk/user=56975) (556 – 1·6) [on 2008/03/28](https://www.wowhead.com/wotlk/quest=10169/losing-gracefully#comments:id=261356) (Patch 2.4.0)		
This quest appears to have been removed now that the soldiers occupying the inner ring of Shattrath are aligned with [Shattered Sun Offensive](https://www.wowhead.com/wotlk/faction=1077)."

**Comment by Grz3s** [comment]
creature_questrelation (Holds NPC quest giver relations on which NPCs start which quests)  shows  0  ,,, for this quest in WoTLKDB.. 
My question here... is did this quest .. show up? and is available for players to take in WoTLKDB ??
Explain me what is the actual issue here... koz at the moment i see only info, that quest X was removed in TBC.

**Comment by rmzV** [comment]
@Grz3s Sorry:)
yes it available for players from this npc
https://www.wowhead.com/wotlk/npc=19485/magister-falris#comments
