### ISSUE TITLE
Elementalist Ioki

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#83]
according to this he is neutral
http://www.wowhead.com/npc=18233/elementalist-ioki
and have quest for both sides
http://www.wowhead.com/quest=9869/the-throne-of-the-elements

but horde already has similar quest...
http://www.wowhead.com/quest=9870/the-throne-of-the-elements

what you think?

**Comment by NeatElves** [comment]
zone Gradar - Horde
zone Telaar - Alliance
start thinking, wowhead not all data.
