### ISSUE TITLE
quest 10594 and 8995

### ISSUE THREAD

**Issue by apo126** [cmangos/wotlk-db#84]
~~The quest 10594 "Gauging the Resonant Frequency"
The Oscillating Frequency Scanner (item 30701) triggers unknown spell - ERROR:EffectTriggerSpell of spell 37390: triggering unknown spell id 37503, so the quest cannot be completed.~~**FIXED**

~~The quest 8995 "Mea Culpa, Lord Valthalak"
After clicking item 22056 "Brazier of Beckoning", ERROR CreatureEventAI: Creature 10299 has events but no events added to list because of instance flags (spawned in map 229, difficulty 0) occurs, so the quest cannot be completed..~~**FIXED**

**Comment by NeatElves** [comment]
1 dbc 434
```sql
INSERT INTO spell_template(Id, Attributes, AttributesEx,AttributesEx2,AttributesEx3,ProcFlags,ProcChance,DurationIndex,Effect1,EffectImplicitTargetA1,EffectImplicitTargetB1,EffectRadiusIndex1,EffectApplyAuraName1,EffectMiscValue1,EffectMiscValueB1,EffectTriggerSpell1,IsServerSide,SpellName) VALUES
(37503, 384, 0, 4, 0, 0, 101, 21, 28, 44, 0, 7, 0, 21796, 64, 0, 1, 'Summon Wyrm from Beyond');
```

**Comment by Grz3s** [comment]
```quote
ERROR CreatureEventAI: Creature 10299 has events but no events added to list because of instance flags (spawned in map 229, difficulty 0)
```
this error has nothing to do with quest ;)
