### ISSUE TITLE
Torturer Alphonse - Wrong name in DB

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#845]
https://www.wowhead.com/wotlk/npc=28554/torturer-alphonse#comments
We have it in db Torturer LeCraft

![image](https://github.com/cmangos/wotlk-db/assets/6240049/18492b8c-d66a-45d9-becf-a619dcdb83f6)

**Comment by Gamemechanicwow** [comment]
LeCraft is the original name. It was replaced by blizzard in 2021.

**Comment by Grz3s** [comment]
https://www.reddit.com/r/wow/comments/pg3xkw/references_to_former_blizzard_employees_jesse/
