### ISSUE TITLE
Apothecary Zamah

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#848]
https://www.wowhead.com/wotlk/quest=853/apothecary-zamah

cant be completed...  i am on timer and standing near questender, have yellow "?" but cant handle, becouse dont have item in my bag?

also if it matter^ its second attemp on this quest, after failed state

**Comment by Grz3s** [comment]
quest tells you to:
Bring the [Rendered Spores](https://www.wowhead.com/wotlk/item=5027/rendered-spores) to [Apothecary Zamah](https://www.wowhead.com/wotlk/npc=3419/apothecary-zamah) in Thunder Bluff, before the time limit is up.
So:
No item = no credit

**Comment by rmzV** [comment]
quest item placed in bag when you accept the quest?

**Comment by rmzV** [comment]
@Grz3s also earlier it was possible to reopen tickets:(

**Comment by Grz3s** [comment]
![432423](https://github.com/cmangos/wotlk-db/assets/2374069/78e74c55-92e7-46a7-8843-4ea586038e04)
just tetsted it twice.... got item every time i started it.

**Comment by rmzV** [comment]
okey.. as soon as i get closer to pc, i made a screen

**Comment by rmzV** [comment]
https://dropmefiles.com/ASZpt

character Warlock BE
i take quest and dont get spore... dissmis pet, drop quest and take it again

as i see from your screen, you completed previous quest and take this one in one take...

**Comment by Grz3s** [comment]
go to bank and check if you didnt left quest item there
This was the only option to reproduce your issue...
every other try worked fine

**Comment by rmzV** [comment]
;( You are completely right! Thanks
