### ISSUE TITLE
10111! Bring me the egg!

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#85]
http://www.wowhead.com/quest=10111/bring-me-the-egg
boss summoned but in non target state

**Comment by Darth-Postal** [comment]
I can confirm this bug and want to add another one: upon turning in this quest, the quest giver casts a buff on you and gives a speech.

I don't remember the specifics, but both the bug and the speech seem VERY wrong, like the buff was called "Warchief's blessing" or some such, and the speech was about about some epic Horde victory. 

Clearly odd for a goblin thanking you for stealing an egg.

**Comment by Grz3s** [comment]
in progress...
