### ISSUE TITLE
Twilights MOBS - Missing Aggro Text

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#861]
![image](https://github.com/cmangos/wotlk-db/assets/6240049/abf36603-e16d-4a78-b712-89b89400e6de)

https://www.wowhead.com/wotlk/npc=4810/twilight-reaver#comments
https://www.wowhead.com/wotlk/npc=4812/twilight-loreseeker#abilities;mode:normal
[Twilight Acolyte](https://www.wowhead.com/wotlk/npc=4809/twilight-acolyte)

**Comment by al3xc1985** [comment]
This image is from a private server. Just for question is this. 
I see the text with "Fools....." that is not listed on wowhead, It can be missing on wowhead?

![image](https://github.com/cmangos/wotlk-db/assets/6240049/90860ebb-e9a6-4b77-8586-12fc36926cb9)

**Comment by Grz3s** [comment]
that extra text does not exist in `broadcast` ...  could be added AFTER-CATA or true missing in our data... but until confirmed in legit source... will never be added

**Comment by al3xc1985** [comment]
yes
understood
