### ISSUE TITLE
Question or Missing RP - Private Merle 

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#864]
https://www.wowhead.com/wotlk/npc=1421/private-merle#comments

So I brought this in past, and I bring it back, cause I am standing near him for like 30 min and he just do the small path inside the camp, but never go outside and do the RP part.

Also I checked the db and .wp show on command and he doesn't have that part in db , at least in creature_movement_Template

**Comment by al3xc1985** [comment]
He has four stages

![image](https://github.com/cmangos/wotlk-db/assets/6240049/2c6370b5-097b-476d-ba38-df561a67cd5a)

**Comment by insunaa** [comment]
The guy who moves is Private Thorsen. When you speak with Private Thorsen after saving him from the tiger attack you get on a quest chain where you have to find some orders and stuff, and then at the end it's revealed that Private Merle is the traitor, at which point he becomes attackable and runs away to Duskwood. If the player doesn't kill him, he's killed by neutral Plague Spreader ghouls right as he enters duskwood.

Private Merle never moves unprompted.

**Comment by al3xc1985** [comment]
I will close this and check private thorsen. Ty

**Comment by insunaa** [comment]
![image](https://github.com/cmangos/wotlk-db/assets/3718129/adb72301-0b8b-4588-8cd2-63936af7e04f)
![image](https://github.com/cmangos/wotlk-db/assets/3718129/445d7d6b-ffa5-4fab-9263-b48dab2c2bfa)

**Comment by al3xc1985** [comment]
well, u are right, what I wannted to se was Private Thorsen.

**Comment by al3xc1985** [comment]
I wanted him to leave the camp and see the event with the kurzen ambushin him
