### ISSUE TITLE
Kobold Laborer - Missing Aggro text

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#879]
`('25701','257','4','0','10','0','0','0','0','0','0','0','1','1868','1864','0','0','0','0','0','0','0','0','0','Kobold Worker - Random Say on Aggro'),`

We need this for Laborers
https://www.wowhead.com/wotlk/npc=80/kobold-laborer

![image](https://github.com/cmangos/wotlk-db/assets/6240049/87023810-1a29-43b7-bf75-d579c7f7355d)

**Comment by Grz3s** [comment]
we do have this:
`-- Kobold Labourer 80 (2.4.2 Official Data)
('8001','80','4','0',**'10'**,'0','0','0','0','0','0','0','1','1868','1864','0','0','0','0','0','0','0','0','0','Kobold Labourer - Random Say on Aggro'),`
- he has 10% chance to display them
didnt bother to check?

**Comment by al3xc1985** [comment]
aa yes.. I could not find him, because he is writen wrong in acid file
he is Labourer instead of Laborer
