### ISSUE TITLE
4021!counterattack 

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#88]
http://db.vanillagaming.org/?quest=4021
scripting required
https://www.youtube.com/watch?v=EKM04KT4Y7o
https://www.youtube.com/watch?v=MWod9b5lqUM

**Comment by rmzV** [comment]
dunno if it allowed, but may be this helps?
https://github.com/TrinityCore/TrinityCore/issues/736

**Comment by AnonXS** [comment]
https://github.com/cmangos/mangos-wotlk/commit/d4b604101f250c85536b0d936b799a9ab2e7a374
