### ISSUE TITLE
Childrens from Goldshire-- Question 

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#881]
Hey @Grz3s what do u think about this?

I can see that this vid is somehow a precata? Am I right?
https://www.youtube.com/watch?v=A3v7-ZxojuM

If nothing good is here u can close it

**Comment by cpevors** [comment]
Definitely not pre-Cataclysm if the bloke is flying a mount in Elwynn Forest.

**Comment by insunaa** [comment]
This event has already been worked on by Grz3s. If it's not in the game yet it soon will be.

**Comment by Grz3s** [comment]
theyre added already... u can see them everyday at 7am ..
