### ISSUE TITLE
Kobolds - Missing 1 more aggro text

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#884]
('601','6','4','0','10','0','0','0','0','0','0','0','1','1868','1864','0','0','0','0','0','0','0','0','0','Kobold Vermin - Random Say on Aggro'),

1864 is the one missing

https://www.wowhead.com/wotlk/npc=475/kobold-tunneler#comments
https://www.wowhead.com/wotlk/npc=40/kobold-miner#comments
https://www.wowhead.com/wotlk/npc=79/narg-the-taskmaster#abilities
https://www.wowhead.com/wotlk/npc=476/kobold-geomancer

**Comment by Grz3s** [comment]
`('1864','Yiieeeee! Me run!')`
Where does it say .. that they should have this text? ...

**Comment by al3xc1985** [comment]
As far as I saw blizzard att a set of texts to a group of mobs.

For example gnols they all have same text, even thou 1 (more often) is not listed on wowhead, but it is seen on vids
Blackrock mobs from Redridge also same thing.

I don't think they have this exceptions

**Comment by Grz3s** [comment]
We do not add stuff ..only because.. `i think thats right` ... i looked on few current wotlk classic avis  and on other source we have.. and didnt find even one with this text showing from someone from that list.
Until you give me proof that i can confirm... it wont be added

**Comment by al3xc1985** [comment]
I will let this here, until than. I will look
