### ISSUE TITLE
Krixx

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#889]
https://www.wowhead.com/wotlk/npc=23635/krixx#comments

1.As far as I can tell this guy should walk ALL around orgrimmar, I mean not  just in valley of honnor
2. And he can tell u the destination of zeppeling outside

**Comment by Grz3s** [comment]
You are completely wrong here... i collected all data req. for this guy.. even recorded him (recorded whole orgrimmar for all movement there)... 

wowhead comments are useful but not all the time..
