### ISSUE TITLE
10545! Bladespire Kegger

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#89]
when i have prequest to find 10of kegs, they where working at destrackting ohgrs but quest item in this quest doesnot work
http://www.wowhead.com/quest=10545/bladespire-kegger

**Comment by Grz3s** [comment]
fixed:
https://github.com/cmangos/wotlk-db/commit/b17ca52ce1a3bc9dabf0e248d9d64123956d7d92
