### ISSUE TITLE
[4922] Glinting Dirt 28362 update error

### ISSUE THREAD

**Issue by virusav** [cmangos/wotlk-db#894]
Core SHA: cae1f222ffd11e8095e75e7e097901805c5f833e.
2 - Install fresh WoTLK-DB only to 'wotlkmangos'.

```
Trying to apply CMaNGOS fixes to dbc datas ...
Applying AreaGroup.sql ... SUCCESS
Applying Spell.sql ... FAILED!
ERROR 1054 (42S22) at line 1004: Unknown column 'EffectBaseDice1' in 'field list'
```

WoTLKDB_1_7_14065.sql - no EffectBaseDice1.
Only 12945_01_mangos_spell_template.sql - present EffectBaseDice1.
dbc/original_data/Spell.sql - no EffectBaseDice1
dbc/cmangos_fixes/Spell.sql - present EffectBaseDice1

**Comment by killerwife** [comment]
Fixed.
