### ISSUE TITLE
Enraged Spirits of Fire and Earth

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#899]
https://www.wowhead.com/tbc/quest=10458/enraged-spirits-of-fire-and-earth

use totem, killed nps = no count(

**Comment by insunaa** [comment]
TBC quest, not WotLK, first of all, then also duplicate of https://github.com/cmangos/issues/issues/3339 and duplicate of https://github.com/cmangos/wotlk-db/issues/486
