### ISSUE TITLE
Greater Fleshripper - Missing Ability

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#907]
https://www.wowhead.com/wotlk/npc=154/greater-fleshripper#abilities

https://www.wowhead.com/wotlk/spell=12166/muscle-tear

**Comment by AnonXS** [comment]
![Uploading image.png…]()

**Comment by al3xc1985** [comment]
ok, one more with wrong name.. Sore @AnonXS one more that I tried to find and has wrong name in Acid file
