### ISSUE TITLE
10714! On spirit wings

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#91]
doesnot work
http://www.wowhead.com/quest=10714/on-spirits-wings
https://www.youtube.com/watch?v=-d9oRsSX8Yg

**Comment by rmzV** [comment]
full chain
http://wowwiki.wikia.com/wiki/Quest:On_Spirit%27s_Wings

**Comment by rmzV** [comment]
https://github.com/cmangos/issues/issues/1764

**Comment by Grz3s** [comment]
fixed some time ago
