### ISSUE TITLE
Defias Conjurer - Missing 1 Ability

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#918]
https://www.wowhead.com/wotlk/npc=619/defias-conjurer#abilities

![image](https://github.com/cmangos/wotlk-db/assets/6240049/77e16536-9582-4ab4-83d5-013d04bb5c51)

**Comment by AnonXS** [comment]
tell what is missing, i can see both spells in wotlk. please some more effort with these reports.

**Comment by al3xc1985** [comment]
hmm this is a mistake I made.. I moment to check

**Comment by al3xc1985** [comment]
yes
![image](https://github.com/cmangos/wotlk-db/assets/6240049/991cb0fb-2bef-49ab-8597-f6a76a6c544c)

He is missing the fireball one

**Comment by Grz3s** [comment]
spell was moved to new `creature_spell_list` .. Eventualy all combat spells will end up there...
More about it here:
https://github.com/cmangos/issues/wiki/creature_spell_list
