### ISSUE TITLE
1 Battered Chest in SM - Graveyard Missing

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#921]
![image](https://github.com/cmangos/wotlk-db/assets/6240049/8a6ec865-1485-4ca8-a3ea-95a596173dd3)

https://youtu.be/noVBbhRzmCQ?t=997

**Comment by AnonXS** [comment]
![image](https://github.com/cmangos/wotlk-db/assets/19734826/797ed42f-0bdf-4b4c-b19d-513d7e5046d0)

.go o 1890114

**Comment by al3xc1985** [comment]
how can I not find them ? :)) u were just lucky
