### ISSUE TITLE
Critter Snake - Question

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#923]
https://www.wowhead.com/wotlk/npc=2914/snake#abilities;mode:heroic

So this guy has 2 abilities as critter?
https://www.wowhead.com/wotlk/spell=413174/blood-of-the-loa
https://www.wowhead.com/wotlk/spell=413265/poisoned-blood-of-the-loa

What is this? any ideas?

**Comment by heyitsbench** [comment]
Possibly a spell that spreads and continues to be cast by those it spreads to?

**Comment by al3xc1985** [comment]
Should they have this spreads added as abilities? We have a critter that if u kill it u got infected

**Comment by Grz3s** [comment]
highest spell id for wotlk is ~81k ... 
here u have 413k ... they both do not exists in wotlk.
also: spells with same name = 0.
