### ISSUE TITLE
Bazil Thredd - Missing his linkings

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#930]
https://www.youtube.com/watch?v=7tYqUNlXOL8
https://www.wowhead.com/wotlk/npc=1716/bazil-thredd

DBGuid 340090 and 340080 should be his links

**Comment by Grz3s** [comment]
no
https://youtu.be/5ayMoXdcWhs?t=1603

**Comment by al3xc1985** [comment]
I wont count on this. I checked wotlk videos and it was the way I reported.
This is classic behaviour

**Comment by Grz3s** [comment]
show me 1 vid .from wotlk.... where they are pulled in normal way instead of bein hit by spell or gun... then i will change it.

**Comment by al3xc1985** [comment]
u don't play fair with me! U ALMOST allways are right!
