### ISSUE TITLE
Mokwar broken quest chain

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#94]
http://wowwiki.wikia.com/wiki/Quest:Just_Compensation_(Horde)
npc didnot gives this quest to me ..after completing previvious quests

**Comment by NeatElves** [comment]
```sql
-- The Left Piece of Lord Valthalak's Amulet & Components of Importance
UPDATE `quest_template` SET `RequiredClasses`=  129 WHERE `entry` in (8962,8966); -- Warrior / Mage
UPDATE `quest_template` SET `RequiredClasses`= 1280 WHERE `entry` in (8963,8967); -- Druentry / Warlock
UPDATE `quest_template` SET `RequiredClasses`=   12 WHERE `entry` in (8964,8968); -- Hunter / Rogue
UPDATE `quest_template` SET `RequiredClasses`=   82 WHERE `entry` in (8965,8969); -- Priest / Paladin / Shaman
-- The Right Piece of Lord Valthalak's Amulet & Components of Importance
UPDATE `quest_template` SET `RequiredClasses`=    9 WHERE `entry` in (8985,8990); -- Warrior / Rogue
UPDATE `quest_template` SET `RequiredClasses`= 1090 WHERE `entry` in (8986,8989); -- Druentry / Paladin / Shaman
UPDATE `quest_template` SET `RequiredClasses`=  144 WHERE `entry` in (8987,8991); -- Priest / Mage
UPDATE `quest_template` SET `RequiredClasses`=  260 WHERE `entry` in (8988,8992); -- Hunter / Warlock
```

**Comment by rmzV** [comment]
well... quest still not available.. plz help

**Comment by Grz3s** [comment]
tested with update and all worked fine... i did preq for this .. and quest show up without any issue...

ok ... give me all details:
what class u playing.. if all prequests are done without any .gm help etc...  ill try to go step by step...

**Comment by rmzV** [comment]
hello
i just going throw quest sequence based on this
http://wowwiki.wikia.com/wiki/Quest:Just_Compensation_(Horde)
i have in my db "character_queststatus" this string
3	8978	1	1	0	1479585743	0	0	0	0	0	0	0	0	0	0
so i think this quest with are prequest completed
https://www.wowhead.com/quest=8978/return-to-mokvar

may be i need to clean smth in my wow instalation?

**Comment by rmzV** [comment]
and i am on pala horde

**Comment by rmzV** [comment]
https://www.wowhead.com/quest=10495/just-compensation
pala quest have 10495 id

**Comment by Grz3s** [comment]
try this:
```sql
-- Mokvar missing quest added
-- part of Dungeon Set 1
DELETE FROM creature_involvedrelation WHERE id = 16012 AND quest = 10495;
INSERT INTO creature_involvedrelation (id, quest) VALUES
(16012,10495);
DELETE FROM creature_questrelation WHERE id = 16012 AND quest = 10495;
INSERT INTO creature_questrelation (id, quest) VALUES
(16012,10495);
```

**Comment by rmzV** [comment]
nothing....(

**Comment by Grz3s** [comment]
Pls: 
- Remove Cache from your WoW Game folder (make sure that game isnt running on that time)
- ReRUN ./installfullDB.sh

**Comment by rmzV** [comment]
ok its worked..
thanks!!

**Comment by rmzV** [comment]
btw
https://www.wowhead.com/quest=10495/just-compensation
was added in 3.3 patch..
just thinking about existing this quest for dk?

**Comment by Grz3s** [comment]
https://wow.gamepedia.com/Dungeon_Set_1
