### ISSUE TITLE
Blackrock Champion - Question

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#944]
https://www.wowhead.com/wotlk/npc=435/blackrock-champion

Is it possible that they are the only blackrock mobs to not have an aggro texts like all others? 
![image](https://github.com/cmangos/wotlk-db/assets/6240049/ef60028b-feae-44a5-9f2d-b98cd5a4512a)

**Comment by AnonXS** [comment]
![Uploading image.png…]()

**Comment by AnonXS** [comment]
1min google

**Comment by al3xc1985** [comment]
Well, u close this but they should have added the aggro text, cause they do not have it
