### ISSUE TITLE
Blackrock Champion - Missing Aggro Text

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#945]
https://github.com/cmangos/wotlk-db/issues/944#issuecomment-1752330425

As talked with AnonXS in a previous bug report (that was closed) they should have aggro text 2 like all others blackrock mobs

**Comment by AnonXS** [comment]
![image](https://github.com/cmangos/wotlk-db/assets/19734826/e2f67fd3-06c3-49a2-bfb8-1cd08d12b6b3)

**Comment by al3xc1985** [comment]
Found it 2. I missed it first time
