### ISSUE TITLE
Fenros - Missing Waypoints

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#952]
https://www.wowhead.com/wotlk/npc=507/fenros#comments

![image](https://github.com/cmangos/wotlk-db/assets/6240049/c3508be2-fe30-4637-99b1-e6b25eed4401)

**Comment by Grz3s** [comment]
https://github.com/cmangos/wotlk-db/commit/38f20b818cde151ede909b594d14daa49249386e
