### ISSUE TITLE
Script between Reginald and and Marcus - Small improvements

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#965]
![image](https://github.com/cmangos/wotlk-db/assets/6240049/ef0aba6b-40a0-410d-b6ad-832db6ec60b9)

https://www.wowhead.com/wotlk/npc=12580/reginald-windsor

1. His normal walking/ horse walking speed is 2 high
2. He is missing his equipment 
3. I believe that after he dismounds he does a punch emote, probably that is the moment he takes his equipment (dunno)

![image](https://github.com/cmangos/wotlk-db/assets/6240049/a3cb5dfc-f788-4656-b056-dd6badae90c9)
4. General Marcus Jonathan - - does not face Reginald correct

**Comment by al3xc1985** [comment]
oh wait @Grz3s This script is actualy removed from the game isn't it?
Cause there is no blovar or prestor. Now is king Varian

**Comment by Grz3s** [comment]
https://www.wowhead.com/wotlk/quest=6403/the-great-masquerade#comments:id=729056

**Comment by al3xc1985** [comment]
ya. Script can remain. it;s nice to have it custom play
