### ISSUE TITLE
Morbent Fel - Combut bugs

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/wotlk-db#978]
https://www.wowhead.com/wotlk/npc=1200/morbent-fel#abilities

craete a paladin, and give yourself nice health.
activate ret aura

and go to him, let him hit you u will notice 3 things:

1.His Touch of Death does not heal him for 65 -70 as the tooltip says
2. After a while the Unholy Shield fades from him, and he receives the effect of become small like when u use the wand on him
3.  He will have a cancel spell behaviour when he start casting Touch of Death after point 2. get in action

**Comment by al3xc1985** [comment]
closing this, as I talked with isinuaa and it's normal bejaviour

**Comment by Grz3s** [comment]
1. it doesnt show in combat log or smth... but he deas receive health after spell cast:
![23423](https://github.com/cmangos/wotlk-db/assets/2374069/b9b10f68-f4a3-433c-b573-4b73918fec28)

2. .. aura has timer (10mins)... You waited that long ?:)... anyway will change aura check from 3secs to 100ms... should fix this issue

**Comment by al3xc1985** [comment]
yes I waited 10 min, that's how I find it out

**Comment by al3xc1985** [comment]
but didn't noticed the 10 min duration
