### ISSUE TITLE
Magical Ledger

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#983]
https://www.wowhead.com/classic/item=20949/magical-ledger#comments

no drop and no dialog option to take quest item((

**Comment by insunaa** [comment]
![image](https://github.com/cmangos/wotlk-db/assets/3718129/0ba67e82-dbcd-4233-801d-bfca92f73a2e)
Can't confirm. If you have completed https://www.wowhead.com/classic/quest=8555/the-charge-of-the-dragonflights and are at Neutral or better with Brood of Nozdormu he has the gossip menu and awards the item

**Comment by rmzV** [comment]
was checking 8555 atm. you are right.(
