### ISSUE TITLE
Dead Man's Plea

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#984]
[Dead Man's Plea](https://www.wowhead.com/classic/quest=8945/dead-mans-plea)

have this quest in quest log... then i remove it, but now i am near strath and use [[[Extra-Dimensional Ghost Revealer]](https://wowpedia.fandom.com/wiki/Extra-Dimensional_Ghost_Revealer)]  but no quest giver available

**Comment by rmzV** [comment]
@Grz3s Can you please check this quest?

**Comment by Grz3s** [comment]
https://github.com/cmangos/issues/issues/3600#issuecomment-1807209464

**Comment by rmzV** [comment]
fixed as for now
