### ISSUE TITLE
9142!Craftsman's Writ [core issue?]

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#99]
quest must be repitable 
each yime npc must give you different order
http://www.wowhead.com/quest=9142/craftsmans-writ
http://wowwiki.wikia.com/wiki/Quest:Craftsman%27s_Writ

orders
http://wowwiki.wikia.com/wiki/Sealed_Craftsman's_Writ

**Comment by NeatElves** [comment]
```sql
UPDATE quest_template SET SpecialFlags = 1 WHERE entry = 9142;
```

**Comment by rmzV** [comment]
well
are you sure that this fix will give you random orders?

**Comment by Grz3s** [comment]
it wont ... but this is core issue (cannot be done by db)
I need to keep some kind of order here.

**Comment by rmzV** [comment]
i just trying to create list of all non working things and afraid , that when core will be able to fix this issue, we will already forgot about it
